### ISSUE TITLE
小模型训练

### ISSUE THREAD

**Issue by pawopawo** [PaddlePaddle/PaddleClas#1002]
SSLD训练策略对小模型有收益吗？ 比如224*224输入下，FLOPs 50M的模型。

**Comment by RainFrost1** [comment]
SSLD是一种蒸馏训练的方式，主要的目标是提升小模型的精度

**Comment by pawopawo** [comment]
谢谢您的回复～但总觉得SSLD更像是一种数据扩充的方式，通过将1M的数据扩充到了5M。或许算是一种数据蒸馏？

**Comment by cuicheng01** [comment]
> 谢谢您的回复～但总觉得SSLD更像是一种数据扩充的方式，通过将1M的数据扩充到了5M。或许算是一种数据蒸馏？

SSLD是一种半监督的知识蒸馏方式，详情请参考论文：https://arxiv.org/pdf/2103.05959v1.pdf
