### ISSUE TITLE
SSLD数据

### ISSUE THREAD

**Issue by pawopawo** [PaddlePaddle/PaddleClas#1004]
您好，请问SSLD中的500M数据能开源吗？

**Comment by pawopawo** [comment]
为什么不直接用21k的数据蒸馏，而是用500M的数据呢？

**Comment by cuicheng01** [comment]
一来是为了降低训练时间，二来是数据量太多会导致训偏，这500w数据其中有400w是经过模型的筛选的，具体可以参考：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/zh_CN/advanced_tutorials/distillation/distillation.md

**Comment by pawopawo** [comment]
数据量太多会导致训偏，这有实验分析吗？目前很多论文(EfficientV2，Swin Transform)都是在21K数据上预训练的呀

**Comment by cuicheng01** [comment]
> 数据量太多会导致训偏，这有实验分析吗？目前很多论文(EfficientV2，Swin Transform)都是在21K数据上预训练的呀

使用ImageNet-21k训练后用预训练去微调ImageNet-1k是没问题的，而且数据量越大往往越好。但是蒸馏的label体系就是ImageNet-1k的体系，涉及太多的不在1k的类会增加太多的噪声。
