### ISSUE TITLE
有办法设置随机数复现结果吗？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleClas#1005]
我在train的main中设置了paddle.seed np.random.seed random.seed，ppcls.data.preprocess.ops.operators里面设置了np.random.seed random.seed，cudnn_deterministic=true，同样的配置跑出来的结果acc一个0.689，一个0.716。浮动这么大，调优没法做啊

**Comment by weisy11** [comment]
这个现象确实比较异常，按照我们之前的测试，浮动应该在0.5%之内。麻烦描述一下你的任务，用的配置，我们来具体跟进以下。

**Comment by bbbxixixixi** [comment]
生成了个项目共享链接
项目“vegitable_disease f1”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/2147086/f6f2deefabf94267a9f65aae7b125e1c

依次执行前4句就行，用的是32g环境，因为一轮在8小时内完不了，所以前面的acc是137轮时的结果
ppcls修改了train.py和operators.py，设置了随机数，其他没动

**Comment by weisy11** [comment]
数据量比较小的情况下，确实会有比较大的波动。建议把batch_size调小一点试试看。
你说的这个随机量固定的问题，我们会具体定位一下。

**Comment by DrewdropLife** [comment]
@bbbxixixixi 如何固定随机种子，能再分享一下吗？谢谢
