### ISSUE TITLE
目标检测模块

### ISSUE THREAD

**Issue by lazyn1997** [PaddlePaddle/PaddleClas#1007]
目前图像识别中的目标检测模块只能使用动态图模型，请问如果期望使用静态图目标检测模型应该如何进行修改呢。

**Comment by cuicheng01** [comment]
动态图的目标检测模型会通过动转静的方式最后导出inference model，静态图的目标检测模型也会导出inference model，所以只做推理的话，动态图静态图不受影响哈。

**Comment by lazyn1997** [comment]
> 动态图的目标检测模型会通过动转静的方式最后导出inference model，静态图的目标检测模型也会导出inference model，所以只做推理的话，动态图静态图不受影响哈。
但是静态图导出的模型和动态图导出的模型文件格式不一样，如下图所示，直接修改目标检测模型的路径无法运行，直接修改静态图模型的文件名为动态图格式也会报错。
![image](https://user-images.githubusercontent.com/34644177/124285147-3c5da900-db80-11eb-9feb-f6f515fe8a27.png)

**Comment by weisy11** [comment]
我们最近更新了主体检测模块的文档，你看能解决你的问题吗？

**Comment by littletomatodonkey** [comment]
你好，目前应该已经不支持静态图inference模型的预测了哈，建议直接使用提供的动态图inference模型哈
