### ISSUE TITLE
打包成exe之后报错Error: Can not import avx core while this file exists: xxx\paddle\fluid\core_avx.pyd

### ISSUE THREAD

**Issue by itues** [PaddlePaddle/PaddleClas#1009]
代码运行正常，打包成exe之后就报错，请问怎么解决
![微信截图_20210705082011](https://user-images.githubusercontent.com/86935392/124403677-290e3180-dd6a-11eb-96d1-b4ab6eb6b24a.png)

**Comment by cuicheng01** [comment]
打包的过程再详细描述下吧

**Comment by itues** [comment]
> 打包的过程再详细描述下吧

早上 这个问题解决了。直接从安装的paddle里把libs里的文件拷出来解决的。但是软件执行的时候慢卡，重启，各种怪异问题，无法使用。我下午换成python3.8环境，打包出来的又有问题，问题如下图。我已经把安装paddle的fluid里所有文件及libs里的都拷过来还是不行。我这次打包的代码是 ：pyinstaller -D -w -c -i  D:\Projects\lmst_p_s\favicon.ico D:\Projects\lmst_p_s\paddleClas.py 
![image](https://user-images.githubusercontent.com/86935392/124486664-68776500-dde0-11eb-99c4-bc30207f2969.png)
