### ISSUE TITLE
关于导出的模型和模型预测问题

### ISSUE THREAD

**Issue by lyw1991** [PaddlePaddle/PaddleClas#1018]
第一次接触图像识别，有几个问题请教一下
模型评估结果中
`[2021/07/07 15:50:34] root INFO: [Eval][Epoch 0][Avg]CELoss: 2.97283, loss: 2.97283, top1: 0.25490, top5: 0.56961`
CELoss、loss分别代表什么
导出模型后调用模型预测名令，返回值为：
`[{'class_ids': [76, 12, 34, 28, 78], 'scores': [0.1285, 0.08516, 0.08284, 0.0635, 0.05591], 'label_names': []}]`
其中class_ids和scores字段分别是什么意思
文档里好像都没有说明

**Comment by weisy11** [comment]
loss是总的损失，CELoss是cross entropy loss的缩写，是交叉熵损失。这里只有一种损失，所以两个值是一样的。
导出的模型返回的结果是置信度从高到低前5名的结果，class_ids是分类的类别的id，scores是对应类别的置信度。
如果您对图像识别不太了解，推荐您先学习一下 https://github.com/PaddlePaddle/awesome-Deeplearning

**Comment by lyw1991** [comment]
> loss是总的损失，CELoss是cross entropy loss的缩写，是交叉熵损失。这里只有一种损失，所以两个值是一样的。
> 导出的模型返回的结果是置信度从高到低前5名的结果，class_ids是分类的类别的id，scores是对应类别的置信度。
> 如果您对图像识别不太了解，推荐您先学习一下 https://github.com/PaddlePaddle/awesome-Deeplearning

好的，谢谢

**Comment by weisy11** [comment]
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/zh_CN/application/mainbody_detection.md
