### ISSUE TITLE
clang: error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by zhao0229** [PaddlePaddle/PaddleClas#1019]
Mac 重新编译时index.so时报错如下：
clang: error: unsupported option '-fopenmp'
请问怎么解决

**Comment by cuicheng01** [comment]
这个是在docker中还是mac机器上呢？可以在提供一些详细的信息吗

**Comment by zhao0229** [comment]
> 这个是在docker中还是mac机器上呢？可以在提供一些详细的信息吗

Mac机器上，版本11.2.3，使用cpu，不在docker里面
识别时报这样的错
<img width="1627" alt="image" src="https://user-images.githubusercontent.com/35862443/124869331-a00a2b00-dff3-11eb-8236-c0dff5c1726f.png">
尝试重新编译index.so，就这样了

M1还是Intel CPU呢

**Comment by weisy11** [comment]
> M1还是Intel CPU呢

确定是M1吗？M1是苹果自研arm架构的CPU，不是intel的x86架构，目前许多环境都支持不佳。我们也在进行适配工作，不过目前有许多依赖问题（例如docker存在不少bug），短期内无法完美解决。

**Comment by zhao0229** [comment]
> > M1还是Intel CPU呢
> 
> 确定是M1吗？M1是苹果自研arm架构的CPU，不是intel的x86架构，目前许多环境都支持不佳。我们也在进行适配工作，不过目前有许多依赖问题（例如docker存在不少bug），短期内无法完美解决。

intel的8代i7

**Comment by baishui2004** [comment]
经测，Mac Intel下，修改PaddleClas/deploy/vector_search/Makefile的第一行为：CXX=/usr/local/bin/g++-11，即which g++-11得到的路径，再执行make即可。
