### ISSUE TITLE
日志文件在哪？

### ISSUE THREAD

**Issue by sunw71** [PaddlePaddle/PaddleClas#102]
FAQ中说“启动运行后，日志会实时输出到mylog/workerlog.*中，可以在这里查看实时的日志。”
但我为什么我运行后却找不到mylog文件夹？另外怎么可视化训练过程？

**Comment by littletomatodonkey** [comment]
您好，最早的日志是打印在文件中的，屏幕中不会显示，后来日志被修改为`实时打印到屏幕中`，如果您需要保存日志信息，可以使用重定向的方法保存：`nohup sh tools/run.sh &> your_log_addr.log &`。感谢提醒，我们更新下faq的内容：https://github.com/PaddlePaddle/PaddleClas/pull/103

**Comment by littletomatodonkey** [comment]
您好，如果没有别的问题，我们将关闭该issue，后续有其他的问题，欢迎随时提issue，非常期待您的反馈~
