### ISSUE TITLE
官网30分钟玩转PaddleClas里的tools/download.py在git仓库里没有了

### ISSUE THREAD

**Issue by Skypow2012** [PaddlePaddle/PaddleClas#1020]
https://paddleclas.readthedocs.io/zh_CN/latest/tutorials/quick_start.html
这里2.1里的tools/download.py这个文件在仓库里没有了

**Comment by cuicheng01** [comment]
暂时不建议看readthedoc的文档，建议先直接看github上的文档，我们最近会重新整理readthedoc的文档哈~
