### ISSUE TITLE
resnet18导出模型以及评估时报错

### ISSUE THREAD

**Issue by nianyush** [PaddlePaddle/PaddleClas#1026]
![image](https://user-images.githubusercontent.com/5505684/124876439-933e0500-dffc-11eb-9b37-e3dd96f5fa3b.png)
使用的pdparams是https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/ResNet18_pretrained.pdparams
paddleclas版本为release/2.2,paddlepaddle2.1 
用pickel输出这个pdparams发现确实没有报错的这几个
![image](https://user-images.githubusercontent.com/5505684/124876775-f92a8c80-dffc-11eb-8553-589e1c196d78.png)

请问会是什么问题呢,是我的环境有问题吗？配置文件用的就是./ppcls/configs/ImageNet/ResNet/ResNet18.yaml，并没有做修改

**Comment by cuicheng01** [comment]
hi,旧版本的resnet使用的权重是你提到的这个路径，在新版本中，resnet被重构了一次，新的resnet18的权重路径是https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/legendary_models/ResNet18_pretrained.pdparams，更多的模型预训练地址，详情这个页面：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/zh_CN/ImageNet_models_cn.md

**Comment by cuicheng01** [comment]
hi,旧版本的resnet使用的权重是你提到的这个路径，在新版本中，resnet被重构了一次，新的resnet18的权重路径是https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/legendary_models/ResNet18_pretrained.pdparams，
更多的模型预训练地址，详情这个页面：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/zh_CN/ImageNet_models_cn.md

**Comment by nianyush** [comment]
> hi,旧版本的resnet使用的权重是你提到的这个路径，在新版本中，resnet被重构了一次，新的resnet18的权重路径是[https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/legendary_models/ResNet18_pretrained.pdparams，](https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/legendary_models/ResNet18_pretrained.pdparams%EF%BC%8C)
> 更多的模型预训练地址，详情这个页面：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/zh_CN/ImageNet_models_cn.md

好的 还有一个问题就是像rexnet mixnet regvgg这些虽然有提供预训练模型，但似乎在ppcls下并没有对应的yaml文件，是没有放出吗

**Comment by cuicheng01** [comment]
感谢提醒，随后更新这些yaml哈
