### ISSUE TITLE
除了官方提供的图片，自己添加的就无法识别了吗

### ISSUE THREAD

**Issue by zhao0229** [PaddlePaddle/PaddleClas#1027]
用官方提供的图片都可以识别出来的，但是自己添加的图就无法识别，是只支持官方提供的图吗

**Comment by cuicheng01** [comment]
hi，您好，我们支持添加其他数据的，请问您添加的是什么数据呢？添加的数据有重新刷特征建索引吗？用的是哪个模型呢？

**Comment by zhao0229** [comment]
> hi，您好，我们支持添加其他数据的，请问您添加的是什么数据呢？添加的数据有重新刷特征建索引吗？用的是哪个模型呢？

我自己添加的是华为p40的图片
按照https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/zh_CN/tutorials/quick_start_recognition.md#未知类别的图像识别体验
里面的未知图像识别又操作了一遍，结果识别不出来，结果为空

**Comment by cuicheng01** [comment]
方便的话提供一下一下入库图片和测试图片，我们帮你检验下。

**Comment by zhao0229** [comment]
> 方便的话提供一下一下入库图片和测试图片，我们帮你检验下。

添加的数据
![001](https://user-images.githubusercontent.com/35862443/124888382-a22ab480-e008-11eb-9327-34e33e467fc1.jpeg)
![002](https://user-images.githubusercontent.com/35862443/124888401-a6ef6880-e008-11eb-83a1-ed0e5534e0cb.jpeg)
![003](https://user-images.githubusercontent.com/35862443/124888418-aa82ef80-e008-11eb-8043-f2afc3aee793.jpeg)
![004](https://user-images.githubusercontent.com/35862443/124888429-ace54980-e008-11eb-96cf-a36678232358.jpeg)
识别对象
![huaweip40](https://user-images.githubusercontent.com/35862443/124888475-b79fde80-e008-11eb-8ecc-b2ef4512b73d.jpeg)

**Comment by zhao0229** [comment]
> 方便的话提供一下一下入库图片和测试图片，我们帮你检验下。
入库图
![feicuishouzhuo001](https://user-images.githubusercontent.com/35862443/124894063-e40a2980-e00d-11eb-804b-4e5edb3c6e7f.jpg)
![feicuishouzhuo002](https://user-images.githubusercontent.com/35862443/124894079-e7051a00-e00d-11eb-96cb-9fcf29eb4956.jpeg)
![feicuishouzhuo003](https://user-images.githubusercontent.com/35862443/124894089-ea000a80-e00d-11eb-8572-ba21a9087030.jpeg)
![feicuishouzhuo004](https://user-images.githubusercontent.com/35862443/124894099-ebc9ce00-e00d-11eb-8caa-5dbbb13e309b.jpg)
![feicuishouzhuo005](https://user-images.githubusercontent.com/35862443/124894110-ee2c2800-e00d-11eb-998c-ef28a21b31ee.jpg)
识别对象
![feicuishouzhuo006](https://user-images.githubusercontent.com/35862443/124894143-f6846300-e00d-11eb-81d6-7e56d2f1e78a.jpg)

**Comment by cuicheng01** [comment]
是余弦相似度不够导致被阈值卡掉了，把IndexProcess.score_thres调小即可

**Comment by zhao0229** [comment]
> 是余弦相似度不够导致被阈值卡掉了，把IndexProcess.score_thres调小即可

牛逼，可以了，谢谢大佬耐心解答
