### ISSUE TITLE
目标识别的2个问题：

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleClas#1029]
1、在图像检索时，如果待识别的目标尺度跨度大，且包含很多很小目标（占整个图像的1/10不到），是把目标用矩形框标记出来训练还是直接用整个图打标签训练？另外小目标用训练的特征提取网络与gallery dataset比较，特征相似度都很高，识别分类错误率高，这如何处理？
2、对于未知的标签，加入gallery dataset可以用于后续的分类识别（无需训练），但是如果前面的检测模型对于未知的标签无法定位检测出来，是否还是要训练前面的检测模型？

谢谢！

**Comment by cuicheng01** [comment]
1.第一个问题是一个相对开放的问题，这个不一定，每个数据集也不太一样。第二个问题这个是一个比较难的问题，主要是去用各种手段让模型的提取能力更强，这里的手段包括更好的backbone、更好的预训练模型、更好的数据增强、更好的Loss等等。
2.如果检测模型在自己的数据集上表现不佳，检测模型需要在自己的检测数据集上再finetune下。
