### ISSUE TITLE
使用AIStudio脚本运行环境基于PaddleClas训练过程的相关问题

### ISSUE THREAD

**Issue by thomas-yanxin** [PaddlePaddle/PaddleClas#1031]
在脚本中选取0,1,2,3GPU训练
![image](https://user-images.githubusercontent.com/58030051/125183581-2e77ea00-e24a-11eb-962f-f3d75899d2e8.png)
出现以下问题
![image](https://user-images.githubusercontent.com/58030051/125183570-130cdf00-e24a-11eb-8e8c-ff71c5a675a4.png)
该如何解决？

**Comment by Intsigstephon** [comment]
确认一下_clas_path的路径是否存在，以及斜杠符号方向是否正确
