### ISSUE TITLE
相同的数据集在PaddleClas2.0和2.2版本却得到完全不同的ACC

### ISSUE THREAD

**Issue by BurrowsWang** [PaddlePaddle/PaddleClas#1036]
>自有图像分类数据集，使用的网络结构都是MobileNetV3_large_x1_0

4月份的时候我用PaddleClas2.0版本在自有数据集上训练过一版分类模型，当时的Top1 acc是99.6%

今天我用PaddleClas2.2版本程序在同一个数据集上进行训练，Top1 acc只有48.0%（ImageNet预训练模型确认是加载了的）

训练过程都是完全按照2个版本的《30分钟玩转教程》进行的，参数的调整只修改了dataset和classnum，2次训练epoch和batchnum是一致的

大家有没有遭遇过这个困境呢？

**Comment by cuicheng01** [comment]
方便发一下两次的batch-size和学习率嘛

**Comment by BurrowsWang** [comment]
> 方便发一下两次的batch-size和学习率嘛

PaddleClas2.0: 
\# 0.00375
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.0/configs/quick_start/MobileNetV3_large_x1_0_finetune.yaml#L19

\# 0.00700
PaddleClas2.2:https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/ppcls/configs/ImageNet/MobileNetV3/MobileNetV3_large_x1_0.yaml#L38

batch_size都是32

感谢您的回复，谢谢

**Comment by cuicheng01** [comment]
> > 方便发一下两次的batch-size和学习率嘛
> 
> PaddleClas2.0:
> # 0.00375
> https://github.com/PaddlePaddle/PaddleClas/blob/release/2.0/configs/quick_start/MobileNetV3_large_x1_0_finetune.yaml#L19
> 
> # 0.00700
> PaddleClas2.2:https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/ppcls/configs/ImageNet/MobileNetV3/MobileNetV3_large_x1_0.yaml#L38
> 
> batch_size都是32
> 
> 感谢您的回复，谢谢

分别是用几张卡训练的呢？

**Comment by BurrowsWang** [comment]
是用单卡训练的。后来把所有训练参数改为2.0版本中使用的参数，在2.2下得到了99.0%的acc。感谢您的帮助
