### ISSUE TITLE
图像识别，颜色匹配不正确

### ISSUE THREAD

**Issue by coderchuan** [PaddlePaddle/PaddleClas#1039]
图像识别，在两个类别仅在颜色上有差异时，似乎不能正确地匹配

**Comment by cuicheng01** [comment]
hi，您好。可以再详细描述一下问题嘛？

**Comment by coderchuan** [comment]
例如：
![image](https://user-images.githubusercontent.com/44311500/125400003-e8ef2480-e3e3-11eb-9c3f-c949c20532b5.png)

![image](https://user-images.githubusercontent.com/44311500/125400013-ebea1500-e3e3-11eb-9283-ff03d6055ed1.png)

这两个图片匹配的结果是错位的，

**Comment by coderchuan** [comment]
> hi，您好。可以再详细描述一下问题嘛？


> 例如：
> 图1
> ![image](https://user-images.githubusercontent.com/44311500/125400003-e8ef2480-e3e3-11eb-9c3f-c949c20532b5.png)
> 
> 图2
> ![image](https://user-images.githubusercontent.com/44311500/125400013-ebea1500-e3e3-11eb-9283-ff03d6055ed1.png)
> 
> 图1中的第一个图匹配到的是图2中的第一个图
> 图1中的第二个图匹配到的是图2中的第二个图
> 它们的颜色不能正确对应

**Comment by coderchuan** [comment]
> hi，您好。可以再详细描述一下问题嘛？



> hi，您好。可以再详细描述一下问题嘛？

**Comment by coderchuan** [comment]
> 图像识别，在两个类别仅在颜色上有差异时，似乎不能正确地匹配

test

**Comment by cuicheng01** [comment]
这个是使用现在提供的商品模型，然后没有继续训练是吧？这两个实际上是同一类嘛？

**Comment by coderchuan** [comment]
> 这个是使用现在提供的商品模型，然后没有继续训练是吧？这两个实际上是同一类嘛？


使用的是未知图像识别建立的索引，添加的两个类别，这两个不同的颜色的商品给的是两个不同的类标签

**Comment by cuicheng01** [comment]
> > 这个是使用现在提供的商品模型，然后没有继续训练是吧？这两个实际上是同一类嘛？
> 
> 使用的是未知图像识别建立的索引，添加的两个类别，这两个不同的颜色的商品给的是两个不同的类标签
『给的是』是真实标签还是预测标签的意思呢？

**Comment by coderchuan** [comment]
真实标签

**Comment by coderchuan** [comment]
> > > 这个是使用现在提供的商品模型，然后没有继续训练是吧？这两个实际上是同一类嘛？
> > 
> > 
> > 使用的是未知图像识别建立的索引，添加的两个类别，这两个不同的颜色的商品给的是两个不同的类标签
> > 『给的是』是真实标签还是预测标签的意思呢？

真实标签

**Comment by cuicheng01** [comment]
我感觉这个真实的数据粒度太细了，一般场景下这应该属于一类

**Comment by coderchuan** [comment]
> 我感觉这个真实的数据粒度太细了，一般场景下这应该属于一类

嗯嗯，好的，感谢。我试试自己训练一个模型来跑看看会不会有好一点儿的结果
