### ISSUE TITLE
关于resnetvd的问题

### ISSUE THREAD

**Issue by ZZHHogan** [PaddlePaddle/PaddleClas#1044]
请问resnetvd指的是什么结构呢，是resnet-d？有相关的论文、资料介绍吗？

**Comment by cuicheng01** [comment]
是resnet-d，具体论文可以参考：https://openaccess.thecvf.com/content_CVPR_2019/papers/He_Bag_of_Tricks_for_Image_Classification_with_Convolutional_Neural_Networks_CVPR_2019_paper.pdf
