### ISSUE TITLE
求公开百度10万分类的图像预训练模型

### ISSUE THREAD

**Issue by fatty-tiger** [PaddlePaddle/PaddleClas#1045]
求官方号在知乎提到过的10万分类预训练模型
https://zhuanlan.zhihu.com/p/137534156

**Comment by cuicheng01** [comment]
静态图的权重详情这个页面：https://github.com/PaddlePaddle/PaddleClas/blob/release/static/docs/en/application/transfer_learning_en.md
动态图的权重最近更新哈，更新后通知你。

**Comment by fatty-tiger** [comment]
> 静态图的权重详情这个页面：https://github.com/PaddlePaddle/PaddleClas/blob/release/static/docs/en/application/transfer_learning_en.md
> 动态图的权重最近更新哈，更新后通知你。

好的 感谢。

**Comment by bityigoss** [comment]
@cuicheng01 你好，动态图的权重近期还会更新吗？
