### ISSUE TITLE
按文档说明重新生成index.dll却还是不能用

### ISSUE THREAD

**Issue by martin1009** [PaddlePaddle/PaddleClas#1050]
![image](https://user-images.githubusercontent.com/3635294/125886500-c220e9f2-11a7-413e-ba12-33763d0e7243.png)
重新生成了n次，还是这个提示，看看怎么回事？

**Comment by littletomatodonkey** [comment]
看下时间戳，是否生成成功了呢？

**Comment by JH95-ai** [comment]
@littletomatodonkey 你好，我也遇到了相同的问题，时间戳显示生成成功，index.dll也是显示找不到指定模块。
生成新index.dll截图如下：
![image](https://user-images.githubusercontent.com/32665609/126092792-63bf44bf-2b54-4d82-90e4-64f181b4886f.png)
![image](https://user-images.githubusercontent.com/32665609/126092806-bd767f9f-a137-4371-9a53-5b701c91d337.png)
报错 如下：
![image](https://user-images.githubusercontent.com/32665609/126092816-bacea193-2ae6-4727-a546-e98931acc7a0.png)
运行环境：win10,python3.6,gcc10.3.0

**Comment by martin1009** [comment]
我删除index.dll，用命令mingw32-make 会重新生成，但无法使用
![image](https://user-images.githubusercontent.com/3635294/126093937-55bfcb2b-d42f-4be0-8ec3-c6510c192bb9.png)

**Comment by littletomatodonkey** [comment]
为啥看着多了一层目录(PClas)？检查下打印的日志中的目录文件是否存在吧，建议先什么都不要用，按照快速开始跑一下，确认环境没有问题

**Comment by TingquanGao** [comment]
由于我们这边的机器暂时未能复现该问题，请问是否可以将以下信息贴出来，方便我们排查问题，谢谢！
1. PaddleClas 分支为：[develop] [release/2.2]；
2. 是否为最新代码，特别确认该处代码是否一致：https://github.com/PaddlePaddle/PaddleClas/blob/83253af0ff3321dc20402273c0a7f3ea99e25a19/deploy/vector_search/interface.py#L37-L40
3. Python版本为：[3.6.0][3.7.0][3.8.0]...等；
4. 系统版本为：[Windows10]...等；
5. 完整的报错信息截图，报错信息中一般包含字段：`Error happened when load lib ...`；
6. 其他您认为有用的信息。

上述信息也可通过QQ: 35441050私发给我。谢谢！

**Comment by JH95-ai** [comment]
@TingquanGao @littletomatodonkey 已解决，感谢回复！
解决过程，上传到linux服务器，跑了一遍index.so及相关快速开始案例。绕过了这个问题。
今天再次在windows尝试index.dll，发现不会报错了。项目自带的还是自己编译的均可成功运行。很玄学。

**Comment by TingquanGao** [comment]
好的，为了排查问题，还想再次确认一下。
今天在Windows平台成功运行的PaddleClas项目代码，是重新从GitHub获取的吗？或仍然是上次运行报错的项目代码？
这次成功运行的PaddleClas项目与之前报错的项目是否是在电脑同一路径下呢？
谢谢！

**Comment by martin1009** [comment]
![1](https://user-images.githubusercontent.com/3635294/126287261-19f74916-4c60-418f-8c91-b7e0cfd10682.png)
我重新获取了最新代码，并按照指定路径，但在运行时报了如下错误：
(NotFound) Cannot open file ./models/product_ResNet50_vd_aliproduct_v1.0_infer\inference.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at C:\home\workspace\Paddle_release\paddle\fluid\inference\api\analysis_predictor.cc:953)
  
  但文件是存在的哦
  
![1](https://user-images.githubusercontent.com/3635294/126287397-d36a47f2-9979-448b-9214-e16a4cc19f9c.png)

**Comment by TingquanGao** [comment]
@martin1009 你好，请尝试将`PaddleClas/models/`路径移至`PaddleClas/deploy/models/`。

**Comment by martin1009** [comment]
移至deploy下执行，出现如下错误：
![image](https://user-images.githubusercontent.com/3635294/126427529-b6d42c51-5fdf-4a76-92ba-dda017f718f6.png)


但检查文件是存在的：
![image](https://user-images.githubusercontent.com/3635294/126427467-d3658498-3873-460d-9a02-a10d7baef3ed.png)

**Comment by TingquanGao** [comment]
您好，请将目录结构组织为如下格式：
```bash
 .
 └── PaddleClas
     └── deploy
         ├── models
         │   ├── ppyolov2_r50vd_dcn_mainbody_v1.0_infer
         │   │   ├── inference.pdiparams
         │   │   ├── inference.pdiparams.info
         │   │   └── inference.pdmodel
         │   └── product_ResNet50_vd_aliproduct_v1.0_infer
         │       ├── inference.pdiparams
         │       ├── inference.pdiparams.info
         │       └── inference.pdmodel
         └── recognition_demo_data_v1.0
```

也即，将 `PaddleClas/deploy/models/recognition_demo_data_v1.0/` 移动至  `PaddleClas/deploy/recognition_demo_data_v1.0/`

**Comment by martin1009** [comment]
谢谢，现在可以了:smiling_face_with_three_hearts:

**Comment by martin1009** [comment]
paddleClas识别效果感觉不佳，我按https://github.com/martin1009/PaddleClas/blob/release/2.2/docs/zh_CN/tutorials/quick_start_recognition.md 文档所示，换了一张“安慕希酸奶”图片，结果就识别不到，返回空数组。
“安慕希酸奶”图片
![image](https://user-images.githubusercontent.com/3635294/126582707-d044415a-0bef-444b-bf98-15670db605e5.png)

其识别结果：
![image](https://user-images.githubusercontent.com/3635294/126582873-d8597b70-a2e9-45aa-9b93-8aadec7e26ac.png)


该如何提高其识别率呢？

**Comment by martin1009** [comment]
我在gallery里又加多了一些样本数据，现在能识别到了，谢谢

**Comment by zssty2010** [comment]
> ![image](https://user-images.githubusercontent.com/3635294/125886500-c220e9f2-11a7-413e-ba12-33763d0e7243.png)
> 重新生成了n次，还是这个提示，看看怎么回事？

我也遇到了这个问题，最终的答案是。它在交叉环境mingw32下编译的，编译时依赖于openmp，然后生成的 index.dll 依赖于 libgomp_64-1.dll。所以如果你脱离mingw64环境运行时，需要到把libgomp_64-1.dll拷到你运行检查路径，或者设置path。例如：把这个libgomp_64-1.dll和index.dll 放在一起，然后`set path=%path%;E:\OpenSource\ai\PaddleClas\deploy\vector_search`。就可以了
