### ISSUE TITLE
请问如何跳过主体检测，直接进行检索

### ISSUE THREAD

**Issue by wjrjsdx** [PaddlePaddle/PaddleClas#1058]
python python/predict_system.py -c configs/inference_product.yaml，教程里面这个是主体检测、特征提取和向量检索串联的例子，但是假设我自己的图片已经是一个主体图片了，然后我通过之前训练的识别模型构建了一个索引库，我应该如何跳过主体检测，直接拿这个图片到索引库进行检索？

**Comment by Intsigstephon** [comment]
直接将主体检测代码修改为"results= {}"，对应python/predict_system.py  89行

**Comment by wjrjsdx** [comment]
有用，谢谢
