### ISSUE TITLE
aistudio平台上安装Python依赖库很慢，有没有什么好的办法？

### ISSUE THREAD

**Issue by Fly-hub** [PaddlePaddle/PaddleClas#1067]
安装Python依赖库是按照官方文档中做的：!pip install --upgrade -r requirements.txt -i https://mirror.baidu.com/pypi/simple
用的还是百度源，为什么这么慢啊？

**Comment by Fly-hub** [comment]
等了半天aistudio把我的终端关了，提示本平台不支持tf、troch等等。我明明是按照官网文档做的好吧。。。

**Comment by Fly-hub** [comment]
opencv-python安装这个的时候很慢，最后也没有成功，将版本改为旧版本就好了，2s完成。opencv-python==3.4.9.31

**Comment by weisy11** [comment]
aistudio的源可能没有更新那么快，具体的使用问题可以咨询aistudio的同学。
