### ISSUE TITLE
SSLD蒸馏训练策略问题

### ISSUE THREAD

**Issue by pawopawo** [PaddlePaddle/PaddleClas#1069]
![image](https://user-images.githubusercontent.com/38682321/126587873-abca34d1-4bd5-4da3-87a8-1376f7b2b1ea.png)
请问SSLD蒸馏训练中，有使用mixup这些trick吗？ 比如上表的83.0，有使用mixup吗？

**Comment by cuicheng01** [comment]
没有使用mixup，但是使用了诸如randaugment这样的策略，其他的数据增强没有怎么使用。

**Comment by marvis** [comment]
@cuicheng01 可以更加详细的描述一下ResNet50_vd_ssld_v2  83.0%这个模型的训练过程吗? 在线文档里面只用了一句话描述 “ResNet50_vd_ssld_v2是在ResNet50_vd_ssld训练策略的基础上加上AutoAugment训练得到”。 我不明白ResNet50_vd_ssld_v2是从头训练得到的， 还是用ResNet50_vd_ssld 82.4%模型finetune得到的？
