### ISSUE TITLE
请问 有可以使用visreader的版本开源吗？

### ISSUE THREAD

**Issue by IamMegatron2025** [PaddlePaddle/PaddleClas#1073]
您好，我的数据交大，在aiflow上，请问 有可以使用visreader的版本吗？

**Comment by weisy11** [comment]
I don't understand your questions. You can speak English if you need.

**Comment by cuicheng01** [comment]
> 您好，我的数据交大，在aiflow上，请问 有可以使用visreader的版本吗？

visreader需要自己配一下，是内部用户吗？可以如流上联系我
