### ISSUE TITLE
同一个inference模型，使用源码进行预测正确，whl包预测结果错误

### ISSUE THREAD

**Issue by wjrjsdx** [PaddlePaddle/PaddleClas#1074]
最新版代码，训练得到颜色9分类模型，用训练模型预测（tools/infer.py）正确，然后导出infernce模型，预测（python/predict_cls.py）也正确：
python python/predict_cls.py -c configs/inference_9cls_finetune.yaml
![image](https://user-images.githubusercontent.com/63723648/126728550-506a5797-61c6-41fd-9140-b79748f3059d.png)

但是使用whl包预测错误：
from paddleclas import PaddleClas
clas = PaddleClas(inference_model_dir=r'F:\pycharm_projects\PaddleClas\inference\9cls_finetune', class_id_map_file=r'F:\pycharm_projects\PaddleClas\ppcls\configs\appearance\9cls.txt', topk=2)
infer_imgs = r'E:\appearance\vehicle_color_cls\paddle\crop_9cls_test\train\0111_184.jpg'
result=clas.predict(infer_imgs)
print(next(result))
![image](https://user-images.githubusercontent.com/63723648/126728585-983bf1a2-a8f1-4ef9-8ccd-3a03d297c9ad.png)

没有改任何代码，尺寸啥都是默认的，但是结果就是不一样。

相关文件见网盘链接
链接：https://pan.baidu.com/s/1R6bUmbytDjvuF7snp9_OkA 
提取码：tt94

**Comment by cuicheng01** [comment]
收到问题，我们会持续跟进。

**Comment by TingquanGao** [comment]
感谢反馈！该问题已修复：
https://github.com/PaddlePaddle/PaddleClas/pull/1075
https://github.com/PaddlePaddle/PaddleClas/pull/1076

可尝试参考文档本地编whl包并安装：
https://github.com/PaddlePaddle/PaddleClas/blob/c7c98efd6d5681fefcee2ddeabdf0a45289ec2f8/docs/zh_CN/whl.md#1-%E5%AE%89%E8%A3%85
```bash
python3 setup.py bdist_wheel
pip3 install dist/*
```

我们也会尽快将修复后的whl包推送到pypi。

**Comment by wjrjsdx** [comment]
本地构建后，测试结果正确

**Comment by ayansengupta17** [comment]
The issue still exists in paddleclass=2.4.3
