### ISSUE TITLE
配置文件中eval infer阶段中cropimage考虑的是什么？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleClas#1077]
ppcls\configs\quick_start\professional\ResNet50_vd_mixup_CIFAR100_finetune.yaml
前面已经有resizeimage控制大小了，这个是为了分割大小投票预测结果吗？

**Comment by littletomatodonkey** [comment]
你好，reisze只是将图片等比例缩放到短边256, 之后还需要对图片进行crop（crop出中心的区域，大小为224x224），作为标准的图像输入大小
