### ISSUE TITLE
关于向量检索可否动态加载到内存中的问题！

### ISSUE THREAD

**Issue by Zhangxinnian** [PaddlePaddle/PaddleClas#1081]
请问，这里使用的Möbius向量检索算法支持类似于faiss的那种index.add()的功能吗，如果有的话，我要怎么实现，
此外这个Möbius检索算法每次构建新的图都要进行train吗，这里的train是为了检索加速还是为了构建相似的图呀，
还请详细解答一下我的疑惑，十分感谢，辛苦！

**Comment by Intsigstephon** [comment]
Mobius提供的检索算法是一种基于图的近似最近邻搜索算法，目前支持两种距离计算方式：inner product和L2 distance.  faiss中提供的index.add功能暂时不支持，如果需要增加检索库的内容，需要从头重新构建新的index.  在每次构建index时，检索算法内部执行的操作是一种类似于train的过程，不同于faiss提供的train接口，我们命名为build, 主要的目的是为了加速检索的速度

**Comment by Zhangxinnian** [comment]
> Mobius 提供的检索算法是一种基于图的近邻搜索算法，目前支持的两种距离计算：内积和L2距离。faiss中提供的index.add功能暂时不支持，如果需要增加检索库的内容，需要从头构建新的index。在每次构建索引时，检索算法的内部执行的操作是一种特定的列车的过程，产生的方法是提供的列车，我们本来就是为了构建，主要的目的是为了加速检索的速度

好的，十分感谢您的回复，辛苦！
