### ISSUE TITLE
ResNeXt101_32x48d_wsl 训练异常

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleClas#1086]
aistudio 2.1  ppcls 2.2
File "/home/aistudio/PaddleClas-release-2.2/ppcls/arch/backbone/model_zoo/resnext101_wsl.py", line 484, in ResNeXt101_32x48d_wsl
    model = ResNeXt101WSL(cardinality=32, width=48, **kwargs)
NameError: name 'kwargs' is not defined

**Comment by weisy11** [comment]
确实，这是个bug，我们修一下

**Comment by cuicheng01** [comment]
> aistudio 2.1 ppcls 2.2
> File "/home/aistudio/PaddleClas-release-2.2/ppcls/arch/backbone/model_zoo/resnext101_wsl.py", line 484, in ResNeXt101_32x48d_wsl
> model = ResNeXt101WSL(cardinality=32, width=48, **kwargs)
> NameError: name 'kwargs' is not defined

之前的这个问题已修复哈~
