### ISSUE TITLE
似乎没有f1 score的评价指标？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleClas#1087]
这在分类中应该算是常用指标吧

**Comment by weisy11** [comment]
不算是，因为分类里面没有tn，也不区分fp和fn，结果要么是true要么是false

**Comment by bbbxixixixi** [comment]
> 不算是，因为分类里面没有tn，也不区分fp和fn，结果要么是true要么是false

f1不是平衡acc和recall的一个指标吗？

**Comment by weisy11** [comment]
> > 不算是，因为分类里面没有tn，也不区分fp和fn，结果要么是true要么是false
> 
> f1不是平衡acc和recall的一个指标吗？

不是，f1是平衡precision和recall的指标，跟acc没有关系

**Comment by weisy11** [comment]
F1计算公式：
![Image](https://wikimedia.org/api/rest_v1/media/math/render/svg/4179c69cf1dde8418c4593177521847e862e7df8)
详情见：https://en.wikipedia.org/wiki/F-score

**Comment by bbbxixixixi** [comment]
> > > 不算是，因为分类里面没有tn，也不区分fp和fn，结果要么是true要么是false
> > 
> > 
> > f1不是平衡acc和recall的一个指标吗？
> 
> 不是，f1是平衡precision和recall的指标，跟acc没有关系

是的，我前面搞错了，但是按照https://www.v7labs.com/blog/image-classification-guide这里面介绍，f1 score是图像分类中一个比较重要的指标

**Comment by weisy11** [comment]
> https://www.v7labs.com/blog/image-classification-guide

我们不对第三方的文章发表看法哈，如果有权威的benchmark采用F1-score，我们会加上的。
