### ISSUE TITLE
数据列表文件 delimiter

### ISSUE THREAD

**Issue by davidlinhl** [PaddlePaddle/PaddleClas#110]
貌似配置里面不能设置数据列表的delimiter，我这数据集里面文件名带空格，能用 | 的话会很方便

**Comment by littletomatodonkey** [comment]
您好，目前PaddleClas还没有支持delimiter可配置，如果您需要修改为"|"的话，可以将这里手动修改为
https://github.com/PaddlePaddle/PaddleClas/blob/7dc5bc9b730321ee31e55f69052fb2dc1ad260bb/ppcls/data/reader.py#L191

```python
img_path, label = line.split("|") 
```

我们也会尽快支持可配置delimiter的功能，感谢您的关注。

**Comment by davidlinhl** [comment]
收到，已经看到了。paddleseg有这个功能觉得很方便，希望能添加。辛苦啦
