### ISSUE TITLE
paddleclas运行出错，但结果却出来了

### ISSUE THREAD

**Issue by davidwkx** [PaddlePaddle/PaddleClas#1101]
运行python python/predict_system.py -c configs/inference_product.yaml -o Global.infer_imgs="/tmp/qsc.jpg" -o IndexProcess.index_path="./recognition_demo_data_v1.0/gallery_product/index_update"  -o Global.use_gpu=False
出现如下错误信息：
WARNING: AVX is supported on local machine, but you have installed paddlepaddle without avx core. Hence, no_avx core which has worse preformance will be imported.You could reinstall paddlepaddle by 'python -m pip install --force-reinstall paddlepaddle-gpu[==version]' or rebuild paddlepaddle WITH_AVX=ON to get better performance.
**The original error is: No module named 'paddle.fluid.core_avx'**

但最后结果还是正常出来了

用虚拟环境python3.8
paddlepaddle按如下命令安装的：
python -m pip install paddlepaddle-2.1.1.noavx-cp38-cp38-linux_x86_64.whl

机器信息：centos7 python3.8.11 gcc8.2.0 安装paddlepaddle2.1.1 cpu版 机器支持 avx2指令集

**Comment by weisy11** [comment]
如果机器支持avx没有必要安装noavx的版本，安装普通的paddle就可以了

**Comment by davidwkx** [comment]
感谢
