### ISSUE TITLE
数据增强实验结果的超参数设置

### ISSUE THREAD

**Issue by rederyang** [PaddlePaddle/PaddleClas#1102]
首先感谢贵团队的工作。
在[此页面](https://paddleclas.readthedocs.io/zh_CN/latest/advanced_tutorials/image_augmentation/ImageAugment.html#)展示了使用不同数据增强方法得到的实验结果。请问这些实验中数据增强的超参数（如Cutmix和Mixup中的alpha）设置是怎样的？是否就是[这里](https://github.com/PaddlePaddle/PaddleClas/tree/2c7ce3c0f8b34477fa341fab0cd0e9510bc02cb9/ppcls/configs/ImageNet/DataAugment)的参数？
期待回复，谢谢！

**Comment by cuicheng01** [comment]
嗨，您好，数据增强中的超参数就是使用的您提供的这个链接中的超参数。

**Comment by rederyang** [comment]
谢谢！
