### ISSUE TITLE
关于添加新的数据与标签

### ISSUE THREAD

**Issue by DongChenwei2000** [PaddlePaddle/PaddleClas#1103]
开发者你好，我想要添加新的数据和标签，请问数据和标签的摆放有其他的要求吗
能否像这样
gallery/anmuxi/001.jpg	安慕希酸奶
gallery/mengniu/001.jpg	蒙牛牛奶
gallery/guangming/001.jpg	光明牛奶
gallery/anmuxi/002.jpg	安慕希酸奶
gallery/mengniu/002.jpg	蒙牛牛奶
gallery/guangming/002.jpg	光明牛奶
gallery/anmuxi/003.jpg	安慕希酸奶
gallery/mengniu/003.jpg	蒙牛牛奶
gallery/guangming/003.jpg	光明牛奶
gallery/anmuxi/004.jpg	安慕希酸奶
gallery/mengniu/004.jpg	蒙牛牛奶
gallery/guangming/004.jpg	光明牛奶
gallery/anmuxi/005.jpg	安慕希酸奶
gallery/mengniu/005.jpg	蒙牛牛奶
gallery/guangming/005.jpg	光明牛奶
还是说只能够像这样
gallery/anmuxi/001.jpg	安慕希酸奶
gallery/anmuxi/002.jpg	安慕希酸奶
gallery/anmuxi/003.jpg	安慕希酸奶
gallery/anmuxi/004.jpg	安慕希酸奶
gallery/anmuxi/005.jpg	安慕希酸奶
gallery/anmuxi/006.jpg	安慕希酸奶
gallery/mengniu/001.jpg	蒙牛牛奶
gallery/mengniu/002.jpg	蒙牛牛奶
gallery/mengniu/003.jpg	蒙牛牛奶
gallery/mengniu/004.jpg	蒙牛牛奶
gallery/mengniu/005.jpg	蒙牛牛奶
gallery/mengniu/006.jpg	蒙牛牛奶
gallery/guangming/001.jpg	光明牛奶
gallery/guangming/002.jpg	光明牛奶
gallery/guangming/003.jpg	光明牛奶
gallery/guangming/004.jpg	光明牛奶
gallery/guangming/005.jpg	光明牛奶
gallery/guangming/006.jpg	光明牛奶

**Comment by weisy11** [comment]
建库的时候没有要求，注意分隔符不要写错就好。
训练的时候与所使用的loss有关系，最好是按顺序排列。
