### ISSUE TITLE
物品识别的score

### ISSUE THREAD

**Issue by DongChenwei2000** [PaddlePaddle/PaddleClas#1108]
开发者你好，在使用识别过程中，我返回的score大于1，这是怎么回事呢？
![image](https://user-images.githubusercontent.com/71364549/128194559-446db56a-3723-4814-a327-95a160642170.png)

**Comment by cuicheng01** [comment]
score大于1是因为没有对最终的特征做归一化，做完就是0-1了哈

**Comment by DongChenwei2000** [comment]
想问下归一化在代码的哪个部分，我想看下是否是我在修改代码的过程中遗漏了这部分

**Comment by cuicheng01** [comment]
> 想问下归一化在代码的哪个部分，我想看下是否是我在修改代码的过程中遗漏了这部分

可以详细说一下你的配置以及命令吗？代码的话在deploy/python/predict_rec.py中的feature_normalize里边

**Comment by DongChenwei2000** [comment]
> > 想问下归一化在代码的哪个部分，我想看下是否是我在修改代码的过程中遗漏了这部分
> 
> 可以详细说一下你的配置以及命令吗？代码的话在deploy/python/predict_rec.py中的feature_normalize里边

配置的话我将检测器和识别器更换为自己的，其他的就只改变了embedding_size成128，不知道是不是这个的原因。

**Comment by 553548793** [comment]
> > 想问下归一化在代码的哪个部分，我想看下是否是我在修改代码的过程中遗漏了这部分
> 
> 可以详细说一下你的配置以及命令吗？代码的话在deploy/python/predict_rec.py中的feature_normalize里边

配置的话我将检测器和识别器更换为自己的，其他的就只改变了embedding_size成128，不知道是不是这个的原因。

**Comment by cuicheng01** [comment]
要不看下feature_normalize是否是打开的呢？
