### ISSUE TITLE
CELoss: nan, loss: nan       SwinTransformer_base_patch4_window12_384.yaml

### ISSUE THREAD

**Issue by Williamlizl** [PaddlePaddle/PaddleClas#1109]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如Linux/Windows/MacOS
  b. Python版本号，如Python3.6/7/8
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

`[Epoch 92/120][Iter: 0/149]lr: 0.00010, CELoss: nan, loss: nan, top1: 0.50000, batch_cost: 3.88269s, reader_cost: 0.27595, ips: 4.12085 images/sec, eta: 4:39:37`

**Comment by cuicheng01** [comment]
可以看一下nan是从哪个epoch开始的吗？另外，有加载预训练权重吗？

**Comment by Williamlizl** [comment]
> 可以看一下nan是从哪个epoch开始的吗？另外，有加载预训练权重吗？

嗯，加载预训练权重了了，我调小了lr:0.001,训练集合就2000多张

**Comment by Williamlizl** [comment]
> 可以看一下nan是从哪个epoch开始的吗？另外，有加载预训练权重吗？

epoch 2开始就是nan了，lr小了也还是nan

**Comment by cuicheng01** [comment]
方便说下加载的方式吗？以及是否有warning

**Comment by cuicheng01** [comment]
> > 可以看一下nan是从哪个epoch开始的吗？另外，有加载预训练权重吗？
> 
> epoch 2开始就是nan了，lr小了也还是nan

您好，现在问题解决了吗

**Comment by Williamlizl** [comment]
> 方便说下加载的方式吗？以及是否有warning
加载是训练模型时，自动下载，有warning,

> > > 可以看一下nan是从哪个epoch开始的吗？另外，有加载预训练权重吗？
> > 
> > 
> > epoch 2开始就是nan了，lr小了也还是nan
> 
> 您好

> > > 可以看一下nan是从哪个epoch开始的吗？另外，有加载预训练权重吗？
> > 
> > 
> > epoch 2开始就是nan了，lr小了也还是nan
> 
> 您好，现在问题解决了吗

还没解决，加载是自动下载权重，warning:UserWarning: Skip loading for head.weight. head.weight receives a shape [1024, 1000], but the expected shape is [1024, 2].

**Comment by cuicheng01** [comment]
数据集是什么样的数据集呢，方便提供我们定位下吗

**Comment by VJoer** [comment]
我也出现了这样的情况，我的数据集是二分类总共有1.2W张图片。我把中间的lr设置成0.000000001，损失才不为nan，但是这么小的学习率导致了网络不能收敛
