### ISSUE TITLE
【Question】PaddleClas与PaddleOCR是什么关系

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleClas#1110]
Hi Team，

想问一下PaddleClas与PaddleOCR是什么关系？能详细解释一下吗，谢谢！

**Comment by weisy11** [comment]
一个组织下的2个开源项目。
PaddleClas主要用于图像分类和通用的图像识别；
PaddleOCR用于文字检测、识别。

**Comment by LangDaoAI** [comment]
好的，非常感谢！
