### ISSUE TITLE
想问下，哪里可以找到Fixing the train-test resolution discrepancy实现？

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [PaddlePaddle/PaddleClas#1112]

**Comment by cuicheng01** [comment]
您好，您是说PaddleClas里吗还是？

**Comment by davidwkx** [comment]
是的，用paddleclas下进行图像识别。

**Comment by zimenglan-sysu-512** [comment]
> 您好，您是说PaddleClas里吗还是？

是的，我在paddleclas里面没有找到

**Comment by cuicheng01** [comment]
> > 您好，您是说PaddleClas里吗还是？
> 
> 是的，我在paddleclas里面没有找到

这个PaddleClas没有直接的实现哈，但是用PaddleClas已有的代码可以直接训练哈，这篇文章主要是用更大的分辨率用eval的预处理单独训一下FC层，所以代码配置可以直接将train的数据预处理改为eval的数据预处理，FC之前的梯度停掉就好。

**Comment by zimenglan-sysu-512** [comment]
thanks
