### ISSUE TITLE
运行swin-Transformer 报关于"shape”的错误

### ISSUE THREAD

**Issue by Derek-Kun** [PaddlePaddle/PaddleClas#1113]
a. 具体操作系统，CentOS7
  b. Python版本号，如Python3.7.11
  c. CUDA/cuDNN版本， 如CUDA10.1/cuDNN 7.6.5
 
运行命令 python /PaddleClas-release-2.2/paddleclas.py --infer_imgs=/test_images --model_name=SwinTransformer_large_patch4_window12_384_22kto1k  后报错：
![1628147761(1)](https://user-images.githubusercontent.com/57475881/128307866-e1f81b51-d402-4a41-9290-15ee26023818.png)
![1628147720(1)](https://user-images.githubusercontent.com/57475881/128307786-e113fc75-7e14-4095-abde-f0be2fcd30fc.png)

**Comment by Derek-Kun** [comment]
换成SwinTransformer_large_patch4_window7_224_22kto1k模型就能正常运行

**Comment by TingquanGao** [comment]
请注意模型的输入数据尺寸，对于部分输入为`384*384`的Transformer模型，需要设置参数resize_short=384, crop_size=384，如下所示

```shell
from paddleclas import PaddleClas, get_default_confg
paddleclas --model_name=ViT_base_patch16_384 --infer_imgs='docs/images/whl/demo.jpg' --resize_short=384 --crop_size=384
```

```python
from paddleclas import PaddleClas
clas = PaddleClas(model_name='ViT_base_patch16_384', resize_short=384, crop_size=384)
```

**Comment by Derek-Kun** [comment]
解决啦，感谢~
