### ISSUE TITLE
ResNeXt101_32_16d_wsl

### ISSUE THREAD

**Issue by Lyang-Never** [PaddlePaddle/PaddleClas#1128]
In '' ppcls\arch\backbone\model_zoo\resnext101_wsl.py "，is the link of "ResNeXt101_32x16d_wsl" in MODEL_URLS wrong?
" https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/ResNeXt101_32x16d_wsl_pretrained.pdparams " instead of 
" https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/ResNeXt101_32x816_wsl_pretrained.pdparams"

**Comment by cuicheng01** [comment]
谢谢提出，已修复~
