### ISSUE TITLE
主体检测使用ppyolo训练的模型会报错

### ISSUE THREAD

**Issue by freefoxcm** [PaddlePaddle/PaddleClas#1133]
我将inference_product.yaml钟的det_inference_model_dir替换为ppyolo_r50vd_dcn_1x_coco模型，则会报错：
    InvalidArgumentError: The 2-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [1, 2048, 20, 20], input[1]'s shape = [1, 1, 19, 19].
      [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:20 != inputs_dims[i][j]:19.] (at D:\v2.0.1\paddle\paddle/fluid/operators/concat_op.h:63)
      [operator < concat > error]

请教一下我改如何来调整配置参数？

**Comment by cuicheng01** [comment]
target_size是多少呢？

**Comment by freefoxcm** [comment]
640 640呢，请问image_shape和 target_size都需要淘到608吗？

**Comment by cuicheng01** [comment]
看下保存的模型可视化有什么问题吗？

**Comment by freefoxcm** [comment]
不是太理解您的意思？

**Comment by cuicheng01** [comment]
1.用inference model在netron或者visualdl可视化一下，确定下模型的输入大小；
2.如果是608x608，需要用640x640的分辨率重新保存inference模型；
补充：PP-YOLO默认的分辨率是608x608，PP-YOLO v2默认的分辨率是640x640

**Comment by freefoxcm** [comment]
那请问如果重新用640x640保存inference模型呢，有文档吗？

**Comment by cuicheng01** [comment]
可以参考这里：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/EXPORT_MODEL.md

**Comment by freefoxcm** [comment]
okok，搞定了谢谢~~
