### ISSUE TITLE
关于PaddleClas的产品中文名倒底是什么？

### ISSUE THREAD

**Issue by jhcgt4869** [PaddlePaddle/PaddleClas#1136]
![image](https://user-images.githubusercontent.com/61859193/129189711-4d18bbb1-b521-4a28-8c2f-93d7f4a8f84c.png)

![e45da05c91a411e8bc955648a0427a3d](https://user-images.githubusercontent.com/61859193/129189841-5c64597f-ec59-45e2-9359-6e1f2c72f0c2.jpg)
？？？
求解答

**Comment by weisy11** [comment]
飞桨图像识别套件，截图这个可能是之前的版本

**Comment by jhcgt4869** [comment]
> 飞桨图像识别套件，截图这个可能是之前的版本

这个是我刚刚在前面截的图，英文版本我怕翻译有问题特意选的中文版本，还看了GitHub和gitee，希望你们先审核后评论

**Comment by jhcgt4869** [comment]
![image](https://user-images.githubusercontent.com/61859193/129225014-85de0f8a-1965-4435-951a-e282f91a92c0.png)

**Comment by jhcgt4869** [comment]
![image](https://user-images.githubusercontent.com/61859193/129225195-6bdab143-faae-4ec3-9663-c10c0d7c0939.png)

**Comment by jhcgt4869** [comment]
现在不会说是之前截的图或者是ps的吧？

**Comment by jhcgt4869** [comment]
抱歉，之前是我理解错误了，至于截图我再去查看一下
