### ISSUE TITLE
如何调用infer的结果

### ISSUE THREAD

**Issue by sinoboy168** [PaddlePaddle/PaddleClas#1137]
各位大佬：默认的infer是打印结果，如果我想调用infer的结果，该怎么做啊？多谢！

**Comment by cuicheng01** [comment]
可以参考https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/deploy/python/predict_system.py
里边串通了检测和识别的流程。

**Comment by sinoboy168** [comment]
谢谢，有没有这个模块的介绍文档

**Comment by cuicheng01** [comment]
> 谢谢，有没有这个模块的介绍文档

文档介绍可以参考：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/zh_CN/tutorials/quick_start_recognition.md

代码本身的讲解是没有的哈
