### ISSUE TITLE
车辆的ReID模型

### ISSUE THREAD

**Issue by freefoxcm** [PaddlePaddle/PaddleClas#1138]
车辆的ReID模型预测有测试实例或者文档吗？

**Comment by cuicheng01** [comment]
您好，车辆的测试方式和商品的大致相同，可以参考以下文档：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/zh_CN/tutorials/quick_start_recognition.md

**Comment by freefoxcm** [comment]
但是这个模型没有提供预测的配置文件，我可以从哪里下载或者怎么生成呢？

**Comment by RainFrost1** [comment]
车辆的配置文件是通用的，即细分类和ReID的配置文件可以通用，改一下模型路径就行
