### ISSUE TITLE
模型库

### ISSUE THREAD

**Issue by sinoboy168** [PaddlePaddle/PaddleClas#1139]
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/zh_CN/ImageNet_models_cn.md
这个页面介绍的有些模型在PaddleClas 没有，比如server models 里面的红色五角星的三个模型好像就没有？还有这三个模型都用红色五角星代码，具体哪个模型对应哪个五角星啊？谢谢指点！

**Comment by cuicheng01** [comment]
红色五角星是ssld的蒸馏预训练模型，比如ResNet50_vd_ssld对应的是ResNet50_vd的ssld预训练模型。具体对应的话，模型越大，精度越高。
