### ISSUE TITLE
实现K折交叉验证时报错ValueError: parameter name [weight] have be been used.

### ISSUE THREAD

**Issue by mookixiao** [PaddlePaddle/PaddleClas#1143]
有个问题，如果我要实现k折交叉验证，也就是说对于一个选定的backbone，针对每折数据都要生成一个版本的模型，这样就会报错
![image](https://user-images.githubusercontent.com/51417260/129480604-99a5fdad-91c0-43e7-a0ae-63af4d971e7f.png)

好像是因为PaddleClas提供的官方模型不允许在一次训练中被多次实例化，具体是由ParamAttr这个类来控制
但是如果我把这个注释上（该方法来自于Paddle论坛[动态图中老是报参数名字已存在怎么解决](https://aistudio.baidu.com/paddle/forum/topic/show/982197)），程序倒是能跑通了，但是生成的.pdopt文件没办法再次导入来继续训练（.pdparams倒是可以继续用），说是没办法设置参数，会报错
![image](https://user-images.githubusercontent.com/51417260/129480728-d3776e6c-3ca6-4159-851b-29f8e9beaf7c.png)

注释示例：
![image](https://user-images.githubusercontent.com/51417260/129480707-c4d2f6a8-9c15-4844-a8ea-e933da328bb9.png)

也就是说.pdopt的参数导入是需要借助ParamAttr的，我注释了ParamAttr所以导致参数设置失败

请问怎么解决，怎么既能让我可以在一次训练中多次初始化PaddleClas提供的backbone，又可以使得得到的权重文件（.pdopt）可以再次导入从而继续训练呢？

**Comment by weisy11** [comment]
建议写shell脚本来跑k折

**Comment by mookixiao** [comment]
> 建议写shell脚本来跑k折

谢谢，我之后会尝试这种方式
