### ISSUE TITLE
windows10 index.dll 编译链接错误

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/PaddleClas#1144]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas 2,2
 2. 训练环境信息：
  Windows10 
  Python3.7
 tdm64-gcc-10.3.0-2.exe
 4. 使用mingw32-make编译
xxx\deploy\vector_search>mingw32-make
g++ -shared -fPIC interface.cc -o index.dll -std=c++11 -Ofast  -march=native -g -flto -funroll-loops -DOMP -fopenmp
interface.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 //MIT License
 ^
lto1.exe: warning: -fPIC ignored for target (all code is position independent)
lto1.exe: warning: -fPIC ignored for target (all code is position independent)
lto1.exe: warning: -fPIC ignored for target (all code is position independent)
lto1.exe: warning: -fPIC ignored for target (all code is position independent)
lto1.exe: warning: -fPIC ignored for target (all code is position independent)
lto1.exe: warning: -fPIC ignored for target (all code is position independent)
lto1.exe: warning: -fPIC ignored for target (all code is position independent)
lto1.exe: warning: -fPIC ignored for target (all code is position independent)
lto1.exe: warning: -fPIC ignored for target (all code is position independent)
lto1.exe: warning: -fPIC ignored for target (all code is position independent)
lto1.exe: warning: -fPIC ignored for target (all code is position independent)
lto1.exe: warning: -fPIC ignored for target (all code is position independent)
lto1.exe: warning: -fPIC ignored for target (all code is position independent)
lto1.exe: warning: -fPIC ignored for target (all code is position independent)
lto1.exe: warning: -fPIC ignored for target (all code is position independent)
lto1.exe: warning: -fPIC ignored for target (all code is position independent)
Cannot export _ZNSt6vectorISt4pairIfjESaIS1_EE12emplace_backIJS1_EEEvDpOT_: symbol wrong type (4 vs 3)
Cannot export _ZNSt6vectorISt4pairIfjESaIS1_EE19_M_emplace_back_auxIJRKS1_EEEvDpOT_: symbol wrong type (4 vs 3)
Cannot export _ZNSt6vectorISt4pairIfjESaIS1_EE19_M_emplace_back_auxIJS1_EEEvDpOT_: symbol wrong type (4 vs 3)
Cannot export _ZNSt6vectorISt4pairIifESaIS1_EE12emplace_backIJS1_EEEvDpOT_: symbol wrong type (4 vs 3)
Cannot export _ZNSt6vectorISt4pairIifESaIS1_EE19_M_emplace_back_auxIJS1_EEEvDpOT_: symbol wrong type (4 vs 3)
Cannot export _ZNSt6vectorISt4pairIjS_IS0_IifESaIS1_EEESaIS4_EE12emplace_backIJS4_EEEvDpOT_: symbol wrong type (4 vs 3)
Cannot export _ZNSt6vectorISt4pairIjS_IS0_IifESaIS1_EEESaIS4_EE19_M_emplace_back_auxIJS4_EEEvDpOT_: symbol wrong type (4 vs 3)
Cannot export _ZNSt6vectorIjSaIjEE19_M_emplace_back_auxIJRKjEEEvDpOT_: symbol wrong type (4 vs 3)
collect2.exe: error: ld returned 1 exit status
mingw32-make: *** [Makefile:12: index] Error 1

**Comment by weisy11** [comment]
我们先复现一下这个问题

**Comment by JiaXiao243** [comment]
未复现该问题：
<img width="672" alt="cb6ff017b7408b0cc71de253a5ca73a7" src="https://user-images.githubusercontent.com/37854899/129723769-8c7692fb-6218-4624-b598-af1ab28e5727.png">

**Comment by weisy11** [comment]
这个问题我们没有复现成功，可以试试这个方法：https://stackoverflow.com/questions/28267100/dll-linking-failed-with-lto-using-mingw-w64
下个版本我们将对检索模块进行替换，从根本上解决编译过程的各种问题。
