### ISSUE TITLE
PaddleClas模型加载预训练权重没有考虑infer函数

### ISSUE THREAD

**Issue by Cli98** [PaddlePaddle/PaddleClas#1145]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如Linux/Windows/MacOS
  b. Python版本号，如Python3.6/7/8
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

版本号：PaddleClas release/2.2
只使用paddle库，无其他依赖
MacOS, python 3.7, CPU测试
代码修改了配置文件 ppcls/config/quick_start/Mobilev3_large_x1_0.yaml

这一版的paddleClas的infer.py没有加载checkpoint的功能，所以导致测试基本没效果，看下面这个例子
例子中 0是墨镜， 1是人， 2是卡通， 3是面罩

<img width="959" alt="image" src="https://user-images.githubusercontent.com/19630616/129512660-921d7058-7f59-4e86-ac30-58468c853560.png">

原因是因为，新版的trainer函数在读取checkpoint的时候，并不是在__init__读的，而是跑到train函数读checkpoint。但是infer却忘了读取checkpoint，这直接导致模型用初始化权重去做测试。

我处理了一下这个问题，解决后再看一下同样的输入给出的结果
<img width="921" alt="image" src="https://user-images.githubusercontent.com/19630616/129512993-3f1f4e12-d4a2-4ed6-9277-ba6ae18402d3.png">

如果你们需要我PR的话我可以把改好的代码PR上来 @cuicheng01

**Comment by cuicheng01** [comment]
您好，checkpoints是用来断点训练的，如果只是用来infer的话，配置pretrained_model即可。

**Comment by Cli98** [comment]
> 您好，checkpoints是用来断点训练的，如果只是用来infer的话，配置pretrained_model即可。

@cuicheng01 感谢前辈指教。可是这样子的话，为什么yaml文件要同时定义pretrain_model和checkpoint的路径呢？是不是留pretrain_model就可以了？

我觉得这样子风险系数比较高。或者文档起码写一下是吧？

**Comment by youqingxiaozhua** [comment]
不知道是不是同一个问题，我在使用`python tools/eval.py -o pretrained_model=abc`的时候，他并不是从abc读取参数，而是读了yaml文件里的pretrained_model……
