### ISSUE TITLE
有么有paddleClas模型转onnx，然后使用onnxruntime推理的？想把商品检测转换onnx，来推理？

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/PaddleClas#1146]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如Linux/Windows/MacOS
  b. Python版本号，如Python3.6/7/8
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

**Comment by xinsuinizhuan** [comment]
商品检测的model是，动态图版本，改怎么转？

**Comment by xinsuinizhuan** [comment]
静态图转完后，模型输入是：
![图片](https://user-images.githubusercontent.com/40679769/129546408-6b01c25f-d9fd-4504-9af1-c7b909ac4550.png)

-1*3*224*224，-1导致没法使用

**Comment by TingquanGao** [comment]
-1 为 batch size，表示可以接受任意batch size，会根据输入自动推算该维度大小。
关于转onnx，如果有 `pdmodel` 和 `pdiparams` 文件，可参考：
https://github.com/PaddlePaddle/Paddle2ONNX

如果有 `pdparams` 文件和模型组网代码，可参考：
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/09_model_to_onnx_cn.html
