### ISSUE TITLE
商品识别的类别文件时哪个？

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/PaddleClas#1147]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如Linux/Windows/MacOS
  b. Python版本号，如Python3.6/7/8
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

**Comment by weisy11** [comment]
请您详细描述一下遇到的问题，谢谢。

**Comment by xinsuinizhuan** [comment]
就是，没看到商品分类里面，表示类别的配置文件，比如我的classid=0,表示什么类别，是旺仔，还是娃哈哈。然后，最后看代码是通过vector_inf那个里面来做的，vector_info那个里面也没看到那个表示列表的文件。

**Comment by weisy11** [comment]
我们似乎没有商品分类模型，只有商品识别模型。商品识别模型不输出分类，只输出特征，根据检索计算的结果可以确定分类。我们目前提供的检索库会返回明确的识别结果。
另外，用于商品识别模型训练的Aliproduct的pretrain是带有分类层的，分类结果对应原数据集的类别标签。Aliproduct没有给出这些类别的标签，我们这里也没有。另外也不建议直接使用这个模型的分类结果用于预测。
