### ISSUE TITLE
ERROR: Unexpected segmentation fault encountered in DataLoader workers. 

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/PaddleClas#1149]
ERROR: Unexpected segmentation fault encountered in DataLoader workers.

**Comment by youngstu** [comment]
把num_workers=0 设置为0修复，但是虽然设置为0不报错，但是无法使用多线程加载数据，模型训练效率可能会受到影响

**Comment by luckysheep861** [comment]
遇到了相同问题，请问解决了吗。。
