### ISSUE TITLE
ResizeImage和CropImage

### ISSUE THREAD

**Issue by ITerydh** [PaddlePaddle/PaddleClas#1153]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2
 2. 环境是aistudio的paddle2.1.0在线环境
 3. 在对yaml进行图像大小的预处理时，ResizeImage和CropImage必须配套使用嘛？我只使用ResizeImage将尺寸改为224会报错，再加上一个CropImage224就没有报错了，这是为什么呢？

**Comment by Intsigstephon** [comment]
理论上是可以单独使用或者是联合使用的。 单独使用ResizeImage(224)会报什么错呢，相应的错误提示信息发下吧
