### ISSUE TITLE
mixup 训练报错

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/PaddleClas#1157]
```
Traceback (most recent call last):
  File "tools/train.py", line 31, in <module>
    trainer.train()
  File "/home/yangshaoxiong/shaoxiong/handpp_work/cls_work/work_exps/v3_0_2_ppcls_shufflenetV2_x1_0_reso112_exp_mixup/ppcls/engine/trainer.py", line 229, in train
    metric_dict = self.train_metric_func(out, batch[-1])
  File "/home/yangshaoxiong/shaoxiong/handpp_work/cls_work/work_exps/v3_0_2_ppcls_shufflenetV2_x1_0_reso112_exp_mixup/ppcls/metric/__init__.py", line 42, in __call__
    metric_dict.update(metric_func(*args, **kwargs))
  File "/home/yangshaoxiong/.conda/envs/py36_paddle2.1/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/yangshaoxiong/shaoxiong/handpp_work/cls_work/work_exps/v3_0_2_ppcls_shufflenetV2_x1_0_reso112_exp_mixup/ppcls/metric/metrics.py", line 35, in forward
    x, label, k=k)
  File "/home/yangshaoxiong/.conda/envs/py36_paddle2.1/lib/python3.6/site-packages/paddle/metric/metrics.py", line 802, in accuracy
    total)
ValueError: (InvalidArgument) ShapeError: label's dimensions of AccuracyOp must be 2. But received label's dimensions = 1, label's shape = [256]
  [Hint: Expected label_dim.size() == 2, but received label_dim.size():1 != 2:2.] (at /paddle/paddle/fluid/operators/metrics/accuracy_op.cc:62)
  [operator < accuracy > error]
```

**Comment by Intsigstephon** [comment]
label's dimensions of AccuracyOp must be 2. But received label's dimensions = 1, label's shape = [256]
依据这句提示，label的维度需要做个升维操作， 参考下paddle.unsqueeze()
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/unsqueeze_cn.html#unsqueeze

**Comment by youngstu** [comment]
使用mixup增强训练时，把metric-Topk 关闭掉解决了

**Comment by Intsigstephon** [comment]
好的

**Comment by se7enXF** [comment]
@Intsigstephon 我也遇到这个问题了，根本原因是使用batch_transform输出的label形状为[batch, cls_num]，而没有这个batch数据增强时输出的label形状为[batch, 1]。也就是说batch_transform的输出被one-hot了，这和默认情况不统一。或者说label的形状本应该是one-hot的，默认情况的[batch, 1]是不常规的。我把发现的问题归纳一下：   
- 模型输出是one-hot解构，默认情况的label输入是标签的int，这不规范，数据预处理就是要统一规范化数据；
- paddle.argmax 默认输出会降维，这不符合常识；
- paddle.metric.accuracy 输入x和label维度不同，sklearn里不会这么做。 

还有一些细节问题不再赘述，希望paddle越做越好。

**Comment by weisy11** [comment]
> @Intsigstephon 我也遇到这个问题了，根本原因是使用batch_transform输出的label形状为[batch, cls_num]，而没有这个batch数据增强时输出的label形状为[batch, 1]。也就是说batch_transform的输出被one-hot了，这和默认情况不统一。或者说label的形状本应该是one-hot的，默认情况的[batch, 1]是不常规的。我把发现的问题归纳一下：
> 
> * 模型输出是one-hot解构，默认情况的label输入是标签的int，这不规范，数据预处理就是要统一规范化数据；
> * paddle.argmax 默认输出会降维，这不符合常识；
> * paddle.metric.accuracy 输入x和label维度不同，这个简直就离谱，sklearn里也不会这么做。
> 
> 还有一些细节问题不再赘述，希望paddle越做越好。

请理性讨论技术问题。

1.sklearn的accuracy，可以参考这个文档：https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html#sklearn.metrics.accuracy_score
paddle的accuracy，可以参考这个文档：
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/metric/accuracy_cn.html#accuracy
2.numpy的argmax，可以参考这个文档：https://numpy.org/doc/stable/reference/generated/numpy.argmax.html
torch的argmax可以参考这个文档：
https://pytorch.org/docs/stable/generated/torch.argmax.html
paddle的argmax，可以参考这个文档：
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/argmax_cn.html#argmax

**Comment by se7enXF** [comment]
@weisy11 我不明白为什么paddle的上述两种函数要特别设置，但是我认为这样做会增加开发成本，反而不利于paddle的推广。学术圈近80%模型开发使用pytorch，参数默认形式向其对齐，我认为有利于paddle在学术圈推广。sklearn是机器学习经典的统计分析库，函数的默认参数向其对齐，我认为没有问题。也许paddle想独树一帜，但我想这不利于推广。
