### ISSUE TITLE
paddleCls模型导出后预测无法和PadddleCls inference对齐

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/PaddleClas#1167]
问题描述：

使用paddleCls_shufflenetV2_x1_0 结构训练的分类模型，使用export_model.py导出后使用paddle静态图预测，预测结果错误，且无法和PaddleCls提供的infer.py 对齐

**Comment by youngstu** [comment]
方便如流联系嘛

**Comment by cuicheng01** [comment]
好的，如流找我吧

**Comment by youngstu** [comment]
已经定位到问题解决了，原因是export_model.py 导出的时候模型参数指定不正确导致。谢谢～

旧的：
-o weights=output/ShuffleNetV2_x1_0/best_model.pdparams

新的：
-o Global.pretrained_model=output/ShuffleNetV2_x1_0/best_model

**Comment by cuicheng01** [comment]
好的
