### ISSUE TITLE
增大batch后Segmentation fault

### ISSUE THREAD

**Issue by ShawnXsw** [PaddlePaddle/PaddleClas#1170]
1. PaddleClas release/2.2
 2. 涉及的其他产品使用的版本号：null
 3. 训练环境信息：
  a. 具体操作系统，Linux，显卡：RTX titanV（24G显存）
  b. Python版本号，Python3.7
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 8.0
 4. 错误信息：
模型：ResNet50_vd_ssld（inputsize=224，batchsize=32 训练正常）
修改size224 to 384，batchsize升高至32，train报错：
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1629788153 (unix time) try "date -d @1629788153" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 33489 (TID 0x7fd76127a740) from PID 0 ***]

Segmentation fault (core dumped)

**同时显存不释放，需要手动kill PID**

降低batchSize至8后，训练正常。

**Comment by ShawnXsw** [comment]
降低batchSize32至8后，其他不改，训练正常，显存占用：
![image](https://user-images.githubusercontent.com/33308054/130573343-699af0c7-acf2-4106-836e-3a57fa55ab6a.png)

**Comment by cuicheng01** [comment]
问题我们跟进下哈

**Comment by 54wb** [comment]
> 降低batchSize32至8后，其他不改，训练正常，显存占用： ![image](https://user-images.githubusercontent.com/33308054/130573343-699af0c7-acf2-4106-836e-3a57fa55ab6a.png)

hi，请问这个错误是什么原因呢，是因为显存不够了嘛

**Comment by Totoro-wen** [comment]
请问解决了吗
