### ISSUE TITLE
请问ppcls支持3D数据集分类吗？

### ISSUE THREAD

**Issue by zhongqiu1245** [PaddlePaddle/PaddleClas#1177]
请问ppcls支持3D数据集分类吗？
比如读入MRI肿瘤的nii文件之后对其进行分类？
谢谢！

**Comment by cuicheng01** [comment]
目前PaddleClas支持的主要是常规图像数据哈，如果是3D的数据，需要稍微修改一些代码，主要是输入那块，如果涉及3D的model，也需要对应更改下~

**Comment by zhongqiu1245** [comment]
谢谢
