### ISSUE TITLE
部分超链接404

### ISSUE THREAD

**Issue by jhcgt4869** [PaddlePaddle/PaddleClas#1178]
文档地址：
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/en/tutorials/getting_started_en.md

![image](https://user-images.githubusercontent.com/61859193/130821680-ad0d93f5-70db-487e-8e53-0c4389d7191f.png)

上面超链接地址为：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/en/tutorials/config_en.md

![image](https://user-images.githubusercontent.com/61859193/130821783-8e42439b-3430-472c-a826-d12447aa0f65.png)

希望尽快修复问题

**Comment by jhcgt4869** [comment]
应该是：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/en/tutorials/config_description_en.md
吧

**Comment by cuicheng01** [comment]
已修复~
