### ISSUE TITLE
PaddleClas文档过期

### ISSUE THREAD

**Issue by franva** [PaddlePaddle/PaddleClas#1189]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：
 PaddlePaddle: 2.1.2
PaddleClas就是 github上的release/2.2

2. 训练环境信息：
  a. 具体操作系统，Ubuntu 20.04
  b. Python版本号，如Python3.8.8
  c. CUDA/cuDNN版本， CUDA11.2

根据最新的[PaddleClas文档](https://paddleclas.readthedocs.io/zh_CN/latest/tutorials/quick_start.html), 在安装完一切需求后,试图根据教程下载预训练模型,如下
![image](https://user-images.githubusercontent.com/5151146/131216916-e425e713-b25b-4fff-b302-ead63f49e22f.png)

但是发现PaddleClas的项目种根本就没有`download.py`这个文件

https://github.com/PaddlePaddle/PaddleClas/tree/release/2.2/tools
![image](https://user-images.githubusercontent.com/5151146/131216968-1cc36fcc-103c-45fb-8362-90635fae7a20.png)

**Comment by cuicheng01** [comment]
您好，这个文档确实过期了，我们近期会整个重新更新一次文档。最新的操作指南可以直接看PaddleClas的github文档哈
