### ISSUE TITLE
when infer a image: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by zhengbiqing** [PaddlePaddle/PaddleClas#119]
aistudio@jupyter-305239-473669:~/work/PaddleClas$ python tools/infer/predict.py -m output_ca/ResNet50_vd/last/model -p output_ca/ResNet50_vd/last/params -i ./test0.jpg --use_gpu=1
Traceback (most recent call last):
  File "tools/infer/predict.py", line 160, in <module>
    main()
  File "tools/infer/predict.py", line 121, in main
    inputs = preprocess(args.image_file, operators)
  File "tools/infer/predict.py", line 88, in preprocess
    data = open(fname).read()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

what the problem?

**Comment by zhengbiqing** [comment]
已解决。修改tools/infer/predict.py：
data = open(fname, 'rb').read()
为：
with open(fname, 'rb') as f:
    data = f.read()

**Comment by littletomatodonkey** [comment]
好的，这个py3兼容的图片读取文件之前已经修复了哈，您拉下最新代码应该就可以的~，也可以参考这里

https://github.com/PaddlePaddle/PaddleClas/blob/f8be9fa37b4691af67cd17aa89e4d509c1f4e32f/tools/infer/predict.py#L88

**Comment by JiaXiao243** [comment]
目前代码库中tools/infer/predict.py：data = open(fname, 'rb').read()，是没有问题的；你之前用的是旧代码，data = open(fname).read()，在python3上会报该问题，该问题之前已修复；
![image](https://user-images.githubusercontent.com/37854899/82044146-5f5c9d80-96df-11ea-8159-21fc256dc754.png)
