### ISSUE TITLE
下载的预训练模型没有pdmodel, pdparam

### ISSUE THREAD

**Issue by franva** [PaddlePaddle/PaddleClas#1190]
![image](https://user-images.githubusercontent.com/5151146/131217066-b5ebbe4e-68cb-420a-ad91-8e63f5174a6c.png)

模型地址:
https://paddle-imagenet-models-name.bj.bcebos.com/MobileNetV3_small_x1_0_pretrained.tar

**Comment by RainFrost1** [comment]
这个应该是静态的模型。动态图模型地址参考：[动态图模型](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/zh_CN/ImageNet_models_cn.md#%E7%A7%BB%E5%8A%A8%E7%AB%AF%E7%B3%BB%E5%88%97)

**Comment by franva** [comment]
非常感谢~!
