### ISSUE TITLE
未知类别的图像识别，运行异常

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleClas#1196]
aistudio环境 paddlecls版本2.2
照着https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/tutorials/quick_start_recognition.md中的操作，报了以下的错误
2021-08-27 15:24:33 INFO: ToCHWImage : None
0%| | 0/400 [00:03<?, ?it/s]
Traceback (most recent call last):
File "/home/aistudio/PaddleClas-release-2.2/deploy/python/build_gallery.py", line 101, in
main(config)
File "/home/aistudio/PaddleClas-release-2.2/deploy/python/build_gallery.py", line 94, in main
system_builder = GalleryBuilder(config)
File "/home/aistudio/PaddleClas-release-2.2/deploy/python/build_gallery.py", line 61, in init
self.build(config['IndexProcess'])
File "/home/aistudio/PaddleClas-release-2.2/deploy/python/build_gallery.py", line 81, in build
gallery_features[i, :] = rec_feat
ValueError: could not broadcast input array from shape (120,) into shape (512,)

配置文件如下
Global:
  rec_inference_model_dir: "/home/aistudio/inference"
  batch_size: 1
  use_gpu: True
  enable_mkldnn: False
  cpu_num_threads: 100
  enable_benchmark: True
  use_fp16: False
  ir_optim: True
  use_tensorrt: False
  gpu_mem: 8000
  enable_profile: False

RecPreProcess:
  transform_ops:
    - ResizeImage:
        size: 480
    - NormalizeImage:
        scale: 1.0/255.0
        mean: [0.477, 0.484, 0.444]
        std: [0.26, 0.254, 0.275]
        order: ''
    - ToCHWImage:

RecPostProcess: null

# indexing engine config
IndexProcess:
  index_path: "/home/aistudio/data/index"
  image_root: "/home/aistudio/data/train_all"
  data_file:  "/home/aistudio/test_update_file.txt"
  append_index: False
  delimiter: "\t"
  dist_type: "IP"
  pq_size: 100
  embedding_size: 512

我原本的类型有120个，配置文件中的embedding_size是512，这两个需要匹配吗？embedding_size感觉应该是中间过程的特征维度，如果要匹配，为何不直接从原始的model中获取？

**Comment by cuicheng01** [comment]
您好，这个模型是您自己训练的是吧，训练配置的FC那块确实有歧义，导致实际的embedding-size是120，这块我们之后修复下。现在您在这个配置文件中的embedding_size改成120即可~
