### ISSUE TITLE
关于主体检测训练数据问题

### ISSUE THREAD

**Issue by xiaodongyichuan** [PaddlePaddle/PaddleClas#1197]
请问训练主体检测 ，公开数据选择中的数据量是图片张数，还是标注框数，还是类别数？

Objects365 | 170W | 6k | 通用场景 | 
COCO2017 | 12W | 5k | 通用场景 | 
iCartoonFace | 2k | 2k | 动漫人脸检测 | 
LogoDet-3k | 3k | 2k | Logo检测 | 
RPC | 3k | 3k | 商品检测 |

**Comment by littletomatodonkey** [comment]
你好，这里指的是图片张数。对于logo数据集，每张图片平均只有1个标注框，对于coco，obj365等数据集，一张图片中会有多个标注框
