### ISSUE TITLE
未知类别的图像分类有例子可以参考吗？前面几个issue提得有问题

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleClas#1201]
这几天问了关于这方面的内容，由于问的是图像识别，造成了误解，现在照着识别的流程做下去报了异常
我自己训练了一个120类的图像分类模型，现在测试集是其他未知的20个类别，这个情况要如何操作？

照着识别的流程做下去，异常出在predict_system.py这一步
inference_product.yaml的配置如下
Global:
  infer_imgs: "/home/aistudio/data/samples_query/query/00001.jpg"
  det_inference_model_dir: "/home/aistudio/inference"
  rec_inference_model_dir: "/home/aistudio/inference"
  rec_nms_thresold: 0.05
  
  batch_size: 1
  image_shape: [3, 480, 480]
  threshold: 0.2
  max_det_results: 5
  labe_list:
  - foreground

  # inference engine config
  use_gpu: True
  enable_mkldnn: False
  cpu_num_threads: 100
  enable_benchmark: True
  use_fp16: False
  ir_optim: True
  use_tensorrt: False
  gpu_mem: 8000
  enable_profile: False

DetPreProcess:
  transform_ops:
    - DetResize:
        interp: 2
        keep_ratio: false
        target_size: [480, 480]
    - DetNormalizeImage:
        is_scale: true
        mean: [0.477, 0.484, 0.444]
        std: [0.26, 0.254, 0.275]
    - DetPermute: {}
DetPostProcess: {}

RecPreProcess:
  transform_ops:
    - ResizeImage:
        size: 480
    - NormalizeImage:
        scale: 1.0/255.0
        mean: [0.477, 0.484, 0.444]
        std: [0.26, 0.254, 0.275]
        order: ''
    - ToCHWImage:

RecPostProcess: null

# indexing engine config
IndexProcess:
  index_path: "/home/aistudio/data/index"
  search_budget: 100
  return_k: 20
  dist_type: "IP"
  score_thres: 0.5

异常如下
Traceback (most recent call last):
  File "/home/aistudio/PaddleClas-release-2.2/deploy/python/predict_system.py", line 134, in <module>
    main(config)
  File "/home/aistudio/PaddleClas-release-2.2/deploy/python/predict_system.py", line 125, in main
    output = system_predictor.predict(img)
  File "/home/aistudio/PaddleClas-release-2.2/deploy/python/predict_system.py", line 89, in predict
    results = self.det_predictor.predict(img)
  File "/home/aistudio/PaddleClas-release-2.2/deploy/python/predict_det.py", line 117, in predict
    input_tensor.copy_from_cpu(inputs[input_names[i]])
KeyError: 'x'

**Comment by cuicheng01** [comment]
`我自己训练了一个120类的图像分类模型`这个模型怎么训练的呢，方便可视化一下inference model吗

**Comment by bbbxixixixi** [comment]
> `我自己训练了一个120类的图像分类模型`这个模型怎么训练的呢，方便可视化一下inference model吗

就是用ppcls的模型训练的，Arch.class_num设置为120

**Comment by looooooooosee** [comment]
解决了吗~    KeyError: 'x'  我也遇到了 寂寞

**Comment by FrankMMMMMM** [comment]
@looooooooosee @bbbxixixixi @cuicheng01 
您好 解决了吗？可以共享下解决方案吗？谢谢
