### ISSUE TITLE
训练Reid模型类别数少时评价指标不变化，且看不到训练过程。

### ISSUE THREAD

**Issue by lazyn1997** [PaddlePaddle/PaddleClas#1203]
1. PaddleClas版本以及PaddlePaddle版本：PaddleClas release/2.2和PaddlePaddle 2.1.0
 3. 训练环境信息：
  a. 操作系统，如Windows
  b. Python版本号，如Python3.7.10
  c. CUDA/cuDNN版本， 如CUDA11.2/cuDNN 8.1.1
我需要识别同一种鱼的不同个体，其中训练数据如下图所示，
![LYC001_second_train_5_1](https://user-images.githubusercontent.com/34644177/131944489-2ca6320d-6128-4ea2-a8c7-ba5973ea76d7.png)

采用的车辆Reid配置文件，未对图像处理以及loss进行修改，只是修改了文件路径，其中训练集与测试集的划分按照图像检索任务进行划分，我一共有637个类，将前242类作为训练集，后395类作为测试集，训练可以正常进行，
![image](https://user-images.githubusercontent.com/34644177/131944775-6a4a337d-ce52-42ee-93a9-f605ac5f9277.png)

然而当类别数只有5个类或50个类时，评价指标不变化，且看不到训练过程，
![1629980507](https://user-images.githubusercontent.com/34644177/131949589-fa4aa09f-713f-4898-aedc-1c65594803db.jpg)

**Comment by weisy11** [comment]
这是个已知bug，修复代码测试中
