### ISSUE TITLE
build检索库的时候， pq_size的大小设置，需要如何和我所要检索的类别数量与单个类别多张图片相适应

### ISSUE THREAD

**Issue by tangdong1994** [PaddlePaddle/PaddleClas#1204]
就是我看你们在初始化设置的时候pg_size=100,那假如我需要识别的类别有150类，其中有一类的图片达到100多张，其他类别也有几十张的，或者几张的。那么这个pg_size是否需要相应的变大，所以这里我想知道pg_size设置的依据是啥，设置它的作用是啥。希望能得到你们的帮助，谢谢🙏

**Comment by weisy11** [comment]
pq_size和类别数没有关系，不需要修改

**Comment by weisy11** [comment]
pq_size是pq检索算法的参数。可以简单理解为这是一种分层检索算法，pq_size是每层的容量。在数据量不太大的情况下，这个参数对性能的影响不是很大，不需要修改

**Comment by tangdong1994** [comment]
> pq_size是pq检索算法的参数。可以简单理解为这是一种分层检索算法，pq_size是每层的容量。在数据量不太大的情况下，这个参数对性能的影响不是很大，不需要修改

好的，了解了。那么假如我要识别的东西有120类的类别数目，其中里面A类的检索图片有110张，B类110张，其他等的类别也都有几十张的数目，也就是一共图片数目有3，4千张的数目。那为了保守起见，我是不是可以把pg_size设置为更大的数字。从而保证建立检索库的时候，不会出现类别之间的覆盖的情况，

**Comment by weisy11** [comment]
不需要修改，几千张图问题不大。
不过，不建议每个类别放太多图，找2-10张有代表性的图就可以了。
