### ISSUE TITLE
在安装了trt-paddle后，出现如下错误

### ISSUE THREAD

**Issue by luckysheep861** [PaddlePaddle/PaddleClas#1215]
Paddle版本2.1.2 (import 时提示You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.)
python版本3.7
cuda版本10.1

请问在安装了trt-paddle后，还是提示缺少TRT动态库：
这个动态库应该如何安装？

    predictor = inference.create_predictor(config)
RuntimeError: (Unavailable) Load tensorrt api getInferLibVersion failed
  [Hint: p_getInferLibVersion should not be null.] (at /paddle/paddle/fluid/platform/dynload/tensorrt.h:114)

_Originally posted by @rainmakerMa in https://github.com/PaddlePaddle/Paddle/issues/34689#issuecomment-895815006_

**Comment by weisy11** [comment]
可能是版本不一致，或者是没找到trt的库。请检查：
1.trt-paddle安装包后缀中的trt、cuda、cudnn版本等是否与本地环境一致
2.当前环境是否能正确找到trt库

**Comment by luckysheep861** [comment]
下载安装对应的TRT包后解决 https://developer.nvidia.com/nvidia-tensorrt-6x-download
