### ISSUE TITLE
EfficientNet目前貌似只有B0版本，请问其他版本什么时候能上线？

### ISSUE THREAD

**Issue by XYZ-916** [PaddlePaddle/PaddleClas#1219]
EfficientNet目前貌似只有BX版本，请问有V2版本吗

**Comment by cuicheng01** [comment]
您好，EfficientNetB0的其他版本权重在这里https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/zh_CN/ImageNet_models_cn.md
训练配置在这里：https://github.com/PaddlePaddle/PaddleClas/pull/1223
EfficientNet目前还没V2哈~

**Comment by XYZ-916** [comment]
谢谢回复。期待EfficientNetV2版本早日上线。
