### ISSUE TITLE
Mixed Precision Training

### ISSUE THREAD

**Issue by sbl1996** [PaddlePaddle/PaddleClas#122]
Mixed precision training is available in [PaddleCV/image_classification](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/image_classification) but not in this repo. According to [Release Notes](https://www.paddlepaddle.org.cn/documentation/docs/en/release_note_en.html) of PaddlePaddle 1.7, AMP interfaces have been added.
![image](https://user-images.githubusercontent.com/13728074/82119257-82ef1900-97af-11ea-8562-a62837436cc2.png)
Based on these, I think it would be convenient to implement it. 

Mixed precision training is critical to fast training on V100. Please consider adding it. Thank you!

**Comment by littletomatodonkey** [comment]
Thanks for your attention, the support for AMP training in PaddleClas is one the way.

**Comment by littletomatodonkey** [comment]
You can refer to this PR for the solution. #124
