### ISSUE TITLE
动漫人物识别的测试集标签id没找到对应的标签

### ISSUE THREAD

**Issue by lhy2001** [PaddlePaddle/PaddleClas#1226]
iCartoonFace中的test集的txt文件中第五列的label_id没找到对应的label
![test_label](https://user-images.githubusercontent.com/61843600/133194411-8f85fcdb-8951-4fbf-9035-67c963753c57.png)
这是train集的标签txt
![train_info](https://user-images.githubusercontent.com/61843600/133194434-a2015060-dd0e-493f-890f-ae5fac3ef277.png)

**Comment by lhy2001** [comment]
train集的label_id怎么给

**Comment by Intsigstephon** [comment]
原数据集里面也只提供了train数据的
