### ISSUE TITLE
ImageNet22k数据集去重

### ISSUE THREAD

**Issue by Ezra-Yu** [PaddlePaddle/PaddleClas#1227]
近期在处理ImageNet22k这个数据集，有一个22k数据集与imagenet1k的验证集存在重复图片的问题。
请问你们可以公开重复图片的list吗？

**Comment by cuicheng01** [comment]
当时去重的是在一个内部处理平台上做的，list目前我们也没有了。不过就是用SIFT匹配卡阈值去重的。
