### ISSUE TITLE
cpp推理结果不对

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleClas#1230]
请问为什么我用cpp推理训练的图像分类模型结果完全不对呢？有什么预处理需要设置吗？

**Comment by Dandelion111** [comment]
训练的时候，验证集的准确率都达到了0.97了，为啥转成inference之后，推理结果却完全不对

**Comment by RainFrost1** [comment]
python的推理跟cpp的推理结果一致吗
