### ISSUE TITLE
eval时-o pretrained_model无法覆盖Global.pretrained_model

### ISSUE THREAD

**Issue by youqingxiaozhua** [PaddlePaddle/PaddleClas#1231]
1. PaddleClas版本以及PaddlePaddle版本： PaddleClas 使用2021年8月9日的commit：659e3d18bcd455cd35757b47e2f7b13ff4f14152 （没有找到在哪里查看version）和PaddlePaddle 2.1.2
 2. 涉及的其他产品使用的版本号：无
 3. 训练环境信息：
  a. 具体操作系统，Linux
  b. Python版本号，如Python3.6
  c. CUDA/cuDNN版本， 如CUDA10.1
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

使用官方eval实例：
```
python tools/eval.py \
    -c ./ppcls/configs/A/B.yaml \
    -o pretrained_model=$ckpt \
    -o load_static_weights=False
```
其并未从$ckpt中读取pretrain，而是从config文件中设置的读取。经检查，可能原因是，config文件中的pretrained_model定义在Global下，而eval中的overwrite没有Global。

**Comment by youqingxiaozhua** [comment]
测试代码：
```
if __name__ == "__main__":
    args = config.parse_args()
    config = config.get_config(
        args.config, overrides=args.override, show=False)
    print(args.override)
    print(config)
    exit()
```

输出：
```
A new filed (pretrained_model) detected!
A new filed (load_static_weights) detected!
['pretrained_model=path/ckpt', 'load_static_weights=False']
{'Global': {'checkpoints': None, 'pretrained_model': None, 'output_dir': './output/',

...

'Eval': [{'TopkAcc': {'topk': [1, 3]}}]}, 'pretrained_model': 'path/ckpt', 'load_static_weights': False}
```

**Comment by TingquanGao** [comment]
你好，覆盖`pretrained_model`时，命令中需要这样写：`-o Global.pretrained_model=`。可以再尝试一下。
另外，`-o pretrained_model`这个命令是哪个文档中写的么？我们修改一下。

**Comment by youqingxiaozhua** [comment]
> 你好，覆盖`pretrained_model`时，命令中需要这样写：`-o Global.pretrained_model=`。可以再尝试一下。
> 另外，`-o pretrained_model`这个命令是哪个文档中写的么？我们修改一下。

你好，文档是在项目主页直接点击Tutorial下面的Image Classification。我已经修改过来了，并提了个PR：https://github.com/PaddlePaddle/PaddleClas/pull/1233

**Comment by TingquanGao** [comment]
感谢~我们尽快review并合入。

**Comment by TingquanGao** [comment]
PR已合入，感谢贡献~

**Comment by TingquanGao** [comment]
PR已合入，感谢贡献~
issue已关闭。
