### ISSUE TITLE
模型训练完，转inference后推理结果完全不对

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleClas#1232]
请问为什么我用cpp推理训练的图像分类模型结果完全不对呢？有什么预处理需要设置吗？
训练的时候，验证集的准确率都达到了0.97了，为啥转成inference之后，推理结果却完全不对

**Comment by Lixin-Liu** [comment]
请问你的问题解决了么？

**Comment by Dandelion111** [comment]
> 请问你的问题解决了么？

解决了，图像分辨率的问题

**Comment by yhpwsid** [comment]
@Dandelion111 这个图像分辨率的问题可以详细描述下吗，我也遇到了相同的问题

**Comment by Dandelion111** [comment]
> @Dandelion111 这个图像分辨率的问题可以详细描述下吗，我也遇到了相同的问题

分辨率和训练的时候保持相同就没问题
