### ISSUE TITLE
请问PaddleClas新发布的2.2版本支持多标签分类吗

### ISSUE THREAD

**Issue by JackDance** [PaddlePaddle/PaddleClas#1236]
请问PaddleClas新发布的2.2版本支持多标签分类吗

**Comment by cuicheng01** [comment]
2.1支持哈，2.3也会支持的，急用可以先用2.1哈

**Comment by JackDance** [comment]
感谢回复，请问paddleclas2.3大概什么时候能发布呢？还有一个问题，就是我用paddleclas2.1进行多标签训练的时候，感觉训练的很奇怪，先是使用[https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/zh_CN/advanced_tutorials/multilabel/multilabel.md](url)提供的数据集和步骤进行训练，测试的结果达不到所说的“验证集最好的正确率应该在0.72左右”，只有42.45%左右。而且我将自己的数据集改成多标签数据集所需要的格式进行训练，根据训练过程中控制台的输出可以发现，准确率最高的epoch竟然是第0个，说明模型应该没有在学习，就感觉挺奇怪的。期待回复。
![image](https://user-images.githubusercontent.com/46999456/133732843-707ee227-e753-4abc-8fd0-5796652f0838.png)
@cuicheng01

**Comment by cuicheng01** [comment]
现在的develop版本已经支持多标签训练，文档参考：https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/advanced_tutorials/multilabel/multilabel.md
准确率应该在0.95左右
