### ISSUE TITLE
请问度量学习怎么用

### ISSUE THREAD

**Issue by kkpssr** [PaddlePaddle/PaddleClas#1240]
您好，我看到最新版本继承了度量学习模型，请问和paddlecv模型库里的度量学习有什么区别，怎样使用

**Comment by Intsigstephon** [comment]
Paddleclas里面的度量学习，算法种类更多，提供4种实用模型，并且和最新paddle2.1适配更好。如果有metric learning的业务需要，建议使用clas里面的方法。
具体使用可以参照 https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/zh_CN/application/feature_learning.md

**Comment by ChrisMengxl** [comment]
> 
链接 里面 配置文件链接 已经失效啦。
