### ISSUE TITLE
特征学习相关问题

### ISSUE THREAD

**Issue by kkpssr** [PaddlePaddle/PaddleClas#1247]
您好，根据识别模型的流程，所有图像会经过物体检测，提取检测出的物体特征然后进行检索，如果我想做一个基于整张图片的特征提取模型（兼顾前景和背景）而非只关注前景，有没有好的预训练模型，如何训练

**Comment by weisy11** [comment]
具体是什么任务呢？一般来说，依然可以使用商品模型作为预训练再finetune。如果不需要检测，将这个模块去掉就可以了。

**Comment by kkpssr** [comment]
> 具体是什么任务呢？一般来说，依然可以使用商品模型作为预训练再finetune。如果不需要检测，将这个模块去掉就可以了。

具体想做相似背景的检测

**Comment by TingquanGao** [comment]
可以尝试去掉检测模块，直接对整个图像进行特征提取。
