### ISSUE TITLE
test_hubserving 和 predict_cls 在相同模型，相同图片下识别结果不同

### ISSUE THREAD

**Issue by omegod** [PaddlePaddle/PaddleClas#1255]
首先感谢作者提供的 PaddleClas 套件，最近在通过 PaddleClas 的图像分类做人脸分类，完成后通过 hub serving 部署，但在部署后发现通过 test_hubserving 调用识别的结果和 predict_cls 不同。
 1. PaddleClas版本：release/2.2
 2. Paddle 版本：CPU 版 2.1 （附：训练使用 ai studio，为 GPU版2.1， cuDNN Version: 7.6.）
 3. Python版本：3.8
识别结果如下：
predict_cls 识别结果为正确
![image](https://user-images.githubusercontent.com/22209885/134464404-6019a371-2918-4ffe-9453-de25787632cd.png)
test_hubserving 识别结果为错误
![image](https://user-images.githubusercontent.com/22209885/134464517-416f9cfc-018e-4728-b326-6769eec0b08e.png)

**Comment by TingquanGao** [comment]
你好，可以参考下述文档，检查一下模型路径是否配置正确呢？
https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.2/deploy/hubserving/readme.md#2-%E4%B8%8B%E8%BD%BD%E6%8E%A8%E7%90%86%E6%A8%A1%E5%9E%8B

**Comment by omegod** [comment]
> 你好，可以参考下述文档，检查一下模型路径是否配置正确呢？ https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.2/deploy/hubserving/readme.md#2-%E4%B8%8B%E8%BD%BD%E6%8E%A8%E7%90%86%E6%A8%A1%E5%9E%8B

好的，这边检查过，配置应该是正确的，我这边是否需要提供导出的模型以及校验图片呢？

**Comment by TingquanGao** [comment]
你好，是否方便提供模型及测试图片给我们呢？或者可以加我qq沟通：35441050。

**Comment by TingquanGao** [comment]
你好，感谢反馈！我们已经验证并在release/2.3与develop分支中修复了该问题。具体可以参考: https://github.com/PaddlePaddle/PaddleClas/pull/1313 https://github.com/PaddlePaddle/PaddleClas/pull/1312

**Comment by omegod** [comment]
> 你好，感谢反馈！我们已经验证并修复该问题。具体可以参考：#1312

十分感谢您的处理，已经可以了
