### ISSUE TITLE
请问大规模分类预训练模型下载地址是否提供

### ISSUE THREAD

**Issue by gj199602** [PaddlePaddle/PaddleClas#126]
文档和model_zoo中均没有找到

**Comment by dyning** [comment]
下载地址如下：
https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_10w_pretrained.tar

**Comment by gj199602** [comment]
> 下载地址如下：
> https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_10w_pretrained.tar

感谢回复，希望可以更新到文档里:smile:

**Comment by dyning** [comment]
OK，文档里我们详细说明下
