### ISSUE TITLE
特征学习训练一个epoch没跑完就进入到下一个epoch

### ISSUE THREAD

**Issue by wjrjsdx** [PaddlePaddle/PaddleClas#1260]
训练教程cub数据集没问题，但是换成自己数据时特征学习训练一个epoch没跑完就进入到下一个epoch，每个epoch应该是跑358次迭代，但是每次跑90次迭代就进入下一个epoch，不会报错最终也能在指定的epoch时终止训练，但是应该有问题，是因为数据量太大吗？训练数据和情况如下：
![2021-09-24_8-56-40](https://user-images.githubusercontent.com/63723648/134603708-5b404a91-fecf-46e3-8431-49c3c0a7b6be.png)
链接：https://pan.baidu.com/s/14lfw2vEBUeTJ6KUruKFe2A 
提取码：2yek

**Comment by cuicheng01** [comment]
您好，这个问题会在下一个版本解决，感谢反馈

**Comment by cuicheng01** [comment]
您好，使用2.3版本的PaddleClas使用PKSampler可以解决这个问题哈

**Comment by KKKKKD821** [comment]
请问这是什么问题导致的啊
