### ISSUE TITLE
SwinTransformer_small_patch4_window7_224好像没有在imagenet22k训练的pretrain模型？

### ISSUE THREAD

**Issue by IamMegatron2025** [PaddlePaddle/PaddleClas#1262]
您好，SwinTransformer_small_patch4_window7_224好像没有在imagenet22k训练的pretrain模型？
我看SwinTransformer_base_patch4_window7_224是有的。

**Comment by cuicheng01** [comment]
您好，small系列暂时是没有的，SwinTransformer的官方代码也暂时没有。
