### ISSUE TITLE
支持从预训练模型转成onnx模型吗

### ISSUE THREAD

**Issue by bingo789** [PaddlePaddle/PaddleClas#1276]
训练后的文件有latest.pdopt、latest.pdparams、latest.pdstates，或别人提供的inference.pdiparams、inference.pdiparams.info、inference.pdmodel，是否支持从这些文件转成onnx模型

版本信息：
PaddleClas版本2.2以及PaddlePaddle版本gpu2.1.2

**Comment by cuicheng01** [comment]
支持的哈，可以参考https://github.com/PaddlePaddle/Paddle2ONNX
实现转换
