### ISSUE TITLE
模型转换出错

### ISSUE THREAD

**Issue by chengxurensheng666** [PaddlePaddle/PaddleClas#128]
![image](https://user-images.githubusercontent.com/48110081/82626359-2e69f480-9c1a-11ea-9cbf-962615c42f97.png)

**Comment by littletomatodonkey** [comment]
您好，加载模型的时候，如果是*.pdparams格式的模型结果文件，需要指定文件的前缀，您这里pretreain应该为`output/--/ppcls`，也可以参考faq文档中的解释。

![image](https://user-images.githubusercontent.com/14270174/82770343-ceb65800-9e6a-11ea-9258-63331ffd44aa.png)

**Comment by chengxurensheng666** [comment]
解决问题了，感谢开发小哥哥
