### ISSUE TITLE
PP-LCNet

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleClas#1280]
您好，PP-LCNet的代码放在哪里，我没找到。在您的论文中提到了PicoDet，这在Paddledetection中具体是哪个模型？

**Comment by cuicheng01** [comment]
您好，感谢关注。PP-LCNet的代码见：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/ppcls/arch/backbone/legendary_models/pp_lcnet.py
PicoDet是PaddleDetection自研的检测模型，详情：https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/picodet
