### ISSUE TITLE
faq_2021_s2.md 文档存在错别字

### ISSUE THREAD

**Issue by lazyn1997** [PaddlePaddle/PaddleClas#1284]
如下图所示，红圈框选位置文字应为 _**与**_ ，望修改。
![image](https://user-images.githubusercontent.com/34644177/136340387-41f16f97-02df-45a4-963b-864ff913cded.png)

**Comment by Intsigstephon** [comment]
收到，感谢您的反馈，我们会尽快修改的~

**Comment by lazyn1997** [comment]
好的~
