### ISSUE TITLE
train list for imagenet

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleClas#1287]
您好，对于imagenet的中类别想要和paddlecls提供的类别具体对应是怎么一个操作流程，因为我发现imagenet的标签是文件名而你们提供的label_list却是0,1,2.....999，就是这样的一个对应关系是怎么样的，谢谢

**Comment by Intsigstephon** [comment]
是说标签隐含在文件名里面，是这个意思吗？ 可以通过写一个简单的脚本，生成需要的train_list.txt和val_list.txt.  每行的内容格式为xxxxxx    label

**Comment by TingquanGao** [comment]
@qdd1234 你好，可以参考一下这个：https://github.com/paddlepaddle/paddleclas/blob/release%2F2.3/ppcls/utils/imagenet1k_label_list.txt
