### ISSUE TITLE
received rank:2 != label_dims.size():3

### ISSUE THREAD

**Issue by weiheshiqingchun** [PaddlePaddle/PaddleClas#129]
报错：  File "tools/train.py", line 124, in <module>
    main(args)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: If Attr(soft_label) == true, Input(X) and Input(Label) shall have the same dimensions. But received: the dimensions of Input(X) is [2],the shape of Input(X) is [-1, 2], the dimensions of Input(Label) is [3], the shape ofInput(Label) is [-1, 1, 2]
  [Hint: Expected rank == label_dims.size(), but received rank:2 != label_dims.size():3.] at (D:\1.8.1\paddle\paddle\fluid\operators\cross_entropy_op.cc:63)
  [operator < cross_entropy > error]
INFO 2020-05-23 18:17:34,812 utils.py:272] terminate all the procs
ERROR 2020-05-23 18:17:34,812 utils.py:416] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2020-05-23 18:17:34,813 utils.py:272] terminate all the procs

图片512*512png，8位深度，类别1，2，3。这个报错里的rank和label_dims.size()分别是什么意思？？

**Comment by weiheshiqingchun** [comment]
还有下载个示例图片下了几个小时没下完。拜托下次换个能放国内服务器得图片集。

**Comment by littletomatodonkey** [comment]
> 报错： File "tools/train.py", line 124, in
> main(args)
> 
> ## Error Message Summary:
> InvalidArgumentError: If Attr(soft_label) == true, Input(X) and Input(Label) shall have the same dimensions. But received: the dimensions of Input(X) is [2],the shape of Input(X) is [-1, 2], the dimensions of Input(Label) is [3], the shape ofInput(Label) is [-1, 1, 2]
> [Hint: Expected rank == label_dims.size(), but received rank:2 != label_dims.size():3.] at (D:\1.8.1\paddle\paddle\fluid\operators\cross_entropy_op.cc:63)
> [operator < cross_entropy > error]
> INFO 2020-05-23 18:17:34,812 utils.py:272] terminate all the procs
> ERROR 2020-05-23 18:17:34,812 utils.py:416] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
> INFO 2020-05-23 18:17:34,813 utils.py:272] terminate all the procs
> 
> 图片512*512png，8位深度，类别1，2，3。这个报错里的rank和label_dims.size()分别是什么意思？？

您好，配置文件中的`classes_num`修改了吗？这个需要修改为您的类别数。

**Comment by weiheshiqingchun** [comment]
改过了，我就一种标签还有背景，classes_num=2



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "littletomatodonkey"<notifications@github.com&gt;; 
发送时间: 2020年5月25日(星期一) 上午9:32
收件人: "PaddlePaddle/PaddleClas"<PaddleClas@noreply.github.com&gt;; 
抄送: "互联网的未来在出海？"<2096466722@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleClas] received rank:2 != label_dims.size():3 (#129)





  
报错： File "tools/train.py", line 124, in
 main(args)
 
Error Message Summary:
 
InvalidArgumentError: If Attr(soft_label) == true, Input(X) and Input(Label) shall have the same dimensions. But received: the dimensions of Input(X) is [2],the shape of Input(X) is [-1, 2], the dimensions of Input(Label) is [3], the shape ofInput(Label) is [-1, 1, 2]
 [Hint: Expected rank == label_dims.size(), but received rank:2 != label_dims.size():3.] at (D:\1.8.1\paddle\paddle\fluid\operators\cross_entropy_op.cc:63)
 [operator < cross_entropy &gt; error]
 INFO 2020-05-23 18:17:34,812 utils.py:272] terminate all the procs
 ERROR 2020-05-23 18:17:34,812 utils.py:416] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
 INFO 2020-05-23 18:17:34,813 utils.py:272] terminate all the procs
 
图片512*512png，8位深度，类别1，2，3。这个报错里的rank和label_dims.size()分别是什么意思？？
  
您好，配置文件中的classes_num修改了吗？这个需要修改为您的类别数。

**Comment by littletomatodonkey** [comment]
您好，`class_num`也是需要算是背景类的，您如果前景有2类，背景1类，那总共应该是3类

**Comment by weiheshiqingchun** [comment]
？我说只有一种标签，加上背景，哪来的第三类？zip发给你你自己跑下：百度网盘https://pan.baidu.com/s/1dGjSZf8e1Ee__mXsfdpb3A 提取码fd3f
先进PaddleClas\dataset的1.py改下path 为ceshi文件夹，再python 1.py然后
python pdseg/train.py --do_eval --use_vdl --vdl_log_dir VDL_LOG_DIR --use_gpu --cfg ResNeXt152_vd_64x4d.yaml




------------------ 原始邮件 ------------------
发件人:&nbsp;"littletomatodonkey"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月25日(星期一) 上午9:37
收件人:&nbsp;"PaddlePaddle/PaddleClas"<PaddleClas@noreply.github.com&gt;;
抄送:&nbsp;"互联网的未来在出海？"<2096466722@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleClas] received rank:2 != label_dims.size():3 (#129)





 
您好，class_num也是需要算是背景类的，您如果前景有2类，背景1类，那总共应该是3类

**Comment by littletomatodonkey** [comment]
麻烦提供下训练的标签文件(train_list.txt & test_list.txt)和配置文件(*.yaml)吧，您zip里面提供的文件名使用该命令无法转换
![image](https://user-images.githubusercontent.com/14270174/82772173-f6a8ba00-9e70-11ea-9b00-71649b49506d.png)

![image](https://user-images.githubusercontent.com/14270174/82772139-dbd64580-9e70-11ea-8f39-d2fd5505cfce.png)

**Comment by weiheshiqingchun** [comment]
命令：
&nbsp;python -m paddle.distributed.launch&nbsp; --selected_gpus="0"&nbsp; tools/train.py -c ResNeXt152_vd_64x4d.yaml


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"littletomatodonkey"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月25日(星期一) 上午10:17
收件人:&nbsp;"PaddlePaddle/PaddleClas"<PaddleClas@noreply.github.com&gt;;
抄送:&nbsp;"互联网的未来在出海？"<2096466722@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleClas] received rank:2 != label_dims.size():3 (#129)





 
麻烦提供下训练的标签文件(train_list.txt &amp; test_list.txt)和配置文件(*.yaml)吧，您zip里面提供的文件名使用该命令无法转换

**Comment by littletomatodonkey** [comment]
感谢您的反馈，已经修复该问题，您拉取下最新代码即可，改动的地方可以参考这个PR。#130
