### ISSUE TITLE
AssertionError: the type of architecture(None) should be dict报错

### ISSUE THREAD

**Issue by leezhao415** [PaddlePaddle/PaddleClas#1292]
问题出现过程描述：
https://aistudio.baidu.com/aistudio/projectdetail/2300718?channelType=0&channel=0
该项目按步骤执行到模型训练过程出现该问题
python tools/train.py -c ./ppcls/configs/quick_start/ResNet50_vd.yaml -o Arch.pretrained=True

系统环境：

Paddle version: 2.1.3
Paddle With CUDA: True

OS: ubuntu 18.04
Python version: 3.6.13

CUDA version: 11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0
cuDNN version: 8.0.4
Nvidia driver version: 470.42.01

报错信息：
Traceback (most recent call last):
File "tools/train.py", line 118, in
main(args)
File "tools/train.py", line 56, in main
config = get_config(args.config, overrides=args.override, show=True)
File "/home/shanshan/PaddleClas/ppcls/utils/config.py", line 196, in get_config
check_config(config)
File "/home/shanshan/PaddleClas/ppcls/utils/config.py", line 106, in check_config
check.check_architecture(architecture)
File "/home/shanshan/PaddleClas/ppcls/utils/check.py", line 65, in check_architecture
("the type of architecture({}) should be dict". format(architecture))
AssertionError: the type of architecture(None) should be dict

**Comment by RainFrost1** [comment]
PaddleClas版本是2.2吗？我们这边使用2.2版本，测试暂时没有复现问题。能否详细说明下复现步骤？感谢~

**Comment by RainFrost1** [comment]
可以检查一下./ppcls/configs/quick_start/ResNet50_vd.yaml，确认一下是否修改过模型名称，即`Arch.name`
