### ISSUE TITLE
ssld系列预训练模型能转为静态图模型参数么(pdiparams)?

### ISSUE THREAD

**Issue by kkpssr** [PaddlePaddle/PaddleClas#1294]
您好，我尝试将ssld系列模型转为静态图参数后提取特征，发现并无对应config?

**Comment by kkpssr** [comment]
尝试导出Fix_resNet_50_vd_ssld 模型，出现
W1014 10:23:19.236249 17589 device_context.cc:422] device: 0, cuDNN Version: 8.1.
/home/pj/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py:1301: UserWarning: Skip loading for stem.0.conv.weight. stem.0.conv.weight is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/pj/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py:1301: UserWarning: Skip loading for stem.0.bn.weight. stem.0.bn.weight is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/pj/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py:1301: UserWarning: Skip loading for stem.0.bn.bias. stem.0.bn.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
所有对应层都找不到，用的config是ResNet50_vd

**Comment by RainFrost1** [comment]
能否详细描述下复现步骤？我们复现一下。config对应，如：`ResNet50_vd_ssld`对应`ResNet50_vd.yaml`

**Comment by ajundo** [comment]
我在导出时遇到相同的问题：
`rm -r 100k;
python3 tools/export_model.py \
-c ppcls/configs/ImageNet/ResNet/ResNet50_vd.yaml \
-o Global.save_inference_dir="100k" \
-o Global.pretrained_model="ResNet50_vd_10w_pretrained"
`
我用pkl打开ResNet50_vd_10w_pretrained.pdparams，里面的key是'bb_x_x.convx._batch_norm._variance'，而export时的warning是UserWarning: Skip loading for blocks.15.conv2.bn._variance.
