### ISSUE TITLE
eval出错，AssertionError: can't find PADDLE_TRAINER_ENDPOINTS

### ISSUE THREAD

**Issue by Amore-HDU** [PaddlePaddle/PaddleClas#131]
执行你们教程，报AssertionError: can't find PADDLE_TRAINER_ENDPOINTS
python tools/eval.py \
    -c ./configs/eval.yaml \
    -o ARCHITECTURE.name="ResNet50_vd" \
    -o pretrained_model=output/ResNet50_vd/19/ppcls

**Comment by Amore-HDU** [comment]
@ZeyuChen @jacquesqiao @zhxfl @zhhsplendid

**Comment by Amore-HDU** [comment]
@littletomatodonkey

**Comment by littletomatodonkey** [comment]
您好，方便提供下您使用的机器的信息吗？目前PaddleClas还没有支持windows

**Comment by Amore-HDU** [comment]
我使用的是ubuntu14.04 ,V100,  cuda9.2

**Comment by littletomatodonkey** [comment]
您好，出现问题的原因是eval.py中用了fleet，如果不使用`paddle.distributed.launch`启动的话，不会定义`PADDLE_TRAINER_ENDPOINTS`变量，因此会出现问题。

您可参考下面的代码片段，也可以参考tools/eval.sh中的写法，
```
python -m paddle.distributed.launch \
    --selected_gpus="0" \
    tools/eval.py
    -c ./configs/eval.yaml
    -o ARCHITECTURE.name="ResNet50_vd"
    -o pretrained_model=output/ResNet50_vd/19/ppcls
```

**Comment by Amore-HDU** [comment]
----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)

**Comment by littletomatodonkey** [comment]
> ## Error Message Summary:
> Error: Blocking queue is killed because the data reader raises an exception
> [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)

您好，有更多的报错日志信息吗？这个可能看不太出来

**Comment by shippingwang** [comment]
To help us figure it out, please report more stack information
Feel free to reopen it~
