### ISSUE TITLE
MixUP

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleClas#1310]
您好，我想问一下，为何我使用FP16训练的情况下无法使用MIxUp？是我配置文件的问题吗，可否给出一个可以在FP16下运行Mixup的源文件示例

**Comment by weisy11** [comment]
你好，可以提供一些细节信息吗？是使用官方提供的配置文件吗？还是做了一些修改呢？具体改了什么？

**Comment by qdd1234** [comment]
> 你好，可以提供一些细节信息吗？是使用官方提供的配置文件吗？还是做了一些修改呢？具体改了什么？

我自己自创的一个模型，不用FP16是可以正常跑的，我下图展示带FP16的Mixup，帮我看看什么原因
![image](https://user-images.githubusercontent.com/68497831/137667857-7635da6c-4dce-4f64-8e84-5eab67f8985f.png)
![image](https://user-images.githubusercontent.com/68497831/137667869-e0946d60-fb3f-4c5d-91db-03bccf3fc1f8.png)
![image](https://user-images.githubusercontent.com/68497831/137667888-d81bc650-383d-4636-ac41-9370148a5d32.png)
![image](https://user-images.githubusercontent.com/68497831/137667899-c352d939-ced9-4851-bd04-0a6862dddc9a.png)
![image](https://user-images.githubusercontent.com/68497831/137667934-314a0c3d-a8b7-48f4-a2d8-121da9b7af9e.png)

**Comment by TingquanGao** [comment]
你好，可以发一下报错信息吗？

**Comment by qdd1234** [comment]
> 你好，可以发一下报错信息吗？

您好，这是报错信息
![image](https://user-images.githubusercontent.com/68497831/137744247-ce00eb00-e1f0-4f06-a729-24d238c857dc.png)

**Comment by TingquanGao** [comment]
你好，在FP16下确实存在该问题。目前该问题已修复，具体可以参考#1279，PR将尽快合入。

**Comment by qdd1234** [comment]
> 你好，在FP16下确实存在该问题。目前该问题已修复，具体可以参考#1279，PR将尽快合入。

谢谢，但是我看修复的是静态图的，动态图是否也一起修复了？还有FP16下是只用改一个yaml文件内容吗

**Comment by TingquanGao** [comment]
动态图和静态图下都修复了的，但是PR目前还没合入develop分支和release/2.3分支，如果不涉及develop的新功能，可以参考这个PR #1334 ，从这里git clone：`git clone -b 2.3/fix_loss https://github.com/TingquanGao/PaddleClas.git`。
在此次PR修复中，统一了mixceloss和celoss，因此需要在yaml文件中将mixceloss改为celoss。其他地方，包括mixup的使用和fp16的使用并没有变化。

**Comment by qdd1234** [comment]
> 动态图和静态图下都修复了的，但是PR目前还没合入develop分支和release/2.3分支，如果不涉及develop的新功能，可以参考这个PR #1334 ，从这里git clone：`git clone -b 2.3/fix_loss https://github.com/TingquanGao/PaddleClas.git`。 在此次PR修复中，统一了mixceloss和celoss，因此需要在yaml文件中将mixceloss改为celoss。其他地方，包括mixup的使用和fp16的使用并没有变化。

非常感谢~

**Comment by TingquanGao** [comment]
嗨，你好！想到一个问题，在使用mixup以及cutmix等数据增强方法时，需要将yaml文件中`Metric.Train.TopkAcc`字段删掉，因为在batch层面的数据增强下无法计算准确率指标。yaml修改可以参考：[mixup](https://github.com/PaddlePaddle/PaddleClas/blob/c30b72c867c648bdd460c6bfcb062f561a0f312e/ppcls/configs/ImageNet/DataAugment/ResNet50_Mixup.yaml?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L125-L128)
