### ISSUE TITLE
显存叠加

### ISSUE THREAD

**Issue by 2mhk** [PaddlePaddle/PaddleClas#1319]
PaddleClas release2.2
 a. 操作系统Windows
 b. Python3.8
vs2019+opencv3.4.6

--------------paddle_inference : -----------------------
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
WITH_ROCM: OFF
CUDA version: 11.0
CUDNN version: v8.0
CXX compiler version: 19.16.27045.0
WITH_TENSORRT: ON
TensorRT version: v7

----------------config.txt:---------------------------
# model load config
use_gpu  1
gpu_id  0
gpu_mem  4000
cpu_math_library_num_threads  10
use_mkldnn 1
use_tensorrt 1
use_fp16 0

# cls config
cls_model_path  inferenceModel/xxxxModel/inference.pdmodel
cls_params_path inferenceModel/xxxxModel/inference.pdiparams
resize_short_size 256
crop_size 224

问题：
多线程导致显存持续增加，创建Classifier的线程与调用Classifier::Run的线程非一个线程时，显存会不断增加（显存泄漏？），只有退掉进程才能释放。同样问题PaddleDetection里未出现。
下面是出现该现象的代码，断点查看classifier创建后及thread a运行结束后的显存情况，可以看出显存的增加。实际使用中Classifier很可能会主线程创建一次，Classifier::Run会在其他多个线程里调用非常多次，从而出现爆显存的情况。若没有办法避免，应在样例的main.cpp或Readme注释一下。

代码改自C++编译的paddleclas的样例代码（需要改的地方加了//todo:）：
int main(/*int argc, char **argv*/) {
    //if (argc < 3) {
    //    std::cerr << "[ERROR] usage: " << argv[0]
    //        << " configure_filepath image_path\n";
    //    exit(1);
    //}

    static std::stringstream csvStream;

    ClsConfig config("config.txt");  //todo: add you config

    config.PrintConfigInfo();

    std::string path("inferenceModel/xxxxModel");  //todo: change you model

    std::vector<std::string> img_files_list;
    string imgPath = "test/2";  //todo: change you image path
    if (cv::utils::fs::isDirectory(imgPath)) {
        std::vector<cv::String> filenames;
        cv::glob(imgPath, filenames);
        for (auto f : filenames) {
            img_files_list.push_back(f);
        }
    }
    else {
        img_files_list.push_back(imgPath);
    }

    std::cout << "img_file_list length: " << img_files_list.size() << std::endl;

    std::cout << std::chrono::steady_clock::now << std::endl;

    Classifier classifier(config.cls_model_path, config.cls_params_path,
        config.use_gpu, config.gpu_id, config.gpu_mem,
        config.cpu_math_library_num_threads, config.use_mkldnn,
        config.use_tensorrt, config.use_fp16,
        config.resize_short_size, config.crop_size);

    std::cout << std::chrono::steady_clock::now << std::endl;

#if 1
    std::thread a([](std::vector<std::string>& img_files_list, Classifier& classifier) {
        double elapsed_time = 0.0;
        int warmup_iter = img_files_list.size() > 5 ? 5 : 0;
        for (int idx = 0; idx < img_files_list.size(); ++idx) {
            std::string img_path = img_files_list[idx];
            cv::Mat srcimg = cv::imread(img_path, cv::IMREAD_COLOR);
            if (!srcimg.data) {
                std::cerr << "[ERROR] image read failed! image path: " << img_path
                    << "\n";
                exit(-1);
            }

            cv::cvtColor(srcimg, srcimg, cv::COLOR_BGR2RGB);

            std::stringstream _stream;
            double run_time = classifier.Run(srcimg, _stream);

            int maxPosition;
            std::string maxPos;
            _stream >> maxPos;
            csvStream << maxPos << "\n";

            if (1 /*idx >= warmup_iter*/) {
                elapsed_time += run_time;
                std::cout << "Current image path: " << img_path << std::endl;
                std::cout << "Current time cost: " << run_time << " s, "
                    << "average time cost in all: "
                    << elapsed_time / (idx + 1 - warmup_iter) << " s." << "\n---------\n";
            }
            else {
                std::cout << "Current time cost: " << run_time << " s." << std::endl;
            }

            std::this_thread::sleep_for(std::chrono::milliseconds(500));        //give more time to watch GPU memory increase
        }

        std::string csv = csvStream.str();

        cout << "\n\n" << csv << "\n\n";

        },std::ref(img_files_list),std::ref(classifier));
    a.join();

#else
    double elapsed_time = 0.0;
    int warmup_iter = img_files_list.size() > 5 ? 5 : 0;
    for (int idx = 0; idx < img_files_list.size(); ++idx) {
        std::string img_path = img_files_list[idx];
        cv::Mat srcimg = cv::imread(img_path, cv::IMREAD_COLOR);
        if (!srcimg.data) {
            std::cerr << "[ERROR] image read failed! image path: " << img_path
                << "\n";
            exit(-1);
        }

        cv::cvtColor(srcimg, srcimg, cv::COLOR_BGR2RGB);

        std::stringstream _stream;
        double run_time = classifier.Run(srcimg, _stream);

        int maxPosition;
        std::string maxPos;
        _stream >> maxPos;
        csvStream << maxPos << "\n";

        if (1 /*idx >= warmup_iter*/) {
            elapsed_time += run_time;
            std::cout << "Current image path: " << img_path << std::endl;
            std::cout << "Current time cost: " << run_time << " s, "
                << "average time cost in all: "
                << elapsed_time / (idx + 1 - warmup_iter) << " s." << "\n---------\n";
        }
        else {
            std::cout << "Current time cost: " << run_time << " s." << std::endl;
        }
    }

    std::string csv = csvStream.str();

    cout << "\n\n" << csv << "\n\n";
#endif

    system("Pause");
    return 0;
}

**Comment by weisy11** [comment]
我们跟进一下这个问题

**Comment by quanxiang-liu** [comment]
@2mhk  hi~ 我在Winodws机器上进行问题复现，除cuda10.2 与 cudnn7不一样外参数配置保持一致：
**model load config：**
use_gpu  1
gpu_id  0
gpu_mem  4000
cpu_threads  10
use_mkldnn 1
use_tensorrt 1
use_fp16 0

分别在两台机器上使用服务端C++预测 与 python预测 ILSVRC2012数据集（val50000张图片），均未发现有  显存/内存持续增加 的情况，部分截图如下：

**C++ inference**
开始且稳定后
![image](https://user-images.githubusercontent.com/38774750/138689303-7aa603f9-5984-4232-bd1a-8862b899fe7a.png)
结束预测之前
![image](https://user-images.githubusercontent.com/38774750/138689355-37b22c90-43f6-400e-93ea-13c1547c8e35.png)

**python inference**
python tools/infer.py -c ppcls/configs/ImageNet/ResNet/ResNet50.yaml  -o Global.pretrained_model=output/ResNet50/latest  -o Infer.infer_imgs="./dataset/ILSVRC2012/val"
开始且稳定后
![image](https://user-images.githubusercontent.com/38774750/138689518-1ebbfec8-b6ba-4d95-8eb2-382be0f8d30a.png)
结束预测之前
![image](https://user-images.githubusercontent.com/38774750/138689558-425a6090-efe5-4b61-af56-8e2cff4e3804.png)

**Comment by 2mhk** [comment]
@quanxiang-liu    修改下代码，开不同的线程，多次调用。将#if ... #else 里的代码改为这样。之前没表述清楚

    for (int i = 0; i < 100; i++)
    {
        std::thread a([](std::vector<std::string>& img_files_list, Classifier& classifier) {
            double elapsed_time = 0.0;
            int warmup_iter = img_files_list.size() > 5 ? 5 : 0;
            for (int idx = 0; idx < img_files_list.size(); ++idx) {
                std::string img_path = img_files_list[idx];
                cv::Mat srcimg = cv::imread(img_path, cv::IMREAD_COLOR);
                if (!srcimg.data) {
                    std::cerr << "[ERROR] image read failed! image path: " << img_path
                        << "\n";
                    exit(-1);
                }

                cv::cvtColor(srcimg, srcimg, cv::COLOR_BGR2RGB);

                std::stringstream _stream;
                double run_time = classifier.Run(srcimg, _stream);

                int maxPosition;
                std::string maxPos;
                _stream >> maxPos;
                csvStream << maxPos << "\n";

                if (1 /*idx >= warmup_iter*/) {
                    elapsed_time += run_time;
                    std::cout << "Current image path: " << img_path << std::endl;
                    std::cout << "Current time cost: " << run_time << " s, "
                        << "average time cost in all: "
                        << elapsed_time / (idx + 1 - warmup_iter) << " s." << "\n---------\n";
                }
                else {
                    std::cout << "Current time cost: " << run_time << " s." << std::endl;
                }

            }

            std::string csv = csvStream.str();

            cout << "\n\n" << csv << "\n\n";

            }, std::ref(img_files_list), std::ref(classifier));
        a.join();

        std::this_thread::sleep_for(std::chrono::milliseconds(5000));        //give more time to watch GPU memory increase

    }

**Comment by 2mhk** [comment]
![16352114199992](https://user-images.githubusercontent.com/23026313/138792932-2d57b60b-8de2-4587-b5ce-d289e1c0e5c5.png)
![16352114493790](https://user-images.githubusercontent.com/23026313/138792942-a16c493d-5f7c-48cd-aac6-5b290131c61e.png)
![1635211467576](https://user-images.githubusercontent.com/23026313/138792947-98751e0e-6f35-4990-9f41-fe727871605f.png)
)

**Comment by weisy11** [comment]
不建议跨线程调用。这个需求不在我们的预设范围之内，没有进行过测试。
如果需要并行，请创建多个Classifier类。
