### ISSUE TITLE
api 接口 utils冲突

### ISSUE THREAD

**Issue by Darki-luo** [PaddlePaddle/PaddleClas#1325]
使用paddleclas api 2.2.1调用模型，项目文件目录也建有utils目录，但是paddleclas会报from utils import logger找不到的错误，应该是检索到项目工程本身的utils的目录了

**Comment by weisy11** [comment]
你好，请问是直接调用paddleclas源码，还是使用python的wheel包？

**Comment by Darki-luo** [comment]
> 你好，请问是直接调用paddleclas源码，还是使用python的wheel包？

使用pip装的paddleclas

**Comment by TingquanGao** [comment]
该问题已解决，可以重新安装试试：pip install paddleclas==2.4.3

如有问题，可以继续评论，感谢对PaddleClas的关注~
