### ISSUE TITLE
--use_tensorrt=True

### ISSUE THREAD

**Issue by Amore-HDU** [PaddlePaddle/PaddleClas#133]
Error: Pass tensorrt_subgraph_pass has not been registered at (/paddle/paddle/fluid/framework/ir/pass.h:170)

**Comment by littletomatodonkey** [comment]
您好，如果需要使用Paddle+tensorRT的话，需要首先编译带tensorRT的paddle whl包，再安装该whl包使用，编译whl包的教程可以参考：[https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html)

**Comment by habout632** [comment]
上面的文档　我看了一下没看明白　不知道要怎么操作
我现在用的是nvidia　现成的带tensorrt的docker容器　我要怎么在上面编译安装paddle呢

**Comment by habout632** [comment]
![Screenshot from 2020-12-04 11-36-10](https://user-images.githubusercontent.com/3166070/101118883-ff025e80-3624-11eb-8ac6-81dfcf6e5c09.png)

**Comment by habout632** [comment]
请问一下这个paddle inference要怎么安装呢？
