### ISSUE TITLE
window10 x64 如何写训练语句

### ISSUE THREAD

**Issue by ruinian394** [PaddlePaddle/PaddleClas#134]
我的笔记本是window10 x64, 显卡是NVIDIA GeForce GTX 1650.

我按照示例程序编写训练语句，如下：python -m paddle.distributed.launch \
    --selected_gpus="0" \
    tools/train.py \
        -c ./configs/quick_start/ResNet50_vd.yaml

结果提示 ”gen_nccl_id ” has not been registered, 咨询QQ群说是window不支持多卡，请问针对我目前情况，应该如何写训练语句

**Comment by littletomatodonkey** [comment]
您好，目前PaddleClas不支持windows上的训练与评估，我们后续会增加PaddleClas对windows的支持，敬请期待。

**Comment by ruinian394** [comment]
好的，了解了

**Comment by chliang** [comment]
> 您好，目前PaddleClas不支持windows上的训练与评估，我们后续会增加PaddleClas对windows的支持，敬请期待。

什么时候能支持 windows

**Comment by littletomatodonkey** [comment]
你好，可以参考这个PR中的写法： #159 
使用`tools/train_multi_platform.py`和`tools/eval_multi_platform.py`脚本即可

**Comment by littletomatodonkey** [comment]
> > 您好，目前PaddleClas不支持windows上的训练与评估，我们后续会增加PaddleClas对windows的支持，敬请期待。
> 
> 什么时候能支持 windows

你好，可以参考这个PR中的写法： #159 
使用`tools/train_multi_platform.py`和`tools/eval_multi_platform.py`脚本即可
