### ISSUE TITLE
预测阶段报错

### ISSUE THREAD

**Issue by Sun-Shun** [PaddlePaddle/PaddleClas#1340]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如Linux/Windows/MacOS
  b. Python版本号，如Python3.6/7/8
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

都是最新版本，CUDA11.0，Windows

cmd 指令：python  tools/infer.py   -c ./ppcls/configs/quick_start/professional/ResNet50_vd_CIFAR100.yaml -o Infer.infer_imgs=dataset/Cat/cat_12_test -o Global.pretrained_model=./output_CIFAR/ResNet50_vd/best_model

前面还能预测，到后面就报错了

[{'class_ids': [9, 4, 3, 7, 8], 'scores': [0.96763, 0.02795, 0.00377, 0.00031, 0.00023], 'file_name': 'dataset/Cat/cat_12_test\\NrPQtw7m31JKOlSbnAU6VHovqhMY2LBG.jpg', 'label_names': []}, {'class_ids': [7, 4, 10, 6, 5], 'scores': [0.99996, 3e-05, 1e-05, 1e-05, 0.0], 'file_name': 'dataset/Cat/cat_12_test\\OHg2wlQf5DdNEr46xqLBXz3ai9oGmKYI.jpg', 'label_names': []}, {'class_ids': [4, 7, 5, 6, 9], 'scores': [0.99989, 7e-05, 3e-05, 0.0, 0.0], 'file_name': 'dataset/Cat/cat_12_test\\OMfQiwJau4WXboyN5LktHSF3grnZDsAG.jpg', 'label_names': []}, {'class_ids': [11, 0, 10, 1, 8], 'scores': [0.95901, 0.03795, 0.00251, 0.00023, 0.0001], 'file_name': 'dataset/Cat/cat_12_test\\P3Bn8ThKFoV1YJIpfSAmqxwbQ2ECv0iu.jpg', 'label_names': []}]
Traceback (most recent call last):
  File "tools/infer.py", line 32, in <module>
    trainer.infer()
  File "<decorator-gen-281>", line 2, in infer
  File "C:\Users\86151\Anaconda3\lib\site-packages\paddle\fluid\dygraph\base.py", line 331, in _decorate_function
    return func(*args, **kwargs)
  File "D:\PaddleClas\ppcls\engine\trainer.py", line 652, in infer
    x = process(x)
  File "D:\PaddleClas\ppcls\data\preprocess\ops\operators.py", line 57, in __call__
    assert img.shape[2] == 3, 'invalid shape of image[%s]' % (
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by weisy11** [comment]
请检查一下文件路径。报错信息看起来是没有正确读入图片。如果路径没有问题，且总是同一张图片报错，可以提交一个badcase我们来检查一下

**Comment by Sun-Shun** [comment]
好的，谢谢啦






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleClas"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月26日(星期二) 下午2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleClas] 预测阶段报错 (Issue #1340)





 
请检查一下文件路径。从报错信息来看，可能是label文件的路径不适应windows
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
