### ISSUE TITLE
文档更新

### ISSUE THREAD

**Issue by Shelly111111** [PaddlePaddle/PaddleClas#1344]
PaddleClas文档更新问题
1. 文档[开始使用](https://paddleclas.readthedocs.io/zh_CN/latest/tutorials/getting_started.html)的模型推理中，python tools/infer/predict.py文件找不到，tools文件夹下只有__init__.py、eval.py、export_model.py、infer.py、train.py这些python脚本文件，该问题同样出现在[分类预测框架](https://paddleclas.readthedocs.io/zh_CN/latest/extension/paddle_inference.html)文档中。
2. 预测方式太多、 `步骤复杂，不便于使用。忘记了从哪找到的一种PaddleClas的预测方式：
`python3 PaddleClas/tools/infer.py \
    -c PaddleClas/ppcls/configs/quick_start/ResNet50_vd.yaml \
    -o Infer.infer_imgs=./cat_12_train \
    -o Global.pretrained_model=./output/ResNet50_vd/best_model
`
这样的就很好，训练时生成的模型配置文件只有pdparams以及pdopt，加载的时候只需要将这两个配置文件共同的文件名输入，然后其他配置信息均在yaml中定义，如PaddleDetection和PaddleSeg一样。建议将所有预测命令同步使用类似命令。

**Comment by cuicheng01** [comment]
您好，感谢提出宝贵意见，readthedocs的文档近期会更新，可以先查看paddleclas repo中的文档～
