### ISSUE TITLE
MixNet只提供pdparams，是否有PaddlePaddle复现的动态图？

### ISSUE THREAD

**Issue by dugusiqing** [PaddlePaddle/PaddleClas#1352]
通过网络的性能表格对比，感觉MixNet_M网络结构的性价比很高，下载链接只有参数文件，没有计算图。是否开源PaddlePaddle版本的复现代码呢？
想用它来做Backbone，试试语义分割和目标检测

**Comment by cuicheng01** [comment]
MixNet的代码可以看这里哈，是动态图的版本，https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/ppcls/arch/backbone/model_zoo/mixnet.py
不过MixNet的速度不是很理想，还是建议使用其他轻量级网络结构，比如PP-LCNet哈
