### ISSUE TITLE
PaddleClas和PaddleDetection是什么关系？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleClas#1355]
PaddleClas和PaddleDetection是什么关系？
这两个有区别吗？感觉大体一致

**Comment by weisy11** [comment]
PaddleDetection是图像检测，PaddleClas是图像分类和图像识别。
两个repo的使用场景确实有一小部分重叠，不过在效率和精度上各有侧重，需要根据场景测试情况做选择。如果在你的场景里面感受不到差别，随便用哪个都行。

**Comment by weisy11** [comment]
PaddleClas和PaddleDetection分别是PaddlePaddle的两个开源项目，关注不同的技术领域。PaddleClas以图像识别和图像分类为主，同时关注基础的骨干网络模型；PaddleDetection以检测技术为主，同时关注关键点、跟踪等方向。
应用场景上，两个repo有一些重合的点，不过各有侧重。就目前版本而言，PaddleClas对小样本区分、识别目标不固定等疑难问题效果更好，整体精度上限更高；PaddleDetection在超轻量模型上更有优势，在移动端设备上速度更快。

**Comment by weisy11** [comment]
在具体的场景中，两个工具的表现各有优劣，如果条件允许，建议都尝试一下，选择更适合的。

**Comment by ericosmic** [comment]
@weisy11  在pp-shitu这样的主体检测项目中，为什么不直接使用paddledectection 模型来作目标识别呢？ 而要作成两阶段识别，再通过矢量索引来分类。
