### ISSUE TITLE
Dataloader 出错

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleClas#1359]
您好，可以帮忙看一下这个报错和警告是什么原因导致的吗
![image](https://user-images.githubusercontent.com/68497831/139574841-b7a54409-8352-4b9e-bc6a-3e21ec28b15b.png)
![image](https://user-images.githubusercontent.com/68497831/139574852-c2b8919d-a769-476d-a064-c1384a88eece.png)
![image](https://user-images.githubusercontent.com/68497831/139574858-e38fe17a-7f0c-4217-bfda-f53e9ede9460.png)

**Comment by weisy11** [comment]
看报错信息像是没有找到训练数据，建议检查一下训练集和验证集数据是否完整
