### ISSUE TITLE
十万分类预训练模型的推断

### ISSUE THREAD

**Issue by youwei2567** [PaddlePaddle/PaddleClas#136]
UnavailableError: Load operator fail to open file pretrained/ResNet50_vd_10w_pretrained/fc_0.w_0, please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(fin) == true, but received static_cast<bool>(fin):0 != true:1.] at (/paddle/paddle/fluid/operators/load_op.h:41)
  [operator < load > error]

**Comment by littletomatodonkey** [comment]
Thanks for your attention, we did not open source the `tag system` and `fc params`, so we can not load the params and infer.
> By the way, the 10W pretrained model can mainly be used to finetune other datasets(the pretrained feature extractor is vital for other tasks).
