### ISSUE TITLE
Error: Pass tensorrt_subgraph_pass has not been registered

### ISSUE THREAD

**Issue by channingblue** [PaddlePaddle/PaddleClas#138]
按照AI Studio中 30分钟玩转PaddleClas的教程，训练完模型并导出后，进行infer的时候报错：

这是指令：
![指令](https://user-images.githubusercontent.com/66236425/83420287-015ae480-a459-11ea-8250-ff545e4bad6b.jpg)

报错 Stack：
![stack](https://user-images.githubusercontent.com/66236425/83420381-25b6c100-a459-11ea-8851-27d1c2890d0f.jpg)

报错 error msg：
![error](https://user-images.githubusercontent.com/66236425/83420404-2c453880-a459-11ea-91b8-8089b220a461.jpg)

请大神帮忙看看，谢谢！

**Comment by channingblue** [comment]
看了前面一个issue中的回答是要安装TensorRT的预编译库，我可不可以把这里的 --use TensorRT设置为False？
改成False又试了一下，但报了另一个错：
![image](https://user-images.githubusercontent.com/66236425/83466083-8faa8700-a4a8-11ea-8494-7fbec17731b9.png)

**Comment by channingblue** [comment]
弄好了，修改了 tools/infer/predict.py 中的代码，将原先的data = open(fname).read()，改为了data = open(fname, 'rb').read()。
执行结果如下：
![image](https://user-images.githubusercontent.com/66236425/83466546-fbd9ba80-a4a9-11ea-9ba0-913552984c97.png)

最后，还是请大神们帮忙指导一下怎么安装TenserRT的预编译库哈，有没有具体步骤，谢谢！

**Comment by littletomatodonkey** [comment]
您好，这篇博客里提到了在T4 GPU上安装并编译trt的paddle：https://blog.csdn.net/u012526003/article/details/106168250
您也可以参考这篇官网文档进行编译和安装：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html

**Comment by channingblue** [comment]
谢谢！
