### ISSUE TITLE
报错：ModuleNotFoundError: No module named 'ppcls'

### ISSUE THREAD

**Issue by qing130** [PaddlePaddle/PaddleClas#1394]
1. 报错：
Traceback (most recent call last):
  File "D:/pyProject/PaddlePaddle-Classification-master/PaddlePaddle-Classification-master/train.py", line 2, in <module>
    from ppcls.data import Reader
ModuleNotFoundError: No module named 'ppcls'

2  测试代码:
from ppcls.data import Reader
from ppcls.utils.config import get_config
from ppcls.utils.save_load import init_model, save_model
from ppcls.utils import logger

补充说明:运行单纯的PaddlePaddle代码是正常，也按照官方方法安装PaddleClas，安装在目录:C:\Users\BHT\PaddleClas。
安装后控制台有提示：
Installing collected packages: prettytable
  Attempting uninstall: prettytable
    Found existing installation: prettytable 2.3.0
    Uninstalling prettytable-2.3.0:
      Successfully uninstalled prettytable-2.3.0
Successfully installed prettytable-2.4.0

然后运行代码import ppcls.data 还是失败。
我的python编译器是用：D:\Anaconda\python.exe  下的。  是否需要把PaddleClas安装到D:\Anaconda目录下？

2. PaddleClas版本：release/static(21-11-03 clone)
   PaddlePaddle版本：2.1.0

 3. 训练环境信息：
  a. Windows10
  b. Python3.8
  c. CUDA11.0/cuDNN cuDNN v8.0.4

**Comment by TingquanGao** [comment]
你好，请问是参考哪个文档运行的呢？启动命令是什么呢？

**Comment by qing130** [comment]
这个close吧。 以上的问题我忘了。 我后来去玩paddleX了。
