### ISSUE TITLE
这几个接口能不能给下用例和参数说明，主要是参数

### ISSUE THREAD

**Issue by ipyffor** [PaddlePaddle/PaddleClas#140]
![image](https://user-images.githubusercontent.com/47955238/83618047-80b4f900-a5bc-11ea-9f54-24c4dd93ccda.png)
其他接口也是，基本没有参数说明

**Comment by littletomatodonkey** [comment]
您好，感谢您的关注，这个脚本里面主要是预处理的实现https://github.com/PaddlePaddle/PaddleClas/blob/master/ppcls/data/imaug/operators.py ，里面有部分解释，我们也会补充该部分的参数解释文档，感谢您的提醒！

**Comment by ipyffor** [comment]
可以聊天回复吗，因为需要用到，每次找不到都提issue太慢了&nbsp;

影


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "littletomatodonkey"<notifications@github.com&gt;; 
发送时间: 2020年6月3日(星期三) 晚上6:09
收件人: "PaddlePaddle/PaddleClas"<PaddleClas@noreply.github.com&gt;; 
抄送: "631707329"<631707329@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleClas] 这几个接口能不能给下用例和参数说明，主要是参数 (#140)





 
您好，感谢您的关注，这个脚本里面主要是预处理的实现https://github.com/PaddlePaddle/PaddleClas/blob/master/ppcls/data/imaug/operators.py ，里面有部分解释，我们也会补充该部分的参数解释文档，感谢您的提醒！

**Comment by ipyffor** [comment]
影


&nbsp;
这个并没有参数说明


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"littletomatodonkey"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月3日(星期三) 晚上6:09
收件人:&nbsp;"PaddlePaddle/PaddleClas"<PaddleClas@noreply.github.com&gt;;
抄送:&nbsp;"631707329"<631707329@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleClas] 这几个接口能不能给下用例和参数说明，主要是参数 (#140)





 
您好，感谢您的关注，这个脚本里面主要是预处理的实现https://github.com/PaddlePaddle/PaddleClas/blob/master/ppcls/data/imaug/operators.py ，里面有部分解释，我们也会补充该部分的参数解释文档，感谢您的提醒！

**Comment by ipyffor** [comment]
![image](https://user-images.githubusercontent.com/47955238/83625023-e8237680-a5c5-11ea-9ec2-acaecbbf9692.png)

**Comment by littletomatodonkey** [comment]
您好，如果您有什么问题需要聊天回复，也可以在这个微信群里提问
![image](https://user-images.githubusercontent.com/14270174/83625697-f02fe600-a5c6-11ea-98f5-16fa2f258c13.png)

**Comment by ipyffor** [comment]
多谢
&nbsp;

影


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "littletomatodonkey"<notifications@github.com&gt;; 
发送时间: 2020年6月3日(星期三) 晚上6:22
收件人: "PaddlePaddle/PaddleClas"<PaddleClas@noreply.github.com&gt;; 
抄送: "631707329"<631707329@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleClas] 这几个接口能不能给下用例和参数说明，主要是参数 (#140)





 
您好，如果您有什么问题需要聊天回复，也可以在这个微信群里提问
