### ISSUE TITLE
qiickstart花朵识别训练报错

### ISSUE THREAD

**Issue by Z-mingyu** [PaddlePaddle/PaddleClas#1402]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，Windows10
  b. Python版本号，Python3.7
  c. CUDA/cuDNN版本， 如CUDA10.1/cuDNN 7.6.5
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log
 
刚搭建的环境，对着这个文档https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/quick_start/quick_start_classification_new_user.md

敲的这行命令
python3 tools/train.py -c ./ppcls/configs/quick_start/ResNet50_vd.yaml -o Arch.pretrained=True

Traceback (most recent call last):
  File "tools/train.py", line 32, in <module>
    engine.train()
  File "D:\PYproject\PaddleClas-release-2.3\ppcls\engine\engine.py", line 265, in train
    self.train_epoch_func(self, epoch_id, print_batch_step)
  File "D:\PYproject\PaddleClas-release-2.3\ppcls\engine\train\train.py", line 49, in train_epoch
    out = forward(engine, batch)
  File "D:\PYproject\PaddleClas-release-2.3\ppcls\engine\train\train.py", line 77, in forward
    return engine.model(batch[0])
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\PYproject\PaddleClas-release-2.3\ppcls\arch\backbone\legendary_models\resnet.py", line 350, in forward
    x = self.stem(x)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\container.py", line 98, in forward
    input = layer(input)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\PYproject\PaddleClas-release-2.3\ppcls\arch\backbone\legendary_models\resnet.py", line 134, in forward
    x = self.conv(x)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\nn\layer\conv.py", line 667, in forward
    use_cudnn=self._use_cudnn)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\nn\functional\conv.py", line 114, in _conv_nd
    pre_bias = getattr(core.ops, op_type)(x, weight, *attrs)
OSError: (External)  Cudnn error, CUDNN_STATUS_EXECUTION_FAILED  (at C:/home/workspace/Paddle_release/paddle/fluid/operators/conv_cudnn_op.cu:348)
  [operator < conv2d > error]

还有就是前面进程设置有警告

D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\reader.py:358: UserWarning: DataLoader with multi-process mode is not supported on MacOs and Windows currently. Please use signle-process mode with num_workers = 0 instead
  "DataLoader with multi-process mode is not supported on MacOs and Windows currently." \
但是代码里面的num_workers 确实是等于0的

**Comment by TingquanGao** [comment]
您好，尝试一下CPU呢：
```shell
python3 tools/train.py -c ./ppcls/configs/quick_start/ResNet50_vd.yaml -o Arch.pretrained=True -o Global.device=cpu
```

**Comment by TingquanGao** [comment]
尝试一下CPU运行呢？
```shell
python3 tools/train.py -c ./ppcls/configs/quick_start/ResNet50_vd.yaml -o Arch.pretrained=True -o Global.device=cpu
```

**Comment by Z-mingyu** [comment]
> 尝试一下CPU运行呢？
> 
> ```shell
> python3 tools/train.py -c ./ppcls/configs/quick_start/ResNet50_vd.yaml -o Arch.pretrained=True -o Global.device=cpu
> ```

CPU可以，我看了一下是cudnn版本出错了，没注意cudnn还要和CUDA版本对应

**Comment by Z-mingyu** [comment]
![屏幕截图 2021-11-05 120325](https://user-images.githubusercontent.com/67858164/140457258-bfc1d9fe-f7fa-4ee0-9108-a0d4ffcf8247.png)
![屏幕截图 2021-11-05 121324](https://user-images.githubusercontent.com/67858164/140457294-19393959-663d-43e3-bc20-e3ac73f1f6de.png)
比较好奇他给我识别程什么了，我怎么看后面的参数就没变过
![屏幕截图 2021-11-05 120755](https://user-images.githubusercontent.com/67858164/140457350-4049786e-c35d-48b6-96b9-7c23106f9d1a.png)
还有这3个哪个是模型文件

**Comment by Z-mingyu** [comment]
返回的是动物名称

**Comment by cuicheng01** [comment]
您好，默认的model_list是ImageNet数据集的，您如果想返回flower对应的名称，需要flower的list，或者这里可以置为None

**Comment by Z-mingyu** [comment]
> 您好，默认的model_list是ImageNet数据集的，您如果想返回flower对应的名称，需要flower的list，或者这里可以置为None

python tools/infer.py -c ./ppcls/configs/quick_start/ResNet50_vd.yaml -o Infer.infer_imgs=dataset/flowers102/jpg/image_00001.jpg -o Global.pretrained_model=output/ResNet50_vd/best_model
这是我的预测命令
请问是改ResNet50_vd.yaml文件吗，但是在里面没找到model_list这个参数

**Comment by Z-mingyu** [comment]
![image](https://user-images.githubusercontent.com/67858164/140517172-a6fdc391-0492-4978-a6fd-f9917239e8d9.png)
是这个参数吗，我改成None后就不显示分类名称了，话说flower的list在哪

**Comment by Z-mingyu** [comment]
![image](https://user-images.githubusercontent.com/67858164/140518267-14f470f4-ba61-41f3-a5fa-5fa81d5ea1f9.png)
这个是生成花卉列表的程序吗，我运行了一下，23行报数组越界错误

**Comment by weisy11** [comment]
> ![image](https://user-images.githubusercontent.com/67858164/140518267-14f470f4-ba61-41f3-a5fa-5fa81d5ea1f9.png) 这个是生成花卉列表的程序吗，我运行了一下，23行报数组越界错误

是的，麻烦看一下上面注释里的Usage部分

**Comment by Z-mingyu** [comment]
![image](https://user-images.githubusercontent.com/67858164/140765554-34097000-a2f8-4901-b1f4-0548de729a7d.png)
主要是这2个.mat文件哪来的，是要自己手动生成吗，我没看懂上面的解释是什么意思

**Comment by weisy11** [comment]
文档写的可能还不够细致，我们优化一下

**Comment by TingquanGao** [comment]
你好！flowes102 数据集的 lable map 文件我们已经上传，请重新下载并解压 `https://paddle-imagenet-models-name.bj.bcebos.com/data/flowers102.zip`。在预测时，请修改配置文件中的 `Infer.PostProcess.class_id_map_file` 字段为 ` ./dataset/flowers102/flowers102_label_list.txt`。具体可参考 #1422 。

关于 Paddle 的模型文件问题，可以参考[文档](https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.3/docs/zh_CN/faq_series/faq_2020_s1.md#q41-paddlepaddle-%E7%9A%84%E6%A8%A1%E5%9E%8B%E6%96%87%E4%BB%B6%E9%83%BD%E6%9C%89%E5%93%AA%E5%87%A0%E7%A7%8D)。

有问题可继续反馈，谢谢！
