### ISSUE TITLE
在GPU下使用图像识别模型报错

### ISSUE THREAD

**Issue by DrewdropLife** [PaddlePaddle/PaddleClas#1409]
```
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1636099131 (unix time) try "date -d @1636099131" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 3521 (TID 0x7fe7f9808740) from PID 0 ***]

Segmentation fault (core dumped)
```
CPU能够正常使用，但GPU会报如上错误信息，paddle版本为2.1.3-gpu

**Comment by cuicheng01** [comment]
您好，这个是在运行哪一步出错的呢？其硬件信息方便提供一下吗？

**Comment by TingquanGao** [comment]
你好，可以试一下代码：
```python
import paddle
paddle.utils.run_check()
```

看看paddle是否安装成功。

**Comment by DrewdropLife** [comment]
> 你好，可以试一下代码：
> 
> ```python
> import paddle
> paddle.utils.run_check()
> ```
> 
> 看看paddle是否安装成功。

Running verify PaddlePaddle program ... 
W1108 14:22:13.180444 11057 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.2
W1108 14:22:13.186300 11057 device_context.cc:422] device: 0, cuDNN Version: 8.0.
PaddlePaddle works well on 1 GPU.
W1108 14:22:15.273317 11057 parallel_executor.cc:601] Cannot enable P2P access from 0 to 1
W1108 14:22:15.273361 11057 parallel_executor.cc:601] Cannot enable P2P access from 1 to 0
W1108 14:22:17.449007 11057 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
PaddlePaddle works well on 2 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

安装没问题

**Comment by DrewdropLife** [comment]
> 您好，这个是在运行哪一步出错的呢？其硬件信息方便提供一下吗？

https://github.com/PaddlePaddle/PaddleClas/blob/de6112a817b64b0561d85d678dc00d5faee13618/deploy/python/predict_det.py#L120

执行python python/predict_system.py -c configs/inference_product.yaml后，在此行报错
CUDA版本11.0

**Comment by TingquanGao** [comment]
试过安装2.2版本的Paddle吗？

**Comment by upperblacksmith** [comment]
> 试过安装2.2版本的Paddle吗？

同样的报错，paddlepaddle就是2.2.0版本的

**Comment by upperblacksmith** [comment]
> > 您好，这个是在运行哪一步出错的呢？其硬件信息方便提供一下吗？
> 
> https://github.com/PaddlePaddle/PaddleClas/blob/de6112a817b64b0561d85d678dc00d5faee13618/deploy/python/predict_det.py#L120
> 
> 执行python python/predict_system.py -c configs/inference_product.yaml后，在此行报错 CUDA版本11.0

你好，请问这个问题解决了吗，环境要求啥的其实都是按照要求来的，但就是不能使用GPU推理，cpu可以

**Comment by cuicheng01** [comment]
您好，方便提供下硬件信息以及安装过程吗？

**Comment by upperblacksmith** [comment]
> 您好，方便提供下硬件信息以及安装过程吗？
你好，具体的安装和硬件信息在这个里面我有提供 https://github.com/PaddlePaddle/PaddleClas/issues/1435 这个报错应该是同一个问题引起的，我用得是pip安装的paddleclas。

**Comment by cuicheng01** [comment]
建议彻底pip uninstall 各种paddlepadlde-gpu和paddlepaddle之后，重新pip install paddlepaddle-gpu试试

**Comment by upperblacksmith** [comment]
> 建议彻底pip uninstall 各种paddlepadlde-gpu和paddlepaddle之后，重新pip install paddlepaddle-gpu试试

还是不起作用，重新换一个新的环境安装还是不work

**Comment by njustczr** [comment]
> > 建议彻底pip uninstall 各种paddlepadlde-gpu和paddlepaddle之后，重新pip install paddlepaddle-gpu试试
> 
> 还是不起作用，重新换一个新的环境安装还是不work

我也碰到这个问题   运行build_gallery.py的时候，楼主解决了吗？
