### ISSUE TITLE
请问一下，飞桨有尝试使用HRNet来进行ImageNet的分类任务吗？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleClas#141]
尊敬的开发者，你好！
请问一下，飞桨有尝试使用HRNet来进行ImageNet的分类任务吗？

期待你的回复！

**Comment by littletomatodonkey** [comment]
您好，感谢您的关注，我们已经复现并在ImageNet上验证了HRNet
* 配置文件地址：https://github.com/PaddlePaddle/PaddleClas/tree/master/configs/HRNet
* 模型文件地址：https://github.com/PaddlePaddle/PaddleClas/blob/master/ppcls/modeling/architectures/hrnet.py
* 分类精度指标和相应的预测速度文档：https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/zh_CN/models/HRNet.md

**Comment by songyuc** [comment]
@littletomatodonkey ，感谢你的信息和分享，
从结果上面看，HRNet的精度似乎不及SENet，

**Comment by littletomatodonkey** [comment]
是的，HRNet因为融合了高层特征和高分辨率特征，所以它在对分辨率信息敏感的任务里还是非常有优势的，比如关键点检测等任务。

**Comment by songyuc** [comment]
@littletomatodonkey ，谢谢你的解答！
