### ISSUE TITLE
centerloss.py中的center始终是随机值，无法收敛

### ISSUE THREAD

**Issue by chenhaohan88** [PaddlePaddle/PaddleClas#1411]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如Linux/Windows/MacOS
  b. Python版本号，如Python3.6/7/8
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

centerloss.py中的center始终是随机值，无法收敛
![image](https://user-images.githubusercontent.com/66461493/140490265-91f37daa-7842-43fc-b332-43c52ca57f53.png)

**Comment by Intsigstephon** [comment]
好的，感谢您的反馈~ 我们会尽快看下

**Comment by Intsigstephon** [comment]
您好，centerloss的实现确实有点问题，正在优化中；如果项目紧急的话，可以先尝试使用arcmargin，该方法已在PaddleClas的多个图像识别任务中被运用，效果也得到验证
