### ISSUE TITLE
车辆ReId里面的Loss

### ISSUE THREAD

**Issue by lucy3589** [PaddlePaddle/PaddleClas#1413]
1.训练和eval的Loss为什么不一样？
2.训练的2个Loss（SuperCon、ArcFace）是按照1:1相加之后作为整体loss反向传播？
3.CE loss属于绝对约束吗？

附录：
Loss:
  Train:
    - CELoss:
        weight: 1.0
    - SupConLoss:
        weight: 1.0
        views: 2
  Eval:
    - CELoss:
        weight: 1.0

**Comment by cuicheng01** [comment]
1.训练同时兼顾了classification based loss和pair based loss，eval的loss无所谓，主要看评价指标，所以eval的loss选什么都无关紧要；
2.目前默认是按1：1的配置，也可以自己定义Loss的权重，在yaml中可以直接修改哈；
3.CELoss算是绝对约束

**Comment by lucy3589** [comment]
谢谢解答
