### ISSUE TITLE
Is it possible to release the documentation in English?

### ISSUE THREAD

**Issue by eladmeir** [PaddlePaddle/PaddleClas#1414]
Hey all

I would really much like to try and test this repo, but all of its documentation is in Chinese (I think...), while the article published in English

I was wondering if an English version documentation is possible?

Thanks.

**Comment by weisy11** [comment]
Yes, you can click "English" on the top of homepage.
![27ed97eabacfe1d21c0759d6ee7f8a1f](https://user-images.githubusercontent.com/19523330/140679303-ab837d5e-df1e-4a1d-94a5-dff40e7bfd81.png)

**Comment by eladmeir** [comment]
Thanks
