### ISSUE TITLE
“未知类别的图像识别体验”中为什么不需要重新训练？

### ISSUE THREAD

**Issue by DaydreamQ** [PaddlePaddle/PaddleClas#1418]
“由于默认的索引库中不包含对应的索引信息，所以这里的识别结果有误，此时我们可以通过构建新的索引库的方式，完成未知类别的图像识别。

当索引库中的图像无法覆盖我们实际识别的场景时，即在预测未知类别的图像时，我们需要将对应类别的相似图像添加到索引库中，从而完成对未知类别的图像识别，这一过程是不需要重新训练的。”

上文是从“快速识图体验”的ReadMe中摘抄出来的，我不明白为什么识别未知图像不需要重新训练模型。依据后文展示，我们还是需要将未知识别图像类似的图片放进gallery文件夹中，并在label.txt中重新定义图片的label，然后重新构建index。这一过程我理解就在重新训练模型，不太明白.md中为什么说不用重新训练。还请解答一下，谢谢~

**Comment by weisy11** [comment]
我们这里的『训练』是指深度学习模型经过前向和反向运算，更新模型中参数的过程。
重新构建index的过程中不涉及反向计算，也不更新深度学习模型的参数，所以这里我们说『不需要重新训练』

**Comment by DaydreamQ** [comment]
> 我们这里的『训练』是指深度学习模型经过前向和反向运算，更新模型中参数的过程。 重新构建index的过程中不涉及反向计算，也不更新深度学习模型的参数，所以这里我们说『不需要重新训练』

好的明白了，谢谢
