### ISSUE TITLE
新建特征索引库时，报错

### ISSUE THREAD

**Issue by upperblacksmith** [PaddlePaddle/PaddleClas#1435]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如Linux/Windows/MacOS
  b. Python版本号，如Python3.6/7/8
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log
![image](https://user-images.githubusercontent.com/34127965/141449800-ae60e79d-f586-4d53-88f5-e992043b1b49.png)
1.paddleclas版本：2.3.0，paddlepaddle版本：2.2.0
3.操作系统：Linux  python版本：3.8

**Comment by upperblacksmith** [comment]
![image](https://user-images.githubusercontent.com/34127965/141452548-25f89ab3-ee3b-4291-b4da-59f4ccf2fbae.png)
![image](https://user-images.githubusercontent.com/34127965/141452613-f9aeda48-22e0-4e47-982c-a57c05b11c45.png)
![image](https://user-images.githubusercontent.com/34127965/141452662-eb03f802-fc06-4609-b34c-c73febbf6565.png)
建立索引库的代码如上两张图所示 build_30sku.yaml
运行命令如第三张图所示
显卡信息：单卡2080ti cuda版本：11.1 cudnn:8.1

**Comment by RainFrost1** [comment]
此问题猜测是底层库跟paddle之间的环境问题，如使用paddle官方docker，则删掉容器后，重新启动，基本可以正常使用。具体问题还在定位中
