### ISSUE TITLE
导出10W预训练模型key不对应

### ISSUE THREAD

**Issue by ajundo** [PaddlePaddle/PaddleClas#1438]
PaddleClas的版本是2.3.

我通过一下命令导出10W的预训练模型：
python3 tools/export_model.py \ 
-c ppcls/configs/ImageNet/ResNet/ResNet50_vd.yaml \ 
-o Global.save_inference_dir="100k" \ 
-o Global.pretrained_model="ResNet50_vd_10w_pretrained"

与此同时，我注释掉了这一行：
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/ppcls/arch/backbone/legendary_models/resnet.py#L355

报如下错误，也就是所有层的参数都没有加载：
UserWarning: Skip loading for blocks.15.conv2.conv.weight. blocks.15.conv2.conv.weight is not found in the provided dict.

我用pkl打开ResNet50_vd_10w_pretrained.pdparams，里面的key是'bb_x_x.convx._batch_norm._variance'。

**Comment by cuicheng01** [comment]
这个模型目前没有最后的FC层的权重，这个权重是用来做finetune的哈，导出inference model没太大的作用~

**Comment by ajundo** [comment]
> 这个模型目前没有最后的FC层的权重，这个权重是用来做finetune的哈，导出inference model没太大的作用~

是的，因此我注释掉了arch里的fc层，用于提取特征，类似于metric learning的做法。目前的问题在于key的不匹配。

**Comment by cuicheng01** [comment]
好的，这个问题我们跟进下，不过我们的PP-ShiTu的模型经过了18w类别的数据，可以试试哦
