### ISSUE TITLE
能够给更多小模型的ssld预训练模型吗？

### ISSUE THREAD

**Issue by guwen007** [PaddlePaddle/PaddleClas#1440]
感谢paddle的预训练模型，非常的work。请问，能够提供更多小模型的ssld预训练模型吗，比如resnet18，hrnetv2-small？

**Comment by cuicheng01** [comment]
您好，这里我们提供了一些移动端的ssld模型，可以试用哦https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/algorithm_introduction/ImageNet_models.md

**Comment by seefun** [comment]
同求，ResNet18_vd这样的更小一点的服务端知识蒸馏模型，未来有计划去做吗

**Comment by cuicheng01** [comment]
您好，我们会考虑，请持续关注PaddleClas~
