### ISSUE TITLE
人脸检索模型训练参照哪个配置文件比较好

### ISSUE THREAD

**Issue by zhufeijuanjuan** [PaddlePaddle/PaddleClas#1442]
我基于LFW数据集，将每张图片的人脸部分切出来作为训练数据，训练集和测试集整理格式如下
三个字段分别为图片名，label和unique_id。训练集人脸类别4700类，测试集人脸类别700类。
尝试着参照MobileNetV1_retireval.yaml训练模型，但是验证集的recall不到0.5。请问做这样的人脸识别任务参照哪个配置文件比较好，谢谢。
train_face/0/Kyle_Shewfelt_0001_0_.jpg 0 0
train_face/1/Jennifer_Garner_0008_0_.jpg 1 1
train_face/1/Jennifer_Garner_0005_1_.jpg 1 2
train_face/1/Jennifer_Garner_0004_2_.jpg 1 3
train_face/1/Jennifer_Garner_0011_3_.jpg 1 4
train_face/1/Jennifer_Garner_0009_4_.jpg 1 5
train_face/1/Jennifer_Garner_0001_5_.jpg 1 6
train_face/1/Jennifer_Garner_0003_6_.jpg 1 7
train_face/1/Jennifer_Garner_0010_7_.jpg 1 8
train_face/1/Jennifer_Garner_0006_9_.jpg 1 9
train_face/1/Jennifer_Garner_0002_10_.jpg 1 10
train_face/1/Jennifer_Garner_0012_11_.jpg 1 11
train_face/2/Prince_Rainier_III_0001_0_.jpg 2 12
train_face/3/Ben_Chandler_0001_0_.jpg 3 13

**Comment by Intsigstephon** [comment]
人脸任务推荐使用ArcFace; 可以参照 GeneralRecognition/GeneralRecognition_PPLCNet_x2_5.yaml

**Comment by Intsigstephon** [comment]
该配置文件使用的是PP-LCNet作为骨干网络，可以使用默认的骨干网络，也可以依据业务的需要修改骨干网络；另外，需要修改训练的类别数和训练数据地址。文档参照： https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/image_recognition_pipeline/feature_extraction.md
