### ISSUE TITLE
PPLCNet训练多类别模型

### ISSUE THREAD

**Issue by lllbq** [PaddlePaddle/PaddleClas#1450]
如果要训练多类别目标，configs中的PPLCNet配置文件可以开箱即用吗？
![image](https://user-images.githubusercontent.com/44738266/142164142-10938e88-8ae5-4315-9658-d7cceff56027.png)

**Comment by lllbq** [comment]
表述有点问题，应该是多标签模型。

**Comment by cuicheng01** [comment]
默认是单标签的，如果训练多标签的，可以参考https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/quick_start/quick_start_multilabel_classification.md
替换模型为PPLCNet即可
