### ISSUE TITLE
bug report: 配置文件中class_num 不起作用

### ISSUE THREAD

**Issue by jeffzhengye** [PaddlePaddle/PaddleClas#1452]
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/ppcls/configs/quick_start/ResNet50_vd.yaml

这些配置文件中不能在Global 中设置 class_num, 建立模型时只用**Arch:**中的配置。

**Comment by Intsigstephon** [comment]
好的，感谢您的反馈，我们会尽快修复的

**Comment by cuicheng01** [comment]
已修复，感谢
