### ISSUE TITLE
PP-ShiTu论文的实现

### ISSUE THREAD

**Issue by TimZhang001** [PaddlePaddle/PaddleClas#1456]
您好，
我看了PP-ShiTu的论文，上面有提到使用了Unified-Deep Mutual Learning以及DeepHash，但是我在看代码的时候没有发现这些功能呀。

**Comment by nan-wang** [comment]
> ... Specifically, we have open sourced three of the most common DeepHash algorithms: DLBHC (Lin et al. 2015), LCDSH (Cao et al. 2017), DSHSD (Wu et al. 2019b).
I have the same question. Where can we find the codes?

**Comment by nan-wang** [comment]
I think the codes are here https://github.com/PaddlePaddle/PaddleClas/blob/9312a29bc5dd34fbce219961c16e012a1baed7f5/ppcls/loss/deephashloss.py

**Comment by TimZhang001** [comment]
我看到了这个代码，但是实际的流程里面没有怎么应用的实例

**Comment by weisy11** [comment]
DeepHash的应用可以参考：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/ppcls/configs/quick_start/professional/VGG19_CIFAR10_DeepHash.yaml
U-DML的应用可以参考：
https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.3/ppcls/configs/ImageNet/Distillation/mv3_large_x1_0_distill_mv3_small_x1_0.yaml
PP-ShiTu的arxiv文章我们正在整理和优化，大约12月中旬之前会放出更新的版本，并同步更新示例配置文件。

**Comment by TimZhang001** [comment]
非常感谢，目前实现的只是增加了一个ArcMargin的度量学习模块，然后根据向量检索的召回率来选择最优化的模型，但是实际的loss还是最简单的CELoss，并没有论文上讲的那么复杂，不知道这个理解对不对？
非常期待U-DML和DeepHash带来的效果提升。

**Comment by weisy11** [comment]
> 非常感谢，目前实现的只是增加了一个ArcMargin的度量学习模块，然后根据向量检索的召回率来选择最优化的模型，但是实际的loss还是最简单的CELoss，并没有论文上讲的那么复杂，不知道这个理解对不对？ 非常期待U-DML和DeepHash带来的效果提升。

这块的配置和代码还在整理当中，后面更新的时候会给出消融实验配置的汇总。
