### ISSUE TITLE
关于PP-ShiTu的识别结果

### ISSUE THREAD

**Issue by Breeze-Zero** [PaddlePaddle/PaddleClas#1458]
我自己的数据集分别对主体检测模型与特征提取模型进行训练，目前出现的问题是：当我输入一张图片到PP-ShiTu进行识别时，每张图(size=320*320)可视化结果都会有一个对于整张图的bbox: [0, 0, 320, 320]，但我并不想要这个结果出现，而且这个结果大多数时候是错误的。请问这是我主体检测模型训练出现了问题还是说代码内默认存在这个操作？

**Comment by weisy11** [comment]
这个是代码内的默认操作，在这里：
https://github.com/PaddlePaddle/PaddleClas/blob/74e934a6be0808358086a07e09f92c78cd2518c6/deploy/python/predict_system.py#L103

**Comment by Breeze-Zero** [comment]
感谢您的回复，这个问题我解决了，但现在又遇到新的一个问题，同心的重叠框，内部应该显示的框并不会被检测到

**Comment by weisy11** [comment]
> 感谢您的回复，这个问题我解决了，但现在又遇到新的一个问题，同心的重叠框，内部应该显示的框并不会被检测到

是的，这种情况下，2个框很可能会被合并成一个框

**Comment by Breeze-Zero** [comment]
> > 感谢您的回复，这个问题我解决了，但现在又遇到新的一个问题，同心的重叠框，内部应该显示的框并不会被检测到
> 
> 是的，这种情况下，2个框很可能会被合并成一个框

那我对NMS代码进行修改，比如改成针对每个类别做NMS，效果会不会提升？因为我数据的特殊性，需要这种不同类别的重叠框，另外，我其实需要衡量检测效果的mAP，比如接入coco eval接口，但目前的代码貌似没有这个功能，不知后续是否会完善

**Comment by Hold-on-li** [comment]
请问安装的faiss支持windows系统吗？

**Comment by weisy11** [comment]
> 请问安装的faiss支持windows系统吗？

支持的

**Comment by weisy11** [comment]
> > > 感谢您的回复，这个问题我解决了，但现在又遇到新的一个问题，同心的重叠框，内部应该显示的框并不会被检测到
> > 
> > 
> > 是的，这种情况下，2个框很可能会被合并成一个框
> 
> 那我对NMS代码进行修改，比如改成针对每个类别做NMS，效果会不会提升？因为我数据的特殊性，需要这种不同类别的重叠框，另外，我其实需要衡量检测效果的mAP，比如接入coco eval接口，但目前的代码貌似没有这个功能，不知后续是否会完善

这个需求我们会记录一下，不过暂时没有计划

**Comment by Hold-on-li** [comment]
> > 请问安装的faiss支持windows系统吗？
> 
> 支持的

请问一下，PP识图中如何将自己拍摄的照片转换为COCO格式的，用什么软件转换？
