### ISSUE TITLE
使用Paddle Serving部署识别模型时运行pipeline_http_client.py出现错误

### ISSUE THREAD

**Issue by intjun** [PaddlePaddle/PaddleClas#1468]
运行pipeline_http_client.py出现错误：
import requests
import json
import base64
import os
imgpath = "../../drink_dataset_v1.0/test_images/001.jpeg"
def cv2_to_base64(image):
    return base64.b64encode(image).decode('utf8')
if __name__ == "__main__":
    url = "http://127.0.0.1:18081/recognition/prediction"

    with open(os.path.join(".", imgpath), 'rb') as file:
        image_data1 = file.read()
    image = cv2_to_base64(image_data1)
    data = {"key": ["image"], "value": [image]}
    for i in range(1):
        r = requests.post(url=url, data=json.dumps(data))
        print(r.json())
报出错误如下：
{'err_no': 8, 'err_msg': '(data_id=4 log_id=0) [det|0] Failed to postprocess: postprocess() takes 4 positional arguments but 5 were given', 'key': [], 'value': [], 'tensors': []}

**Comment by NingRC** [comment]
PipelineClient::predict pack_data time:1637734865.062319
PipelineClient::predict before time:1637734865.0626535
err_no: 8
err_msg: "(data_id=0 log_id=0) [det|1] Failed to postprocess: postprocess() takes 4 positional arguments but 5 were given"

我也遇到相同问题，请问解决了吗？参考[](https://blog.csdn.net/a18838956649/article/details/120766977)，没有得到解决

**Comment by NingRC** [comment]
PipelineClient::predict pack_data time:1637734865.062319
PipelineClient::predict before time:1637734865.0626535
err_no: 8
err_msg: "(data_id=0 log_id=0) [det|1] Failed to postprocess: postprocess() takes 4 positional arguments but 5 were given"

我也遇到同样的问题，请问解决了吗？，参考[https://blog.csdn.net/a18838956649/article/details/120766977](url)没有得到解决。

**Comment by Intsigstephon** [comment]
已修复该问题，请参考develop分支上的代码

**Comment by flash0729** [comment]
修复是def postprocess(self, input_dicts, fetch_data, data_id, log_id)，这里添加data_id参数吗？

> 已修复该问题，请参考develop分支上的代码
