### ISSUE TITLE
关于图像通道顺序的提示。

### ISSUE THREAD

**Issue by GaussRieman** [PaddlePaddle/PaddleClas#1474]
在build_gallery.py中，有一句
`img = img[:, :, ::-1]`
作用是将OpenCV读取的BGR图像转成RGB，因为项目里默认的模型输入是RGB的。

但如果我们用其他的模型来提特征，输入不是RGB，就要注意了，可能会因为颜色空间不对造成最终结果不对。

建议把这种预处理操作，统一放到feature部分去处理。

**Comment by RainFrost1** [comment]
感谢所提建议，能否详细描述下，统一放到feature部分处理的做法及期望，我们评估一下

**Comment by Intsigstephon** [comment]
> 在build_gallery.py中，有一句 `img = img[:, :, ::-1]` 作用是将OpenCV读取的BGR图像转成RGB，因为项目里默认的模型输入是RGB的。
> 
> 但如果我们用其他的模型来提特征，输入不是RGB，就要注意了，可能会因为颜色空间不对造成最终结果不对。
> 
> 建议把这种预处理操作，统一放到feature部分去处理。

这儿说的其他的模型是指？
