### ISSUE TITLE
res2net 200模型命名python2错误

### ISSUE THREAD

**Issue by miraclebiu** [PaddlePaddle/PaddleClas#148]
在创建res2net 200层模型时，py2会报错：
`UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 4: invalid start byte`

因为层数超过26个英文字母，代码里的命名会出错
`conv_name = "res" + str(block+2) + chr(97+i) `

代码里的上一个分支应该增加res2net200
`if layers in [101, 152, 200] and block == 2:  `

**Comment by miraclebiu** [comment]
下载下来的res2net 200 weights中的命名方式已经变了，但是代码没变
[https://paddleclas.readthedocs.io/zh_CN/latest/models/models_intro.html#id4](url)

**Comment by littletomatodonkey** [comment]
您好，我们给出的是res2net200-vd的模型结构文件。
https://github.com/PaddlePaddle/PaddleClas/blob/b1835f01d40e01d370899f492a2137e3ad189ae9/ppcls/modeling/architectures/res2net_vd.py#L84
您使用的时候是vd结构吗？

**Comment by miraclebiu** [comment]
> 您好，我们给出的是res2net200-vd的模型结构文件。
> https://github.com/PaddlePaddle/PaddleClas/blob/b1835f01d40e01d370899f492a2137e3ad189ae9/ppcls/modeling/architectures/res2net_vd.py#L84
> 
> 
> 您使用的时候是vd结构吗？

下载的比较早，原来已经修复了。
