### ISSUE TITLE
优化参数

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleClas#1484]
![image](https://user-images.githubusercontent.com/87969070/143518718-f2a72fe6-877b-4692-b2df-0d35f9a0b560.png)
请问这个k对应是哪一个值？具体的含义是什么？

**Comment by cuicheng01** [comment]
k是某一个数，这个数是多少取决于你的设置

**Comment by cuicheng01** [comment]
就是比如你现在的配置是256的bs，0.1的lr，为了最后的精度一致，那你也可以用512的bs，0.2的lr去训练。
