### ISSUE TITLE
 demo运行出错

### ISSUE THREAD

**Issue by Cristhine** [PaddlePaddle/PaddleClas#149]
paddle环境1.7.2 cuda9.0 cudnn7.5
如果使用命令/home/vis/duyuting/app/anaconda3/bin/python -m paddle.distributed.launch     --selected_gpus="0"     tools/train.py         -c ./configs/quick_start/ResNet50_vd.yaml 会报错:
Error: Failed to find dynamic library: libnccl.so ( /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/vis/duyuting/app/nccl_2.5.6-1+cuda10.0_x86_64/lib/libnccl.so) )
 Please specify its path correctly using following ways:
 Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS.
 For instance, issue command: export LD_LIBRARY_PATH=...
 Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled. at (/paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:177)
  [operator < gen_nccl_id > error] 看起来是nccl问题
去官网下载了cuda9版本的nccl报错：
Error: An error occurred here. There is no accurate error hint for this error yet. We are continuously in the process of increasing hint for this kind of error check. It would be helpful if you could inform us of how this conversion went by opening a github issue. And we will resolve it with high priority.
  - New issue link: https://github.com/PaddlePaddle/Paddle/issues/new
  - Recommended issue content: all error stack information
  [unhandled system error] at (/paddle/paddle/fluid/operators/distributed_ops/gen_nccl_id_op.cc:162)
  [operator < gen_nccl_id > error]
如果不使用分布式命令:/home/vis/duyuting/app/anaconda3/bin/python tools/train.py         -c ./configs/quick_start/ResNet50_vd.yaml 报错：Traceback (most recent call last):
  File "tools/train.py", line 133, in <module>
    main(args)
  File "tools/train.py", line 59, in main
    fleet.init(role)
  File "/home/vis/duyuting/app/anaconda3/lib/python3.7/site-packages/paddle/fluid/incubate/fleet/base/fleet_base.py", line 202, in init
    self._role_maker.generate_role()
  File "/home/vis/duyuting/app/anaconda3/lib/python3.7/site-packages/paddle/fluid/incubate/fleet/base/role_maker.py", line 500, in generate_role
    assert self._worker_endpoints is not None, "can't find PADDLE_TRAINER_ENDPOINTS"
这个库难道不能单gpu运行？？？？

**Comment by littletomatodonkey** [comment]
您好，PaddleClas是支持单GPU运行的，这个可能是因为您的glibc版本有问题导致的，建议升级下glibc库

**Comment by Cristhine** [comment]
> 您好，PaddleClas是支持单GPU运行的，这个可能是因为您的glibc版本有问题导致的，建议升级下glibc库

我指定了一个nccl2.1.15 单gpu跑通了 但是多gpu还是不可以 请问多gpu应该去下载哪个版本的nccl 我试了很多版本 依然报错nccl 问题的错误

**Comment by littletomatodonkey** [comment]
您好，nccl版本和paddle版本以及平台的对应关系在这里，
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.6/beginners_guide/install/index_cn.html

**Comment by Cristhine** [comment]
> 您好，nccl版本和paddle版本以及平台的对应关系在这里，
> https://www.paddlepaddle.org.cn/documentation/docs/zh/1.6/beginners_guide/install/index_cn.html

解决一下不用python -m paddle.distributed.launch这个命令报错can't find PADDLE_TRAINER_ENDPOINTS"解决方案吧 感觉这个分布式要求太多 以前旧版本可以不用这个分布式运行

**Comment by littletomatodonkey** [comment]
好的，感谢您的反馈，我们近期会添加对非fleet环境的支持，敬请期待。

**Comment by littletomatodonkey** [comment]
您好，我们已经添加对windows和cpu环境的模型训练与评估支持，您可以参考这个PR： #159
