### ISSUE TITLE
I want to submit the weight of paddle's vgg-bn converted from the weight of pytorch's vgg-bn

### ISSUE THREAD

**Issue by zhangjinCV** [PaddlePaddle/PaddleClas#1499]
I want to submit the weight of paddle's vgg-bn converted from the weight of pytorch's vgg-bn, but I don't know the process of submitting the weight file. Is it to upload the weight to Baidu network disk? Can you tell me the  PR process for submitting weight files?

**Comment by weisy11** [comment]
你好，欢迎给PaddleClas贡献代码。vgg-bn和vgg模型结构不同，如果你想添加Vgg-bn到PaddleClas，需要以下步骤：
1.根据[贡献指南](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/advanced_tutorials/how_to_contribute.md) 提交vgg-bn的网络结构代码和配置文件，可以参考vgg进行修改。考虑到现有用户的使用，我们建议将vgg-bn作为一个新的系列模型，添加独立的代码和配置，而不是修改现有vgg的代码和配置
2.通过百度网盘等第三方网盘上传权重文件，附在PR的说明里。我们会下载这些权重并进行验证，验证通过后上传到百度的公网服务器上，方便其他用户下载
