### ISSUE TITLE
PaddleClas的backbone里MODEL_URLS链接有误

### ISSUE THREAD

**Issue by hfy-swu** [PaddlePaddle/PaddleClas#1502]
具体位置：PaddleClas/ppcls/arch/backbone/model_zoo/se_resnext_vd.py
![QQ图片20211130164545](https://user-images.githubusercontent.com/83652390/144014858-c2e563a2-a3ec-4e4e-8552-0834e974ee6d.png)
可以看到两条URL都是Se_ReNeXt50_vd的预训练模型

**Comment by cuicheng01** [comment]
这里确实有重复，已更新：https://github.com/PaddlePaddle/PaddleClas/pull/1504
感谢发现问题。
