### ISSUE TITLE
resnet_vd训练出错，没有is_test字段

### ISSUE THREAD

**Issue by barry2025** [PaddlePaddle/PaddleClas#151]
paddle版本：1.7.1
config: ResNet50_vd.yaml
执行训练后出错：
![image](https://user-images.githubusercontent.com/20043808/84037732-90c04480-a9d1-11ea-8071-efe130860ec2.png)
resnet50_vd init中确实没有is_test字段，但是program.create_model中会传入这个字段：
![image](https://user-images.githubusercontent.com/20043808/84037827-b3eaf400-a9d1-11ea-826c-5bbd196eccc1.png)
请问下这里是我的版本问题吗？

**Comment by littletomatodonkey** [comment]
您好，这个问题已经修复，麻烦获取下最新代码，您也可以参考这个PR： #147

**Comment by barry2025** [comment]
多谢！更新paddle版本后已解决。现在是出现如下错误：
![image](https://user-images.githubusercontent.com/20043808/84098855-e11fbc80-aa3a-11ea-8ff1-e91523feca33.png)
看着跟算loss有关，请问下是类别配置的问题么

**Comment by littletomatodonkey** [comment]
您好，看着应该是某个变量的stop_gradient应该设置为true，方便提供下您的训练脚本吗？我这边复现看下

**Comment by barry2025** [comment]
训练脚本：https://bj.bcebos.com/v1/mct-imagedb/tangxin-bos/tmp/prob/train.sh
yaml文件：https://bj.bcebos.com/v1/mct-imagedb/tangxin-bos/tmp/prob/ResNet50_vd.yaml
构建数据集后，修改yaml文件，模型结构方面没有修改
目前paddleclas版本：
![image](https://user-images.githubusercontent.com/20043808/84102674-b25a1400-aa43-11ea-848a-1b01ee332683.png)
麻烦帮忙看下

**Comment by littletomatodonkey** [comment]
您好，您可以切换到Paddle1.8以上版本，也可以参考 #153  去获取下最新代码。

**Comment by barry2025** [comment]
请问下您这边的建议呢，跑paddlelclas库是用paddle18比较好？(我这边目前跑paddledection用paddle18，跑其中一个yml时，会有一个element op相关的错误)

**Comment by littletomatodonkey** [comment]
您可以修改代码之后，使用paddle1.7或者2.0

**Comment by barry2025** [comment]
好的，非常感谢！修改后可以跑起来了
