### ISSUE TITLE
PPShiTu识别系统的特征提取部分

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleClas#1510]
有没有该部分的数据集下载链接
![image](https://user-images.githubusercontent.com/87969070/144188533-4324c1fd-7d41-4908-b446-e59b38c4cfe6.png)
我在官方下载的数据集，并没有按照特征提取数据集样式出现

**Comment by Intsigstephon** [comment]
需要写个脚本转化下，转成识别数据集的格式：https://github.com/Intsigstephon/PaddleClas/blob/develop/docs/zh_CN/data_preparation/recognition_dataset.md#1
