### ISSUE TITLE
增加线程数，特征抽取和特征检索耗时增加是什么情况

### ISSUE THREAD

**Issue by upperblacksmith** [PaddlePaddle/PaddleClas#1518]
![image](https://user-images.githubusercontent.com/34127965/144396551-849865c6-39cf-427b-9425-1a492929b66c.png)
![image](https://user-images.githubusercontent.com/34127965/144396695-89297536-16e1-4a31-ba63-266b89567b15.png)

服务器cpu是10核20线程的，两次均使用cpu推理

**Comment by Intsigstephon** [comment]
enable_mkldnn设置为True试试
