### ISSUE TITLE
PPShiTu预测报错

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleClas#1520]
![image](https://user-images.githubusercontent.com/87969070/144556649-e076d0f8-3b65-447a-b342-cd03738f7946.png)
![image](https://user-images.githubusercontent.com/87969070/144556670-53c21e0f-9db4-4dc7-9f85-5e430d9b5980.png)
单独使用主体检测时预测没有问题，但是运行最后的预测报该错误，请问是怎么一回事呢？路径都检测很多遍了

**Comment by 18362890185** [comment]
> ![image](https://user-images.githubusercontent.com/87969070/144556649-e076d0f8-3b65-447a-b342-cd03738f7946.png) ![image](https://user-images.githubusercontent.com/87969070/144556670-53c21e0f-9db4-4dc7-9f85-5e430d9b5980.png) 单独使用主体检测时没有问题，但是运行最后的预测报该错误，请问是怎么一回事呢？路径都检测很多遍了

主体检测预测没有问题
