### ISSUE TITLE
PPShiTu预测

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleClas#1521]
![image](https://user-images.githubusercontent.com/87969070/144560281-5b18feed-174b-4acd-9b53-34d5af151fd4.png)
![image](https://user-images.githubusercontent.com/87969070/144560229-18c010d7-2c66-4cd2-9263-8484de5d147f.png)
图一是主体检测预测的结果，图二是PPShiTu最终预测的结果,
![image](https://user-images.githubusercontent.com/87969070/144560395-f38b998f-8e9d-4687-85be-0b4a96bbb009.png)
对比了检测参数，两者是一样的，请问结果不一致是怎么回事呢？

**Comment by Intsigstephon** [comment]
因为在对每个检测到的物体，做识别之后，还加入了nms后处理； 详见： https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/deploy/python/predict_system.py   121-123行。 这部分可以依据具体任务调整。

**Comment by Hold-on-li** [comment]
> 因为在对每个检测到的物体，做识别之后，还加入了nms后处理； 详见： https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/deploy/python/predict_system.py 121-123行。 这部分可以依据具体任务调整。

请问具体的原理是什么呢？我尝试着调大与调小发现并没有太大的改变

**Comment by Intsigstephon** [comment]
就是把一般检测时需要做的nms，放到识别后去做了
