### ISSUE TITLE
单机多卡运行报错

### ISSUE THREAD

**Issue by wstchhwp** [PaddlePaddle/PaddleClas#1527]
操作系统：linux
python版本号：3.7.11
CUDA版本：11.1 ,cudnn版本没有找到
paddle版本：paddlepaddle-gpu+2.1.2.post110

**单卡运行没有报错，多卡运行报错了**

运行命令：
export CUDA_VISIBLE_DEVICES=0,1
python3 -m paddle.distributed.launch \
    --gpus="0,1" \
    tools/train.py \
        -c ./ppcls/configs/RoadRiskIdentification/ResNet50_vd.yaml \
        -o Arch.pretrained=True

代码报错如下：
RuntimeError: (PreconditionNotMet) The third-party dynamic library (libnccl.so) that Paddle depends on is not configured correctly. (error code is libnccl.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at /paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:265)

**Comment by weisy11** [comment]
提示说cuda或cudnn版本不匹配。建议排查：
1.cuda版本不匹配，paddle包对应的cuda版本是11.0，但是看你的留言cuda是11.1，不确定小版本是否有diff
2.cudnnn版本确实需要确认，可以在系统cuda文件夹的lib下找到cudnnn的库文件，可以通过文件名确认版本，如果在对应cuda的库里面没找到cudnn，说明可能没有安装成功。
3.确认一下命令、不同的卡是否有问题，比如只把命令中的--gpus="0,1" 换成--gpus="1"，试试看

**Comment by wstchhwp** [comment]
你好，我发现没有安装nccl的愿意，代码已经跑起来了，谢谢 @weisy11

**Comment by caomao1111** [comment]
> 

单机多卡报错parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device，是cuda版本太低了吗？安装的cuda10.2版本和cudnn7.6.5,nccl2.9.6

**Comment by weisy11** [comment]
> > 
> 
> 单机多卡报错parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device，是cuda版本太低了吗？安装的cuda10.2版本和cudnn7.6.5,nccl2.9.6

cuda 10.2我们是支持的，但是需要注意安装的环境是否匹配，注意cuda、cudnn、paddle相互之间的版本依赖

**Comment by ByZ0e** [comment]
您好 cuda 11.3建议装哪个版本的paddle
