### ISSUE TITLE
2.3版本C++部署报错

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleClas#1529]
![image](https://user-images.githubusercontent.com/87969070/144819001-5261644b-afdb-495c-9d4f-2a9fce9f680b.png)
请问一下，2.3版本部署时报无法解析外部符号，请问该如何解决呢？

**Comment by Intsigstephon** [comment]
看样子是opencv的库没有设置对，确认下opencv相关的环境变量配置是否正确
