### ISSUE TITLE
通用识别模型PPLCNet_x2_5的预训练模型问题

### ISSUE THREAD

**Issue by sp-ljw** [PaddlePaddle/PaddleClas#1537]
在《特征提取》章节里面提供了"通用识别预训练模型"的预训练模型地址，如下：
https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/rec/models/pretrain/general_PPLCNet_x2_5_pretrained_v1.0.pdparams
①这个预训练模型general_PPLCNet_x2_5_pretrained_v1.0.pdparams有700多M。

https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/algorithm_introduction/ImageNet_models.md
②这个里面PPLCNet_x2_5和PPLCNet_x2_5_ssld_pretrained.pdparams同为34M

且在快速上手中，直接下载的推理模型
③general_PPLCNet_x2_5_lite_v1.0_infer里的推理模型为33M

请问一下，①和③是对应的预训练模型和推理模型吗？
如果我要使用GeneralRecognition_PPLCNet_x2_5.yaml训练的话，我该选取哪个预训练模型？

**Comment by weisy11** [comment]
我们在训练通用识别模型的时候，用了较大的数据集，所以模型后面有一个比较大的FC层。这部分参数在量化、裁剪等任务中需要使用，因此我们将这部分参数也导出来了。
如果需要在通用识别的基础上进行finetune，建议使用①；如果想用ImageNet预训练模型为基础，可以使用②；如果直接预测，使用③。如果需要训练，且不确定场景适合哪一种，我们建议使用①。
使用①或②训练的模型，存储的预训练模型大小取决于训练的类别数量，导出的推理模型是33M的，这点请不用担心。

**Comment by chinesejunzai12** [comment]
> 我们在训练通用识别模型的时候，用了较大的数据集，所以模型后面有一个比较大的FC层。这部分参数在量化、裁剪等任务中需要使用，因此我们将这部分参数也导出来了。 如果需要在通用识别的基础上进行finetune，建议使用①；如果想用ImageNet预训练模型为基础，可以使用②；如果直接预测，使用③。如果需要训练，且不确定场景适合哪一种，我们建议使用①。 使用①或②训练的模型，存储的预训练模型大小取决于训练的类别数量，导出的推理模型是33M的，这点请不用担心。

你好, 我在①的基础上进行了模型的finetune, 但是最后的训练结果还不如base模型, 数据集90w+, 请问可能得原因是什么?
