### ISSUE TITLE
自己训练的LCNet主体检测模型预测报错TypeError: only size-1 arrays can be converted to Python scalars

### ISSUE THREAD

**Issue by niancheng** [PaddlePaddle/PaddleClas#1542]
1. PaddleClas版本以及PaddlePaddle版本：PaddleClas release/2.3，PaddlePaddle 2.2.0，
 2. 涉及的其他产品使用的版本号：PaddleDetection release/2.3
 3. 训练环境信息：Linux，Python3.7，CUDA 11.2，cuDNN 8
 4. 使用数据集CUB_200_2011，修改所有检测框的 category_id 修改为1，使用PaddleDetection基于[picodet_PPLCNet_x2_5_mainbody_lite_v1.0_pretrained.pdparams](https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/rec/models/pretrain/picodet_PPLCNet_x2_5_mainbody_lite_v1.0_pretrained.pdparams)训练主体检测模型，训练相关配置文件和日志：[yml&log.zip](https://github.com/PaddlePaddle/PaddleClas/files/7689502/yml.log.zip)
 5. 训练完成后使用[PaddleDetection/blob/release/2.3/tools/export_model.py](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/tools/export_model.py)导出模型，使用[PaddleDetection/blob/release/2.3/tools/infer.py](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/tools/infer.py)可以正常预测，但使用[PaddleClas/blob/release/2.3/deploy/python/predict_det.py](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/deploy/python/predict_det.py)预测时报如下错误：
 
![image](https://user-images.githubusercontent.com/23421457/145507796-88b48681-b029-424c-9c91-d13033640b52.png)

6. 另外，训练日志中的shape unmatched问题要如何解决？谢谢

**Comment by Enn29** [comment]
我也是一样的报错
环境信息：win10，Python3.7，CUDA 10.1，cuDNN 7.6.5
config文件用的是PaddleDetection（2.3版本）给出的yaml文件（https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/application/mainbody_detection/picodet_lcnet_x2_5_640_mainbody.yml），预训练没有改（https://paddledet.bj.bcebos.com/models/pretrained/LCNet_x2_5_ssld_pretrained.pdparams）

**Comment by RainFrost1** [comment]
好的，我定位一下

**Comment by Enn29** [comment]
刚才试了一下用PP-YOLO训练出来的就没有这个问题

**Comment by RainFrost1** [comment]
能提供一下inference model吗？ @Enn29 @niancheng

**Comment by niancheng** [comment]
> 能提供一下inference model吗？ @Enn29 @niancheng

**Comment by Enn29** [comment]
[inference.zip](https://github.com/PaddlePaddle/PaddleClas/files/7690755/inference.zip)

**Comment by niancheng** [comment]
@RainFrost1 [inference.zip](https://wx.mail.qq.com/ftn/download?func=3&key=9ec73a37aff5de11acb44a373332363539f7f736313236354417075155050153570f490253575018550d50051c50070c59155156530b030c535b5503000b3b35085602524357585604161e5e41265d0f437d8b114965f9e245b6872b5dcbad2dd41d&code=a8d71265&k=9ec73a37aff5de11acb44a373332363539f7f736313236354417075155050153570f490253575018550d50051c50070c59155156530b030c535b5503000b3b35085602524357585604161e5e41265d0f437d8b114965f9e245b6872b5dcbad2dd41d&fweb=1&cl=1)

**Comment by RainFrost1** [comment]
好的，我试一下，看你之前close掉了，我以为解决了。。。

**Comment by RainFrost1** [comment]
已经找到原因。在老版本的PaddleDeteciton中，导出inference model的时候 ，在网络后面自动加入的nms操作。现在的的版本的PaddleDetection，在导出inferecne model，没有加入nms，而nms的处理放到预测代码了。这块PaddleClas暂时还没有适配。我这周开始适配，预计最晚下周代码合入

**Comment by niancheng** [comment]
> 已经找到原因。在老版本的PaddleDeteciton中，导出inference model的时候 ，在网络后面自动加入的nms操作。现在的的版本的PaddleDetection，在导出inferecne model，没有加入nms，而nms的处理放到预测代码了。这块PaddleClas暂时还没有适配。我这周开始适配，预计最晚下周代码合入

感谢回复，训练时报shape unmatched的问题也是这个原因导致的吗？

**Comment by RainFrost1** [comment]
shape unmatched的问题，估计是你用了coco的picodet yaml文件, 他的导致维度不匹配。可以用[这个文件](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/application/mainbody_detection/picodet_lcnet_x2_5_640_mainbody.yml)试一下

**Comment by garment-chan** [comment]
请问适配完成了吗？

**Comment by Theodoric008** [comment]
一样的问题， 请问解决了吗？

**Comment by niancheng** [comment]
您好！您的来信我已经收到，我会尽快查阅并回复您的！

**Comment by niancheng** [comment]
您好！您的来信我已经收到，我会尽快查阅并回复您的！

**Comment by ericosmic** [comment]
2023年10月， 使用paddleclas-2.5版本，paddledetection =2.3 版本训练的模型依然不适配，代码依然有这个问题。 难道这个bug还没有改吗

**Comment by niancheng** [comment]
您好！您的来信我已经收到，我会尽快查阅并回复您的！

**Comment by dlaoy** [comment]
我产生一样的问题，请问适配好了吗

**Comment by niancheng** [comment]
您好！您的来信我已经收到，我会尽快查阅并回复您的！

**Comment by WillWang325** [comment]
一样的问题，请问适配好了吗

**Comment by niancheng** [comment]
您好！您的来信我已经收到，我会尽快查阅并回复您的！
