### ISSUE TITLE
检索模型精度 低于 分类模型精度

### ISSUE THREAD

**Issue by EthanChen1234** [PaddlePaddle/PaddleClas#1553]
1. PaddleClas：release/2.3，PaddlePaddle：2.1.2.post112
 2. 涉及的其他产品使用的版本号：无
 3. 训练环境信息：
  a. 具体操作系统，unbuntu16.4
  b. Python版本号，如Python3.7
  c. CUDA/cuDNN版本， 如CUDA11.2/CUDNN8
 4. 训练精度问题
1）数据集CUB_200_2011
2）
![image](https://user-images.githubusercontent.com/45474996/145798455-ab29ac29-1844-4d0c-b1c3-5c3dbb1914ad.png)
3）配置文件
[3个配置文件.zip](https://github.com/PaddlePaddle/PaddleClas/files/7703112/3.zip)

**Comment by EthanChen1234** [comment]
macro f1 指标是自己加入的代码，可以忽略。对齐recall1就可以。

**Comment by TingquanGao** [comment]
因为检索用的是度量学习，和图像分类不同，这个无法对齐。

**Comment by EthanChen1234** [comment]
同学，关键是度量学习的指标比分类任务差太多了，直接影响到实际使用。
之前的经验是，分类的backbone加上检索的流程后，检索指标会略低于分类(1%左右)

**Comment by niancheng** [comment]
我也有类似的需求，也准备在CUB_200_2011上做实验。

**Comment by niancheng** [comment]
我也有类似的需求，也准备在CUB_200_2011上做实验。
会不会是因为在细粒度分类任务上，分类模型确实要比检索模型高不少？如果在粗粒度分类上，可能差距会更小一些？

**Comment by EthanChen1234** [comment]
> 我也有类似的需求，也准备在CUB_200_2011上做实验。 会不会是因为在细粒度分类任务上，分类模型确实要比检索模型高不少？如果在粗粒度分类上，可能差距会更小一些？

度量学习，在细分类任务上有优势的。

**Comment by TingquanGao** [comment]
@niancheng 你好，可以先检查一下数据集。如果是作为分类任务，那么训练集、评测集应均为200类。如果是度量学习任务，那么应该划分100类用于训练，剩下的100类用于评测，关于度量学习的数据集划分可以参考这里：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/models_training/recognition.md#2-%E7%89%B9%E5%BE%81%E6%A8%A1%E5%9E%8B%E8%AE%AD%E7%BB%83
