### ISSUE TITLE
关于蒸馏训练过程出现的问题

### ISSUE THREAD

**Issue by 205418367** [PaddlePaddle/PaddleClas#1608]
1. PaddleClas版本以及PaddlePaddle版本：最新版本
 2. 训练环境信息：
  a. 具体操作系统，Linux
  b. Python版本号，Python3.6
  c. CUDA/cuDNN版本， CUDA10.2/cuDNN 7.6.5 

具体过程：
1、准备了50个类别数据集，生成 list.txt等文件并训练R50
2、把训练好的R50 best model 放入 pretrained目录
3、在先前的50个类别中随意加入未分类的数据，并重新生成 list.txt等文件
4、使用蒸馏训练Mobilenet-large model，训练了120 epoch
5、测试Mobilenet-large best model，发现准确率非常低

请问上述训练过程是否正确？问题处在哪里？

**Comment by littletomatodonkey** [comment]
蒸馏的log要不发出来看下呢？可能是参数没有加载成功

**Comment by 205418367** [comment]
在自己的数据集上做蒸馏训练必须要设置
-o Arch.use_ssld=True ？

**Comment by ChrisMengxl** [comment]
> 蒸馏的log要不发出来看下呢？可能是参数没有加载成功

#1677 好像我的也出现这种情况。见日志。谢谢。
