### ISSUE TITLE
跪求clas项目合集

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PaddleClas#1611]
https://aistudio.baidu.com/aistudio/projectdetail/450925?channelType=0&channel=0
paddlex等很多套件已经出了一个项目合集,并且有静态图和动态图版本,项目合集中蕴含了paddlex的4个主要方向,图像分类,目标检测,语义分割,实例分割,每个方向都至少有一个项目,项目里面包含项目代码,一些参数和代码的解释,注释等.
希望clas也可以出一个项目合集,蕴含clas目前所包含的所有比较不同的方向,比如根据模型有较大差异,ResNet,Transformer,pp_shitu,图像分类,知识蒸馏,量化等方向做一个项目合集,最好是包含静态图和动态图版本,如果你们没精力的话,做个动态图版本也行,这样我们这些学习者就不用到处找项目和代码来学习了.动态图版本肯定要支持飞桨2.2.1和clas最新release版本.最好就是学习完这个clas项目合集,可以把clas多数知识都会应用了,不要求掌握原理,比如模型原理等.clas目前我只知道用于图像分类和pp_shitu这两个方向,不知道还能否用于其他方向.而且你们做这个合集,希望可以包含一个项目,项目里面的网络是自定义,比较深的网络,包含卷积,池化,drop等API,这种项目太少见了,现在都是直接应用ResNet,搞得我简单的神经网络编程反而不会了,估计MNIST适合做这个项目.有些图像分类只需要很小的网络,因为对于延迟要求非常低.最好再来个项目教导我们如何写ResNet,毕竟这个技术对于图像分类太有用了.做视频太慢了,还是做个项目合集好,做视频半年精力才几个小视频,甚至讲解基础知识.做项目对你们来说,7天就可以弄个项目合集了,包含很多知识了,只限于应用,不限于原理,我只需要改代码,哈哈哈哈.
还有一个建议,你们的clas更新文档能否加个中文,现在看clas更新,好像只有英文,我不懂英文.

**Comment by weisy11** [comment]
1.Clas的文档有中文，点击这里可以切换
![image](https://user-images.githubusercontent.com/19523330/148032265-09caf99e-852f-4cf5-a8a4-bfc5749f8110.png)
2.PP-ShiTu计划2022年推出中文版电子书，预计在上半年内可以发布，欢迎关注
3.如果是Deep Learning初学者的话，可以关注 https://github.com/PaddlePaddle/awesome-DeepLearning
