### ISSUE TITLE
请问配置文件如何配置

### ISSUE THREAD

**Issue by Atiuiee** [PaddlePaddle/PaddleClas#1612]
![9443ce29ac5d5e2b6f80a9a4749b75c](https://user-images.githubusercontent.com/31364852/147807344-e50deb2e-a5db-4518-ae68-c5f81e6345c8.png)
上述预训练模型的配置文件如何配置，比如这个ResNet101_vd.yaml，在PaddleOCR项目里做检测的，训练时报各种参数错误

**Comment by weisy11** [comment]
这方面请参考PaddleOCR的文档~不确定PaddleOCR是否可以支持这些模型
