### ISSUE TITLE
图像分类

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleClas#1623]
您好，对于一张图像，图片中可能有其它的物体，这个能用于图像分类识别吗？
比如判断一张图片中是否有火车，图片如下面这样，然后我训练集中都是如下这样的图片，最终可以可以用图像分类来检测图像中是否有火车吗？
![image](https://user-images.githubusercontent.com/43515926/148342696-dea2d4e2-e622-462d-b30b-67a851d6e4ea.png)

**Comment by Intsigstephon** [comment]
理论上可以当做分类问题去处理，但有可能背景的影响会比较大；可以先训练一个模型，看看实际效果，再做进一步优化

**Comment by zcswdt** [comment]
> 

因为我关心的不是图像中火车的位置在哪里，而是关心图像中是否有火车，所以我没有用目标检测来做，不知道分类能不能做，请教一下，图像分类这个训练的数据配置等在哪介绍啊

**Comment by Intsigstephon** [comment]
配置文件可以参照如下文档：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/models_training/config_description.md
