### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleClas#1625]
您好，我训练1分类，执行下面脚本，python tools/train.py -c ./ppcls/configs/quick_start/ResNet50_vd.yaml -o Arch.pretrained=True
报错如下：
![image](https://user-images.githubusercontent.com/43515926/148358659-cfe9a922-5a92-4a45-ac21-599edb9502b1.png)

**Comment by Intsigstephon** [comment]
1分类？是一个2分类的任务吧.. .从报错信息看，需要修改label的数据类型，改成int32试试吧

**Comment by zcswdt** [comment]
> 1分类？是一个2分类的任务吧.. .从报错信息看，需要修改label的数据类型，改成int32试试吧

您好，我修改了训练的标签，之前标签我使用的/t分隔，我改了解决了int32。现在数据能正常加载，加载完预训练模型的报错在上路所示，麻烦您在帮忙看一下，谢谢。

**Comment by Intsigstephon** [comment]
您说的报错信息在哪，还是上面的那个log吗？
