### ISSUE TITLE
1分类训练报错

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleClas#1629]
您好，我的类别只有1个，我在配置文件中把类别数目改成1，
![image](https://user-images.githubusercontent.com/43515926/148486687-9da1a4bc-b7b3-4846-8119-48e10d4c84eb.png)
但是训练会报如下的错误，麻烦帮忙看看，谢谢了。
![image](https://user-images.githubusercontent.com/43515926/148486789-dd56121f-1cf3-4bc1-be46-7550939b583d.png)

**Comment by Intsigstephon** [comment]
这个问题之前的issue有回答，参见 https://github.com/PaddlePaddle/PaddleClas/issues/1625； 另外，对于二分类的情况，类别数设置为2
