### ISSUE TITLE
c++ 部署

### ISSUE THREAD

**Issue by czyczyczy** [PaddlePaddle/PaddleClas#1631]
请问有PP-LCNet的openvino工具的demo吗？

**Comment by TingquanGao** [comment]
您好！我们没有计划提供相应的demo。
简单地说，模型的转换可以使用 `paddle2onnx` 将paddle模型转为 onnx 模型，再使用 `openvino-dev` 将 onnx 模型转为 openvino 模型。paddle2onnx 和 openvino-dev 均有 python whl 包可以直接安装使用，您可以自行尝试。

另外想问一下，为什么您想要使用openvino来做部署推理呢？
