### ISSUE TITLE
模型推断问题

### ISSUE THREAD

**Issue by legendxty** [PaddlePaddle/PaddleClas#164]
请教下大佬：
1、使用如下命令貌似只能推断一张图片，如果做到推断一个文件夹呢？类似paddle detection那样指定一个infer_dir。
python tools/infer/predict.py \
    -m model文件路径 \
    -p params文件路径 \
    -i 图片路径 \
    --use_gpu=1 \
    --use_tensorrt=True

2、windows环境下，怎样设置环境变量呢？我用aistudio上面的命令，Windows终端不认啊：
export PYTHONPATH=$PWD:$PYTHONPATH

**Comment by littletomatodonkey** [comment]
1. 您好，在预测时，我们建议先导出为inference model，再使用预测引擎去预测，这样就可以保证预测过程与模型无关，便于迁移，您可以参考这篇文档：https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/zh_CN/extension/paddle_inference.md
2. windows下设置环境变量，是这样的：`set PYTHONPATH=.`
如果您希望在windows下使用PaddleClas，使用方法可以参考这个PR： #159 ，需要使用`tools/train_multi_platform.py`与`tools/eval_multi_platform.py`来进行训练与评估。

**Comment by shippingwang** [comment]
Feel free to reopen it~
