### ISSUE TITLE
learning rate的实现是不是存在问题？

### ISSUE THREAD

**Issue by renmada** [PaddlePaddle/PaddleClas#1641]
无论是linear还是cosine，只要warmup>0，直接变成LinearWarmup。
PolynomialDecay，CosineAnnealingDecay，LinearWarmup这三者应该是不同的衰减策略
![image](https://user-images.githubusercontent.com/43545086/149566958-bdeb1210-e2e6-410c-850a-2e5d9c7ee14e.png)
![image](https://user-images.githubusercontent.com/43545086/149567017-33a6228b-2545-4b1d-af88-b8f173679f74.png)

**Comment by weisy11** [comment]
你好，这个代码没有问题，可以再仔细阅读一下代码，或者写个测试试试看。
另外，不建议在无关的地方mention issue，我们看到之后都会解答的

**Comment by renmada** [comment]
那cosine的举例，当sefl.warmup_steps>0的时候， lr是LinearWarmup
LinearWarmup和CosineAnnealingDecay怎么会一样呢

**Comment by weisy11** [comment]
> 那cosine的举例，当sefl.warmup_steps>0的时候， lr是LinearWarmup LinearWarmup和CosineAnnealingDecay怎么会一样呢

learning_rate作为参数被传入了LinearWarmup。建议再仔细看一下代码，不要被名字迷惑

**Comment by weisy11** [comment]
LinearWarmup可以理解为Warmup的过程是Linear的，而不是一个LinearDecay带了Warmup。例如CosineAnnealingDecay，可以理解为在原有的CosineAnnealingDecay的基础上套一层LinearWarmup

**Comment by renmada** [comment]
了解了，感谢解答
