### ISSUE TITLE
请问paddleClas支持win10下，cuda10.2，python3.8的版本吗？

### ISSUE THREAD

**Issue by ZZHHogan** [PaddlePaddle/PaddleClas#1647]
请问paddleClas支持win10下，cuda10.2，python3.8的版本吗？我这里运行例程一直报错，无法使用gpu，但是可以使用cpu。另外关于paddle的环境配置有教程吗？

**Comment by Intsigstephon** [comment]
应该是支持的。 关于paddle环境安装可以参照：  https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/installation/install_paddle.md
