### ISSUE TITLE
请问支持linux多核CPU训练吗，是需要配置什么参数吗

### ISSUE THREAD

**Issue by we1085789948** [PaddlePaddle/PaddleClas#1655]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如Linux/Windows/MacOS
  b. Python版本号，如Python3.6/7/8
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

**Comment by we1085789948** [comment]
我发现训练的时候只有一个进程在跑

**Comment by weisy11** [comment]
使用环境变量：FLAGS_paddle_num_threads  可以控制线程数量。不过CPU训练效率较低，建议使用GPU训练。

**Comment by we1085789948** [comment]
好的，我先尝试一下

**Comment by we1085789948** [comment]
> 使用环境变量：FLAGS_paddle_num_threads 可以控制线程数量。不过CPU训练效率较低，建议使用GPU训练。

您好，是直接export FLAGS_paddle_num_threads，然后执行python tools\train.py吗
我发现好像还是只有一个进程

**Comment by we1085789948** [comment]
> 使用环境变量：FLAGS_paddle_num_threads 可以控制线程数量。不过CPU训练效率较低，建议使用GPU训练。

**Comment by weisy11** [comment]
![image](https://user-images.githubusercontent.com/19523330/152931372-e908e709-cca5-466e-97e8-a4ccdbdeb851.png)

paddle是开启mkldnn的版本吧？按理说，不应该只有一个进程在跑,哪怕使用GPU训练，CPU上也会有多个进程。这个现象是比较奇怪的，可能需要具体看一下你的代码
