### ISSUE TITLE
商品识别复现问题

### ISSUE THREAD

**Issue by JR-Wang** [PaddlePaddle/PaddleClas#1666]
你好，我用release2.3版本代码，本机cuda11.4，容器内cuda11.1来复现商品识别。检测模型结果不对。流程和教程一致，请问是什么问题？
![nongfu_spring](https://user-images.githubusercontent.com/53750640/151650036-165a6011-87bc-467f-a4e3-c27b6995a9df.jpeg)

**Comment by cuicheng01** [comment]
您好，我这边没有问题，可以提供一下你下载的检测模型的地址链接吗？

**Comment by JR-Wang** [comment]
wget https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/rec/models/inference/picodet_PPLCNet_x2_5_mainbody_lite_v1.0_infer.tar && tar -xf picodet_PPLCNet_x2_5_mainbody_lite_v1.0_infer.tar

我用这个指令下载的

**Comment by JR-Wang** [comment]
> 您好，我这边没有问题，可以提供一下你下载的检测模型的地址链接吗？

wget https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/rec/models/inference/picodet_PPLCNet_x2_5_mainbody_lite_v1.0_infer.tar && tar -xf picodet_PPLCNet_x2_5_mainbody_lite_v1.0_infer.tar

我用这个指令下载的

**Comment by cuicheng01** [comment]
您好，我也是用的这个检测模型，我这边无法复现你的问题。你要不重新下载模型试一下呢？

**Comment by JR-Wang** [comment]
> 您好，我也是用的这个检测模型，我这边无法复现你的问题。你要不重新下载模型试一下呢？

我调试看了检测模型的结果，应该是没有问题的。是识别模型的结果不对导致可视化不对了。我用的识别模型如下
wget https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/rec/models/inference/general_PPLCNet_x2_5_lite_v1.0_infer.tar && tar -xf general_PPLCNet_x2_5_lite_v1.0_infer.tar
用python3.7 python/build_gallery.py -c configs/build_general.yaml -o Global.rec_inference_model_dir=./models/general_PPLCNet_x2_5_lite_v1.0_infer重新提取了底库特征。但是最终识别结果不对。
另外，python/predict_system.py脚本中，113行的scores, docs = self.Searcher.search(rec_results, self.return_k)一句，我调试看scores的值是升序排列的，但是后处理取score[0][0]要大于识别阈值，请问这里是为什么呢？
谢谢

**Comment by weisy11** [comment]
> 我调试看scores的值是升序排列的，但是后处理取score[0][0]要大于识别阈值，请问这里是为什么呢？ 谢谢

排名靠前的结果，如果score没有超过阈值，也认为是不可信的，这样可以减少误检。如果在你的任务里不关注误检，可以把阈值减小

**Comment by alanzhai219** [comment]
请问如何生成picodet_PPLCNet_x2_5_mainbody_lite_v1.0_infer.tar导出啊？
