### ISSUE TITLE
人脸识别问题

### ISSUE THREAD

**Issue by zgwg** [PaddlePaddle/PaddleClas#1672]
请问，在PP-ShiTu中，将主体检测模型换成人脸识别模型后，是不是就变成了人脸识别应用了呢，还需要修改其他的内容吗？

**Comment by weisy11** [comment]
主体检测模型换成人脸检测模型，可以试试看。如果精度不够，可以把特征提取模型也换成人脸识别专用的模型。

**Comment by zgwg** [comment]
谢谢，再问一下PaddlePaddle有没有精度好的人脸特征提取模型？

**Comment by weisy11** [comment]
PaddleClas暂无人脸识别模型，可以参考insightface-paddle: https://github.com/deepinsight/insightface/tree/master/recognition/arcface_paddle

**Comment by zgwg** [comment]
OK，感谢！
