### ISSUE TITLE
商品识别配置文件问题

### ISSUE THREAD

**Issue by upperblacksmith** [PaddlePaddle/PaddleClas#1696]
![image](https://user-images.githubusercontent.com/34127965/154878858-c983e183-1a95-44c1-a2dc-ac08316e9179.png)
  在商品识别部分，存在以上四个配置文件，红框中两个配置文件都是没有预训练模型的，蓝框中两个配置文件都是有预训练模型的，想请问一下蓝框中的两个的配置文件预训练模型是用什么数据训练出来的，单看预训练模型的名称，里面有包含Aliproduct这个单词，具体存疑，希望能得到回复，谢谢。

**Comment by weisy11** [comment]
你好，用的数据集就是配置文件名写的那样，分别是aliproduct, inshop和sop。

**Comment by upperblacksmith** [comment]
> 你好，用的数据集就是配置文件名写的那样，分别是aliproduct, inshop和sop。

![image](https://user-images.githubusercontent.com/34127965/154880496-7ebdce21-16b5-4e95-a968-99dc365dcf55.png)
谢谢，但是画红框部分的命名让人很疑惑。我的意思是配置文件名是以SOP的结尾，但是文件里面预训练模型的命名又包含了Aliproduct。

**Comment by weisy11** [comment]
> > 你好，用的数据集就是配置文件名写的那样，分别是aliproduct, inshop和sop。
> 
> ![image](https://user-images.githubusercontent.com/34127965/154880496-7ebdce21-16b5-4e95-a968-99dc365dcf55.png) 谢谢，但是画红框部分的命名让人很疑惑。我的意思是配置文件名是以SOP的结尾，但是文件里面预训练模型的命名又包含了Aliproduct。

如果不需要使用Aliproduct作为预训练模型，可以删掉这个链接
