### ISSUE TITLE
生成的模型无法在Netron中可视化

### ISSUE THREAD

**Issue by zhuangh7** [PaddlePaddle/PaddleClas#1700]
```bash
使用的指令
python3.7 tools/export_model.py -c ./ppcls/configs/ImageNet/ResNet/ResNet50.yaml -o Global.device=xpu
```
生成的文件
![image](https://user-images.githubusercontent.com/16149477/155086645-40b68770-f28a-4418-a3f2-cc9eef110639.png)

拖入Netron报错
![8134b099d0ef20b2096f7b0ae35b0140](https://user-images.githubusercontent.com/16149477/155086696-4761373b-f9fe-4463-a7c0-f74d92c66d95.png)

**Comment by RainFrost1** [comment]
python3.7 tools/export_model.py -c ./ppcls/configs/ImageNet/ResNet/ResNet50.yaml -o Global.device=gpu，inference.pdmodel应该可以可视化

**Comment by zhuangh7** [comment]
> python3.7 tools/export_model.py -c ./ppcls/configs/ImageNet/ResNet/ResNet50.yaml -o Global.device=gpu，inference.pdmodel应该可以可视化

后来用静态图生成的模型跟 inference 生成的模型都可以正常的可视化。

但是普通的动态图生成的就不行。

而且静态图的运行的 to_static 参数似乎并不能正常使用，最后使用 /ppcls/static/train.py 脚本才跑起来的。

**Comment by RainFrost1** [comment]
对的，只有静态图的模型能可视化

**Comment by TingquanGao** [comment]
@zhuangh7 你好，关于Paddle保存的不同类型的模型文件，可以看一下这个文档，有具体说明：
https://github.com/paddlepaddle/paddleclas/blob/release%2F2.3/docs/zh_CN/faq_series/faq_2020_s1.md#q41-paddlepaddle-%E7%9A%84%E6%A8%A1%E5%9E%8B%E6%96%87%E4%BB%B6%E9%83%BD%E6%9C%89%E5%93%AA%E5%87%A0%E7%A7%8D

因此，只有pdmodel文件可以通过netron等工具进行可视化。

**Comment by zhuangh7** [comment]
感谢~
