### ISSUE TITLE
请教一下，多标签分类可以用度量学习吗？可以用triplet_loss吗？

### ISSUE THREAD

**Issue by jjl001** [PaddlePaddle/PaddleClas#1704]
请教一下，多标签分类可以用度量学习吗？可以用triplet_loss吗？

**Comment by Intsigstephon** [comment]
理论上也可以使用度量学习的方法去做；比较少看到有这么做的，可能是效果并不是很好

**Comment by jjl001** [comment]
如果训练多标签分类任务，不使用度量学习。每次添加新类的话，最后一层新增一个单元，并冻结模型之前训练的全部参数，只训练新增单元的权重，这种可以实现吗？

**Comment by Intsigstephon** [comment]
可以的。类似于采用一种级联结构，可以复用上一版训练的结果

**Comment by jjl001** [comment]
谢谢，请问有可以参考的案例吗？

**Comment by Intsigstephon** [comment]
没有参考案例
