### ISSUE TITLE
backbone-neck-head之间的激活函数

### ISSUE THREAD

**Issue by jjl001** [PaddlePaddle/PaddleClas#1717]
backbone和neck，neck和head之间没有发现激活函数，是不需要吗？或者是我理解错了？
![861646041442_ pic](https://user-images.githubusercontent.com/40778859/156322012-dacc3089-f8ea-4c24-be78-14f287ab00b2.jpg)
下图是FC
![911646041794_ pic](https://user-images.githubusercontent.com/40778859/156322156-d411141d-019c-41ee-bb33-43b6b2e0e58e.jpg)

**Comment by Intsigstephon** [comment]
Neck部分主要的作用为特征增强和特征维度变换，一般为自定义的函数；在自定义的时候，可以依据应用的需要选择是否加激活函数
