### ISSUE TITLE
paddle-gpu 安装后默认使用CPU问题

### ISSUE THREAD

**Issue by Williamwsk** [PaddlePaddle/PaddleClas#1725]
按paddle安装手册上，使用Docker环境命令（sudo docker run --name ppcls -v $PWD:/paddle --shm-size=8G --network=host -it paddlepaddle/paddle:2.1.0-gpu-cuda10.2-cudnn7 /bin/bash）进行容器后，报警告只能使用CPU，无法使用GPU

Python 3.7.0 (default, May  9 2021, 21:14:18) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py:299: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  "You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default."
>>> 

我本地的配置为NVIDIA-SMI 440.118.02   Driver Version: 440.118.02   CUDA Version: 10.2，本地环境跑pytorch模型没有问题，希望这个问题能获得解决！

**Comment by TingquanGao** [comment]
使用nvidia-docker试试呢：
```
# 对于 GPU 用户
sudo nvidia-docker run --name ppcls -v $PWD:/paddle --shm-size=8G --network=host -it paddlepaddle/paddle:2.1.0-gpu-cuda10.2-cudnn7 /bin/bash
```

**Comment by Williamwsk** [comment]
> 使用nvidia-docker试试呢：
> 
> ```
> # 对于 GPU 用户
> sudo nvidia-docker run --name ppcls -v $PWD:/paddle --shm-size=8G --network=host -it paddlepaddle/paddle:2.1.0-gpu-cuda10.2-cudnn7 /bin/bash
> ```
一样，也是不行，GPU也不能用

**Comment by TingquanGao** [comment]
你好！想问一下问题解决了吗？
