### ISSUE TITLE
MobileNetV2：pool2d 算子 ksize 参数有疑问

### ISSUE THREAD

**Issue by SpectrePrediction** [PaddlePaddle/PaddleClas#1731]
事情经过：我通过paddleclas-2.3训练了MobileNetV2

并通过工具链（模型-》转换模型导出-》模型转换成paddle.js支持模型）

但出现精度丢失异常，根据paddle.js排查，问题出现在pool2d算子上

由于引擎里有自动修正机制，所以 paddlepaddle 不会出错，但是转到 paddlejs 就会出错

具体过程查看https://github.com/PaddlePaddle/Paddle.js/issues/388#issuecomment-1059742374

希望paddleclas越来越好，致上

**Comment by weisy11** [comment]
感谢你的反馈，我们内部讨论一下。
