### ISSUE TITLE
增加convnext模型

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PaddleClas#1734]
我看了clas的图像分类模型库,好像swint模型最牛逼,top1和top5都最高.
https://aistudio.baidu.com/aistudio/projectdetail/3407445?channelType=0&channel=0
https://aistudio.baidu.com/aistudio/projectdetail/3476364?channelType=0&channel=0
这两个项目都说convnext是CNN的极限,甚至超越swint,我看了clas所有模型库,好像没找到convnext这个模型,我想问问,这个模型复现了吗?
如果没复现,clas能增加这个模型吗?
passl里面好像实现了convnext这个模型,但是clas模型库中没找到.
还有一个问题,passl库里面实现了几个自监督模型,我想问问,对于图像分类来说,你们打算几时引入自监督模型呢?目前在clas和dec好像没找到自监督模型.
我手头有一堆图片,我需要图像分类,我只知道分类成2类,但我不知道如何分类,换个说法,我是个瞎子,看不到图片,需要算法或者模型帮我分类,希望早日引入自监督图像分类模型,谢谢.

**Comment by weisy11** [comment]
感谢你对PaddleClas的关注
convnext暂时没有复现计划。极限只是暂时的，总会有更高的算法超越它。我们在复现的时候一方面考虑精度，另一方面也会考虑模型结构的价值，从更长远的角度考虑复现对PaddleClas的价值，并不是某一段时间的热点模型我们就一定会复现。
目前没有计划引入自监督。你的这个需求可以了解一下PP-ShiTu，如果两个类别不是特别相似的话，是可以区分的。
