### ISSUE TITLE
ppshitu使用自己训练的主体检测模型推理报错

### ISSUE THREAD

**Issue by JiehangXie** [PaddlePaddle/PaddleClas#1745]
操作系统：Windows
Python：3.7.9
CUDA: 11.2
Paddle: 2.2.2

自己使用paddledetection训练picodet主体检测模型，按照文档教程导出模型并改名为inference.model，然后使用ppshitu的predict脚本推理，报错 TypeError: only size-1 arrays can be converted to Python scalars，使用文档官方提供的inference demo推理正常，怀疑是模型导出的配置错误。

导出的命令是：
python tools/export_model.py -c configs/picodet_l_640_coco.yml --output_dir=./inference/bodydet/20220310/inference -o weights=./output/bodydet/20220310/picodet_l_640_coco/best_model.pdparams

![微信截图_20220310104725](https://user-images.githubusercontent.com/51190264/157578447-6beefe2a-91b6-45ba-8ab4-77e7c4b26e36.png)

**Comment by JiehangXie** [comment]
需要更新到paddledetection的develop分支，然后添加参数 export_post_process: True
参考：https://github.com/PaddlePaddle/PaddleDetection/issues/5290

**Comment by suay1113** [comment]
> 需要更新到paddledetection的develop分支，然后添加参数 export_post_process: True 参考：[PaddlePaddle/PaddleDetection#5290](https://github.com/PaddlePaddle/PaddleDetection/issues/5290)

2023年develop分支也不具备这个参数，需要怎么修改呢？
