### ISSUE TITLE
关于车辆细分类模型和车辆ReID模型

### ISSUE THREAD

**Issue by BackT0TheFuture** [PaddlePaddle/PaddleClas#1759]
repo中发布的[车辆细分类模型和车辆ReID模型](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/quick_start/quick_start_recognition.md)文件是一样，最终输出都是一个512维向量， 细分类模型不应该是车辆相关的属性吗？细分类模型在哪可以下载到，谢谢！

**Comment by weisy11** [comment]
不是的，我们暂时没有提供车辆属性的模型。

**Comment by BackT0TheFuture** [comment]
@weisy11  
哦，如果要用来分类，也就是自己要用提供的模型在样本上进行特征提取，然后再向量搜索比对喽？

**Comment by weisy11** [comment]
> 
是的

**Comment by weisy11** [comment]
> @weisy11 哦，如果要用来分类，也就是自己要用提供的模型在样本上进行特征提取，然后再向量搜索比对喽？

是的

**Comment by BackT0TheFuture** [comment]
明白了，谢谢
