### ISSUE TITLE
请问是否有c++的部署代码？

### ISSUE THREAD

**Issue by barry2025** [PaddlePaddle/PaddleClas#176]
请问下目前paddleclas是否有c++的部署代码，以及采用c++部署后的性能结果？

**Comment by littletomatodonkey** [comment]
您好，目前还PaddleClas中还没有集成C++的部署代码，如果您希望基于PaddleLite去进行C++部署，可以参考这篇文档：https://paddle-lite.readthedocs.io/zh/latest/demo_guides/cpp_demo.html
这个部署示例就是以分类为例。

**Comment by shippingwang** [comment]
Feel free to reopen it~
