### ISSUE TITLE
无法可视化

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleClas#1768]
请问各位大佬，我训练完之后用命令visualdl --logdir ./log --port 8080可视化，但是显示不出来，训练中的可视化参数也开启了
![image](https://user-images.githubusercontent.com/48303408/158958718-4718bbd9-cb59-46f0-970f-918086405e78.png)

**Comment by weisy11** [comment]
log方便share一下吗？

**Comment by Dandelion111** [comment]
> log方便share一下吗？

![image](https://user-images.githubusercontent.com/48303408/159245185-34e3f06d-7832-4e43-9101-ac4e64dcfe9e.png)
默认的文件夹名字是这个vdl，但是里面的文件我打不开

**Comment by TingquanGao** [comment]
你好，vdl的日志文件需要使用vdl打开并显示，命令如下：`visualdl --logdir ./output/vdl/`
你的命令中的--logdir 参数值不对。
相关文档可以参考：https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.3/docs/zh_CN/others/VisualDL.md
