### ISSUE TITLE
什么时候使用paddle.to_tensor()问题

### ISSUE THREAD

**Issue by LiquorPerfect** [PaddlePaddle/PaddleClas#1771]
https://github.com/PaddlePaddle/PaddleClas/blob/6845df2bb13106e342a9573f0bba4801aef3c7e1/ppcls/engine/train/train.py#L54
这边的模型输入没有使用paddle.to_tensor()。而https://github.com/PaddlePaddle/PaddleClas/blob/6845df2bb13106e342a9573f0bba4801aef3c7e1/ppcls/engine/evaluation/retrieval.py#L120
这边的模型输入使用了paddle.to_tensor()来进行数据类型转换。
请问一下什么时候需要用到paddle.to_tensor()，什么时候可以不用？
谢谢。

**Comment by weisy11** [comment]
1.输入到网络里的都需要是tensor类型
2.如果已经是tensor了，就不用再调用to_tensor，如果你好奇这个类型是不是tensor，可以直接运行一下，打印这个输入的type；假如对tensor调用了to_tensor，也不会有什么变化，只是增加一些耗时
3.使用正常的dataloader，返回的是一个list, list里面的类型是tensor，这个时候不需要再to_tensor；但是一些特殊的dataloader，给出的类型不是tensor，这时候就必须要手动调用dataloader
4.如果手写了batch_sampler，返回的类型取决于sampler的实现，有部分sampler返回的类型不是tensor，这些数据也需要手动调用to_tensor
