### ISSUE TITLE
se+hrnet 

### ISSUE THREAD

**Issue by lxk767363331** [PaddlePaddle/PaddleClas#178]
因为我想在HRNet下加上注意力机制，所以选择使用se+hrnet，在赢一个issue中反馈给我的是SE+HRNet需要有带SE的预训练，直接加载没有SE的预训练的模型精度会比较低。
我的问题：
1.是否有SE+HRNet的预训练
2.如果没有，我应该怎么训练能有一个较好的结果，是否有可行性的建议
3.是否有其他易于训练的注意力机制，相较于SE+HRNet在没有预训练模型的情况下容易训练。

**Comment by cuicheng01** [comment]
hi~正如你说的，加载SE模块需要有相应的SE模块的预训练模型。就你的问题回答如下：
1.目前还没有加载SE的预训练模型，如果需要，可以提需求，我们排期发布。
2.不加载预训练效果可能会差一下，你需要哪个系列的可以告诉我们，我们之后提供。
3.目前SE算是比较鲁棒的一种注意力机制，但是是否有更容易训练的注意力机制，这块目前没有明确结论。

**Comment by lxk767363331** [comment]
非常感谢解答，需求是在这里提么，我想要的是SE_HRNet_W32_C 或者SE_HRNet_W64_C的预训练模型

**Comment by cuicheng01** [comment]
好的，我们近期release SE_HRNet_W64_C的模型。

**Comment by lxk767363331** [comment]
非常感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "cuicheng01"<notifications@github.com&gt;; 
发送时间: 2020年6月23日(星期二) 晚上8:59
收件人: "PaddlePaddle/PaddleClas"<PaddleClas@noreply.github.com&gt;; 
抄送: "不要冲动保持心态"<767363331@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleClas] se+hrnet  (#178)





 
好的，我们近期release SE_HRNet_W64_C的模型。

**Comment by shippingwang** [comment]
Feel free to reopen it~
