### ISSUE TITLE
对paddle模型转换的onnx模型简化报错

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleClas#1780]
![image](https://user-images.githubusercontent.com/48303408/159424901-8598119a-ff73-4355-a1f5-8ac88c6b7eba.png)
请问各位大佬，我训练的LCNet模型，在转换到onnx模型之后，在简化的时候出现这个错误，请问这个怎么解决

**Comment by jiangjiajun** [comment]
python -m onnxsim model.onnx new_model.onnx --dynamic-input-shape --input-shape [1,3,224,224]
