### ISSUE TITLE
PP识图数据处理问题

### ISSUE THREAD

**Issue by Yetdream** [PaddlePaddle/PaddleClas#1781]
我想用pp识图对一些猫的图片进行分类，但是我弄了很久，在执行predict_system.py的时候都有这个问题
![屏幕截图 2022-03-22 162844](https://user-images.githubusercontent.com/100469824/159439354-bd9c0aee-d53f-4c15-96a1-48821522ab25.png)
我想知道这是什么导致的

**Comment by TingquanGao** [comment]
您是想用度量学习做，还是图像分类做呢？训练的模型是哪一种？
