### ISSUE TITLE
'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by wonder2025** [PaddlePaddle/PaddleClas#1787]
训练时报错，查过该路径是有图片的
比如下图报错
![6-3c0703b8-24a4-4437-ac37-e01d7d55b31f](https://user-images.githubusercontent.com/20439438/160247281-ca55d660-470d-42c7-878e-567e7c067878.jpg)

报错截图如下
![image](https://user-images.githubusercontent.com/20439438/160247306-ac09a21a-3357-4439-9ccc-63a7f9470c26.png)

**Comment by TingquanGao** [comment]
检查一下train_list.txt中对应该行格式是否正确呢？比如图片文件路径和label的分隔符？或者是否有其他多余的符号？

**Comment by wonder2025** [comment]
是图片格式的问题
