### ISSUE TITLE
项目内存在失效的软连接，在AI Studio无法保存新版本。

### ISSUE THREAD

**Issue by CPones** [PaddlePaddle/PaddleClas#1791]
···
!git clone https://gitee.com/paddlepaddle/PaddleClas.git -b release/2.3
···
AI Studio克隆该项目到BML CodeLab中，保存新版本时报错如下：
项目中存在失效的软连接, 影响版本生成，请先删除软连接再尝试生成版本。

**Comment by TingquanGao** [comment]
感谢反馈，我们将尽快修复该问题。您也可以尝试将PaddleClas/README.md文件删除。

**Comment by cuicheng01** [comment]
无效软连接问题已修复，请clone最新的PaddleClas的代码再重新试一下呢
