### ISSUE TITLE
使用paddleserving 部署ResNet101_vd_serving报错

### ISSUE THREAD

**Issue by wonder2025** [PaddlePaddle/PaddleClas#1792]
按照要求转换了ResNet101_vd 模型但是client调用的时候报错
![image](https://user-images.githubusercontent.com/20439438/160340709-3fe6fb34-7f05-410d-8b7c-d31ce0a5d132.png)

serving_server_conf.prototxt和serving_client_conf.prototxt内容如下

![image](https://user-images.githubusercontent.com/20439438/160340803-17f3fa56-5cf7-4dfe-abcf-9b9eb1cd01e2.png)

不知道还要修改哪里的配置

**Comment by Intsigstephon** [comment]
feed_var和fetch_var的name和alias_name需要修改；参见https://github.com/PaddlePaddle/PaddleClas/tree/release/2.3/deploy/paddleserving#3.1

**Comment by wonder2025** [comment]
> feed_var和fetch_var的name和alias_name需要修改；参见https://github.com/PaddlePaddle/PaddleClas/tree/release/2.3/deploy/paddleserving#3.1

修改成什麽呢，好像文档中没说根据什么规则来改，并且也没有说要改name呢

**Comment by Intsigstephon** [comment]
你给的serving_server_conf.prototxt和serving_client_conf.prototxt文件应该不是ResNet101模型转换过来的；fetch_var的shape不应该是14，是不是弄错文件了？
