### ISSUE TITLE
slurm调度paddleclas单机多卡运行却只有单卡运行

### ISSUE THREAD

**Issue by CauchyFood** [PaddlePaddle/PaddleClas#1801]
我当前运行paddle版本
```shell
pip list | grep paddle
paddlepaddle-gpu     2.2.2.post110
```
训练环境: V100 GPU，Slurm0.5环境，Cuda11.0

**运行脚本test.sh**
```
g=$(($1<8?$1:8))
srun -p test --async -n$1 --gres=gpu:$g --ntasks-per-node=$g  --quotatype=auto --cpus-per-task=6 \
    --job-name="test" \
python tools/train.py -c ./config/resnet50vd.yaml
```

**运行命令**
```
sh test.sh 4
```

**错误信息：**
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/81349827/160956135-f9d3d33c-a7e7-4f45-b231-3b2f4d5405db.png">

<img width="721" alt="image" src="https://user-images.githubusercontent.com/81349827/160956083-44b43dd8-b2f7-4ecf-9e26-1ecb6b4e259b.png">

**Comment by TingquanGao** [comment]
使用PaddleClas 2.3分支，训练命令：
```bash
export CUDA_VISIBLE_DEVICES=0,1,2,3
python3 -m paddle.distributed.launch \
    --gpus="0,1,2,3" \
    tools/train.py \
        -c ./ppcls/configs/quick_start/MobileNetV3_large_x1_0.yaml
```

具体请参考文档：
https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.3/docs/zh_CN/models_training/classification.md#3.2
