### ISSUE TITLE
PPshitu Faiss相似度算法受背景干扰大

### ISSUE THREAD

**Issue by JiehangXie** [PaddlePaddle/PaddleClas#1806]
操作系统：Windows
Python版本号，如Python3.7.9
CUDA/cuDNN版本：11.2
算法配置：HNSW32 + METRIC_INNER_PRODUCT
数据总共5类，每一类图片数量在30-50张范围内。

对同一张图片，更换背景信息之后，就识别错误，鲁棒性极低。
如图，左边识别正确，右边识别错误。

![微信图片_20220402144306](https://user-images.githubusercontent.com/51190264/161370672-caf74221-d2d8-4705-b47d-c3e44ef515eb.png)

**Comment by cuicheng01** [comment]
您好，PP-ShiTu的识别模型中的训练数据确实不包含植物，所以在植物的类别上泛化性可能有限。你可以基于PP-ShiTu的识别模型的pretrained model在植物数据集上继续finetune，会满足你这个场景哈～

**Comment by JiehangXie** [comment]
> 您好，PP-ShiTu的识别模型中的训练数据确实不包含植物，所以在植物的类别上泛化性可能有限。你可以基于PP-ShiTu的识别模型的pretrained model在植物数据集上继续finetune，会满足你这个场景哈～

收到，已在训练特征模型，时间大概8天左右，训练好之后在这个issue反馈效果。

**Comment by JiehangXie** [comment]
已解决

**Comment by PaulX1029** [comment]
> 已解决

请问大佬，继续训练是基于ShiTu的预训练模型加上自己的数据集吗？相关yaml文件有修改吗，请大佬赐教！ @JiehangXie
