### ISSUE TITLE
图像分类针对未知分类问题如何解决？

### ISSUE THREAD

**Issue by onair1314** [PaddlePaddle/PaddleClas#1808]
比如图像分类中的二分类，假设我只想区分某张图片中是否有火车（有火车就被标记为0类，没火车就被标记为1类）；
现实生活中的不包含火车的图片包罗万象，不可能都被拿来作为训练集；
如果测试集中出现了未知的物体，但一定不是火车，如果更准确的把这张图片推理为1类呢？
训练数据或定义标签时可否定义一个blank来解决这个问题呢？
望各位大神慷慨解答

**Comment by weisy11** [comment]
可以使用PP-ShiTu，将火车数据建立一个特征库，进行识别
