### ISSUE TITLE
Mixformer

### ISSUE THREAD

**Issue by TheshowN** [PaddlePaddle/PaddleClas#1814]
Mixformer的开源代码有放出来吗？

**Comment by chensnathan** [comment]
代码已经更新在[这个pr](https://github.com/PaddlePaddle/PaddleClas/pull/1813)里了，训练好的模型还需要过几天

**Comment by chensnathan** [comment]
代码在新提的[这个pr](https://github.com/PaddlePaddle/PaddleClas/pull/1820)里面了
