### ISSUE TITLE
关于训练日志配置参数 怀疑有BUG

### ISSUE THREAD

**Issue by gutao0315** [PaddlePaddle/PaddleClas#1815]
![3c3186cc0a8a9cde356f0f3030d026a](https://user-images.githubusercontent.com/77281977/162153628-5b730097-2076-4214-b8b4-0572fba3a259.png)
我的数据集已经是RGB格式了 为什么这个参数去掉训练就会报错说读取图片发生意外

**Comment by weisy11** [comment]
这个参数是做图像解码的。如果你的数据集是jpg等压缩格式，那么就不能去掉这个参数。
