### ISSUE TITLE
训练占GPU为什么跟这个参数有关

### ISSUE THREAD

**Issue by gutao0315** [PaddlePaddle/PaddleClas#1816]
为什么训练占的内存跟输入的尺寸无关
![b266fce3a7fd714ae373c918d7a0443](https://user-images.githubusercontent.com/77281977/162155254-fc83d69a-7ded-42af-a16b-8cffe194b25a.png)
只跟Train里的RandCropImage有关
![f1bc1c30d433bfaf4f23d1efd9c4b07](https://user-images.githubusercontent.com/77281977/162155446-386542ec-1f04-4b47-aadb-1de98065451e.png)

**Comment by weisy11** [comment]
因为这个参数改变了图像的大小。

**Comment by gutao0315** [comment]
能不能填矩形

**Comment by weisy11** [comment]
可以填宽高，例如：
size: [100, 200]

**Comment by gutao0315** [comment]
> 可以填宽高，例如： size: [100, 200]

这是把图片resize了 还是裁剪了

**Comment by weisy11** [comment]
> 

都有，具体可以参考源码：
https://github.com/PaddlePaddle/PaddleClas/blob/d2bfa3a3ce7c6939444752bfcdde24069b6c8c9d/ppcls/data/preprocess/ops/operators.py#L167
