### ISSUE TITLE
faiss error

### ISSUE THREAD

**Issue by tuteming** [PaddlePaddle/PaddleClas#1823]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
==>PaddleClas release/2.2
 3. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 4. 训练环境信息：
  a. 具体操作系统==>Windows
  b. Python版本号==>3.8.8
  c. CUDA/cuDNN版本， 如CUDA11.1/cuDNN 8
 5. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log
 ==>根據https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/quick_start/quick_start_recognition.md
2.2 瓶装饮料识别与检索   提及:
注意，此部分使用了 faiss 作为检索库，安装方法如下：
pip install faiss-cpu==1.7.1post2
若使用时，不能正常引用，则 uninstall 之后，重新 install，尤其是 windows 下。
error:
d:\PaddleClas-release-2.3\deploy>python python/build_gallery.py -c configs/build_general.yaml
Traceback (most recent call last):
  File "python/build_gallery.py", line 21, in <module>
    import faiss
  File "C:\Users\tutm\anaconda3\lib\site-packages\faiss\__init__.py", line 39, in <module>
    from .loader import *
  File "C:\Users\tutm\anaconda3\lib\site-packages\faiss\loader.py", line 65, in <module>
    from .swigfaiss import *
  File "C:\Users\tutm\anaconda3\lib\site-packages\faiss\swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: DLL load failed while importing _swigfaiss: 找不到指定的模組。

請問如何解決?

**Comment by weisy11** [comment]
faiss有一定概率出现安装失败，卸载之后重新安装即可，可能需要重复2-3次

**Comment by ANDROIDTODO** [comment]
我已经重试了50遍。。。
pip install faiss-cpu==1.7.1post2 --no-cache-dir
pip uninstall faiss-cpu==1.7.1post2

依然还是报如此的错误

**Comment by Derek851029** [comment]
有相同的问题, 重新安装依然没有办法
