### ISSUE TITLE
Bug: 训练时Eval 结果无法复现，并且不同GPU数量eval结果不同

### ISSUE THREAD

**Issue by ppalantir** [PaddlePaddle/PaddleClas#1825]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如Linux/Windows/MacOS
  b. Python版本号，如Python3.6/7/8
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

问题：训练时得到Eval结果（ce loss, metric），在训练完成后用eval.py和保存的权重无法复现。并且卡数不同情况下，loss avg结果还不同。

解决：
无语了。排查了一天。最后很明确是bug。环境信息不想贴了，check下代码就知道。希望能有负责同学检查下ppcls/engine/evaluation/classification里面计算loss和metric的代码。

**Comment by ppalantir** [comment]
多说两句，真心希望这么多人使用的工具，评价指标计算这么基本的东西能100%没错误

**Comment by weisy11** [comment]
> 多说两句，真心希望这么多人使用的工具，评价指标计算这么基本的东西能100%没错误

希望大家都能就事论事，理性的讨论问题。如果你想为PaddleClas贡献代码，欢迎提PR。

**Comment by TingquanGao** [comment]
你好，感谢对PaddleClas的关注，所涉及的问题已经修复：#1833

其中，训练中的eval loss，训练完成后单独eval无法复现的问题，是因为在多卡时，bn层的统计量没有同步导致的，将bn转为sync bn即可，但考虑到速度问题，我们没有使用sync bn。

**Comment by ppalantir** [comment]
@TingquanGao 亲，肯定不止这个原因呀，可以看下我提issues时ppcls/engine/evaluation/classification里面计算loss和metric的代码， 计算metric做了多卡gather，所以求avg=val/sum时，sum总数是对的，计算loss时没做多卡gather，求avg时sum会根据不同卡数而不同。

**Comment by TingquanGao** [comment]
共有三个问题：1. 训练中eval loss无法在单独eval时复现；2. eval时，gpu卡数不同引起loss变化；3. eval时，gpu卡数不同引起top1 acc变化。
针对问题 1. ，是因为不同卡中bn层的统计量没有同步，这个可以通过改为sync bn解决。
针对问题 2.，是因为计算loss前没有gather prediction和label，这个已经在PR #1833 修了。
针对问题 3.，是因为当样本数无法被整分为mini batch时，最后一个mini batch中有重复采样的样本需要剔除，batch样本数量有变化，这个也已经在PR #1833 修了。
