### ISSUE TITLE
lite_shitu android端，通过教程进行部署，识别完全无法匹配

### ISSUE THREAD

**Issue by ANDROIDTODO** [PaddlePaddle/PaddleClas#1827]
Hi,
我使用develop分支的代码进行android端的lite_shitu进行部署，运行后发现，我使用drink里面本身的图片进行识别，但是完全不匹配，这个是什么情况呢？

**Comment by weisy11** [comment]
你好，请问你具体是怎么使用的呢？

**Comment by ANDROIDTODO** [comment]
@weisy11 
我这边按照 https://github.com/PaddlePaddle/PaddleClas/blob/develop/deploy/lite_shitu/README.md 提供的方式来一步一步进行转换，部署使用的。 最后调用 ./pp_shitu shitu_config.json 进行分类

日志如下

emulator64_arm64:/data/local/tmp/deploy # ./pp_shitu shitu_config.json                                                                                                                                   
WARNING: linker: Warning: "/data/local/tmp/deploy/libpaddle_light_api_shared.so" unused DT entry: DT_RPATH (type 0xf arg 0x1f7b0) (ignoring)
Usage: ./pp_shitu [config_path](option) [image_dir](option)
config created
before object detector
[I  4/11 17:58:26.921 ...and/Paddle-Lite/lite/core/device_info.cc:238 get_cpu_arch] Unknow cpu arch: 0
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:238 get_cpu_arch] Unknow cpu arch: 0
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:238 get_cpu_arch] Unknow cpu arch: 0
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:238 get_cpu_arch] Unknow cpu arch: 0
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:1118 Setup] ARM multiprocessors name: _GOLDFISH_ARM64__
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:1119 Setup] ARM multiprocessors number: 4
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 0, max freq: 0, min freq: 0, cluster ID: 0, CPU ARCH: A-1
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 1, max freq: 0, min freq: 0, cluster ID: 0, CPU ARCH: A-1
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 2, max freq: 0, min freq: 0, cluster ID: 0, CPU ARCH: A-1
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 3, max freq: 0, min freq: 0, cluster ID: 0, CPU ARCH: A-1
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:1127 Setup] L1 DataCache size is: 
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 32 KB
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 32 KB
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 32 KB
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 32 KB
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:1131 Setup] L2 Cache size is: 
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 512 KB
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 512 KB
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 512 KB
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 512 KB
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:1135 Setup] L3 Cache size is: 
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 0 KB
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 0 KB
[I  4/11 17:58:26.922 ...and/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 0 KB
[I  4/11 17:58:26.923 ...and/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 0 KB
[I  4/11 17:58:26.923 ...and/Paddle-Lite/lite/core/device_info.cc:1139 Setup] Total memory: 2013212KB
create object detector
[W  4/11 17:58:26.941 ...e-Lite/lite/model_parser/model_parser.cc:879 LoadModelFbsFromFile] 
warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version.
      version of opt:v2.10
      version of current Paddle-Lite:v2.10-rc
feature extract model create!
faiss index load success!
images/0.jpg:
	result0: bbox[2, 0, 142, 402], score: 0.986125, label: 维果清_蔬菜汁

但是实际images/0.jpg 是可口可乐的图片

**Comment by RainFrost1** [comment]
你好，目前lite模型精度略低于inference model，建议先使用cpp_shitu。lite版本还在继续优化中，目前模型预测可能存在错误

**Comment by RainFrost1** [comment]
可以尝试[新版本](https://github.com/PaddlePaddle/PaddleClas/pull/2144)
