### ISSUE TITLE
cpp_shitu main.cpp

### ISSUE THREAD

**Issue by tuteming** [PaddlePaddle/PaddleClas#1838]
請問在cpp_shitu main.cpp 
line 256-260
// step2: add the whole image for recognition to improve recall
        Detection::ObjectResult result_whole_img = {
                {0, 0, srcimg.cols - 1, srcimg.rows - 1}, 0, 1.0};
        det_result.push_back(result_whole_img);
        det_bbox_num[0] = det_result.size() + 1;

1.  step2: add the whole image for recognition to improve recall    是甚麼意義?
2. result_whole_img = { {0, 0, srcimg.cols - 1, srcimg.rows - 1}, 0, 1.0};中最後2個參數0, 1.0  是甚麼意義?

請不吝賜教  謝謝

**Comment by RainFrost1** [comment]
现在PP-ShiTu的流程是先经过检测器，检测处理的bbox输入到识别模型。
问题1:step2 是将整张图加入到detection的检测结果，为了防止检测器将整张图的结果丢失，特别是图像中只有一个大物体的情况。
问题2: 0是检测器的检测物体类别，目前主体检测的检测类别只有一个，ID为0， 1.0是检测的置信度
