### ISSUE TITLE
博主，想问下训练和验证过程用visualdl可视化，怎么改程序呢?

### ISSUE THREAD

**Issue by yy11223** [PaddlePaddle/PaddleClas#184]

**Comment by shippingwang** [comment]
首先 要确保安装了visualdl 2.0.0之上的版本（现在只支持python3）
指定vdl_dir 例如：--vdl_dir='./scalar'
现在代码中可以可视化 训练过程的loss变化 
参考这个PR https://github.com/PaddlePaddle/PaddleClas/pull/137
acc/评估等 你可以自己加上去

**Comment by yy11223** [comment]
参考这个PR #137后，训练的时候出现了这个错误,
![QQ截图20200703132228](https://user-images.githubusercontent.com/67571483/86434829-05687380-bd31-11ea-8e83-874b5fa6d19a.png)，
我的训练命令是这个，
![N71FP8CH R (F6)0R7OPYQ](https://user-images.githubusercontent.com/67571483/86434955-5bd5b200-bd31-11ea-86a0-bbed15e5651b.png)

**Comment by littletomatodonkey** [comment]
您这里需要添加一个反斜杠，来连接第6行和第7行的内容
![image](https://user-images.githubusercontent.com/14270174/86439494-3cdc1d80-bd3b-11ea-8dd5-e81b626d14f2.png)

**Comment by yy11223** [comment]
反斜杠加了，但运行还是出现这个问题，是怎么回事呢？![QQ截图20200703145316](https://user-images.githubusercontent.com/67571483/86440576-4797b200-bd3d-11ea-9333-bd28a087fe7d.png)
