### ISSUE TITLE
使用ai studio 4卡v100训练失败

### ISSUE THREAD

**Issue by violetweir** [PaddlePaddle/PaddleClas#1840]
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/78856426/163505484-b7ec22a7-0901-49aa-8c58-d04b5f23e6ae.png">
每次sh使用ai studio4卡v100都出现这种情况
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/78856426/163505514-01657517-83c3-4c01-8c46-ffb63abf9ee2.png">
然后使用python setup.py install 之后又报错

**Comment by weisy11** [comment]
看报错信息是aistudio的资源问题，后台提工单吧

**Comment by hatimwen** [comment]
这个问题我是这么解决的，运行`pip install -r requirements.txt`之前，

把requirements.txt里面的
scikit-learn==0.23.2 版本号去掉就好了：
scikit-learn

这是我的requirements.txt内容(其中opencv-python我看环境里有也顺手注释了)：

```
prettytable
ujson
# opencv-python==4.4.0.46
pillow
tqdm
PyYAML
visualdl >= 2.2.0
scipy
scikit-learn
# scikit-learn==0.23.2
gast==0.3.3
faiss-cpu==1.7.1.post2
```
