### ISSUE TITLE
构建新的索引库问题

### ISSUE THREAD

**Issue by coallar** [PaddlePaddle/PaddleClas#1842]
[[您好，我目前需要在900w+张图片中，将cartoon图片筛选出来，目前在看 文档第三章内容](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/quick_start/quick_start_recognition.md#3-%E6%9C%AA%E7%9F%A5%E7%B1%BB%E5%88%AB%E7%9A%84%E5%9B%BE%E5%83%8F%E8%AF%86%E5%88%AB%E4%BD%93%E9%AA%8C) 遇到几个问题：

1. 构建新的索引库的时候，需要重新遍历所有的图片数据吗？
2. 构建是否可以直接跳过构建索引库直接使用通用检测模型+cartoon动漫人物识别模型呢？

希望得到的结果时在批量输入的时候，将识别为cartoon图片提取出来。谢谢

**Comment by TingquanGao** [comment]
您好，关于您咨询的问题：
1. 目前在构建新的索引库时，支持增量构建，具体可以参考[文档](https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/image_recognition_pipeline/vector_search.md#31-%E5%BB%BA%E5%BA%93%E5%8F%8A%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E5%8F%82%E6%95%B0)中参数index_operation的说明。
2. 不能。PP-Shitu是基于度量学习的图像识别工具，对于预测图像的类别预测必须依赖于索引底库。
3. 你这个问题是二分类问题，可以尝试人为选取一些具有代表性的卡通图与非卡通图，并构建底库，然后再使用PP-Shitu完成预测。

**Comment by coallar** [comment]
> 
好的 谢谢
