### ISSUE TITLE
[BUG]【论文复现】2个严重bug

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/PaddleClas#1843]
在aistudio脚本中使用PaddleClas进行论文复现时，因为时长问题，在engine中设置每50轮停止并输出一次训练参数，前50轮已正常训练，在51-100轮训练时，出现严重bug！！！！！！

bug1： 原有配置无法正常运行
使用原有配置resume，每次在51轮的eval时，就会停止，并且没有保存内容！！！
多次尝试后，将batchsize由200改成196，才可以正常运行？？？

bug2：保存参数不完整
51-100轮训练结束后，保存的pdparams不完整？？？50轮的pdparams大小为109.07MB，而100轮的pdparams大小为39.59MB！2天多的训练过程作废了！

上一期的论文复现也用的是同一套代码，没这么多bug呀

**Comment by huilin16** [comment]
51-100轮的脚本任务id——135963

**Comment by HydrogenSulfate** [comment]
你好，提issue的格式可以参考https://github.com/PaddlePaddle/PaddleClas/issues/new?assignees=&labels=bug&template=---clas-issue-.md&title=%5BBUG%5D。
