### ISSUE TITLE
【论文复现】找不到ImageNet数据集的`train_list.txt`和`val_list.txt`

### ISSUE THREAD

**Issue by Dandelight** [PaddlePaddle/PaddleClas#1844]
###  使用场景

在使用`PaddleClas`复现图像分类论文时，需要`train_list.txt`和`val_list.txt`文件。

###  数据情况

ImageNet ILSVRC 2012 (ImageNet-1K) train/val，数据集完整。

### 问题描述

在使用`PaddleClas`复现图像分类论文时，没有`train_list.txt`和`val_list.txt`文件，只有[`ppcls/utils/imagenet1k_label_list.txt`](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/ppcls/utils/imagenet1k_label_list.txt)定义了类别代号，所以不知道怎么获得上述两个文件以使用ImageNet进行训练。

###  预期效果

提供统一的`train_list.txt`和`val_list.txt`文件方便训练和验收。

**Comment by 13136983989** [comment]
padlecals文件夹里有 去config里找路径

**Comment by weisy11** [comment]
版权问题，我们不方便提供这个列表。
标注文件格式可以参考：
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/data_preparation/classification_dataset.md#2.1
