### ISSUE TITLE
train from scratch

### ISSUE THREAD

**Issue by EwardJohn** [PaddlePaddle/PaddleClas#187]
你好，我想问一下，需要使用paddleClas从头训练自己的数据，但是那个train_list.txt 中除了图片路径外，位置坐标是使用中心点坐标和宽高，还是使用左上右下坐标呢？
![image](https://user-images.githubusercontent.com/63114159/86098507-c942d200-bae8-11ea-927f-1c7a730f026c.png)

**Comment by littletomatodonkey** [comment]
您好，分类中不涉及到位置坐标，您只需要提供图片路径和图片类别即可，您上面的截图中，空格左边是图片路径，右边的`65`是该图片所属的类别ID。

**Comment by EwardJohn** [comment]
哦哦，谢谢！
