### ISSUE TITLE
[HOW TO]自定义数据集在.yaml配置文件里的配置问题

### ISSUE THREAD

**Issue by 13136983989** [PaddlePaddle/PaddleClas#1871]
在config文件夹里设置.yaml配置文件
DataLoader：
                    dataset：
                                 name： 设置了自己做的数据集的文件夹的名字(默认是ImageNetDataset)
训练时报错：NameError: name 'test' is not defined
设置成默认ImageNetDataset报错：ValueError: invalid literal for int() with base 10: '2_1.jpg'

看官方[配置说明](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/models_training/config_description.md)

_参数名字  | 具体含义                        | 默认值                        | 可选值
name        | 读取数据的类的名字 | ImageNetDataset | VeriWild 等其他读取数据类的名字_

这个可选值该怎么填？VeriWild 等其他读取数据类的名字是什么意思？

**Comment by 13136983989** [comment]
解决了..数据集有点问题 重新弄了一下

**Comment by LijiaDong1220** [comment]
> 解决了..数据集有点问题 重新弄了一下

请问怎么解决的... 我也遇到这个问题了 TT

**Comment by Mios-dream** [comment]
检查数据集图片的文件名，不要包含特殊字符。如我使用train_  (11).jpg这个图片时出现这个错误，修改为train1.jpg时，正常运行了
