### ISSUE TITLE
self.concrete_program_specify_input_spec(input_spec=None) ？

### ISSUE THREAD

**Issue by coallar** [PaddlePaddle/PaddleClas#1873]
运行：
python python/my_predict_system.py -c configs/inference_ccartoon.yaml
报错了，输入shape的问题吗？

![image](https://user-images.githubusercontent.com/66529823/164977351-403934e5-da81-4059-a868-2138751bc9cd.png)
![image](https://user-images.githubusercontent.com/66529823/164977318-c3d1d5b0-3e9e-48cf-bab4-4d90bf5a4cce.png)

配置文件：
 rec_nms_thresold: 0.05

  batch_size: 1
  image_shape: [3, 256, 256]
  threshold: 0.2
  max_det_results: 5
  labe_list:
  - foreground

  use_gpu: True
  enable_mkldnn: True
  cpu_num_threads: 10
  enable_benchmark: True
  use_fp16: False
  ir_optim: True
  use_tensorrt: False
  gpu_mem: 8000
  enable_profile: False

DetPreProcess:
  transform_ops:
    - DetResize:
        interp: 2
        keep_ratio: false
        target_size: [256, 256]
    - DetNormalizeImage:
        is_scale: true
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    - DetPermute: {}

DetPostProcess: {}

RecPreProcess:
  transform_ops:
    - ResizeImage:
        resize_short: 256
    - CropImage:
        size: 224
    - NormalizeImage:
        scale: 0.00392157
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
    - ToCHWImage:

**Comment by cuicheng01** [comment]
想问下代码部分有做修改吗？

**Comment by coallar** [comment]
> 想问下代码部分有做修改吗？

主体没改，就是改了一些数据读取的方式，因为我的图片是url存放在txt文件里的

**Comment by cuicheng01** [comment]
具体改的部分可以分享下吗？感觉这里没有改对
