### ISSUE TITLE
[HOW TO]关于person Re-Identification

### ISSUE THREAD

**Issue by luluaa** [PaddlePaddle/PaddleClas#1880]
您好！请问文章_Implicit Sample Extension for Unsupervised Person Re-Identification_的代码是还没放出来吗，我从文章里给的网址跳转过来的，但是没有从给出的网址找到代码，打扰您了！

**Comment by AsuradaYuci** [comment]
+1

**Comment by weisy11** [comment]
https://github.com/PaddlePaddle/PaddleClas/pull/1851
可以看下这个PR
目前模型推理的部分和权重已经合入，训练的部分代码还在调试中，预计最近也会放出，欢迎持续关注。
