### ISSUE TITLE
[HOW TO]商品SOP、Inshop和Aliproduct数据集怎么处理成检索可用的数据集？

### ISSUE THREAD

**Issue by ZhuXiongwei24** [PaddlePaddle/PaddleClas#1881]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题。如果您的问题比较复杂，想与我们直接交流，可以首页扫码加入微信群。

**Comment by HydrogenSulfate** [comment]
可以看一下识别检索部分的文档中，建立索引库的部分https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/quick_start/quick_start_recognition.md#31-%E5%87%86%E5%A4%87%E6%96%B0%E7%9A%84%E6%95%B0%E6%8D%AE%E4%B8%8E%E6%A0%87%E7%AD%BE
