### ISSUE TITLE
[BUG]识别配置文件字段待优化

### ISSUE THREAD

**Issue by lazyn1997** [PaddlePaddle/PaddleClas#1895]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：

### 必要信息
** 如果您不能提供以下必要信息，可能会影响问题解决的速度 **
#### 1. PaddleClas版本以及PaddlePaddle版本

PaddleClas release/2.3
##### 2.1 原始代码问题

deploy/configs/inference中label列表中的字段名称为labe_list，不应该为label_list吗，不知道是写错了还是故意为之

#### 2.修复建议

建议修改字段名为label_list，同时应该对deploy/python/predict.py中相关行代码进行修改，修改建议见下图：
![image](https://user-images.githubusercontent.com/34644177/167246939-f8314bb9-0163-4b7d-a564-b5f775774000.png)

![image](https://user-images.githubusercontent.com/34644177/167246983-6bc46bd4-766e-40b4-a67f-ff706ca65bd6.png)

**Comment by HydrogenSulfate** [comment]
感谢建议
