### ISSUE TITLE
[BUG]predict_det.py未检测到目标时出错

### ISSUE THREAD

**Issue by lazyn1997** [PaddlePaddle/PaddleClas#1896]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：

#### 1. PaddleClas版本以及PaddlePaddle版本
PaddleClas release/2.3 paddlepaddle-gpu 2.2.2.post112
##### 2.1 原始代码问题
我自己编写程序对视频内容进行识别，将每一帧传入predict_det.py进行检测，未对predict_det.py进行修改，然后当其未检测到目标时出错，因为未检测到目标时会得到空数组，对空数组进行结果处理会出现下标越界类似的问题
#### 3. 报错信息和log
![image](https://user-images.githubusercontent.com/34644177/167261400-1d09c016-926a-498e-80b2-f0067ef0204f.png)
##### 1.1 操作系统  
Windows
##### 1.2 Python版本号  
Python3.7

#### 2.修复建议
建议将self.parse_det_results处理放置到判断语句内，else时执行该操作，修改如下图所示。
![image](https://user-images.githubusercontent.com/34644177/167261645-48dff9aa-3062-4cee-97e9-9b0f03330be1.png)

**Comment by HydrogenSulfate** [comment]
感谢建议
