### ISSUE TITLE
怎么在paddleclas使用类似VisualDL的可视化工具呢

### ISSUE THREAD

**Issue by BainOuO** [PaddlePaddle/PaddleClas#1898]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题。如果您的问题比较复杂，想与我们直接交流，可以首页扫码加入微信群。

**Comment by TingquanGao** [comment]
可以参考一下这个文档：

https://github.com/paddlepaddle/paddleclas/blob/release%2F2.3/docs/zh_CN/others/VisualDL.md
