### ISSUE TITLE
向量检索问题

### ISSUE THREAD

**Issue by 140ai** [PaddlePaddle/PaddleClas#1909]
index_vectors = np.random.rand(100000,128).astype(np.float32) 
query_vector = index_vectors[0, :]
index_docs = ["ID_"+str(i) for i in range(100000)]

# 初始化索引结构
indexer = Graph_Index(dist_type="L2") #支持"IP"和"L2"
indexer.build(gallery_vectors=index_vectors, gallery_docs=index_docs, pq_size=100, index_path='test')

# 查询
scores, docs = indexer.search(query=query_vector, return_k=10, search_budget=100)
print(scores)
print(docs)

['ID_61691', 'ID_85420', 'ID_50524', 'ID_91696', 'ID_57114', 'ID_72919', 'ID_86812', 'ID_66704', 'ID_31456', 'ID_35245']

以上代码是用index_vectors的第一个向量进行检索，请问为什么检索到的不是第一个呢

**Comment by TingquanGao** [comment]
目前PaddleClas默认使用faiss作为后端检索库，可以先试一下faiss。还是说您有其他需求必须使用mobius呢？
