### ISSUE TITLE
刚刚接触paddleclas,有些疑问,求解答

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PaddleClas#1923]
1.教程为什么都是clone整个仓库,而不是使用pip install paddleclas这种方式呢?
2.使用pip install paddleclas方式安装paddleclas,结果需要安装opencv-python4.4.0,我电脑已经安装有opencv-python4.5.5.64,paddleclas没有适配opencv-python最新版本吗?而且通过pip安装opencv-python4.4.0的whl安装包非常慢,10k/s左右,下载还不到一半就总是报错,我不知道去哪里找opencv-python4.4.0这个库,能给个下载地址吗?
3.如果只是通过pip方式安装paddleclas,没有clone整个仓库,是不是只能用python语言使用paddleclas进行预测?是不是就无法使用C++语言进行预测呢?
4.通过pip install安装某个包,然后通过pip list --outdated,就可以知道哪些包需要更新,通过pip install --upgrade 就可以更新包.如果clone整个仓库,如何知道是否该更新仓库了呢?具体如何更新呢?把paddleclas整个文件夹删了,然后重新clone整个仓库吗?

**Comment by cuicheng01** [comment]
hi，您好～
1.paddleclas也可以支持pip install, 不过目前只支持推理预测功能；
2.高于这个版本的opencv在安装时需要编译，会比较慢。当然如果你本地有高于这个版本的opencv，可以忽略这个信息。另外，你pip安装的过程慢是因为pip源的问题，可以考虑更换pip源，更换方法可以参考：https://zhuanlan.zhihu.com/p/109939711
3.目前只支持python预测，C++预测的方式我们后续也会考虑支持，不过现阶段可能无法支持；
4.可以使用git pull 或者git fetch等命令更新当前仓库，命令的具体含义可以参考https://www.zhihu.com/question/38305012

**Comment by yuwoyizhan** [comment]
@cuicheng01 感谢大佬的解答.认真看了您的解答,我还有些疑惑.
1.使用pip install paddleclas方式安装paddleclas,你提到只能用python语言进行预测,不能用C++进行预测,我还想问问,那能否使用python进行训练等呢?
2.我电脑原来安装有opencv-python4.5.5.64,安装paddleclas时,才自动降低为opencv-python4.4.0.46.如果我安装完paddleclas后,使用命令把opencv-python的版本提升为4.5.5.64,是否会兼容paddleclas呢?你说的高于4.4.0.46版本的opencv-python,需要编译,这句话如何理解?
3.我看paddledet仓库安装文档,pip安装paddledet时,最后一条命令是需要编译的,而paddleclas却没有编译这条命令,为什么paddleclas就不需要编译呢?

**Comment by weisy11** [comment]
1.不能
2.没有报错可以忽略这个提示
3.不需要，详细原理不好解释，如果你感兴趣可以仔细阅读一下源码。
