### ISSUE TITLE
希望paddleclas适配opencv-python和 gast最新版本,谢谢

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PaddleClas#1924]
使用pip安装paddleclas,安装的opencv-python和 gast两个包都不是最新版本,希望paddleclas可以适配opencv-python和 gast最新版本,谢谢

**Comment by cuicheng01** [comment]
您的问题我们已经收到，我们会根据兼容性和易用性在合适的时候更新，感谢反馈。
