### ISSUE TITLE
使用自己的训练集train from scratch

### ISSUE THREAD

**Issue by EwardJohn** [PaddlePaddle/PaddleClas#193]
你好，我使用自己的训练集（只有1类物体）进行train from scratch ,但是训练的过程中，top1和top2始终是1.0000（eval也是这样的），如图所示：
使用的配置文件为resnet50_vd.yaml,在配置文件中我改了类别数为2，请问这种情况应该怎末更改配置文件？还有一个问题是，如何拿PaddleClas训练完成的分类模型使用PaddleDetection进行目标检测？谢谢！
![image](https://user-images.githubusercontent.com/63114159/86236032-f74d1280-bbcb-11ea-9986-72f29cea98fd.png)

**Comment by littletomatodonkey** [comment]
您好
1. 您的train list和val list中包含了多少个类别呢？如果只包含一类的话 acc一直是1是正常的（但是这种情况也没有必要训练了）。
2. 分类模型一般是作为PaddleDetection中的检测任务，如果您需要将PaddleClas中的预训练模型用在PaddleDetection中，需要将骨干网络集成在PaddleDetection中，然后再去搭建自己的网络。您可以参考PaddleClas中的vgg和PaddleDetection的vgg网络的写法
https://github.com/PaddlePaddle/PaddleDetection/blob/master/ppdet/modeling/backbones/vgg.py
https://github.com/PaddlePaddle/PaddleClas/blob/master/ppcls/modeling/architectures/vgg.py

**Comment by EwardJohn** [comment]
好的，谢谢
