### ISSUE TITLE
[BUG]NO module named 'ppcls' 

### ISSUE THREAD

**Issue by feifaxiaoming** [PaddlePaddle/PaddleClas#1932]
使用的是paddleClas relase版本 2.3
问题：
当我使用https://github.com/PaddlePaddle/PaddleClas/blob/deploy_v2/docs/zh_CN/advanced_tutorials/gallery2fc.md
这个链接识别模型转分类模型转分类模型的使用，运行
python ppcls/utils/gallery2fc.py -c ppcls/configs/GeneralRecognition/Gallery2FC_PPLCNet_x2_5.yaml的使用
一直提示NO module named 'ppcls'  
只要是导入的头部带from ppcls.arch import build_model  就直接报错。
找不到ppcls，但是我是正常安装的啊。

**Comment by feifaxiaoming** [comment]
这个问题解决了，但是通过paddle_lite_opt --model_file=/data/huangheming/project/PaddleClas-release-2.3/interface/rec/inference.pdmodel --param_file=/data/huangheming/project/PaddleClas-release-2.3/interface/rec/inference.pdiparams --optimize_out=./interface/nb  去转换上述对应生成的模型的时候，报错。Error: This model is not supported, because 1 ops are not supported on 'arm'. These unsupported ops are: 'moving_average_abs_max_scale'.

**Comment by cuicheng01** [comment]
请问paddlelite的版本是？

**Comment by Liamkk** [comment]
请问解决了吗

**Comment by arrywu** [comment]
我遇到同样的问题，paddlepaddle2.6.2，路径都是正确的，但一输入paddleclas命令就报错ModuleNotFoundError: No module named 'ppcls'
请问你是如何解决的？

**Comment by zhouwei5113** [comment]
> 我遇到同样的问题，paddlepaddle2.6.2，路径都是正确的，但一输入paddleclas命令就报错ModuleNotFoundError: No module named 'ppcls' 请问你是如何解决的？

你解决了吗？
