### ISSUE TITLE
[BUG]Error: This model is not supported, because 1 ops are not supported on 'arm'. These unsupported ops are: 'moving_average_abs_max_scale'.

### ISSUE THREAD

**Issue by feifaxiaoming** [PaddlePaddle/PaddleClas#1934]
在使用https://github.com/PaddlePaddle/PaddleClas/blob/deploy_v2/docs/zh_CN/advanced_tutorials/gallery2fc.md
这个是在paddlecls developv2中转换的。因为2.3relase中报错。
这个将识别模型转换之后，使用paddlelite转成nb模型的时候报错。
使用的命令：
paddle_lite_opt --model_file=./interface/rec.pdmodel --param_file=./interface/rec.pdiparams --optimize_out_type=naive_buffer --optimize_out=./interface/rec_nb --valid_targets=arm

我使用的paddlepaddle -gpu ==2.2.0
paddlelite = 2.10rc
运行上述命令之后报错。
Error: This model is not supported, because 1 ops are not supported on 'arm'. These unsupported ops are: 'moving_average_abs_max_scale'.

请问您那边nb模型是怎么转出来的，我完全按照这个说的转的。转成nb模型的时候就报错。

**Comment by cuicheng01** [comment]
您好，建议使用最新的paddlelite哈
