### ISSUE TITLE
PaddleClass识别网络如何冻结预训练模型的backbone参数

### ISSUE THREAD

**Issue by MrLPF** [PaddlePaddle/PaddleClas#1935]
我在使用PaddleClass2.2中的Logo识别模型时想冻结backbone中加载预训练模型的权重，该如何解决？

**Comment by RainFrost1** [comment]
backbone应该是Resnet, 可以将Resnet中lr_mult_list参数全部设置为0

**Comment by RainFrost1** [comment]
应该有两种方法：
1、 使用模型中`nn.Layer`中`stop_gradient()`方法，可参考[此链接](https://github.com/RainFrost1/PaddleClas/blob/24e968b8d9f7d9e2309e713cbf2afe8fda9deacd/ppcls/engine/train/train_idml.py#L40-L66)。使用此方法后，loss到stop_gradient的层回停止，即之前的层的权重也被固定
2、在loss回传后，使用`nn.Layer`中`clear_gradients()`方法。对要固定的层，使用此方法，不用影响loss回传。
