### ISSUE TITLE
Efficientnet是否支持tensorrt推理

### ISSUE THREAD

**Issue by litao-zhx** [PaddlePaddle/PaddleClas#1937]

**Comment by RainFrost1** [comment]
理论上是支持的，遇到bug了吗

**Comment by litao-zhx** [comment]
对的，和pytorch版用tensorrt推理一样，觉得是因为最后那层的全局平均池化所致

**Comment by litao-zhx** [comment]
![1653274745(1)](https://user-images.githubusercontent.com/76981650/169735017-d41236f4-04b7-4778-97d7-429f8bed910d.jpg)
完整报错如上

**Comment by RainFrost1** [comment]
好的，我验证一下

**Comment by litao-zhx** [comment]
你好，请问问题有找到吗？

**Comment by RainFrost1** [comment]
我这边测试是可以跑通的，主要要安装好合适的trt的环境，相应的库[见链接](https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html)

**Comment by litao-zhx** [comment]
我的环境就是根据这个链接去安装的，您那边测试时的输入尺寸是多少

**Comment by RainFrost1** [comment]
yaml文件中默认的尺寸
