### ISSUE TITLE
[HOW TO]请问可以直接在 app 中执行这个推理过程吗。

### ISSUE THREAD

**Issue by mrqinshou** [PaddlePaddle/PaddleClas#1940]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题。如果您的问题比较复杂，想与我们直接交流，可以首页扫码加入微信群。

###  使用场景
app 中进行图片推理
### 问题描述
需要在 app 中进行图片推理，文档上貌似只有命令进入 shell 执行，请问在 app 上有运行有相关教程吗

**Comment by cuicheng01** [comment]
您好，你说的是什么样的app呢？是说安卓端的还是？

**Comment by mrqinshou** [comment]
> 

您好，是的，Android 端 App，目前按照文档，我只是将手机连接到电脑，通过 adb 进入 shell 执行了 pp_shitu 脚本进行了推理，但是这个过程请问能移植到 app 中直接通过代码运行吗

**Comment by PaulX1029** [comment]
> > 
> 
> 你好，是的，Android端App，目前按照文档运行，我只是将手机连接到电脑，通过adb进入shell执行了pp_shitu脚本了推理，但是这个过程可以通过代码直接迁移到app中吗

JNI开发，上层代码调用底层推理
