### ISSUE TITLE
动态图版本支持情况

### ISSUE THREAD

**Issue by luuuyi** [PaddlePaddle/PaddleClas#195]
如题，开发者你好，请问一下目前这个库的动态图版本代码能正常运行么？和静态图版本的开发进度目前有哪些是不对齐的？

**Comment by littletomatodonkey** [comment]
您好，目前已经开源出来的动态图模型代码都是可以正常运行的，resnet，hrnet，dpn，densenet等，也可以加载之前的预训练模型直接进行前向预测。

**Comment by luuuyi** [comment]
@littletomatodonkey 了解了 谢谢
