### ISSUE TITLE
关于paddle resnet50模型动态图concat reduce_mean、reduce_mean_grad、c_broadcast 的作用

### ISSUE THREAD

**Issue by daming5432** [PaddlePaddle/PaddleClas#1956]
你好，在打印模型训练log时发现resnet50会执行到concat、reduce_mean、reduce_mean_grad、c_braodcast这些op。我用
netron打开保存的模型并没有发现这些op。能帮忙解释一下为什么会用到这些op，以及这些op在训练过程中的作用吗？非常感谢~

**Comment by weisy11** [comment]
保存的模型是推理模型吗？在保存推理模型时，会删除训练过程中的部分算子，也会对一些计算用到的算子进行合并。如果你对Paddle的底层实现感兴趣，可以查看https://github.com/PaddlePaddle/Paddle
如果你只是想了解resnet，阅读论文和paddleclas中的代码就足够了，不需要过于关注log当中的中间结果。
