### ISSUE TITLE
resnet50vd耗时

### ISSUE THREAD

**Issue by Amore-HDU** [PaddlePaddle/PaddleClas#196]
你好，我在v100上测试resnet50vd耗时接近24ms，你们的5ms以内是怎么测试的

**Comment by littletomatodonkey** [comment]
您好，我们使用的是Python API+tensorRT进行预测得到的速度指标：您可以参考这篇文档：https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/zh_CN/extension/paddle_inference.md
具体的benchmark脚本是`tools/infer/predict.py`。

**Comment by Amore-HDU** [comment]
多谢，原来是tensorRT加速得到的，想问下你们支持直接转caffe模型吗，还是说必须转成onnx，然后到caffe @littletomatodonkey

**Comment by littletomatodonkey** [comment]
> 多谢，原来是tensorRT加速得到的，想问下你们支持直接转caffe模型吗，还是说必须转成onnx，然后到caffe @littletomatodonkey

我这边没有转过，不过目前是支持caffe/tf/onnx转成Paddle的，您可以在这里看支持的转换列表：https://github.com/PaddlePaddle/X2Paddle/blob/develop/x2paddle_model_zoo.md

**Comment by Amore-HDU** [comment]
安装paddle的时候 import paddle.fluid   报这个错 dlopen: cannot load any more object with static TLS，请问下怎么解决

**Comment by Amore-HDU** [comment]
@littletomatodonkey

**Comment by littletomatodonkey** [comment]
> 安装paddle的时候 import paddle.fluid 报这个错 dlopen: cannot load any more object with static TLS，请问下怎么解决

您安装的Paddle版本是什么呢？建议您安装paddle1.7.0或者paddle1.7.1，都属于比较稳定的版本。或者有docker的话，可以直接拉取paddle的docker进行实验：https://www.paddlepaddle.org.cn/install/quick

**Comment by Amore-HDU** [comment]
1.8.2版本会报这个错，1.8.0不会报错

**Comment by Amore-HDU** [comment]
我要用x2paddle,提示要1.8.0以上的

**Comment by littletomatodonkey** [comment]
> 我要用x2paddle,提示要1.8.0以上的

那您先使用paddle1.8.0或者paddle2.0呢？1.8.2这个安装问题我也反馈下

**Comment by Amore-HDU** [comment]
你好，你们有模型可视化的工具吗 @littletomatodonkey

**Comment by littletomatodonkey** [comment]
> 你好，你们有模型可视化的工具吗 @littletomatodonkey

可以使用netron这个软件对导出的模型(`tools/export_model.py`)进可视化：https://github.com/lutzroeder/netron

**Comment by Amore-HDU** [comment]
你好，我这边训练保存出来的模型是ppcls.pdmodel ppcls.pdopt ppcls.pdparams，请问export_model.py参数说明有吗-m -p应该对应哪个

**Comment by Amore-HDU** [comment]
也有合并后的,只有model 和 params，到底哪个是可以可视化的

**Comment by littletomatodonkey** [comment]
model是可以可视化的，model是结构文件，您将其修改为`__model__` (前后各2各下划线，目前netron只支持这种文件名)，就可以进行可视化了

**Comment by Amore-HDU** [comment]
你好，我训练的是一个res34VD的7类的分类器，在config中修改过 classes_num:7,然后训练出来的模型按照你的做法，在mode前后各加两个下划线，可视化出来发现全连接层维度依旧还是imagenet的1000，觉得很奇怪为什么是1000而不是7  @littletomatodonkey

**Comment by littletomatodonkey** [comment]
> 你好，我训练的是一个res34VD的7类的分类器，在config中修改过 classes_num:7,然后训练出来的模型按照你的做法，在mode前后各加两个下划线，可视化出来发现全连接层维度依旧还是imagenet的1000，觉得很奇怪为什么是1000而不是7 @littletomatodonkey

你导出模型的时候也需要指定class_dim，默认是1000

https://github.com/PaddlePaddle/PaddleClas/blob/d7d5353bee94cd0eca1fed8222598fa5868ff1f5/tools/export_model.py#L26

**Comment by Amore-HDU** [comment]
多谢，这个问题解决了，还有两个问题：
1. 一个就是我在模型可是话的时候，fc层为什么被你们展开成两层了（mul和elementwise_add），能直接变成fc层吗，方便转模型
2. 转出来的模型在softmax后面为什么还接了一个scale层；然后转成onnx之后变成了softmax->Identity->scale_0.tmp_0
麻烦解答下

**Comment by Amore-HDU** [comment]
您好，还有一个问题，我这边模型转出来的精度对不上，我想把中间层打印出来对下相似度，请问有什么函数可以直接获取当中某一层吗 @ @littletomatodonkey

**Comment by littletomatodonkey** [comment]
> 多谢，这个问题解决了，还有两个问题：
> 
> 1. 一个就是我在模型可是话的时候，fc层为什么被你们展开成两层了（mul和elementwise_add），能直接变成fc层吗，方便转模型
> 2. 转出来的模型在softmax后面为什么还接了一个scale层；然后转成onnx之后变成了softmax->Identity->scale_0.tmp_0
>    麻烦解答下 @littletomatodonkey

你好，
1. paddle的fc是通过mul和elem_add组合实现的，因此可以认为是2个单元，目前没法变成fc层
2. 在预测的时候，Paddle中为了使用zerocopyrun的特性，会给所有的输出添加一个scale的操作。

**Comment by littletomatodonkey** [comment]
> 您好，还有一个问题，我这边模型转出来的精度对不上，我想把中间层打印出来对下相似度，请问有什么函数可以直接获取当中某一层吗 @ @littletomatodonkey

你直接将要返回的tensor作为fetch list，拿出来就可以的，也可以使用fluid.layers.Print函数，在跑网络的时候实时打印tensor

**Comment by Amore-HDU** [comment]
> > 您好，还有一个问题，我这边模型转出来的精度对不上，我想把中间层打印出来对下相似度，请问有什么函数可以直接获取当中某一层吗 @ @littletomatodonkey
> 
> 你直接将要返回的tensor作为fetch list，拿出来就可以的，也可以使用fluid.layers.Print函数，在跑网络的时候实时打印tensor

能否举个例子，比如说我要把全连接层前的卷积层的featuremap打出来，我该怎么操作

**Comment by littletomatodonkey** [comment]
> > > 您好，还有一个问题，我这边模型转出来的精度对不上，我想把中间层打印出来对下相似度，请问有什么函数可以直接获取当中某一层吗 @ @littletomatodonkey
> > 
> > 
> > 你直接将要返回的tensor作为fetch list，拿出来就可以的，也可以使用fluid.layers.Print函数，在跑网络的时候实时打印tensor
> 
> 能否举个例子，比如说我要把全连接层前的卷积层的featuremap打出来，我该怎么操作

以ResNet为例，在pool之后添加fluid.layers.Print(pool, summarize=10)就行，其中10是你要打印的feature map的元素数量。
https://github.com/PaddlePaddle/PaddleClas/blob/ad6b6debb8e0ccee14baa921d37e3f04d833e4f1/ppcls/modeling/architectures/resnet.py#L94

**Comment by wang-kangkang** [comment]
> 能否举个例子，比如说我要把全连接层前的卷积层的featuremap打出来，我该怎么操作

paddle读取参数权重矩阵 weight = np.array(fluid.global_scope().find_var('conv2d_0.w_0').get_tensor())

**Comment by Amore-HDU** [comment]
> > > > 您好，还有一个问题，我这边模型转出来的精度对不上，我想把中间层打印出来对下相似度，请问有什么函数可以直接获取当中某一层吗 @ @littletomatodonkey
> > > 
> > > 
> > > 你直接将要返回的tensor作为fetch list，拿出来就可以的，也可以使用fluid.layers.Print函数，在跑网络的时候实时打印tensor
> > 
> > 
> > 能否举个例子，比如说我要把全连接层前的卷积层的featuremap打出来，我该怎么操作
> 
> 以ResNet为例，在pool之后添加fluid.layers.Print(pool, summarize=10)就行，其中10是你要打印的feature map的元素数量。
> https://github.com/PaddlePaddle/PaddleClas/blob/ad6b6debb8e0ccee14baa921d37e3f04d833e4f1/ppcls/modeling/architectures/resnet.py#L94

按你的添加了，然后执行tools/infer/predict.py 来跑一张图，发现没进到刚添加的那段代码里

**Comment by Amore-HDU** [comment]
> > 能否举个例子，比如说我要把全连接层前的卷积层的featuremap打出来，我该怎么操作
> 
> paddle读取参数权重矩阵 weight = np.array(fluid.global_scope().find_var('conv2d_0.w_0').get_tensor())

这个打印的是权重，我想打印的是featuremap

**Comment by littletomatodonkey** [comment]
> > > > > 您好，还有一个问题，我这边模型转出来的精度对不上，我想把中间层打印出来对下相似度，请问有什么函数可以直接获取当中某一层吗 @ @littletomatodonkey
> > > > 
> > > > 
> > > > 你直接将要返回的tensor作为fetch list，拿出来就可以的，也可以使用fluid.layers.Print函数，在跑网络的时候实时打印tensor
> > > 
> > > 
> > > 能否举个例子，比如说我要把全连接层前的卷积层的featuremap打出来，我该怎么操作
> > 
> > 
> > 以ResNet为例，在pool之后添加fluid.layers.Print(pool, summarize=10)就行，其中10是你要打印的feature map的元素数量。
> > https://github.com/PaddlePaddle/PaddleClas/blob/ad6b6debb8e0ccee14baa921d37e3f04d833e4f1/ppcls/modeling/architectures/resnet.py#L94
> 
> 按你的添加了，然后执行tools/infer/predict.py 来跑一张图，发现没进到刚添加的那段代码里

`toos/infer/predict.py`是加载inference model运行，如果要在预测的时候打印中间值，你需要使用`toos/infer/infer.py`

**Comment by Amore-HDU** [comment]
> > > > > > 您好，还有一个问题，我这边模型转出来的精度对不上，我想把中间层打印出来对下相似度，请问有什么函数可以直接获取当中某一层吗 @ @littletomatodonkey
> > > > > 
> > > > > 
> > > > > 你直接将要返回的tensor作为fetch list，拿出来就可以的，也可以使用fluid.layers.Print函数，在跑网络的时候实时打印tensor
> > > > 
> > > > 
> > > > 能否举个例子，比如说我要把全连接层前的卷积层的featuremap打出来，我该怎么操作
> > > 
> > > 
> > > 以ResNet为例，在pool之后添加fluid.layers.Print(pool, summarize=10)就行，其中10是你要打印的feature map的元素数量。
> > > https://github.com/PaddlePaddle/PaddleClas/blob/ad6b6debb8e0ccee14baa921d37e3f04d833e4f1/ppcls/modeling/architectures/resnet.py#L94
> > 
> > 
> > 按你的添加了，然后执行tools/infer/predict.py 来跑一张图，发现没进到刚添加的那段代码里
> 
> `toos/infer/predict.py`是加载inference model运行，如果要在预测的时候打印中间值，你需要使用`toos/infer/infer.py`

你好，值我打印出来了，我能把中间结果获取出来吗，因为发现fluid.layers.Print只能打印，没法保存

**Comment by littletomatodonkey** [comment]
> > > > > > > 您好，还有一个问题，我这边模型转出来的精度对不上，我想把中间层打印出来对下相似度，请问有什么函数可以直接获取当中某一层吗 @ @littletomatodonkey
> > > > > > 
> > > > > > 
> > > > > > 你直接将要返回的tensor作为fetch list，拿出来就可以的，也可以使用fluid.layers.Print函数，在跑网络的时候实时打印tensor
> > > > > 
> > > > > 
> > > > > 能否举个例子，比如说我要把全连接层前的卷积层的featuremap打出来，我该怎么操作
> > > > 
> > > > 
> > > > 以ResNet为例，在pool之后添加fluid.layers.Print(pool, summarize=10)就行，其中10是你要打印的feature map的元素数量。
> > > > https://github.com/PaddlePaddle/PaddleClas/blob/ad6b6debb8e0ccee14baa921d37e3f04d833e4f1/ppcls/modeling/architectures/resnet.py#L94
> > > 
> > > 
> > > 按你的添加了，然后执行tools/infer/predict.py 来跑一张图，发现没进到刚添加的那段代码里
> > 
> > 
> > `toos/infer/predict.py`是加载inference model运行，如果要在预测的时候打印中间值，你需要使用`toos/infer/infer.py`
> 
> 你好，值我打印出来了，我能把中间结果获取出来吗，因为发现fluid.layers.Print只能打印，没法保存

你直接将要返回的tensor作为fetch list，拿出来就可以的，转成numpy之后就可以存储了，比如infer.py里的out拿出来，之后每次exe.run，就可以拿到结果，保存了

**Comment by Amore-HDU** [comment]
> > > > > > > > 您好，还有一个问题，我这边模型转出来的精度对不上，我想把中间层打印出来对下相似度，请问有什么函数可以直接获取当中某一层吗 @ @littletomatodonkey
> > > > > > > 
> > > > > > > 
> > > > > > > 你直接将要返回的tensor作为fetch list，拿出来就可以的，也可以使用fluid.layers.Print函数，在跑网络的时候实时打印tensor
> > > > > > 
> > > > > > 
> > > > > > 能否举个例子，比如说我要把全连接层前的卷积层的featuremap打出来，我该怎么操作
> > > > > 
> > > > > 
> > > > > 以ResNet为例，在pool之后添加fluid.layers.Print(pool, summarize=10)就行，其中10是你要打印的feature map的元素数量。
> > > > > https://github.com/PaddlePaddle/PaddleClas/blob/ad6b6debb8e0ccee14baa921d37e3f04d833e4f1/ppcls/modeling/architectures/resnet.py#L94
> > > > 
> > > > 
> > > > 按你的添加了，然后执行tools/infer/predict.py 来跑一张图，发现没进到刚添加的那段代码里
> > > 
> > > 
> > > `toos/infer/predict.py`是加载inference model运行，如果要在预测的时候打印中间值，你需要使用`toos/infer/infer.py`
> > 
> > 
> > 你好，值我打印出来了，我能把中间结果获取出来吗，因为发现fluid.layers.Print只能打印，没法保存
> 
> 你直接将要返回的tensor作为fetch list，拿出来就可以的，转成numpy之后就可以存储了，比如infer.py里的out拿出来，之后每次exe.run，就可以拿到结果，保存了

稍微有点不理解
ax = np.array(fluid.layers.Print(pool, summarize=10))
????

**Comment by Amore-HDU** [comment]
你好，我想问下能不能直接指定某一层的feature map进行打印

**Comment by littletomatodonkey** [comment]
> 你好，我想问下能不能直接指定某一层的feature map进行打印

可以参考下是怎么拿到softmax输出结果的，把out替换成你需要的feature map就行
https://github.com/PaddlePaddle/PaddleClas/blob/ad6b6debb8e0ccee14baa921d37e3f04d833e4f1/tools/infer/infer.py#L68

**Comment by shippingwang** [comment]
Feel free to reopen it~
