### ISSUE TITLE
C++编程相关

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PaddleClas#1981]
pytorch在一年多以前,就非常完善的支持C++编程了,比如图像分类这个任务,可以从头到尾,不使用一行python代码完成数据集下载,加载,训练,预测等步骤.知乎和CSDN也有很多pytorch的C++编程代码,可以让我们学习和参考.目前我都没看到一个项目使用C++完成飞桨任务的,无论是图像分类clas等开发套件,还是飞桨paddlepaddle,我想请问,飞桨是否打算支持C++编程呢?
我不敢说pytorch支持C++20,C++23这些很新的标准,但是用VS2022编写pytorch代码,完全没有问题.对于飞桨框架来说,目前C++似乎只能用于预测,而且一个预测的代码,比如图像分类clas的C++预测代码,超级多代码,无语,能否封装一下,像python一样,实现一行C++代码预测呢?如果目前C++已经能用于飞桨的话,麻烦你们多提供项目案例,让我知道如何写代码,谢谢,比如可以一个开发套件做一个C++案例.

我还想请问下,我现在使用windows,C++,5600gCPU,飞桨.对于图像分类clas和目标检测dec这两个开发套件来说,预测时使用的是多核心多线程还是单核心单线程CPU?另外,预测是否可以让客户自主选择使用多少个CPU线程?
我有一个预测任务,单开任务的话,我希望,CPU的6核心12线程都可以参与预测.但是如果双开任务,我就希望为每个预测任务分配3核心6线程.

**Comment by weisy11** [comment]
感谢你的建议，关于Paddle框架对C++编程的支持，可以在Paddle的主repo提issue：
https://github.com/PaddlePaddle/Paddle

**Comment by weisy11** [comment]
> 比如图像分类clas的C++预测代码,超级多代码,无语,能否封装一下,像python一样,实现一行C++代码预测呢?

C++的代码确实要比python复杂，无法实现一行代码预测。

>  比如可以一个开发套件做一个C++案例.

这个建议我们后续会考虑的，谢谢

> 我还想请问下,我现在使用windows,C++,5600gCPU,飞桨.对于图像分类clas和目标检测dec这两个开发套件来说,预测时使用的是多核心多线程还是单核心单线程CPU?另外,预测是否可以让客户自主选择使用多少个CPU线程?
我有一个预测任务,单开任务的话,我希望,CPU的6核心12线程都可以参与预测.但是如果双开任务,我就希望为每个预测任务分配3核心6线程.

目前不支持这个功能。
