### ISSUE TITLE
下载预训练模型报错，请帮忙看一下

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleClas#199]
!python tools/download.py -a ResNet50_vd -p ./pretrained -d True
!python tools/download.py -a ResNet50_vd_ssld -p ./pretrained -d True
!python tools/download.py -a MobileNetV3_large_x1_0 -p ./pretrained -d True

Traceback (most recent call last):
  File "tools/download.py", line 17, in <module>
    from ppcls import model_zoo
ModuleNotFoundError: No module named 'ppcls'
Traceback (most recent call last):
  File "tools/download.py", line 17, in <module>
    from ppcls import model_zoo
ModuleNotFoundError: No module named 'ppcls'
Traceback (most recent call last):
  File "tools/download.py", line 17, in <module>
    from ppcls import model_zoo
ModuleNotFoundError: No module named 'ppcls'

**Comment by littletomatodonkey** [comment]
您需要先设置下环境变量：`export PYTHONPATH=$PWD:$PYTHONPATH`

可以参考下这个脚本
https://github.com/PaddlePaddle/PaddleClas/blob/dab1feb0d4399dac2fbd45a88b3f4915d6e7a45c/tools/run_download.sh#L3
