### ISSUE TITLE
Vehicle's type classification (car,bus,truck ...)

### ISSUE THREAD

**Issue by centurions** [PaddlePaddle/PaddleClas#1998]
Which model is better for vehicle's type classification ? THX

**Comment by cuicheng01** [comment]
Hi, you can try the vehicle_attribute_recognition model, the types of vehicles that can be recognized are "sedan", "suv", "van", "hatchback", "mpv", "pickup", "bus","truck", " estate", you can refer to [here](https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/en/PULC/PULC_vehicle_attribute_en.md) for related instructions
