### ISSUE TITLE
缺少模型列表！

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleClas#1999]
hi,
     请问下，7个精选系列模型支持结构快速修改   您指的是哪些？ 有具体的详细列表或者链接吗？多谢
BR

**Comment by 2050airobert** [comment]
hello，anyone here？

**Comment by weisy11** [comment]
https://github.com/PaddlePaddle/PaddleClas/tree/develop/ppcls/arch/backbone/legendary_models
