### ISSUE TITLE
模型推理报错

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleClas#205]
你好，我在aistudio上已将训练的模型转成inference模型之后，在推断的时候报错了:
!export PYTHONPATH=./:$PYTHONPATH && python tools/infer/predict.py \
    -m=./inference/ResNet50_vd/model \
    -p=./inference/ResNet50_vd/params \
    -i=./dataset/flowers102/jpg/image_02275.jpg \
    --use_gpu=1 \
    --use_tensorrt=True

报错信息如下：

Traceback (most recent call last):
  File "tools/infer/predict.py", line 156, in <module>
    main()
  File "tools/infer/predict.py", line 110, in main
    predictor = create_predictor(args)
  File "tools/infer/predict.py", line 66, in create_predictor
    predictor = create_paddle_predictor(config)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::framework::ir::PassRegistry::Get(std::string const&) const
3   paddle::inference::analysis::IRPassManager::CreatePasses(paddle::inference::analysis::Argument*, std::vector<std::string, std::allocator<std::string> > const&)
4   paddle::inference::analysis::IRPassManager::IRPassManager(paddle::inference::analysis::Argument*)
5   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
7   paddle::AnalysisPredictor::OptimizeInferenceProgram()
8   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
9   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
10  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
11  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)

----------------------
Error Message Summary:
----------------------
Error: Pass tensorrt_subgraph_pass has not been registered at (/paddle/paddle/fluid/framework/ir/pass.h:201)

请问如何解决？

**Comment by greatyang** [comment]
有相同的错误，尝试编译paddle with tensorrt，编译成功，还是报错

**Comment by littletomatodonkey** [comment]
你好，编译paddle with trt成功，并且安装成功之后，还需要将trt的路径添加到LD_LiBRARY_PATH中，比如下面这种

`export LD_LIBRARY_PATH=/paddle/libs/TensorRT-5.1.2.2/lib:$LD_LIBRARY_PATH`

**Comment by greatyang** [comment]
@littletomatodonkey 请问正常的trt lib目录下有哪些文件？我把trt的lib加入到LD_LIBRARY_PATH后 问题依旧

**Comment by greatyang** [comment]
参照这个页面做的https://paddle-inference.readthedocs.io/en/latest/user_guides/source_compile.html
是在aistudio上编译的，原有的paddle是1.7.2的版本
git clone https://github.com/PaddlePaddle/Paddle.git
cd Paddle
git checkout v1.7.2

mkdir build && cd build

export C_INCLUDE_PATH=/opt/conda/envs/python35-paddle120-env/include/python3.7m/:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/opt/conda/envs/python35-paddle120-env/include/python3.7m/:$CPLUS_INCLUDE_PATH

cmake -DPY_VERSION=3 -DWITH_TESTING=OFF -DWITH_MKL=ON -DWITH_GPU=ON -DON_INFER=ON -DCMAKE_BUILD_TYPE=Release -DPYTHON_INCLUDE_DIR=/opt/conda/envs/python35-paddle120-env/include/ --DPYTHON_LIBRARY=/opt/conda/envs/python35-paddle120-env/lib/ ..

make -j6

pip install ./python/dist/paddlepaddle_gpu-1.8.0-cp37-cp37m-linux_x86_64.whl -t /home/aistudio/external-libraries/

make inference_lib_dist -j6

以上操作是否有误？接下来需要做哪些工作？

**Comment by greatyang** [comment]
需要安装TENSORRT，同时在cmake 时指定 -DTENSORRT_ROOT
同时在make时会报错，可以参考https://github.com/PaddlePaddle/Paddle/issues/25209

**Comment by littletomatodonkey** [comment]
> 1.7.2

编译成功之后，在`build/python/dist`下面有一个whl包，pip install一下，就可以了

**Comment by shippingwang** [comment]
Feel free to reopen it~
