### ISSUE TITLE
关于主体检测，分类数据不在一张图片上

### ISSUE THREAD

**Issue by QuStarry** [PaddlePaddle/PaddleClas#2064]
每个分类单独的类别图片数据，我希望能最终使用的时候按照主体，再额外的检测到每一个类别，对于分类数据不在一张图片上的这种情况，我应该做怎样的训练呢？是训练多个分类模型，在使用的时候进行组合预测；还是有什么办法可以把这些不同类别的数据通过一个模型训练得到。

**Comment by weisy11** [comment]
没太理解，分类数据不在一张图片上是什么意思呢？是说要把多张图组合起来，才能有类别的语义吗？

**Comment by QuStarry** [comment]
是的，我现在的分类数据是有多个单独类别的图片，最后想把这多个类别在一张图片中全识别出来。主要是这个整体（包含多个类别）的图片没有标注数据，而对应的类别有数据。

**Comment by weisy11** [comment]
这个用PP-ShiTu就可以了。

**Comment by QuStarry** [comment]
好的，非常感谢
