### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by alexiycv** [PaddlePaddle/PaddleClas#2068]
[2022/06/15 14:03:52] ppcls INFO: train with paddle 2.3.0 and device Place(gpu:0)
/home/PaddleClas/ppcls/data/preprocess/ops/operators.py:44: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
/home/PaddleClas/ppcls/data/preprocess/ops/operators.py:45: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
/home/PaddleClas/ppcls/data/preprocess/ops/operators.py:46: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
/home/PaddleClas/ppcls/data/preprocess/ops/operators.py:47: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
/home/PaddleClas/ppcls/data/preprocess/ops/operators.py:48: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
/home/PaddleClas/ppcls/data/preprocess/ops/operators.py:49: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
Traceback (most recent call last):
  File "tools/train.py", line 31, in <module>
    engine = Engine(config, mode="train")
  File "/home/PaddleClas/ppcls/engine/engine.py", line 133, in __init__
    self.config["DataLoader"], "Train", self.device, self.use_dali)
  File "/home/PaddleClas/ppcls/data/__init__.py", line 81, in build_dataloader
    dataset = eval(dataset_name)(**config_dataset)
  File "/home/PaddleClas/ppcls/data/dataloader/imagenet_dataset.py", line 31, in __init__
    super(ImageNetDataset, self).__init__(image_root, cls_label_path, transform_ops)
  File "/home/PaddleClas/ppcls/data/dataloader/common_dataset.py", line 59, in __init__
    self._load_anno()
  File "/home/PaddleClas/ppcls/data/dataloader/imagenet_dataset.py", line 46, in _load_anno
    self.labels.append(np.int64(l[1]))
IndexError: list index out of range
INFO 2022-06-15 14:03:57,940 launch_utils.py:343] terminate all the procs
INFO 2022-06-15 14:03:57,940 launch_utils.py:343] terminate all the procs
ERROR 2022-06-15 14:03:57,941 launch_utils.py:642] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] was aborted. Please check its log.
ERROR 2022-06-15 14:03:57,941 launch_utils.py:642] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] was aborted. Please check its log.
INFO 2022-06-15 14:04:01,946 launch_utils.py:343] terminate all the procs
INFO 2022-06-15 14:04:01,946 launch_utils.py:343] terminate all the procs
INFO 2022-06-15 14:04:01,947 launch.py:402] Local processes completed.
INFO 2022-06-15 14:04:01,947 launch.py:402] Local processes completed.

**Comment by HydrogenSulfate** [comment]
看报错信息可能是self.labels.append(np.int64(l[1]))这句出了问题，可以打印一下变量`l`，并检查`_cls_path`对应路径的文本文件内容是否正确，文本文件的格式可以参照https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/PULC/PULC_train.md#2.1，

**Comment by andyz168** [comment]
在使用paddlelabel导出的voc数据，train_list.txt内容如下
JPEGImages\230209_075442_0000000009_CAM2_NG.jpg Annotations\230209_075442_0000000009_CAM2_NG.xml
` File "/home/aistudio/PaddleClas-2.4.0/ppcls/data/dataloader/imagenet_dataset.py", line 46, in _load_anno
    self.labels.append(np.int64(l[1]))
ValueError: invalid literal for int() with base 10: 'Annotations\\230209_075442_0000000009_CAM2_NG.xml'`

尝试过导出yolo，也是这个错误，无法转换成int，是不是多分类的问题

**Comment by Chase-Xuu** [comment]
我也出现了这个报错，通过删除txt文件末尾多出来的空行解决了
