### ISSUE TITLE
如何在paddleHub上部署

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleClas#207]
你好，我用SSLD模型微调-基于ResNet50_vd_ssld预训练模型来做训练，然后生成了inference模型，想用PaddleHub进行部署的操作，有没有什么借壳快速部署的方式替换一下原来的module下的inference模型就可以启动部署的方式。

**Comment by xialei2821212670** [comment]
你好，请问window下可以进行训练？

**Comment by littletomatodonkey** [comment]
你好，支持的，可以使用`tools/train_multi_platform.py`这个脚本，具体的使用方法可以参考这个PR： #159
