### ISSUE TITLE
lite_shitu在安卓上预测结果都错了。

### ISSUE THREAD

**Issue by superdu12138** [PaddlePaddle/PaddleClas#2075]
我是按照这份文档一步一步操作的(https://github.com/PaddlePaddle/PaddleClas/tree/develop/deploy/lite_shitu)， 预测结果都错了，而且官方的readme里的图片和预测结果也不匹配啊

![image](https://user-images.githubusercontent.com/20619835/174021401-988f7489-5dbd-4f0d-988c-35e7d940a7d3.png)

![image](https://user-images.githubusercontent.com/20619835/174020728-cea8626a-8dc2-4549-9b86-b2ac65d7c888.png)

**Comment by RainFrost1** [comment]
此版本的lite_cpp确实存在问题。可以先试用2.3版本的lite_cpp

**Comment by superdu12138** [comment]
> 此版本的lite_cpp确实存在问题。可以先试用2.3版本的lite_cpp

在这份 https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/inference_deployment/export_model.md 文档里
![image](https://user-images.githubusercontent.com/20619835/175198300-5fab0252-f764-4e7a-9268-57a439be4e72.png)
说是只支持分类模型导出，请问识别模型是怎么导出的，还有识别时的映射文件怎么得到，训练时并没有用到啊

**Comment by RainFrost1** [comment]
你好，目前这部分代码及流程，正在修复中

**Comment by superdu12138** [comment]
> > 此版本的lite_cpp确实存在问题。可以先试用2.3版本的lite_cpp
> 
> 在这份 https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/inference_deployment/export_model.md 文档里 ![image](https://user-images.githubusercontent.com/20619835/175198300-5fab0252-f764-4e7a-9268-57a439be4e72.png) 说是只支持分类模型导出，请问识别模型是怎么导出的，还有识别时的映射文件怎么得到，训练时并没有用到啊

我是想在安卓上部署图像识别系统，参考这份文档 [PP-ShiTu在Paddle-Lite端侧部署](https://github.com/PaddlePaddle/PaddleClas/tree/release/2.3/deploy/lite_shitu)
在模型准备步骤中，下载的模型带有一个 label.txt 文件，内容如下，而且文档最后 FAQ 有说替换模型需要替换映射文件。
![image](https://user-images.githubusercontent.com/20619835/176358015-af75a8b5-66d2-42ec-9e93-18a947380dd6.png)

![image](https://user-images.githubusercontent.com/20619835/176358109-da3a4e99-9b18-4b18-bada-23c0d65d3cd2.png)

**Comment by RainFrost1** [comment]
PP-ShiTu有三个部分：检测、特征提取、检索。在2.3版本的lite_cpp中，为了方便开发，将检索部分合并到了特征提取模型上，即将index库的特征转成了一个fc的权重，将特征提取模型变成了一个分类模型，这个映射文件就是对应的分类模型的类别。转换过程可参考[此链接](https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/advanced_tutorials/gallery2fc.md)

**Comment by superdu12138** [comment]
> PP-ShiTu有三个部分：检测、特征提取、检索。在2.3版本的lite_cpp中，为了方便开发，将检索部分合并到了特征提取模型上，即将index库的特征转成了一个fc的权重，将特征提取模型变成了一个分类模型，这个映射文件就是对应的分类模型的类别。转换过程可参考[此链接](https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/advanced_tutorials/gallery2fc.md)

好，谢谢，能不能提供完整的流程，这一会儿2.3，一会儿develop的

**Comment by RainFrost1** [comment]
这部分有待优化，文档及代码还在优化中。demo先更新在2.3中。文档之后添加在dev分支，同时也更新了代码，但是dev分支现在代码可能存在bug，所以暂时建议使用dev文档+2.3分支代码

**Comment by LMR2018** [comment]
@superdu12138  兄弟，你在安卓上成功跑通了吗？

**Comment by superdu12138** [comment]
按照这份文档 https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/advanced_tutorials/gallery2fc.md 操作，在执行这个命令时 `python ppcls/utils/gallery2fc.py -c ppcls/configs/GeneralRecognition/Gallery2FC_PPLCNet_x2_5.yaml`，一直报内存不足，我本地有8G显存，在AI studio上用40G显存的环境，也还是一样的错误。
![image](https://user-images.githubusercontent.com/20619835/176818747-7799f706-de7f-412d-a238-83f8fb225544.png)

![image](https://user-images.githubusercontent.com/20619835/176819069-1fe7688a-94e9-48df-a6c7-4341392d5f51.png)

**Comment by RainFrost1** [comment]
bs调整过吗？是不是太大了，如果还是不行的话，用cpu运行试一下。paddle.set_device('cpu')

**Comment by superdu12138** [comment]
> bs调整过吗？是不是太大了，如果还是不行的话，用cpu运行试一下。paddle.set_device('cpu')

batch_size 原来是2，已经改成 1了，还是不行，换成cpu运行，会被killed。

**Comment by RainFrost1** [comment]
检索库有多大呢？是不是检索库太大了

**Comment by superdu12138** [comment]
> 检索库有多大呢？是不是检索库太大了

检索库也就90个，我主要是想先跑通整个流程，验证可行性

**Comment by RainFrost1** [comment]
我验证下

**Comment by RainFrost1** [comment]
可以先用下这个[版本](https://github.com/PaddlePaddle/PaddleClas/pull/2144)
