### ISSUE TITLE
Error importing paddleclas after install

### ISSUE THREAD

**Issue by acul3** [PaddlePaddle/PaddleClas#2079]
i got error

```
local variable 'total_width' referenced before assignment
```

when use `import paddleclas` for the first time after installation
i use branch develop and using guide from readme_en.md

error gone when i change the total_width to arbitary int number

https://github.com/PaddlePaddle/PaddleClas/blob/95edc0d6d3f3e1cc299a7f58012177769fc63fb4/paddleclas.py#L352

after i change,,i got another error that say

```
AssertionError: logger should not be initialized twice or more.
```  

error gone when i comment this line https://github.com/PaddlePaddle/PaddleClas/blob/95edc0d6d3f3e1cc299a7f58012177769fc63fb4/ppcls/utils/logger.py#L42

and after that, the paddleclas work perfectly

maybe you guys can take a look before merging #2036

**Comment by weisy11** [comment]
Thanks for reporting bug. It will be solved by PR #2084
