### ISSUE TITLE
回归任务

### ISSUE THREAD

**Issue by fengyanWang** [PaddlePaddle/PaddleClas#2097]
请问如何修改paddlecls中的配置文件，使其能够完成回归预测任务呢？有没有示例可以参考？

**Comment by weisy11** [comment]
目前暂时没有这方面的案例

**Comment by fengyanWang** [comment]
> 目前暂时没有这方面的案例

那只能用paddle从头开始搭吗？

**Comment by weisy11** [comment]
> > 目前暂时没有这方面的案例
> 
> 那只能用paddle从头开始搭吗？

可以在分类的基础上改，不过目前没有例子可以参考。
