### ISSUE TITLE
MobileVIT

### ISSUE THREAD

**Issue by Sqhttwl** [PaddlePaddle/PaddleClas#2099]
MobileVIT系列的三个模型怎么模型越大效果越差了，是不是写反了。
![mmexport1656004019391.png](https://user-images.githubusercontent.com/61459740/175355558-51f335d4-e677-4299-b123-397461734830.png)

**Comment by cuicheng01** [comment]
您好，模型和精度都没有问题哈，不过FLOPs和Params在XXS和S上写反了，已修复，详情：https://github.com/PaddlePaddle/PaddleClas/pull/2107 ，感谢提醒。
