### ISSUE TITLE
faiss的C++库安装

### ISSUE THREAD

**Issue by TimZhang001** [PaddlePaddle/PaddleClas#2101]
我这边需要使用PP-Shitu的C++部署，但是其中使用到了Faiss库，不过Paddle没有提供Faiss的编译版本。
是否可以提供一下Faiss的Windows和Linux的C++版本，这样部署起来简单很多

**Comment by weisy11** [comment]
关于faiss的需求请直接到faiss的github留言：
https://github.com/facebookresearch/faiss
