### ISSUE TITLE
模型推理问题

### ISSUE THREAD

**Issue by gxqnba** [PaddlePaddle/PaddleClas#211]
python tools/export_model.py \
    --model=模型名字 \
    --pretrained_model=预训练模型路径 \
    --output_path=预测模型保存路径
对训练好的模型进行转换以后，再用一下命令：
python tools/infer/predict.py \
    -m model文件路径 \
    -p params文件路径 \
    -i 图片路径 \
    --use_gpu=1 \
    --use_tensorrt=True
进行推理，只能进行单张图片推理，请问能对文件夹下所有的图片进行推理吗

**Comment by shippingwang** [comment]
predict.py是一个预测示例, 预测文件夹现在这里需要自己写一下for循环～
