### ISSUE TITLE
NameError: name 'total_width' is not defined

### ISSUE THREAD

**Issue by ishangxue** [PaddlePaddle/PaddleClas#2117]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如Linux/Windows/MacOS
  b. Python版本号，如Python3.9
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

全新系统，全新anaconda pycharm 虚拟环境 一且安装顺利
但是执行检测时提示错误，无从下手了

E:\Anaconda3\envs\paddle_venv\python.exe E:/ai/test/paddletest/main.py
E:\Anaconda3\envs\paddle_venv\lib\site-packages\paddleclas\ppcls\data\preprocess\ops\timm_autoaugment.py:39: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  _RANDOM_INTERPOLATION = (Image.BILINEAR, Image.BICUBIC)
E:\Anaconda3\envs\paddle_venv\lib\site-packages\paddleclas\ppcls\data\preprocess\ops\timm_autoaugment.py:39: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  _RANDOM_INTERPOLATION = (Image.BILINEAR, Image.BICUBIC)
Traceback (most recent call last):
  File "E:\ai\test\paddletest\main.py", line 5, in <module>
    import paddleclas
  File "E:\Anaconda3\envs\paddle_venv\lib\site-packages\paddleclas\__init__.py", line 16, in <module>
    from .paddleclas import PaddleClas
  File "E:\Anaconda3\envs\paddle_venv\lib\site-packages\paddleclas\paddleclas.py", line 456, in <module>
    class PaddleClas(object):
  File "E:\Anaconda3\envs\paddle_venv\lib\site-packages\paddleclas\paddleclas.py", line 460, in PaddleClas
    print_info()
  File "E:\Anaconda3\envs\paddle_venv\lib\site-packages\paddleclas\paddleclas.py", line 357, in print_info
    "  ".join(PULC_MODELS), width = total_width).center(table_width - 4)
NameError: name 'total_width' is not defined

进程已结束,退出代码1

求解原因呢

**Comment by ishangxue** [comment]
https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/PULC/PULC_quickstart.md
按着上面的步骤开始的

**Comment by tkzt** [comment]
@ishangxue check this PR #2084

**Comment by cuicheng01** [comment]
安装最新的paddleclas whl包(2.4.2)可以解决哈~
