### ISSUE TITLE
Resnet网络的实现和预训练模型哪里下载

### ISSUE THREAD

**Issue by peach-xiao** [PaddlePaddle/PaddleClas#2120]
我想使用Resnet的模型做实验，但是我看到Passleseg提供的是resnet-vc版本，我只想用最原始的实现和模型，就和pytorch库timm一样的，不需要变体，因为我其他模型也没有使用变体。请问哪里可以下载paddlse代码的实现resnet和相应的预训练模型.pdparams呢？因为不一致的话加载模型会出错。

感谢！！！

**Comment by cuicheng01** [comment]
可以在这里下载对应的版本的模型哈https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/algorithm_introduction/ImageNet_models.md#ResNet

**Comment by fhong-jpg** [comment]
这也放得太隐蔽了，应该放在首页

> 可以在这里下载对应的版本的模型哈https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/algorithm_introduction/ImageNet_models.md#ResNet
