### ISSUE TITLE
PULC ARM端推理耗时与官方给出耗时相差较大

### ISSUE THREAD

**Issue by fengyanWang** [PaddlePaddle/PaddleClas#2122]
环境信息：paddlepaddle-gpu   2.2.0.post101   paddlelite         2.11

问题描述：使用高通730g，基于paddle lite推理pulc分类模型（输入为68*68），单个大核耗时11毫秒多，和官方的CPU端3毫秒（输入为224*224）相差较大，请问是什么原因导致的？（ps:通过对导出的nb模型可视化，发现其包含一个FC层，不知道是不是这个原因，如果是的话，如何替换掉？）

**Comment by cuicheng01** [comment]
官方模型测试使用的CPU是Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz，这块在文档中有描述哈，如：
![image](https://user-images.githubusercontent.com/45199522/176859173-1834ef19-a5e0-40b7-9745-169770970a45.png)
不同的设备速度不一致。

**Comment by fengyanWang** [comment]
> 是Intel(R) Xeon(R) Gold 6148 CPU @ 2.40

那请问如何要将FC层替换成CONV的话，配置文件部分应该怎么修改，会影响效果吗？影响有多大？

**Comment by cuicheng01** [comment]
这一层只是占Params，对FLOPs和速度影响不大
