### ISSUE TITLE
快速开始如何启动？

### ISSUE THREAD

**Issue by LiuYuKate** [PaddlePaddle/PaddleClas#2134]
所有配置均按readme配置完成，但是在快速开始的readme中
python3.7 python/predict_system.py -c configs/inference_general.yaml -o Global.use_gpu=False
这段用于开始测试的代码应该在哪里输入？我在vscode的终端输入识别不到python3.7

**Comment by HydrogenSulfate** [comment]
1. 首先保证安装了python3.7，然后记下你pyhton3.7的路径，一般是xxx/xxx/xxx/python.exe
2. 在vscode里按ctrl+shift+p，输入select interpreter，然后选Python Select Interpreter
    ![image](https://user-images.githubusercontent.com/23737287/177679428-e998ddc9-6632-4e5b-92c2-ec0c301853a1.png)
    然后填入第一步你找到的python.exe地址，并按回车
    ![image](https://user-images.githubusercontent.com/23737287/177679460-65fcb602-ce00-4ba0-b940-c1b42cc971d5.png)

3. 此时vscode知道了你python解释器的地址，你就可以在终端右侧，按"+"右边的"v"按钮，新建一个powershell窗口
![image](https://user-images.githubusercontent.com/23737287/177679571-3bd495eb-ca82-4f21-9d71-aa007dcadeba.png)
在新建出来的窗口里执行`python3.7 python/predict_system.py -c configs/inference_general.yaml -o Global.use_gpu=False`，如果显示找不到python3.7，那就执行`python python/predict_system.py -c configs/inference_general.yaml -o Global.use_gpu=False`即可

**Comment by LiuYuKate** [comment]
感谢解答，目前出现了新的问题，faiss库无法导入，这个库是无法运行在windows环境下吗？必须要使用linux环境才能运行？

**Comment by HydrogenSulfate** [comment]
> 感谢解答，目前出现了新的问题，faiss库无法导入，这个库是无法运行在windows环境下吗？必须要使用linux环境才能运行？


可以按文档里说明的删除重装faiss包试试，https://github.com/PaddlePaddle/PaddleClas/blob/release/2.4/docs/zh_CN/quick_start/quick_start_recognition.md#22-%E7%93%B6%E8%A3%85%E9%A5%AE%E6%96%99%E8%AF%86%E5%88%AB%E4%B8%8E%E6%A3%80%E7%B4%A2
