### ISSUE TITLE
多标签分类有一个BUG望修改

### ISSUE THREAD

**Issue by xxddccaa** [PaddlePaddle/PaddleClas#2136]
出错的分支：
我下载的分支是release/2.4
出错的文件：
vim ppcls/data/dataloader/multilabel_dataset.py
此文件中函数def __getitem__(self, idx)里面，`if self.label_ratio is not None` 这句判断是不是存在语法错误，self中不存在label_ratio 这个属性定义。

我临时改成这样在跑：
![](https://raw.githubusercontent.com/xddun/picgo_picture/main/20220706192452.png)

**Comment by cuicheng01** [comment]
这个在develop上修复了，我们会尽快cherrypick到2.4上哈

**Comment by cuicheng01** [comment]
> 这个在develop上修复了，我们会尽快cherrypick到2.4上哈

已cherry-pick

**Comment by xxddccaa** [comment]
谢谢！ 同时也谢谢你们这个greate 开源项目！
