### ISSUE TITLE
文档方向分类程序运行错误

### ISSUE THREAD

**Issue by xu-peng-7** [PaddlePaddle/PaddleClas#2137]
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：
 2. 地址链接：https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/PULC/PULC_text_image_orientation.md
 3. 环境：AIstudio V100 32G
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log
 ：2.3 预测部分->在 Python 代码中预测
代码报错：UnboundLocalError: local variable 'total_width' referenced before assignment

**Comment by weisy11** [comment]
这个问题已经修复了，请拉取最新代码

**Comment by xu-peng-7** [comment]
pip 安装方式的也修复了吗？ 文档里还是pip安装paddleclas

**Comment by cuicheng01** [comment]
> pip 安装方式的也修复了吗？ 文档里还是pip安装paddleclas

pip的方式也修复了哈，可以uninstall后再install试下，会安装最新的paddleclas。

**Comment by xu-peng-7** [comment]
pip3 install paddleclas 安装仍然报一样的错。

**Comment by cuicheng01** [comment]
> pip3 install paddleclas 安装仍然报一样的错。

使用`pip list | grep paddleclas`看下版本号呢？

**Comment by cuicheng01** [comment]
如果使用的是清华源或者第三方源，可能还没有同步更新，可以直接下载pypi源的whl安装，地址：https://files.pythonhosted.org/packages/8a/eb/8e39b624b68fedce86b3f6f41d0c686d4ce44c91f9d19b71caefc5daafff/paddleclas-2.4.2-py3-none-any.whl
