### ISSUE TITLE
paddleservering部署自训练模型失败，如何修改

### ISSUE THREAD

**Issue by charm8686** [PaddlePaddle/PaddleClas#2145]
1. PaddleClas release/2.3和PaddleClas release/2.4都试过。PaddlePaddle 2.2.0和PaddlePaddle 2.2.2和PaddlePaddle 2.3.1都试过
 2. PaddleServing==0.7.0和0.9.0都试过
 3. 训练环境信息：
  a. ubuntu18 paddle推荐docker
  b. Python3.6
  c. CUDA11.2/cuDNN 8.0.0等
 4. 使用百度提供ResNet50_vd预训练模型训练自定义数据集模型，在使用paddle_serving_client.convert转换模型后，按照https://github.com/PaddlePaddle/PaddleClas/tree/release/2.4/deploy/paddleserving文档部署后一直报错。
 5. 报错日志：
 ERROR 2022-07-11 22:18:18,717 [operator.py:979] (data_id=0 log_id=0) [imagenet|0] Failed to process(batch: [0]): 'x'
Traceback (most recent call last):
  File "/home/miniconda3/envs/clas/lib/python3.6/site-packages/paddle_serving_server/pipeline/operator.py", line 966, in _run_process
    feed_batch, typical_logid)
  File "/home/miniconda3/envs/clas/lib/python3.6/site-packages/paddle_serving_server/pipeline/operator.py", line 577, in process
    log_id=typical_logid)
  File "/home/miniconda3/envs/clas/lib/python3.6/site-packages/paddle_serving_app/local_predict.py", line 281, in predict
    if isinstance(feed[name], list):
KeyError: 'x'
ERROR 2022-07-11 22:18:18,718 [operator.py:1024] (log_id=0) imagenet failed to predict.
ERROR 2022-07-11 22:18:18,720 [dag.py:410] (data_id=0 log_id=0) Failed to predict: (log_id=0) imagenet failed to predict.
6. 打印feed为inputs，但是模型输入为'x'，即使改了serving_server_conf.prototxt的name也无用

**Comment by RainFrost1** [comment]
已经更新，具体请查看最新[pr](https://github.com/PaddlePaddle/PaddleClas/pull/1975)

**Comment by HydrogenSulfate** [comment]
可以尝试将[classification_web_service.py](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.4/deploy/paddleserving/classification_web_service.py#L50)的`{"inputs": input_imgs}`改为{"x": input_imgs}，保证你导出的serving_server_conf.prototxt文本里feed_var的name与上述代码中的一致
