### ISSUE TITLE
关于ISE论文中和mixup方法的比较

### ISSUE THREAD

**Issue by gybwyy-art** [PaddlePaddle/PaddleClas#2156]
请问在论文“Our ISE vs. Mixup”部分中，在market-1501上实现mixup时是fully unsupervised吗？是对所有的正负样本都进行随机mixup吗？是在哪一层进行mixup的呢？

**Comment by HydrogenSulfate** [comment]
麻烦@zhangxinyu-xyz 解答一下用户的疑惑

**Comment by zhangxinyu-xyz** [comment]
> 

谢谢您的提问。
1）在market-1501上实现mixup时是fully unsupervised吗？是的。
2）是对所有的正负样本都进行随机mixup吗？我们是对一个batch当中所有的正负样本随机mixup的。
3）是在哪一层进行mixup的呢？我们是在原始图片的pixel上进行mixup的，参考原始mixup原始paper [1] 和code [2]。该方法需要将图片和label都进行mixup，在unsupervised的setting下，label为pseudo label。

[1] Hongyi Zhang, Moustapha Cisse, Yann N Dauphin, and David Lopez-Paz. mixup: Beyond empirical risk minimiza- tion. In Int. Conf. Learn. Represent., 2017.
[2] https://github.com/facebookresearch/mixup-cifar10/blob/eaff31ab397a90fbc0a4aac71fb5311144b3608b/train.py#L119

**Comment by zhangxinyu-xyz** [comment]
> 请问在论文“Our ISE vs. Mixup”部分中，在market-1501上实现mixup时是fully unsupervised吗？是对所有的正负样本都进行随机mixup吗？是在哪一层进行mixup的呢？

谢谢您的提问。
1）在market-1501上实现mixup时是fully unsupervised吗？是的。
2）是对所有的正负样本都进行随机mixup吗？我们是对一个batch当中所有的正负样本随机mixup的。
3）是在哪一层进行mixup的呢？我们是在原始图片的pixel上进行mixup的，参考原始mixup原始paper [1] 和code [2]。该方法需要将图片和label都进行mixup，在unsupervised的setting下，label为pseudo label。

[1] Hongyi Zhang, Moustapha Cisse, Yann N Dauphin, and David Lopez-Paz. mixup: Beyond empirical risk minimiza- tion. In Int. Conf. Learn. Represent., 2017.
[2] https://github.com/facebookresearch/mixup-cifar10/blob/eaff31ab397a90fbc0a4aac71fb5311144b3608b/train.py#L119

**Comment by gybwyy-art** [comment]
“我们是对一个batch当中所有的正负样本随机mixup的”，该怎么理解呢？正负样本不是都存储在memory bank中吗？一个batch中的query需要mixup吗？

**Comment by gybwyy-art** [comment]
> > 请问在论文“Our ISE vs. Mixup”部分中，在market-1501上实现mixup时是fully unsupervised吗？是对所有的正负样本都进行随机mixup吗？是在哪一层进行mixup的呢？
> 
> 谢谢您的提问。 1）在market-1501上实现mixup时是fully unsupervised吗？是的。 2）是对所有的正负样本都进行随机mixup吗？我们是对一个batch当中所有的正负样本随机mixup的。 3）是在哪一层进行mixup的呢？我们是在原始图片的pixel上进行mixup的，参考原始mixup原始paper [1] 和code [2]。该方法需要将图片和label都进行mixup，在unsupervised的setting下，label为pseudo label。
> 
> [1] Hongyi Zhang, Moustapha Cisse, Yann N Dauphin, and David Lopez-Paz. mixup: Beyond empirical risk minimiza- tion. In Int. Conf. Learn. Represent., 2017. [2] https://github.com/facebookresearch/mixup-cifar10/blob/eaff31ab397a90fbc0a4aac71fb5311144b3608b/train.py#L119

“我们是对一个batch当中所有的正负样本随机mixup的”，该怎么理解呢？正负样本不是都存储在memory bank中吗？一个batch中的query需要mixup吗？

**Comment by zhangxinyu-xyz** [comment]
> > > 请问在论文“Our ISE vs. Mixup”部分中，在market-1501上实现mixup时是fully unsupervised吗？是对所有的正负样本都进行随机mixup吗？是在哪一层进行mixup的呢？
> > 
> > 
> > 谢谢您的提问。 1）在market-1501上实现mixup时是fully unsupervised吗？是的。 2）是对所有的正负样本都进行随机mixup吗？我们是对一个batch当中所有的正负样本随机mixup的。 3）是在哪一层进行mixup的呢？我们是在原始图片的pixel上进行mixup的，参考原始mixup原始paper [1] 和code [2]。该方法需要将图片和label都进行mixup，在unsupervised的setting下，label为pseudo label。
> > [1] Hongyi Zhang, Moustapha Cisse, Yann N Dauphin, and David Lopez-Paz. mixup: Beyond empirical risk minimiza- tion. In Int. Conf. Learn. Represent., 2017. [2] https://github.com/facebookresearch/mixup-cifar10/blob/eaff31ab397a90fbc0a4aac71fb5311144b3608b/train.py#L119
> 
> “我们是对一个batch当中所有的正负样本随机mixup的”，该怎么理解呢？正负样本不是都存储在memory bank中吗？一个batch中的query需要mixup吗？

我可能理解错了您的正负样本。
我这里说的是指的一个batch（因为batch里面是采样P个ID，每个ID有K个样本，所以自然而然组成了正负样本对）。
您可以直接理解为：就是一个batch里面的样本做随机的mixup。（跟memory bank没有任何关系）
