### ISSUE TITLE
可复现性

### ISSUE THREAD

**Issue by sandy-ssdut** [PaddlePaddle/PaddleClas#2157]
你好，我想重新finetune pp-shitu 的general_PPLCNet_x2_5_lite_v1.0_infer，但是发现，使用相同的图像时，用deploy/build_gallery.py 里面用推理模型生成的feature 与 用tool/eval.py 用Model 前向生成的feature是不一样的。

请问是哪里出现问题了吗？

**Comment by RainFrost1** [comment]
推理的模型是用pretrained model导出的模型吗？
