### ISSUE TITLE
问题一 - Classification metrics can‘t handle a mix of multiclass-multioutput and binary targets报错

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleClas#2158]
`
自己定义的数据集与分类数有问题

<p><img src="http://ztg.diyyq.com/123/1.jpg" /><br />
    <img src="http://ztg.diyyq.com/123/2.png" /><br />
    <br />
    <img src="http://ztg.diyyq.com/123/3.png" /><br />
  <br />
  <img src="http://ztg.diyyq.com/123/4.png" /><br />
  <br />
  到底是怎么回事报：<br />
  <img src="http://ztg.diyyq.com/123/5.png" /></p>
`

**Comment by cuicheng01** [comment]
数据集list中的分隔符是\t还是空格呢？

**Comment by gg22mm** [comment]
> 数据集list中的分隔符是\t还是空格呢？

是\t 

`
下载：
<p><a href="http://ztg.diyyq.com/test_list.txt">test_list.txt</a></p>
<p><a href="http://ztg.diyyq.com/train_list.txt">train_list.txt</a></p>
`

我只要在:  train_list.txt中删除一条又可以通过，非常奇怪。我现在拿一些数据出来测试，您可以下载试试。 只要删除最后一条就成功。  让人琢磨不透

**Comment by cuicheng01** [comment]
数据麻烦也分享一下吧

**Comment by gg22mm** [comment]
> 数据麻烦也分享一下吧
下载这个吧
[test.rar](http://ztg.diyyq.com/test.rar)

**Comment by cuicheng01** [comment]
里边只有一张图像数据，麻烦把train_list的65张都提供下吧

**Comment by gg22mm** [comment]
> 里边只有一张图像数据，麻烦把train_list的65张都提供下吧

一张图已经能提现出问题来了哦，不用那么多图。你用一张图复制65份都是一样的结果

**Comment by cuicheng01** [comment]
注意到你生成的 list不对，里边应该只含有0和1的标签才对

**Comment by gg22mm** [comment]
> 的标签才对

这样的啊，那这样的话格式就只能是如： 颜色：(是，否) ，尺寸：(是，否)
那如果想做成这样的格式怎么办？如：颜色：(红，蓝，黄...) ，尺寸：(10寸，12寸，15寸)

**Comment by tranngocphuong89** [comment]
> > 的标签才对
> 
> 这样的啊，那这样的话格式就只能是如： 颜色：(是，否) ，尺寸：(是，否) 那如果想做成这样的格式怎么办？如：颜色：(红，蓝，黄...) ，尺寸：(10寸，12寸，15寸)

应该 把各个属性 看成 一个标签吧。
比如： 红（是，否）， 蓝（是，否）， 黄（是，否），  10寸（是，否）， 12寸（是，否）， 15寸（是，否）

**Comment by gg22mm** [comment]
> 红（是，否）

对这样可以，糊涂了~~

**Comment by gg22mm** [comment]
> 注意到你生成的 list不对，里边应该只含有0和1的标签才对
但是报错：Classification metrics can‘t handle a mix of multiclass-multioutput and binary targets  不是这个问题，我把所有的2和3都替换成0还是这个错

**Comment by cuicheng01** [comment]
我这边不能复现你的问题，我替换后完全正常了。麻烦check下是否全都替换

**Comment by gg22mm** [comment]
> 我这边不能复现你的问题，我替换后完全正常了。麻烦check下是否全都替换

好的，我现在重新生成的.txt可以了。  多谢~~
