### ISSUE TITLE
paddle2onnx转主体检测模型onnx中出现"Constant"这个额外输入怎么处理

### ISSUE THREAD

**Issue by lovegit2021** [PaddlePaddle/PaddleClas#2160]
我使用paddle2onnx转主体检测模型ppyolov2_r50vd_dcn_mainbody_v1.0_infer时候出现onnx中有一个“Constant”的输入，要怎么处理掉啊

**Comment by HydrogenSulfate** [comment]
这个问题可以在PaddleDetection代码库中提问，https://github.com/PaddlePaddle/PaddleDetection/issues
