### ISSUE TITLE
在单分类任务中，如果处理包含多个类别的图片

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleClas#2164]
使用PaddleClas做的单分类任务，有一批数据包含了多个类别，这种情况如何处理？
如果删除就很可惜。
使用多分类任务，整体的准确率就不高。
因为是重叠的，无法使用目标检测分开。
这种情况有什么好的处理办法吗？

**Comment by cuicheng01** [comment]
建议还是使用多分类去做，您说的整体准确率不高是会低很多吗？

**Comment by yeyupiaoling** [comment]
>您说的整体准确率不高是会低很多吗？

主要是泛化能力太差。

我现在的做法是用单分类直接识别，混合的作为一类，然后有多分类模型在对识别为混合这一类别进行识别。

**Comment by tranngocphuong89** [comment]
@yeyupiaoling  你的 应该属于 多标签分类模型吧，
请参考以下链接，可能对你有用

https://aistudio.baidu.com/aistudio/projectdetail/4247343?channelType=0&channel=0

**Comment by yeyupiaoling** [comment]
@tranngocphuong89 我现在做法是：目标检测->单分类->多分类
