### ISSUE TITLE
missing file configs/build_product.yaml

### ISSUE THREAD

**Issue by PhanAnh1001** [PaddlePaddle/PaddleClas#2166]
Any one downloaded the file configs/build_product.yaml, please create a url download for me.
Thank you very much!

Error from this document:
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.4/docs/en/quick_start/quick_start_recognition_en.md#21-download-and-unzip-the-inference-model-and-demo-data

Step:
python python/build_gallery.py -c configs/build_product.yaml -o Global.rec_inference_model_dir=./models/general_PPLCNet_x2_5_lite_v1.0_infer

Error:
Traceback (most recent call last):
  File "python/build_gallery.py", line 213, in <module>
    config = config.get_config(args.config, overrides=args.override, show=True)
  File "/home/anhtp/PycharmProjects/pythonProject/PaddleClas/deploy/utils/config.py", line 164, in get_config
    'config file({}) is not exist'.format(fname))
AssertionError: config file(configs/build_product.yaml) is not exist

**Comment by HydrogenSulfate** [comment]
did you mean this file? https://github.com/PaddlePaddle/PaddleClas/blob/bcc86834ec44ad02e0cab6747e912638e6cad62e/deploy/configs/build_product.yaml
