### ISSUE TITLE
图片分类模型加载inference模型时报错

### ISSUE THREAD

**Issue by KyleWang-Hunter** [PaddlePaddle/PaddleClas#2169]
环境信息：
  a. Linux
  b. Python3.6
  c.  CUDA10.2/cuDNN 7.6.5
报错信息：
InvalidArgumentError: The inverse of Fused batch norm variance should be finite. Found nonfinite values! Please check batch_norm_6.w_2
[Hint: Expected std::isfinite(variance_array[i]) == true, but received std::isfinite(variance_array[i]):0 != true:1.] (at /paddle/paddle/fluid/framework/ir/conv_bn_fuse_pass.cc:101)

**Comment by weisy11** [comment]
请问是加载哪个模型时报错呢？可以提供下paddle和PaddleClas的版本号吗？

**Comment by Zenmaster188** [comment]
当我转换为检测模型时，我得到了同样的错误,  , 我使用最新的桨克隆
, 2022.5.9 Release PaddleOCR [release/2.5](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.5), 我该怎么办，这是我的错误
PaddleOCR/tools/infer/utility.py", line 317, in create_predictor
    predictor = inference.create_predictor(config)
ValueError: (InvalidArgument) The inverse of Fused batch norm variance should be finite. Found nonfinite values! Please check batch_norm_55.w_2 
  [Hint: Expected std::isfinite(variance_array[i]) == true, but received std::isfinite(variance_array[i]):0 != true:1.] (at /paddle/paddle/fluid/framework/ir/conv_bn_fuse_pass.cc:105)

**Comment by weisy11** [comment]
你好，OCR的问题请在PaddleOCR的repo下提问
