### ISSUE TITLE
模型评估时map的使用

### ISSUE THREAD

**Issue by fan-min-97** [PaddlePaddle/PaddleClas#2170]
在paddleClas中的PaddleClas/ppcls/configs/quick_start/professional/MobileNetV1_multilabel.yaml ：

Metric:
Train:
- HammingDistance:
- AccuracyScore:
Eval:
- HammingDistance:
- AccuracyScore:
- mAP: {}

在最后添加map:{}这行时，训练验证部分会报错
TypeError: forward() missing 2 required positional arguments: 'gallery_img_id' and 'keep_mask'
，如果想查看map该怎么写呢

**Comment by cuicheng01** [comment]
这个mAP指标是特指metric learning的指标，多标签目前不支持mAP的评价指标，后续我们会支持的，敬请期待。

**Comment by tranngocphuong89** [comment]
我也期待 ~~~
