### ISSUE TITLE
paddle-shitu训练集下载

### ISSUE THREAD

**Issue by tingyuyan** [PaddlePaddle/PaddleClas#2172]
请问paddleClas里的paddle-shitu中的提到的Aliproduct，GLDv2，VeRI-Wild，LogoDet-3K，iCartoonFace，SOP，Inshop 7个数据集，其中有的链接已经下载不到了，可以提供一份训练集下载地址吗，谢谢。

**Comment by weisy11** [comment]
抱歉，版权所限，我们无法直接提供第三方的数据集。
