### ISSUE TITLE
按照官方文档实现图像分类服务部署出错，

### ISSUE THREAD

**Issue by Lanqingsong** [PaddlePaddle/PaddleClas#2173]
部署环境：docker,PaddleClas release/2.4,. PaddleServing0.7
问题：在启动客户端程序test_cpp_serving_clien.py 后出现如下报错： TypeError: numpy_predict(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle_serving_client.serving_client.PredictorClient, arg0: List[numpy.ndarray[float32]], arg1: List[str],
    2. 
![图片](https://user-images.githubusercontent.com/31660684/181742919-43757eb7-448f-4b5d-9a13-99930a5046e6.png)

**Comment by RainFrost1** [comment]
@HydrogenSulfate 看一下

**Comment by HydrogenSulfate** [comment]
模型部署这块尤其是C++部署，文档和代码都更新过，建议使用develop分支的文档和代码进行部署，C++部署的速度会更快

**Comment by HydrogenSulfate** [comment]
用户你好，目前已经把develop分支的serving文档与代码同步到了release/2.4分支中，可以用2.4分支或者develop分支再次尝试看看。对应PR是https://github.com/PaddlePaddle/PaddleClas/pull/2204
