### ISSUE TITLE
下载预训练模型

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleClas#2178]
请问一下，
![image](https://user-images.githubusercontent.com/87969070/182106910-eca80a29-c1d4-48c7-b0dc-016abfb7fcc1.png)
该配置文件中的预训练模型哪有呢？

**Comment by TingquanGao** [comment]
是这个配置文件对应的预训练模型吗？可以在这个页面找到：https://github.com/paddlepaddle/paddleclas/blob/release%2F2.4/docs/zh_CN/algorithm_introduction/ImageNet_models.md

预训练模型下载链接：
https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/Res2Net200_vd_26w_4s_pretrained.pdparams

ssld蒸馏的预训练模型下载链接：
https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/Res2Net200_vd_26w_4s_ssld_pretrained.pdparams
