### ISSUE TITLE
release/2.2特征学习部分特征图

### ISSUE THREAD

**Issue by lazyn1997** [PaddlePaddle/PaddleClas#2182]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本：PaddleClas release/2.2

![image](https://user-images.githubusercontent.com/34644177/182406716-48a598a6-b29b-408f-822c-f18968713708.png)
如图所示，请问VehicleNeck执行Flatten()操作后输出向量尺寸是[bs, 512*14*14]吗？

**Comment by cuicheng01** [comment]
您好，这里的shape应该是[bs, 512]

**Comment by lazyn1997** [comment]
为什么呢，VehicleNeck部分不就是一个卷积加一个flatten吗，卷积得到的shape是[bs, 512, 14, 14]，那Flatten()操作后不就应该是[b2, 512\*14\*14]吗？
![image](https://user-images.githubusercontent.com/34644177/182555163-16b95935-2e11-4cd5-b745-f4de6d8a4a72.png)
