### ISSUE TITLE
docker: failed to register layer: open /eddata/overlay2/2a3cadb118906de3d274d7fcaf6f8c1473e3c52d8d0576330ba7fc42e68d1983/committed: no such file or directory. 

### ISSUE THREAD

**Issue by xiaomujiang** [PaddlePaddle/PaddleClas#2184]
ubuntu18.04  python3.7   CUDA10.2/cuDNN 7.6.5 PaddlePaddle
按照教程安装docker版本的paddleclas 提示错误docker: failed to register layer: open /eddata/overlay2/2a3cadb118906de3d274d7fcaf6f8c1473e3c52d8d0576330ba7fc42e68d1983/committed: no such file or directory.

**Comment by RainFrost1** [comment]
应该是docker环境问题，检索使用Paddle官方[docker镜像](https://www.paddlepaddle.org.cn/)

**Comment by cuicheng01** [comment]
> ubuntu18.04 python3.7 CUDA10.2/cuDNN 7.6.5 PaddlePaddle 按照教程安装docker版本的paddleclas 提示错误docker: failed to register layer: open /eddata/overlay2/2a3cadb118906de3d274d7fcaf6f8c1473e3c52d8d0576330ba7fc42e68d1983/committed: no such file or directory.

请问你拉取的是哪个docker呢，地址可以发一下吗？

**Comment by xiaomujiang** [comment]
> > ubuntu18.04 python3.7 CUDA10.2/cuDNN 7.6.5 PaddlePaddle 按照教程安装docker版本的paddleclas 提示错误docker: failed to register layer: open /eddata/overlay2/2a3cadb118906de3d274d7fcaf6f8c1473e3c52d8d0576330ba7fc42e68d1983/committed: no such file or directory.
> 
> 请问你拉取的是哪个docker呢，地址可以发一下吗？
官网文档中的
sudo nvidia-docker run --name ppcls -v $PWD:/paddle --shm-size=8G --network=host -it registry.baidubce.com/paddlepaddle/paddle:2.3.0-gpu-cuda10.2-cudnn7 /bin/bash

**Comment by cuicheng01** [comment]
加代理试一下吧~
