### ISSUE TITLE
无法找到相应文件

### ISSUE THREAD

**Issue by hice1207** [PaddlePaddle/PaddleClas#2185]
PaddleClas release/2.4和PaddlePaddle 2.3.1
Linux
 如Python3.7
CUDA10.2/cuDNN 7.6.5
 
PULC快速体验时
paddleclas --model_name=person_exists --infer_imgs=pulc_demo_imgs/person_exists/objects365_01780782.jpg
发生找不到图片问题，在训练测试数据集flower102时也发生找不到所在数据集文件

**Comment by RainFrost1** [comment]
@cuicheng01 麻烦看一下

**Comment by hice1207** [comment]
> @cuicheng01 麻烦看一下

已解决，某些环境包没有安装，建议你们在环境配置那里写的详细一点，部分包是在另外一个文档看到需要安装。

**Comment by cuicheng01** [comment]
> 已解决，某些环境包没有安装，建议你们在环境配置那里写的详细一点，部分包是在另外一个文档看到需要安装。

麻烦问下是哪些包没有安装呢？

**Comment by hice1207** [comment]
> > 已解决，某些环境包没有安装，建议你们在环境配置那里写的详细一点，部分包是在另外一个文档看到需要安装。
> 
> 麻烦问下是哪些包没有安装呢？

记得有个visualdl，还有个P开头的，另外有几个包版本跟我原来环境冲突需要手动安装。

**Comment by TingquanGao** [comment]
你好，我这边只安装了paddleclas和paddlepaddle：`pip install paddleclas paddlepaddle`，并且准备好数据后，运行命令：`paddleclas --model_name=person_exists --infer_imgs=pulc_demo_imgs/person_exists/objects365_01780782.jpg` 是没问题的。可以再详细说一下问题的复现步骤吗？我们再排查一下。

**Comment by hice1207** [comment]
> 你好，我这边只安装了paddleclas和paddlepaddle：`pip install paddleclas paddlepaddle`，并且准备好数据后，运行命令：`paddleclas --model_name=person_exists --infer_imgs=pulc_demo_imgs/person_exists/objects365_01780782.jpg` 是没问题的。可以再详细说一下问题的复现步骤吗？我们再排查一下。

实在不好意思，因为是一个月之前的问题了，而且当时就解决了这个问题，如果没有记错就是缺少几个环境包，另外跟我之前安装的paddleocr的几个包版本有冲突，因为当时建环境直接在之前的ocr环境基础上进行的。不是什么大问题，当时看问题区也就我一个人有这个问题，很抱歉没法向您提供当时的问题源码了。

**Comment by TingquanGao** [comment]
好的，后续使用中有任何问题都可以再反馈，我们也会持续优化使用体验。感谢~
