### ISSUE TITLE
paddle_serving僵尸进程，请问我显卡资源占了75%的时候，开启的这个paddleClas识别服务还是会变成僵尸进程defunct。到底是什么原因造成服务进程defunct的了？

### ISSUE THREAD

**Issue by chen960217** [PaddlePaddle/PaddleClas#2190]
请问我显卡资源占了75%的时候，开启的这个paddleClas识别服务还是会变成这样。到底是什么原因造成服务进程defunct的了？具体进程状态如下图

**Comment by chen960217** [comment]
![a9f33f45e0c982b53645486fb3bda5c](https://user-images.githubusercontent.com/78129986/183277307-aefb7faa-0fdf-4a8f-845d-71a6ea41c60e.jpg)

**Comment by TingquanGao** [comment]
可以具体说一下进行了什么操作吗？启动命令是什么，启动后做了什么呢？

**Comment by chen960217** [comment]
> 可以具体说一下进行了什么操作吗？启动命令是什么，启动后做了什么呢？

我使用了paddleClas的图像识别功能，启动了图像识别的服务，python3 logo2_recognition_web_service.py &>log.txt &，这是启动命令，图像识别的启动服务脚本名我改了的。然后显卡资源占到大概70%的时候，这些服务的进程就会变为defunct，如上图。请问造成这种僵尸进程的具体原因是什么了？

**Comment by chen960217** [comment]
> 可以具体说一下进行了什么操作吗？启动命令是什么，启动后做了什么呢？

启动服务后进行了很多张图片的图像识别，服务进程变为defunct后，服务就是用不了了。没有返回值，我查看日志pipeline_log,也没有提示说错误，就是服务无法运行了。日志如下
![image](https://user-images.githubusercontent.com/78129986/183352668-e06def3e-113c-453d-8dcb-209a2676b828.png)

**Comment by TingquanGao** [comment]
收到，我先自己试一下哈。

**Comment by chen960217** [comment]
> 收到，我先自己试一下哈。

好的，麻烦了哈。目前遇到这个问题解决不了，不知道是什么原因。

**Comment by TingquanGao** [comment]
你一直说显存占用，是会随着请求的不断增加，显存占用也不断增加吗？每次请求处理完成后，显存是否有释放呢？

**Comment by chen960217** [comment]
> 你一直说显存占用，是会随着请求的不断增加，显存占用也不断增加吗？每次请求处理完成后，显存是否有释放呢？

不会一直增加，启动的服务并发数没变，我就正常识别图片（数量挺多），只发出一个请求，显存没增加，差不多是稳定的。我之所以说显存的情况，是因为我一开始是以为由于显存占用的比例太大导致的。现在就不知道什么会导致这个服务变成defunct

**Comment by chen960217** [comment]
> 你一直说显存占用，是会随着请求的不断增加，显存占用也不断增加吗？每次请求处理完成后，显存是否有释放呢？

您好，请问你这边找到原因了么？

**Comment by TingquanGao** [comment]
我没有复现这个问题。是否修改了代码或者配置文件呢？如果是直接使用PaddleClas提供的代码和配置文件，是否有问题呢？

**Comment by chen960217** [comment]
> 使用PaddleClas提供的代码
paddleclas的recognition服务的配置文件我只修改了检测和识别模型，其余参数均为修改，代码也没有修改

**Comment by TingquanGao** [comment]
可以使用PaddleClas提供的模型试试么？看看是否还会出现该问题。以及一般是需要发送多少次请求会出现该问题呢？

**Comment by chen960217** [comment]
> 可以使用PaddleClas提供的模型试试么？看看是否还会出现该问题。以及一般是需要发送多少次请求会出现该问题呢？

使用PaddleClas提供的模型也会。有时候可能也会出现。就是启动服务的并发数上限是多少了？

**Comment by TingquanGao** [comment]
参数concurrency设置了并发数的上限，如果是0表示不设置上限。另外，是否有注意cpu利用率和内容的占用情况呢？

**Comment by chen960217** [comment]
> 参数concurrency设置了并发数的上限，如果是0表示不设置上限。另外，是否有注意cpu利用率和内容的占用情况呢？

concurrency我没有改，一直是1，cpu很充足。

**Comment by HydrogenSulfate** [comment]
> > 参数concurrency设置了并发数的上限，如果是0表示不设置上限。另外，是否有注意cpu利用率和内容的占用情况呢？
> 
> concurrency我没有改，一直是1，cpu很充足。

建议是暂时保持低并发量设置，并保证serving启动后显存的占用率不要过高，如果仍然无法解决，可以在Serving的repo中提一个issue：https://github.com/PaddlePaddle/Serving/issues
并附上具体的预测配置，后续有进展的话会第一时间回复
