### ISSUE TITLE
用来判断图片模糊 或 清晰 没有效果

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleClas#2191]
用的数据集：https://aistudio.baidu.com/aistudio/projectdetail/535801?channelType=0&channel=0
![1](https://user-images.githubusercontent.com/6648329/183321865-00763ad3-c43b-4d33-847d-4c643d6a2926.png)
![2](https://user-images.githubusercontent.com/6648329/183321873-eaf27e26-3cb9-4259-bcfd-a1ce51e694f8.png)
![3](https://user-images.githubusercontent.com/6648329/183321876-34a86b70-71db-4892-8cf2-6e6fc7416223.png)

![或是老是识别某个分类](https://user-images.githubusercontent.com/6648329/183329743-fe343540-0e3d-4aef-84f5-a1584a851618.png)

老是识别某个分类，分不清楚是清晰 或 模糊，  都显示是 [{'class_ids': [0], 'scores': [0.8815], 'file_name': './images/mohu/img/qingXi.jpg', 'label_names': []}]

**Comment by weisy11** [comment]
请问你用的是哪个模型呢？

**Comment by gg22mm** [comment]
> 请问你用的是哪个模型呢？

您好：用的是MobileNetV1_multilabel.yaml 我这个用来做二分类，有问题是吧，那我应该用：MobileNetV3_large_x1_0.yaml 是吧

./ppcls/configs/quick_start/professional/MobileNetV1_multilabel.yaml

**Comment by weisy11** [comment]
看了下，这应该不是个多标签分类的任务吧？只是要判断模糊/清晰的二分类吗？

**Comment by gg22mm** [comment]
> 看了下，这应该不是个多标签分类的任务吧？只是要判断模糊/清晰的二分类吗？

是的，那我应该用的是：MobileNetV3_large_x1_0.yaml 是吧

**Comment by gg22mm** [comment]
非常感谢 “崔先生”大老 指导： https://github.com/PaddlePaddle/PaddleClas/blob/release/2.4/docs/zh_CN/PULC/PULC_person_exists.md
  原来是我把二分类问题用多分类的用，  现在改用：./ppcls/configs/PULC/person_exists/PPLCNet_x1_0.yaml 达到理想的效果。非常感谢
