### ISSUE TITLE
还有为什么导出模型没有deploy.yaml

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleClas#2192]
python tools/export_model.py -c ./ppcls/configs/quick_start/professional/MobileNetV1_multilabel_st.yaml -o Global.pretrained_model=./weight/best_model_tongue -o Global.save_inference_dir=./inference_model

还有为什么导出模型没有：deploy.yaml

![5](https://user-images.githubusercontent.com/6648329/183331524-1fdc75b4-c8ad-45ca-bab6-f51ea36a771b.png)

**Comment by weisy11** [comment]
请问用官方原始代码和配置导出有yaml文件吗？如果原版代码没问题，可以比较一下，检查自己的代码缺少了什么

**Comment by gg22mm** [comment]
> 

您好，图片分类导出都是没有的，只能用：/deploy/configs/下面对应的，导出没有，但不影响使用

**Comment by weisy11** [comment]
你好，看了你的几个issue，建议再仔细阅读一下文档哈

**Comment by gg22mm** [comment]
> 

嗯嗯，二分类已经解决了，  非常感谢~~！ 我再过一遍，没有问题我就一个一个的关闭了  ~~
