### ISSUE TITLE
如何合并生成的log文件

### ISSUE THREAD

**Issue by Hxd8991** [PaddlePaddle/PaddleClas#2195]
由于我的模型是断点训练，所有每次重新加载模型的时候会重新生成log日志，在使用use_visualdl: True时候，如何将多个log合并起来。我在官方文档中没有看到如果合并log文件。

**Comment by RainFrost1** [comment]
这部分功能是暂时没有的，目前只能手动或者写个脚本，按照训练epoch的训练顺序，将log合并
