### ISSUE TITLE
UnboundLocalError: local variable 'fp' referenced before assignment

### ISSUE THREAD

**Issue by sweetboxwwy** [PaddlePaddle/PaddleClas#2206]
安全帽识别代码报错：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.4/docs/zh_CN/PULC/PULC_safety_helmet.md

换了一个数据集就会报以上错误

原因是PaddleClas\ppcls\metric\metrics.py第201行fpr在赋值前被引用，换了个数据集就会报这个错误呢。不换数据集不会报这个错误，是因为代码没有考虑到数据量小于10000的情况嘛

            if len(gt_neg_score_list) == 0 and tpr > max_tpr:
                max_tpr = tpr
                result = "threshold: {}, fpr: {}, tpr: {:.5f}".format(
                    threshold, fpr, tpr)
            fpr = np.sum(
                gt_neg_score_list > threshold) / len(gt_neg_score_list)

**Comment by RainFrost1** [comment]
@cuicheng01 麻烦看一下哈

**Comment by cuicheng01** [comment]
您好，抱歉刚看到问题，麻烦可以提供以下可以复现的数据集吗？我这边复现以下。
