### ISSUE TITLE
有没有替换backbone的详细指导？比如我在训练通用识别模型的时候

### ISSUE THREAD

**Issue by alexHxun** [PaddlePaddle/PaddleClas#2208]
用的GeneralRecognition_PPLCNet_x2_5.yaml ，想把backbone替换成efficientnetB3，支不支持？如何改？

我改了一下，报错：
 EfficientNet object has no attribute "stop_after"

**Comment by RainFrost1** [comment]
可以参考一下这个[文档](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.4/docs/zh_CN/advanced_tutorials/theseus_layer.md)。目前灵活的修改backbone主要是`theseus_layer`的功能实现，而只有[legendary_models](https://github.com/PaddlePaddle/PaddleClas/tree/release/2.4/ppcls/arch/backbone/legendary_models)下的模型，才支持`theseus_layer`，其他的模型都暂时不支持的
