### ISSUE TITLE
模型获取

### ISSUE THREAD

**Issue by j2538318409** [PaddlePaddle/PaddleClas#221]
请问 有通用的模型可以获取吗 Inception-v4的 我主要用于获取图像的特征向量用于计算余玄相似度

**Comment by littletomatodonkey** [comment]
您好，目前PaddleClas中大部分模型是基于ImageNet1k数据集训练得到的1000分类模型，我们所有预训练模型都在这里：https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/zh_CN/models/models_intro.md
我们也开源了10W类的预训练模型（基于ResNet50vd，fc层参数没有开源），您也可以基于这个预训练模型提取fc层前面的2048维特征，下载地址在这里：https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_10w_pretrained.tar

**Comment by wqz960** [comment]
inception-v4 模型：https://paddle-imagenet-models-name.bj.bcebos.com/InceptionV4_pretrained.tar

**Comment by j2538318409** [comment]
@wqz960 感谢

**Comment by j2538318409** [comment]
@littletomatodonkey 有具体的操作文档吗 我看readme上写的东西不是操作的东西

**Comment by wqz960** [comment]
@j2538318409 什么操作，加载模型还是跑inference?

**Comment by chinesejunzai12** [comment]
> 您好，目前PaddleClas中大部分模型是基于ImageNet1k数据集训练得到的1000分类模型，我们所有预训练模型都在这里：https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/zh_CN/models/models_intro.md 我们也开源了10W类的预训练模型（基于ResNet50vd，fc层参数没有开源），您也可以基于这个预训练模型提取fc层前面的2048维特征，下载地址在这里：https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_10w_pretrained.tar

有这个模型的使用文档么? @wqz960
