### ISSUE TITLE
多标签图像分类训练，预测结果没有label_name

### ISSUE THREAD

**Issue by phoenixliu666** [PaddlePaddle/PaddleClas#2210]
1. PaddleClas版本：PaddleClas release/2.4
 2. 文件是：/PaddleClas/blob/release/2.4/deploy/python/postprocess.py
 3. 
![image](https://user-images.githubusercontent.com/111444479/185170539-5553ade1-6e04-4f7e-b254-5fc364b6c9cb.png)
继承父类的初始化函数时没有传参topk、class_id_map_file到父类初始化函数，导致模型预测结果没有获取到映射文件的label_name(s)

**Comment by cuicheng01** [comment]
您好，多标签的结果的class_id_map_file这里我们之后会考虑找一个更权威的多标签数据集（如COCO）去做新功能的增加，当前的demo数据集暂时不支持class_id_map_file。

**Comment by phoenixliu666** [comment]
好的，感谢你们的付出！

**Comment by cuicheng01** [comment]
您好，代码已支持该功能，详情：https://github.com/PaddlePaddle/PaddleClas/pull/2219
