### ISSUE TITLE
多标签图像分类，topk参数设置不为1，预测结果仍是只有1个预测值

### ISSUE THREAD

**Issue by phoenixliu666** [PaddlePaddle/PaddleClas#2211]
1. PaddleClas版本：PaddleClas release/2.4
 2. ![image](https://user-images.githubusercontent.com/111444479/185180145-1316188b-8815-4f39-8cd6-91cc7bba8c9f.png)
 继承父类的__call__方法，传入的multilabel参数为True会导致代码跳到else语句，结果也就是topk参数设置>1无效
![image](https://user-images.githubusercontent.com/111444479/185180596-aa1051f4-02a2-4a0f-904c-467b77fd3dd0.png)

**Comment by cuicheng01** [comment]
hi，您好，多标签分类不应该有top-k这个约束，应该用阈值来卡结果，默认是0.5，你也可以尝试其他阈值，详情改动请见：https://github.com/PaddlePaddle/PaddleClas/pull/2219
