### ISSUE TITLE
训练模型时gpu无法被识别

### ISSUE THREAD

**Issue by JHQY** [PaddlePaddle/PaddleClas#2222]
_目前使用的是：paddlepaddle-gpu 2.1.3 和最新版本的paddleclas,
windows系统，显卡配有集显和3060
python 3.7 cuda11.6 cudnn 8.4.1_

在使用train训练模型时，出现gpu少于4的提示，调整batch等训练参数后仍然出现内存不足无法继续训练的情况。后发现训练过程中并没有调用gpu。
指定gpu=“1”后提示gpu范围只有[0,1)，无法识别全显卡。
求解！感谢！

**Comment by weisy11** [comment]
1.请检查Paddle官网的安装说明，确保安装的是正确的版本
2.消费级的显卡有可能不支持，我们没有验证过3060这个型号。
3.如果本地的卡不方便，推荐使用aistudio https://aistudio.baidu.com/aistudio/index
