### ISSUE TITLE
如何修改PULC训练配置文件

### ISSUE THREAD

**Issue by ANDROIDTODO** [PaddlePaddle/PaddleClas#2223]
Hi PaddleClas Team,
我这边使用PULC进行分类，我图片的长度高度一般固定在35，但是宽度是不一定的，那训练和评估配置文件中ResizeImg应该怎么填写会比较好？ 我在使用原始的160,80效果不太理想

**Comment by cuicheng01** [comment]
hi，图片尺寸如果特别小的话，可以将stride_list=[2, 2, 2, 2, 2]，改为[2, 2, 2, 2, 1]，可以直接在yaml中修改。另外，宽度不固定的话一般有多少呢？

**Comment by ANDROIDTODO** [comment]
@cuicheng01 
hi, 我这边宽度可能在100到1000之间。

**Comment by cuicheng01** [comment]
好的，那建议您写一个动态shape采样的机制，把长边相似的resize后组合成一个batch训练。或者也可以找一个中间值比如长边resize到300训练。
