### ISSUE TITLE
请问主体检测的轻量模型配置文件在哪？

### ISSUE THREAD

**Issue by BackT0TheFuture** [PaddlePaddle/PaddleClas#2230]
[picodet_PPLCNet_x2_5_mainbody_lite_v1.0_pretrained.pdparams](https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/rec/models/pretrain/picodet_PPLCNet_x2_5_mainbody_lite_v1.0_pretrained.pdparams)
如题，导出onnx时要用，但在repo下没找到。
谢谢！

**Comment by HydrogenSulfate** [comment]
PP-picodet是PaddleDetection的工作，放在这里https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/picodet/legacy_model/application/mainbody_detection/README.md

**Comment by BackT0TheFuture** [comment]
谢谢
