### ISSUE TITLE
请问作者如何在eval的时候生成precisions, recalls, fscores值

### ISSUE THREAD

**Issue by Hxd8991** [PaddlePaddle/PaddleClas#2235]
作者您好，请问在evaluate的时候如何生成precisions, recalls, fscores值，我在metrics.py中看到def precision_recall_fscore(output, target):函数，想请问作者如何添加在网络中，输出这些值（precisions, recalls, fscores）

**Comment by cuicheng01** [comment]
您好，具体是训练什么任务的需求呢？

**Comment by Hxd8991** [comment]
感谢您的回复，我的训练任务是5分类的任务，由于输出日志中只含有loss，精度，top1-top5等，但是我需要precisions, recalls, fscores这三个值，请问如何输出这些值？再次感谢您的帮助。

**Comment by cuicheng01** [comment]
五分类的话你是怎么定义precision和recall这些值呢？
