### ISSUE TITLE
按照教程来的，前向的时候就出错了

### ISSUE THREAD

**Issue by sssssshf** [PaddlePaddle/PaddleClas#2237]
File "/media/shf/shf_moredian/Moredian/code/vedio_demo/paddleclas.py", line 31, in <module>
    from .ppcls.arch import backbone
ImportError: attempted relative import with no known parent package

**Comment by TingquanGao** [comment]
是哪个教程呢？可以详细说一下复现步骤么？

**Comment by sssssshf** [comment]
> 是哪个教程呢？可以详细说一下复现步骤么？
额　已经解决了．．谢谢

**Comment by TingquanGao** [comment]
好的，那我就把issue关掉了。如果使用过程中，感觉文档描述不清楚，或者功能设置不合理，也可以提出建议，我们会持续优化PaddleClas的使用体验。谢谢~

**Comment by sssssshf** [comment]
> 好的，那文档我关了。如果使用过程中，我们接受描述，或者功能设置不使用的，可以建议建议会持续优化PaddleClas体验。谢谢~
语言模型转为onnx之后，验证输入到onn的分类与paddle送入网络前的分类一致，为什么两个推理结果图会
一致
。 “得分”：[0.90685，0.01525]，'label_names'：['abaric'，'japan']，'fileName'：'pulc_demo_imgs/landaging_classification/word_20.png'
} 0.00880358]]　
这是我转ｏｎｎｘ跑出来的结果：
outputs
0.8517078 0.00980616 0.01587173 0.01225313 0.04719041 0.01292864 0.01291773 0.01338265 0.01218982 0.01175191
虽然分类结果是对的 但是这个置信度值怎么会有这么大偏差．
还有ｏｎｎｘ的推理结果该怎么解析　有对应的文档说明吗

**Comment by zhanghangzzz** [comment]
请问这个问题你是怎样解决的
