### ISSUE TITLE
主体检测推理代码存在bug

### ISSUE THREAD

**Issue by Zhao-Yian** [PaddlePaddle/PaddleClas#2239]
代码位置：PaddleClas/deploy/python/predict_system.py 94-98行：
`
        # st1: get all detection results
        results = self.det_predictor.predict(img)

        # st2: add the whole image for recognition to improve recall
        results = self.append_self(results, img.shape)
`
这里，首先将主体检测的检测结果放入results，然后为了提高精度，又添加了一张整图的shape。这样理论上没有问题，如果主体检测推理的bbox都不合适的话，整张图像送入特征提取模型一定会得到一个比较好的结果，因为索引库的编码都是整图编码。但是经过多次实验发现，主体检测大多数情况下性能都不错，这样的话检测到效果最好的图像主体分数一般接近1，但是整图的分数会更高，之后nms会将最好的bbox过滤掉，最后输出的可视化结果如下图所示：

![image](https://user-images.githubusercontent.com/77494834/187343304-8ba1ce0b-d729-4965-bc58-49496c3c2488.png)

删除 
 `# st2: add the whole image for recognition to improve recall
  results = self.append_self(results, img.shape)`
之后，可视化结果如下图所示：

![image](https://user-images.githubusercontent.com/77494834/187343357-f44b1296-4c37-4380-a669-f729f0b012f1.png)

这种做法其实导致的问题就是主体检测最好的那个bbox很多时候会被丢弃，改进策略如下：

**一开始的results里面不要添加整图，当对所有的bbox都进行了一遍特征提取和比对之后，如果最好的score没有超过阈值，再使用整图做一次特征提取，这样只有主体检测模型真正没有检测到的时候才会输出一个整图的预测框，这样可以最大限度的利用好主体检测模型的推理结果。**

**Comment by HydrogenSulfate** [comment]
感谢你的建议，由于涉及改动较多，在后续版本更新会加入这个优化意见
