### ISSUE TITLE
pat100k 标签不对

### ISSUE THREAD

**Issue by sssssshf** [PaddlePaddle/PaddleClas#2241]
为什么百度盘的人体属性标签是不对的?
我检查每一张图去核验标签 大概几十张图标签全部是错的是为啥? 还能用于训练?

**Comment by sssssshf** [comment]
另外如何利用pplcnet训练一个超轻量化网络呢.配置文件如何修改?

**Comment by cuicheng01** [comment]
您好，可以可视化一些错误的图吗？

**Comment by sssssshf** [comment]
> 你好，可以找出一些错误的图吗？
例如这张，我查阅资料说这个ｐａｔ１００ｋ标签确实存在很多不对的．只能通过训练的一些策略解决．
![image](https://user-images.githubusercontent.com/68574922/187616999-8d82b0f6-22d4-45b6-91d1-be50be1b43f5.png)

您可以告诉我第二个问题　ｐｐｌｃｎｅｔ如何修改网络参数吗　例如ｍｏｂｉｌｅｎｅｔｖ系列一样修改ｂｌｏｃｋ数量　通道数　这样去降低网络ｆｌｏｐｓ

**Comment by TingquanGao** [comment]
修改blocks和通道数的话，需要改组网代码：ppcls/arch/backbone/legendary_models/pp_lcnet.py

修改通道数比较简单，直接参考组网代码中的`PPLCNet_x1_0`等的实现，修改`scale`即可：
https://github.com/PaddlePaddle/PaddleClas/blob/20c4c45d75ac573838b149da8dfc48b49f6eeb65/ppcls/arch/backbone/legendary_models/pp_lcnet.py#L408-L421

修改`blocks`的话，可以改这里：
https://github.com/PaddlePaddle/PaddleClas/blob/20c4c45d75ac573838b149da8dfc48b49f6eeb65/ppcls/arch/backbone/legendary_models/pp_lcnet.py#L59-L69
