### ISSUE TITLE
看到test_cpp_serving_client.py里有一句大约没有用的话

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/PaddleClas#2242]
在PaddleClas/deploy/paddleserving/recognition/test_cpp_serving_client.py文件中，导入库有这么一句
第18行 ：`from paddle_serving_app.reader import *`

我测试了一下，在这个文件中把这句注释掉是不会报错的。
不太明白这句话存在的意义，请教一下。

或者是 paddle_serving_app.reader里面的某些个函数会在一些语境下用到？

**Comment by HydrogenSulfate** [comment]
老版C++ serving的图片与处理是在放置在serving外使用，所以使用了paddle_serving_app.reader提供的API，而现在的预处理已经写成了OP的形式内置在serving中了，所以这行代码应该是可以注释掉的，后续我们会去掉这行代码，感谢你的建议
