### ISSUE TITLE
能否提供AdaFace数据集的分割过程

### ISSUE THREAD

**Issue by Zheng-Bicheng** [PaddlePaddle/PaddleClas#2243]
AdaFace配置文件中提到的数据集需要在哪里下载啊，或者如何制作和分割数据集呢，有无参考demo？

**Comment by RainFrost1** [comment]
具体原数据集下载请查看[原文档](https://github.com/mk-minchul/AdaFace/blob/master/README_TRAIN.md)，具体[下载地址](https://github.com/deepinsight/insightface/tree/master/recognition/_datasets_)。我刚看了一下原repo，应该是有更新，PaddleClas这边后期应该会更新一下。
另外，在实际使用过程中，建议生成[此yaml文件格式](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.4/ppcls/configs/GeneralRecognition/GeneralRecognition_PPLCNet_x2_5.yaml)的数据集，方便使用，具体为`image_list.txt`中每一行`image_path id`。
