### ISSUE TITLE
PaddleDetection主题检测的矩形框和PaddleCls主体检测不一致问题？

### ISSUE THREAD

**Issue by jeomincham** [PaddlePaddle/PaddleClas#2247]
https://aistudio.baidu.com/aistudio/projectdetail/344560

将示例中的通用主体检测模型替换为自己训练的主体检测模型后，最后的图像检索结果矩形框大多框住的是整个图片，没有框住物体主体。

但是把自训练的主体检测模型直接做主体检测的推断是没问题的，请问问题出在什么地方呢？谢谢！

**Comment by zengshao0622** [comment]
PP-ShiTu检索过程会额外添加整个图像作为一个检测结果。具体可参考：https://github.com/PaddlePaddle/PaddleClas/blob/20c4c45d75ac573838b149da8dfc48b49f6eeb65/deploy/python/predict_system.py#L98

**Comment by jeomincham** [comment]
> 
好的，谢谢！
