### ISSUE TITLE
关于resnet vd结构

### ISSUE THREAD

**Issue by MARD1NO** [PaddlePaddle/PaddleClas#225]
您好，想请教一下resnet vd整体结构是什么呢？方便贴下论文链接吗谢谢

**Comment by littletomatodonkey** [comment]
你好，可以参考这篇文章：[Bag of Tricks for Image Classification with Convolutional Neural Networks](https://arxiv.org/abs/1812.01187)

**Comment by MARD1NO** [comment]
> 你好，可以参考这篇文章：[Bag of Tricks for Image Classification with Convolutional Neural Networks](https://arxiv.org/abs/1812.01187)

十分感谢~赞一个Paddle处理issue的速度
