### ISSUE TITLE
请问类别少于5,训练-o Metric.Eval.TopkAcc.topk={}该怎么-o

### ISSUE THREAD

**Issue by Juruobudong** [PaddlePaddle/PaddleClas#2259]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如Linux/Windows/MacOS
  b. Python版本号，如Python3.6/7/8
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

二分类，三分类之类的
。我是这样的，" -o Metric.Train.TopkAcc.topk={} -o Metric.Eval.TopkAcc.topk={}".format([1,class_num], [1,class_num])
但不起作用，请问如何-o才对呢。因为一些原因不能直接改yaml，只能命令行-o,谢谢

另外1629issue，https://github.com/PaddlePaddle/PaddleClas/issues/1629的解答也没了，问题之前的issue有回答，参见 https://github.com/PaddlePaddle/PaddleClas/issues/1625%EF%BC%9B 另外，对于二分类的情况，类别数设置为2

**Comment by TingquanGao** [comment]
你好，可以通过`-o`的方式，因为`Metric.Train`是list，所以需要这样写：`-o Metric.Train.0.TopkAcc.topk="[1]"`。
另外，当topk设置错误时（如二分类任务中，topk设置了[1, 5]），程序会抛出warning，并不会因为error中断，因此，如果warning没有影响的话，可以忽略。

**Comment by Juruobudong** [comment]
谢谢 学习啦
