### ISSUE TITLE
人的属性与output的值匹配吗？！

### ISSUE THREAD

**Issue by XingYuanWei** [PaddlePaddle/PaddleClas#2265]
>>> result
[{'attributes': ['Male', 'Age18-60', 'Back', 'Glasses: False', 'Hat: False', 'HoldObjectsInFront: False', 'Backpack', 'Upper: LongSleeve UpperPlaid', 'Lower:  Trousers', 'No boots'], 'output': [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1], 'filename': 'pulc_demo_imgs/person_attribute/090004.jpg'}] 在人的属性检测中，这个output的输出值和这个检测出的attributes有什么对应关系吗？分别表示什么属性呢？都没有任何的说明

**Comment by cuicheng01** [comment]
感谢提问，近期我们会在文档中补充该部分内容～

**Comment by XingYuanWei** [comment]
thks for your responses. because i have been doing my own experiments recently，if can speed up updates，i m thank you very very&nbsp; much！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月8日(周四) 上午10:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleClas] 人的属性与output的值匹配吗？！ (Issue #2265)




 
感谢提问，近期我们会在文档中补充该部分内容～

**Comment by cuicheng01** [comment]
您好，这个PR里提供了属性的说明。https://github.com/PaddlePaddle/PaddleClas/pull/2312
