### ISSUE TITLE
Understanding the output

### ISSUE THREAD

**Issue by jaideep11061982** [PaddlePaddle/PaddleClas#2271]
`  {'attributes': 'Color: (yellow, prob: 0.9893478155136108), Type: (hatchback, prob: 0.9734099507331848)', 'output': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]}`

what does the hot encoding in the outmeans , 1 at certain places ?

**Comment by cuicheng01** [comment]
0-9 means color，10-18 means type，we will update the documentation soon
![image](https://user-images.githubusercontent.com/45199522/189805823-90493fe7-4528-46e2-aba1-34752d882fc7.png)

**Comment by cuicheng01** [comment]
Of course, you can also see more details here~ https://github.com/PaddlePaddle/PaddleClas/pull/2312
