### ISSUE TITLE
模型库中 pretrained weights 结构不符于 paddlepaddle/models/paddleCV/image_classification/se_resnext_vd.py 中模型结构和

### ISSUE THREAD

**Issue by XiminLin** [PaddlePaddle/PaddleClas#228]
测试过 SE_ResNeXt50_vd_32x4d 和 SE_ResNeXt101_vd_32x4d.

在 pretrained weights 当中, 对于 paddleClas 里面的第一层 conv1_3 在 paddlepaddle 中 num_filters 为 128. 但是在 模型库的 pretrained weights 中 num_filters 为 64.

**Comment by XiminLin** [comment]
没事.... 我下错模型了

**Comment by littletomatodonkey** [comment]
嗯嗯，SE_ResNeXt50_vd_32x4d的下载链接是这个~

https://paddle-imagenet-models-name.bj.bcebos.com/SE_ResNeXt50_vd_32x4d_pretrained.tar
