### ISSUE TITLE
运行文档中实用工具-分类预测框架-三预测引擎+inference模型预测时出错

### ISSUE THREAD

**Issue by gaooolianggg** [PaddlePaddle/PaddleClas#230]
报错信息如下：
InvalidArgumentError: tensor version 1904018048 is not supported, Only version 0 is supported
  [Hint: Expected version == 0U, but received version:1904018048 != 0U:0.] at (/paddle/paddle/fluid/framework/lod_tensor.cc:287)

使用的模型是30分钟玩转paddleclas文档中3.2模型微调得到的模型，数据集使用的是flowers102.
3.2步完成后得到的模型是inference模型吧，所以就直接运行了预测引擎的语句
python ./tools/infer/predict.py \
    -i=./test.jpeg \
    -m=./resnet50-vd/model \
    -p=./resnet50-vd/params \
    --use_gpu=1 \
    --use_tensorrt=True

paddlepaddle-gpu版本为1.7.2
系统为ubuntu18.04

**Comment by gaooolianggg** [comment]
30分钟玩转paddleclas得到的模型名称是ppclspdmodel,ppcls.pdparams，我直接把文件重命名为了model 和params ，这个没问题吧

**Comment by littletomatodonkey** [comment]
你好，需要使用[export_model.py](https://github.com/PaddlePaddle/PaddleClas/blob/master/tools/export_model.py)将pdparams的模型转化为inference model，可以参考这里的教程：https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/zh_CN/tutorials/getting_started.md#%E4%B8%89%E6%A8%A1%E5%9E%8B%E6%8E%A8%E7%90%86

**Comment by gaooolianggg** [comment]
@littletomatodonkey 你好，可是文档中写的是，那种文件夹内有很多个小文件的模型类型才需要转换啊，这个示例运行之后，已经是model和params了，还需要转换吗？
另外，如果需要转换的化，那转换程序的参数怎么给呢？--model这个参数是输入model这个文件路径，还是包含model与params的文件夹路径呢

**Comment by littletomatodonkey** [comment]
这个示例运行之后是pdparams文件，也是需要转换的，比如说你要转换ResNet50的模型，预训练保存为`pretrained/ResNet50_pretrained.pdparams`，那么导出脚本可以如下所示。
```
export PYTHONPATH=$PWD:$PYTHONPATH
python tools/export_model.py -p pretrained/ResNet50_pretrained -m ResNet50 -o inference/ --class_dim=1000
```

**Comment by gaooolianggg** [comment]
@littletomatodonkey 可以转换了，多谢
