### ISSUE TITLE
文档image_recognition_pipeline/feature_extraction.md错误

### ISSUE THREAD

**Issue by lazyn1997** [PaddlePaddle/PaddleClas#2300]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：如PaddleClas release/2.5
 
文档image_recognition_pipeline/feature_extraction.md恢复训练部分关键字错误，文档中为-o Global.checkpoint，应该为-o Global.checkpoints

**Comment by HydrogenSulfate** [comment]
感谢建议，问题已经修复，https://github.com/PaddlePaddle/PaddleClas/pull/2305
