### ISSUE TITLE
能否分享一下text_image_orientation识别的训练模型

### ISSUE THREAD

**Issue by qiyuezhiguang** [PaddlePaddle/PaddleClas#2307]
该模型性能还是很强大的，但只提供了inference的模型，没有提供预训练的模型，由于要训练自己的数据，能否分享一下text_image_orientation识别的训练模型，非常感谢。

另外如果有了您的预训练模型了，只需要在config中的
Global：
     pretrained_model:您提供的预训练模型地址

进行修改就可以了吧。

非常感谢您的答复。

**Comment by cuicheng01** [comment]
在[这里](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/PULC/PULC_model_list.md)有提供训练的模型。对，更改Global.pretrained_model就可以。

**Comment by xbc922** [comment]
@cuicheng01 您好，您链接的超链接无效了，请问是否文档已经更换地址，我从仓库中docs下看了下都没找到这个model_list
