### ISSUE TITLE
CVPR2022中发表的Implicit Sample Extension for Unsupervised Person Re-Identification部分代码

### ISSUE THREAD

**Issue by krmui** [PaddlePaddle/PaddleClas#2338]
您好，我在阅读了CVPR2022中Implicit Sample Extension for Unsupervised Person Re-Identification的论文，对您的ISE和PLI部分内容十分感兴趣，但是在论文中给出的github地址中并未能很好的找到相关的部分代码，希望您能够帮我指明一下这部分的代码在何处，十分感谢

**Comment by weisy11** [comment]
可以参考这里：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/algorithm_introduction/ISE_ReID.md
