### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by peiwenYe** [PaddlePaddle/PaddleClas#2378]
请问release/2.4版本有CSwinTransformer，PVTv2，MobileViT，VAN这几个系列的模型的预训练模型吗？配置文件里没找到。

**Comment by TingquanGao** [comment]
在release/2.4中，可以从这里找到这几个模型下预训练模型下载地址：https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.4/docs/zh_CN/algorithm_introduction/ImageNet_models.md

我们在release/2.5中重构了用户文档目录，建议使用release/2.5：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/models/ImageNet1k/model_list.md

其中VAN模型还未更新到上述文档中，在更新后会在本issue中回复。谢谢关注！

**Comment by peiwenYe** [comment]
> 

收到，感谢～

**Comment by TingquanGao** [comment]
van 系列模型目前提供了 van b0 的pretrained: https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/VAN_B0_pretrained.pdparams
