### ISSUE TITLE
train_multi_platform.py的问题

### ISSUE THREAD

**Issue by haixiao990** [PaddlePaddle/PaddleClas#238]
![image](https://user-images.githubusercontent.com/17689011/89384702-07a75e80-d731-11ea-954b-ad8a45d098e1.png)
`Traceback (most recent call last):
  File "tools/train_multi_platform.py", line 157, in <module>
    main(args)
  File "tools/train_multi_platform.py", line 122, in main
    epoch_id, 'train', vdl_writer)
  File "/home/aistudio/PaddleClas/tools/program.py", line 463, in run
    if idx % config.get('print_interval', 10) == 0:
AttributeError: 'NoneType' object has no attribute 'get'`
train_multi_platform.py里调用program.run()时没有传config，默认是None，然后在第10个steps的时候调用config.get就崩了。

**Comment by littletomatodonkey** [comment]
你好，训练和评估的时候是必须填写config文件的，这块我们也完善下参数异常提醒，感谢反馈~

**Comment by haixiao990** [comment]
> 你好，训练和评估的时候是必须填写config文件的，这块我们也完善下参数异常提醒，感谢反馈~

不是异常参数提醒的问题，我命令行参数里给了config文件，是"tools/train_multi_platform.py",  line 122,
`program.run(train_dataloader, exe, compiled_train_prog, train_fetchs,
                    epoch_id, 'train', vdl_writer)`
代码里少了一个参数，加一个参数就好了。
`program.run(train_dataloader, exe, compiled_train_prog, train_fetchs,
                    epoch_id, 'train', config, vdl_writer)`

**Comment by littletomatodonkey** [comment]
> > 你好，训练和评估的时候是必须填写config文件的，这块我们也完善下参数异常提醒，感谢反馈~
> 
> 不是异常参数提醒的问题，我命令行参数里给了config文件，是"tools/train_multi_platform.py", line 122,
> `program.run(train_dataloader, exe, compiled_train_prog, train_fetchs, epoch_id, 'train', vdl_writer)`
> 代码里少了一个参数，加一个参数就好了。
> `program.run(train_dataloader, exe, compiled_train_prog, train_fetchs, epoch_id, 'train', config, vdl_writer)`

你好，修改代码已经提PR，感谢反馈~
