### ISSUE TITLE
PaddleClas\deploy\python\predict_rec.py", line 23, in from utils import logger ImportError: cannot import name 'logger' from 'utils'

### ISSUE THREAD

**Issue by yangguangyu369** [PaddlePaddle/PaddleClas#2380]
PaddleClas\deploy\python\predict_rec.py", line 23, in
from utils import logger
ImportError: cannot import name 'logger' from 'utils'

用的是paddleocr-2.6
PaddleClas 2.4.0

**Comment by TingquanGao** [comment]
这个代码应该是release/2.3分支吧，2.4修改了这个地方：
https://github.com/PaddlePaddle/PaddleClas/blob/3bd78eb1d37f42f2266c80a4aba9ee721953782f/deploy/python/predict_rec.py#L23

**Comment by TingquanGao** [comment]
hi，请问这个问题解决了不？
