### ISSUE TITLE
faiss-cpu==1.7.1.post2   ,不支持python3.10

### ISSUE THREAD

**Issue by yangguangyu369** [PaddlePaddle/PaddleClas#2386]
faiss-cpu==1.7.1.post2   ,不支持python3.10
python3.10安装 PaddleClas 2.4.3时 faiss-cpu==1.7.1.post2 出错

**Comment by RainFrost1** [comment]
可以先尝试最新版本的faiss-cpu，目前主要针对python3.7、3.8进行适配。python3.10暂时没有具体的适配
