### ISSUE TITLE
PaddleX数据集格式，能通用吗

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleClas#2394]
1. PaddleX数据集格式，能通用吗
```
labels.txt
xx1
xx2

train_list.txt
xx1\1.jpg 0
xx2\1.jpg 1

val_list.txt
test_list
```

2. 另外我的数据集是
XX1
XX2
XX3
XX4
文件夹

在WIN中
怎么转换为PaddleClas需要的格式

3. PPHGNet_base.yaml 进行训练
```

Infer:
  infer_imgs: E:\XX1\1.jpg
    class_id_map_file: E:\XX1\labels.txt
```
labels.txt 格式 和 默认的 imagenet1k_label_list.txt 不对

**Comment by zengshao0622** [comment]
推荐了解一下[图像分类数据集说明](https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/training/single_label_classification/dataset.md)和[图像识别数据集说明](https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/training/metric_learning/dataset.md)

**Comment by monkeycc** [comment]
PaddleClas 为什么不增加一个 数据集划分工具 呢
