### ISSUE TITLE
WARNING: device:  . The installed Paddle is compiled with CUDNN 8.4, but CUDNN version in your machine is 8.2, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleClas#2395]
1. PaddleClas版本以及PaddlePaddle版本：paddleclas 2.4.3     paddlepaddle-gpu 2.3.2.post116
 3. 训练环境信息：
  a. 具体操作系统：Windows
  b. Python版本号，anaconda  Python3.7
  c. CUDA/cuDNN版本， cuda 11.6  ,  cudnn 8.4.0
```


python3 tools/infer.py \
    -c ppcls/configs/ImageNet/PPHGNet/PPHGNet_small.yaml \
    -o Global.pretrained_model=output/PPHGNet_small/best_model

```

提示 
`WARNING: device:  . The installed Paddle is compiled with CUDNN 8.4, but CUDNN version in your machine is 8.2, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.`

cudnn-windows-x86_64-8.4.0.27_cuda11.6-archive
覆盖还是一样

**Comment by zengshao0622** [comment]
覆盖cudnn后，建议确认一下当前环境cudnn版本是否切换到8.4

**Comment by monkeycc** [comment]
否  
覆盖8.40 或者 8.41
重启电脑   也是提示8.2

**Comment by zengshao0622** [comment]
建议覆盖后，配置一下当前环境的环境变量，确认cudnn版本切换到8.4
