### ISSUE TITLE
层级分类

### ISSUE THREAD

**Issue by LeeLear** [PaddlePaddle/PaddleClas#2396]
paddleclas 可以支持层级分类吗

**Comment by zengshao0622** [comment]
PaddleClas目前主要支持[图像分类](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/algorithm_introduction/image_classification.md)和[图像识别](https://github.com/PaddlePaddle/PaddleClas/tree/release/2.5/docs/zh_CN/models/PP-ShiTu)任务。

**Comment by LeeLear** [comment]
是的，就是一个大类狗，然后在大类继续分下去这种可以支持吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleClas"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月19日(星期三) 下午3:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleClas] 层级分类 (Issue #2396)





 
PaddleClas目前主要支持图像分类和图像识别任务。

**Comment by weisy11** [comment]
可以有这几种方法：
1.用多个模型来做，一个模型分大类，之后每个大类再一个模型细分类
2.用一个模型来做，直接把细分类作为分类的类别，大类只作为标签的一部分
