### ISSUE TITLE
最新分支release/2.5怎么训练PPShiTu的量化模型

### ISSUE THREAD

**Issue by superdu12138** [PaddlePaddle/PaddleClas#2399]
请问，怎么在最新分支的代码中训练PPShiTu的量化模型，都没看到相关的配置文件，slim目录下的`GeneralRecognition_PPLCNet_x2_5_quantization.yaml`应该是PPShiTu V1的配置文件吧

**Comment by RainFrost1** [comment]
目前PP-ShiTuV2 识别的模型的量化，是直接离线量化的，没有量化训练，具体可以参考[离线量化文档](https://github.com/PaddlePaddle/PaddleClas/tree/release/2.5/deploy/slim)

**Comment by wenzhu2018** [comment]
请问PPshituV2的主体检测模型怎么量化？weights:  https://paddledet.bj.bcebos.com/models/picodet_s_320_coco.pdparams
那主体检测这个weight在哪里？

**Comment by wenzhu2018** [comment]
请问是哪种离线量化？通过opt动态离线量化直接导致RK3588重启，静态离线量化没看见配置说明
