### ISSUE TITLE
报错 from .ppcls.arch import backbone

### ISSUE THREAD

**Issue by xinyujituan** [PaddlePaddle/PaddleClas#2402]
执行 python3.7 python/predict_system.py -c configs/inference_general.yaml -o Global.use_gpu=False
报错：from .ppcls.arch import backbone
我感觉像是github上下载的PaddleClas源码和PaddleClas的安装包冲突了，这个如何解决？
我是win10 or win11

**Comment by weisy11** [comment]
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/installation.md#13-%E5%AE%89%E8%A3%85-paddleclas-%E5%8F%8A%E5%85%B6-python-%E4%BE%9D%E8%B5%96%E5%BA%93
如需使用源码，可以尝试使用1.3中的第二种方法安装paddleclas
`python setup.py install`

**Comment by zhanghangzzz** [comment]
请问解决了吗？我现在也遇到这个问题

**Comment by verseboys** [comment]
> 执行 python3.7 python/predict_system.py -c configs/inference_general.yaml -o Global.use_gpu=False 报错：from .ppcls.arch import backbone 我感觉像是github上下载的PaddleClas源码和PaddleClas的安装包冲突了，这个如何解决？ 我是win10 or win11

根据你的理解，我把下载的代码删了，就正常了。只保留pip安装的。
