### ISSUE TITLE
Cant install paddleclas

### ISSUE THREAD

**Issue by JonhSilver** [PaddlePaddle/PaddleClas#2404]
Python 3.10

pip3 install paddleclas==2.2.1
Collecting paddleclas==2.2.1
  Using cached paddleclas-2.2.1-py3-none-any.whl (306 kB)
Collecting prettytable
  Using cached prettytable-3.4.1-py3-none-any.whl (26 kB)
Requirement already satisfied: visualdl>=2.0.0b in c:\users\1\appdata\local\programs\python\python310\lib\site-packages (from paddleclas==2.2.1) (2.4.1)
Collecting ujson
  Using cached ujson-5.5.0-cp310-cp310-win_amd64.whl (37 kB)
Collecting gast==0.3.3
  Using cached gast-0.3.3-py2.py3-none-any.whl (9.7 kB)
Collecting scikit-learn==0.23.2
  Using cached scikit-learn-0.23.2.tar.gz (7.2 MB)
  Installing build dependencies ... /
... a lot of shits

```
       error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD 
	   -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 
	   -Ibuild\src.win-amd64-3.1\numpy\core\src\umath -Ibuild\src.win-amd64-3.1\numpy\core\src\npymath 
	   -Ibuild\src.win-amd64-3.1\numpy\core\src\common -Inumpy\core\include 
	   -Ibuild\src.win-amd64-3.1\numpy\core\include/numpy -Inumpy\core\src\common -Inumpy\core\src -Inumpy\core 
	   -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort 
	   -IC:\Users\1\AppData\Local\Programs\Python\Python310\include 
	   -IC:\Users\1\AppData\Local\Programs\Python\Python310\Include -Ibuild\src.win-amd64-3.1\numpy\core\src\common 
	   -Ibuild\src.win-amd64-3.1\numpy\core\src\npymath -Ibuild\src.win-amd64-3.1\numpy\core\src\common 
	   -Ibuild\src.win-amd64-3.1\numpy\core\src\npymath -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared 
	   -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um 
	   -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt 
	   -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tcbuild\src.win-amd64-3.1\numpy\core\src\multiarray\scalartypes.c 
	   /Fobuild\temp.win-amd64-cpython-310\Release\build\src.win-amd64-3.1\numpy\core\src\multiarray\scalartypes.obj" failed with exit status 2
        [end of output]
```

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure

      Encountered error while trying to install package.

      numpy

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by JonhSilver** [comment]
python -m pip install paddleclas==2.4.2  -i https://mirror.baidu.com/pypi/simple

     Collecting numpy==1.19.3
        Using cached https://mirror.baidu.com/pypi/packages/cb/c0/7b3d69e6ee68bc54c97ba51f8c3c3e43ff1dbc7bd97347cc19a1f944e60a/numpy-1.19.3.zip (7.3 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        Preparing metadata (pyproject.toml) did not run successfully.
        exit code: 1

        [267 lines of output]
        setup.py:67: RuntimeWarning: NumPy 1.19.3 may not yet support Python 3.10.
          warnings.warn(
        Running from numpy source directory.
        setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates

**Comment by HydrogenSulfate** [comment]
try:
```python
git clone https://github.com/PaddlePaddle/PaddleClas.git
cd PaddleClas
git checkout develop
python setup.py install
```

**Comment by JonhSilver** [comment]
> try:
> 
> ```python
> git clone https://github.com/PaddlePaddle/PaddleClas.git
> cd PaddleClas
> git checkout develop
> python setup.py install
> ```

@HydrogenSulfate  Im on Windows

error: pathspec 'develop' did not match any file(s) known to git

**python setup.py install  return**


C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
error: Setup script exited with error: command 'swig.exe' failed: None



Best match: faiss-cpu 1.7.1.post2
Processing faiss-cpu-1.7.1.post2.tar.gz
Writing C:\Users\1\AppData\Local\Temp\easy_install-to3jnbis\faiss-cpu-1.7.1.post2\setup.cfg
Running faiss-cpu-1.7.1.post2\setup.py -q bdist_egg --dist-dir C:\Users\1\AppData\Local\Temp\easy_install-to3jnbis\faiss-cpu-1.7.1.post2\egg-dist-tmp-r1g9shf8
C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
faiss\faiss\python\swigfaiss.i(250) : Error: Unable to find 'faiss\impl\platform_macros.h'
faiss\faiss\python\swigfaiss.i(254) : Error: Unable to find 'faiss\utils\ordered_key_value.h'
faiss\faiss\python\swigfaiss.i(255) : Error: Unable to find 'faiss\utils\Heap.h'
faiss\faiss\python\swigfaiss.i(260) : Error: Unable to find 'faiss\utils\AlignedTable.h'
faiss\faiss\python\swigfaiss.i(261) : Error: Unable to find 'faiss\utils\partitioning.h'
faiss\faiss\python\swigfaiss.i(262) : Error: Unable to find 'faiss\utils\hamming.h'
faiss\faiss\python\swigfaiss.i(365) : Error: Unable to find 'faiss\utils\utils.h'
faiss\faiss\python\swigfaiss.i(366) : Error: Unable to find 'faiss\utils\distances.h'

**Comment by HydrogenSulfate** [comment]
> ```python
> python setup.py install
> ```

you can delete `faiss-cpu==1.7.1.post2` in `requirements.txt` and then using the commands given above.

I had installed successfully in my Win11 laptop.
```log
Using d:\miniconda3\envs\py37\lib\site-packages
Searching for MarkupSafe==2.1.1
Best match: MarkupSafe 2.1.1
Adding MarkupSafe 2.1.1 to easy-install.pth file

Using d:\miniconda3\envs\py37\lib\site-packages
Finished processing dependencies for paddleclas==0.0.0
```

**Comment by JonhSilver** [comment]
it alll not works

**Comment by HydrogenSulfate** [comment]
> it alll not works

what is the error message now?

**Comment by weisy11** [comment]
Please use python3.7 or python3.8.  We are working on supporting python3.9 recently. Python3.10 is not supported for now.

**Comment by githubmuziyi** [comment]
python 3.9 is work
