### ISSUE TITLE
服务器部署中，request中需要传入其他参数，怎么改呀？

### ISSUE THREAD

**Issue by Firestick-Xia** [PaddlePaddle/PaddleClas#2409]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如Linux/Windows/MacOS
  b. Python版本号，如Python3.6/7/8
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

**Comment by TingquanGao** [comment]
是看的那个文档呢？

**Comment by Firestick-Xia** [comment]
@TingquanGao recognition_web_service.py

**Comment by HydrogenSulfate** [comment]
> @TingquanGao recognition_web_service.py

request传入参数的地方在`pipeline_http_client.py`
![image](https://user-images.githubusercontent.com/23737287/197697631-ea964b79-02c4-4108-9b59-185d9af6d361.png)
把需要额外传入的参数添加到"key"和"values"里
然后在`recognition_web_service.py`接受到序列化后的数据，然后把数据重新解码回原本的结构
![image](https://user-images.githubusercontent.com/23737287/197698119-49df01ae-b594-4363-88bb-8eff49ad4332.png)
现有的代码只对图片进行传输，所以仿照图片的传输方式添加你要传输的数据即可

**Comment by Firestick-Xia** [comment]
@HydrogenSulfate 解决了 谢谢
