### ISSUE TITLE
RepVgg配置文件

### ISSUE THREAD

**Issue by peiwenYe** [PaddlePaddle/PaddleClas#2412]
请问RepVgg的配置文件在哪里呢？官方给的目录下没有找到
![image](https://user-images.githubusercontent.com/37332773/197666345-9049966b-9dbb-4532-93a9-7966c0cf4466.png)

**Comment by cuicheng01** [comment]
您的问题已收到，这里之前有点小问题暂时删除了，我们会尽快上传最新的yaml文件

**Comment by cuicheng01** [comment]
最新的配置文件已上传～
