### ISSUE TITLE
pulc模型python服务部署问题

### ISSUE THREAD

**Issue by gitmhg** [PaddlePaddle/PaddleClas#2418]
我正在按部署文档部署人员属性模型python server ,服务能够正常启动，我i客户端提测出现一下问题：
INFO 2022-10-28 13:59:48,868 [local_service_handler.py:197] Models(/opt/DS61/paddle/PaddleClas-release-2.5/deploy/models/person_exists_vd_serving) will be launched by device gpu. use_gpu:True, use_trt:False, use_lite:False, use_xpu:False, device_type:1, devices:[0], mem_optim:True, ir_optim:False, use_profile:False, thread_num:2, client_type:local_predictor, fetch_names:None, precision:fp32, use_calib:False, use_mkldnn:False, mkldnn_cache_capacity:0, mkldnn_op_list:None, mkldnn_bf16_op_list:None, use_ascend_cl:False, min_subgraph_size:3,is_set_dynamic_shape_info:False
INFO 2022-10-28 13:59:48,868 [operator.py:1393] Init cuda env in process 0
INFO 2022-10-28 13:59:48,868 [local_service_handler.py:233] GET_CLIENT : concurrency_idx=0, device_num=1
INFO 2022-10-28 13:59:49,671 [local_predict.py:150] pdmodel_file_list:['/opt/DS61/paddle/PaddleClas-release-2.5/deploy/models/person_exists_vd_serving/inference.pdmodel'], pdiparams_file_list:['/opt/DS61/paddle/PaddleClas-release-2.5/deploy/models/person_exists_vd_serving/inference.pdiparams']
INFO 2022-10-28 13:59:49,672 [local_predict.py:168] LocalPredictor load_model_config params: model_path:/opt/DS61/paddle/PaddleClas-release-2.5/deploy/models/person_exists_vd_serving, use_gpu:True, gpu_id:0, use_profile:False, thread_num:2, mem_optim:True, ir_optim:False, use_trt:False, use_lite:False, use_xpu:False, precision:fp32, use_calib:False, use_mkldnn:False, mkldnn_cache_capacity:0, mkldnn_op_list:None, mkldnn_bf16_op_list:None, use_feed_fetch_ops:False, use_ascend_cl:False, min_subgraph_size:3, dynamic_shape_info:{}
INFO 2022-10-28 13:59:50,506 [operator.py:428] init_client, feed_list:['x'], fetch_list: ['prediction']
INFO 2022-10-28 13:59:50,507 [operator.py:1415] [imagenet|0] Succ init
INFO 2022-10-28 13:59:54,507 [pipeline_server.py:64] (log_id=0) inference request name:imagenet self.name:imagenet time:1666936794.5075152
INFO 2022-10-28 13:59:54,508 [operator.py:1826] RequestOp unpack one request. log_id:0, clientip:             name:imagenet, method:prediction, time:1666936794.508803
INFO 2022-10-28 13:59:54,509 [dag.py:379] (data_id=0 log_id=0) Succ Generate ID
ERROR 2022-10-28 13:59:54,531 [error_catch.py:106]
Log_id: 0
Traceback (most recent call last):
  File "/home/sysadmin/miniconda3/envs/byom/lib/python3.6/site-packages/paddle_serving_server/pipeline/error_catch.py", line 97, in wrapper
    res = func(*args, **kw)
  File "/home/sysadmin/miniconda3/envs/byom/lib/python3.6/site-packages/paddle_serving_server/pipeline/error_catch.py", line 160, in wrapper
    raise CustomException(CustomExceptionCode.INPUT_PARAMS_ERROR, "invalid arg list: {}".format(invalid_argument_list), True)
paddle_serving_server.pipeline.error_catch.CustomException:
        exception_code: 5000
        exception_type: INPUT_PARAMS_ERROR
        **error_msg: invalid arg list: ['feed_batch']**
        is_send_to_user: True
Classname: Op.process.<locals>.feed_fetch_list_check_helper
FunctionName: feed_fetch_list_check_helper
**ERROR 2022-10-28 13:59:54,531 [operator.py:1101] [imagenet] failed to predict. Log_id: 0  Raise_msg:  invalid arg list  ClassName: Op.process.<locals>.feed_fetch_list_check_helper  FunctionName: feed_fetch_list_check_helper. Please check the input dict and checkout PipelineServingLogs/pipeline.log for more details.
INFO 2022-10-28 13:59:54,531 [operator.py:1488] prometheus inf count +1
ERROR 2022-10-28 13:59:54,534 [dag.py:420] (data_id=0 log_id=0) Failed to predict: [imagenet] failed to predict. Log_id: 0  Raise_msg:  invalid arg list  ClassName: Op.process.<locals>.feed_fetch_list_check_helper  FunctionName: feed_fetch_list_check_helper. Please check the input dict and checkout PipelineServingLogs/pipeline.log for more details.**

**Comment by cuicheng01** [comment]
麻烦您可以再提供一下详细信息吗？包括python版本，paddle版本，paddleclas版本，模型的情况等

**Comment by gitmhg** [comment]
> 麻烦您可以再提供一下详细信息吗？包括python版本，paddle版本，paddleclas版本，模型的情况等

哦，不好意思抱歉哈！
python                      3.6.13
paddleclas                2.4.3
paddlepaddle-gpu          2.3.2.post116
方便的话请您加下我qq：1529418187,  我目前正在测试paddleclas的全部模型serving部署，谢谢

**Comment by cuicheng01** [comment]
已添加

**Comment by sunetic** [comment]
请问解决了吗？

**Comment by fanruifeng** [comment]
请问解决了嘛  给个反馈呀

**Comment by 2018-Summer** [comment]
请问解决了吗？
