### ISSUE TITLE
加载模型

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/PaddleClas#2419]
导出inference模型后怎么使用paddle.load()加载模型？
![_ T84OGR{F977D92GP1QDT1](https://user-images.githubusercontent.com/53975909/198541980-1bde334d-1f02-4af5-bc4d-ad4dbdef1a7f.png)

**Comment by weisy11** [comment]
请参考文档：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/deployment/image_classification/python.md
