### ISSUE TITLE
使用paddleseving部署shitu，一次请求多张图片，det模型耗时随图片数量线性增加

### ISSUE THREAD

**Issue by yywangfei** [PaddlePaddle/PaddleClas#2424]
请求代码如下所示：
`imgpath = "../../drink_dataset_v1.0/test_images/001.jpeg"

def cv2_to_base64(image):
    return base64.b64encode(image).decode('utf8')

if __name__ == "__main__":
    url = "http://127.0.0.1:18081/recognition/prediction"

    with open(os.path.join(".",  imgpath), 'rb') as file:
        image_data1 = file.read()
    image = cv2_to_base64(image_data1)
    data = {"key": ["image0xxxx","image1xx","image2x","image3x","image4"], "value": [image]*5}
    data = {"key": ["image0xxxx"], "value": [image]}
    for i in range(1):
        r = requests.post(url=url, data=json.dumps(data))
        print(r.json())`
对比了一张图片和五张图片，1是20ms，5张是50ms，10张大概是100ms：
一张：
2022-10-28 20:18:54,831 Op(det):
2022-10-28 20:18:54,831 	in[103813.24 ms]
2022-10-28 20:18:54,831 	prep[12.466 ms]
2022-10-28 20:18:54,831 	midp[19.438 ms]
2022-10-28 20:18:54,831 	postp[0.154 ms]
2022-10-28 20:18:54,831 	out[0.705 ms]
2022-10-28 20:18:54,831 	idle[0.9996912928849077]
五张：
2022-10-28 20:17:04,702 Op(det):
2022-10-28 20:17:04,702 	in[435137.036 ms]
2022-10-28 20:17:04,702 	prep[58.18 ms]
2022-10-28 20:17:04,702 	midp[49.842 ms]
2022-10-28 20:17:04,702 	postp[0.391 ms]
2022-10-28 20:17:04,703 	out[1.503 ms]

配置文件：
`#worker_num, 最大并发数。当build_dag_each_worker=True时, 框架会创建worker_num个进程，每个进程内构建grpcSever和DAG
##当build_dag_each_worker=False时，框架会设置主线程grpc线程池的max_workers=worker_num
worker_num: 1

#http端口, rpc_port和http_port不允许同时为空。当rpc_port可用且http_port为空时，不自动生成http_port
http_port: 18081
rpc_port: 9994

dag:
    #op资源类型, True, 为线程模型；False，为进程模型
    is_thread_op: False
    use_profile: True
    
    tracer:
        interval_s: 10
op:
    rec:
        #并发数，is_thread_op=True时，为线程并发；否则为进程并发
        concurrency: 1

        #当op配置没有server_endpoints时，从local_service_conf读取本地服务配置
        local_service_conf:

            #uci模型路径
            model_config: ../../models/general_PPLCNet_x2_5_lite_v1.0_serving

            #计算硬件类型: 空缺时由devices决定(CPU/GPU)，0=cpu, 1=gpu, 2=tensorRT, 3=arm cpu, 4=kunlun xpu
            device_type: 1

            #计算硬件ID，当devices为""或不写时为CPU预测；当devices为"0", "0,1,2"时为GPU预测，表示使用的GPU卡
            devices: "0" # "0,1"

            #client类型，包括brpc, grpc和local_predictor.local_predictor不启动Serving服务，进程内预测
            client_type: local_predictor

            #Fetch结果列表，以client_config中fetch_var的alias_name为准
            fetch_list: ["features"]

    det:
        concurrency: 1
        local_service_conf:
            client_type: local_predictor
            device_type: 1
            devices: '0'
            fetch_list:
            - save_infer_model/scale_0.tmp_1
            model_config: ../../models/picodet_PPLCNet_x2_5_mainbody_lite_v1.0_serving/
`

**Comment by weisy11** [comment]
请问具体使用的是哪种模式呢？如果对性能要求较高，建议使用C++版本。
另外，可以关注下硬件资源的占用率，如果已经达到较高占用率，那确实很难进一步提升效率了。
