### ISSUE TITLE
请问有含文字图像方向分类模型的预训练模型吗？

### ISSUE THREAD

**Issue by ZzyChris97** [PaddlePaddle/PaddleClas#2442]
请问有含文字图像方向分类模型的预训练模型吗？使用的模型为PPLCNet_x1_0+SSLD

**Comment by cuicheng01** [comment]
PULC的所有的预训练模型都在[这里](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/models/PULC/model_list.md)，可以找到对应的下载哈～
