### ISSUE TITLE
PreconditionNotMetError

### ISSUE THREAD

**Issue by luckyriko** [PaddlePaddle/PaddleClas#2446]
Windows WSL Ubuntu 22.04
![图片](https://user-images.githubusercontent.com/12975204/199690372-13a10c82-5065-429d-b4f3-0a2266bc7585.png)
```
docker run --name dev --gpus all -v $PWD:/mnt -p 8888:8888 -it --shm-size=32g paddlecloud/paddleocr:2.4-gpu-cuda10.2-cudnn7-latest /bin/bash
```
代码：
```
python3.7 python/predict_system.py -c configs/inference_general.yaml
```
报错：
![图片](https://user-images.githubusercontent.com/12975204/199690910-d4371580-19e8-4c0e-86cb-40e002aaf0ea.png)
![图片](https://user-images.githubusercontent.com/12975204/199690952-a3aff123-7292-49d0-818e-99d3616bcf66.png)
![图片](https://user-images.githubusercontent.com/12975204/199690987-ced2914a-eeb0-4425-ae32-599753c0b2e3.png)
![图片](https://user-images.githubusercontent.com/12975204/199691021-cd4fffba-4f7d-4491-93fb-2c358f1faa84.png)
![图片](https://user-images.githubusercontent.com/12975204/199691068-1b82319c-2489-410e-a3e3-eea6a02002c3.png)

**Comment by weisy11** [comment]
6GB memory is not enough, please use cpu or a better gpu card.
