### ISSUE TITLE
关于使用OpenVINO和GPU inference推理输出结果有差异的问题

### ISSUE THREAD

**Issue by lujx1024** [PaddlePaddle/PaddleClas#2447]
# 概述
模型网络为`GeneralRecognition_PPLCNet_x2_5`,完成训练后，导出inference模型，因需要测试CPU平台的运行情况，使用同一张图片、相同的预处理方式，分别在`PaddleClas`项目源码中使用`CUDA`环境和`OpenVINO runtime`环境中进行特征提取，对比数据时候发现，二者输出的`512维特征向量`比对有差异

# 环境
- PaddlePaddle ： v2.3
- CUDA :  10.1
- OpenVINO: 2022.02

# 差异情况如下(仅截取部分数据)：
![image](https://user-images.githubusercontent.com/36251986/199731574-3db2f99e-b97c-48ee-8230-fd60ab827ef5.png)

# 请教您： 该情况是否属于正常现象？ 如果不是，如何处理与改进？

**Comment by RainFrost1** [comment]
我测试了一下，paddle gpu跟openvino确实有误差，绝对误差和相对误差，一般不会超过1e-5，应该不会影响精度。不同库、不同硬件之间，确实会存在一些diff，但一般不影响结果

**Comment by lujx1024** [comment]
ok，了解了，谢谢您的解答！@RainFrost1
