### ISSUE TITLE
预测卡死

### ISSUE THREAD

**Issue by David-19940718** [PaddlePaddle/PaddleClas#2453]
python3.8 python/predict_system.py -c configs/inference_general.yaml

运行完之后就一直卡主不动了。
![image](https://user-images.githubusercontent.com/38575158/200269931-4501da1b-a95a-414b-bb5c-0065f1c4fc7f.png)

**Comment by RainFrost1** [comment]
估计是paddle版本和cuda等环境不匹配，建议查看一下
