### ISSUE TITLE
训练时报错Found inf or nan

### ISSUE THREAD

**Issue by JiehangXie** [PaddlePaddle/PaddleClas#2457]
虽然训练能继续，但是一直触发异常处理报这个错误，想问下是哪个脚本会报这个错误？麻烦告知方便定位问题，谢谢了！

[2022/11/08 14:54:54] ppcls INFO: [Train][Epoch 2/800][Iter: 0/366]lr(LinearWarmup): 0.05000000, CELoss: 11.76099, TripletAngularMarginLoss: 0.68000, loss: 12.44099, batch_cost: 0.54552s, reader_cost: 0.41536, ips: 117.31981 samples/s, eta: 1 day, 20:18:47
Found inf or nan, current scale is: 3.0517578125e-05, decrease to: 3.0517578125e-05*0.5
Found inf or nan, current scale is: 1.52587890625e-05, decrease to: 1.52587890625e-05*0.5
Found inf or nan, current scale is: 7.62939453125e-06, decrease to: 7.62939453125e-06*0.5
Found inf or nan, current scale is: 3.814697265625e-06, decrease to: 3.814697265625e-06*0.5
Found inf or nan, current scale is: 1.9073486328125e-06, decrease to: 1.9073486328125e-06*0.5
Found inf or nan, current scale is: 9.5367431640625e-07, decrease to: 9.5367431640625e-07*0.5
Found inf or nan, current scale is: 4.76837158203125e-07, decrease to: 4.76837158203125e-07*0.5
Found inf or nan, current scale is: 2.384185791015625e-07, decrease to: 2.384185791015625e-07*0.5
Found inf or nan, current scale is: 1.1920928955078125e-07, decrease to: 1.1920928955078125e-07*0.5
Found inf or nan, current scale is: 5.960464477539063e-08, decrease to: 5.960464477539063e-08*0.5

**Comment by JiehangXie** [comment]
去掉amp配置解决。

**Comment by keepgoing365** [comment]
> 去掉amp配置解决。

遇到了同样的问题，感谢大佬
