### ISSUE TITLE
PP-ShiTuV2构建索引时是否有先进行目标检测切图选项

### ISSUE THREAD

**Issue by 983183947** [PaddlePaddle/PaddleClas#2474]
PP-ShiTuV2推理是先进行目标检测再做图片相似度比较。但是建索引时我查了下好像没有先用目标检测进行切图再进行索引构建。是否有此选项可以配置。如果没有先检测切图再构建索引会出现推理时检测出来的对象还是整张图片。
 1. PaddleClas版本 v2.5

**Comment by weisy11** [comment]
没有这个流程，需要自行运行检测切图。
不这样做的原因是一个图可能检测出多个目标，无法判断哪个才是需要加库的。建议跑一遍检测并crop，之后做人工筛选再加库。
