### ISSUE TITLE
如何将车辆的ReID模型与Deepsort结合到一起

### ISSUE THREAD

**Issue by MessonC** [PaddlePaddle/PaddleClas#2476]
请问如何将车辆的ReID模型与Deepsort结合到一起 并导出推理模型？ 就像PaddleDetection中Deepsort_pplcnet_vehicle.tar这样的 我想将其中的pplcnet替换掉 谢谢

**Comment by weisy11** [comment]
暂不支持。

**Comment by Evezerest** [comment]
建议在detection中提问
