### ISSUE TITLE
大规模提取特征速度慢

### ISSUE THREAD

**Issue by kkpssr** [PaddlePaddle/PaddleClas#2477]
操作系统为ubuntu/centos
Python3.9
CUDA/cuDNN版本， 11.2
使用predict_rec,单卡T4，模型为Global_General_v2,batch=8,速度非常不稳定，3it/s-20s/it都有，同时gpu_utils较低，长期处在0

**Comment by zengshao0622** [comment]
这边测试了一下对应环境下的运行情况，可以参考一下：
操作系统为ubuntu
Python3.9
CUDA/cuDNN版本， 11.2
单卡Tesla V100, 模型为Global_General_v2, batch=8

运行命令如下：
python3.9 python/predict_rec.py -c configs/inference_rec.yaml -o Global.infer_imgs="/dataset/ppshitu_testdata/images" -o Global.use_gpu=True -o Global.batch_size=8
速度相对于不同batch在60its-90its间：
<img width="217" alt="image" src="https://user-images.githubusercontent.com/108920665/202990150-ac71f605-c758-490b-959e-247726133aa4.png">
 gpu_utils在4%-9%间，测试结果正常。

建议检查：
1.是否启用GPU进行特征提取； （-o Global.use_gpu=True）
2.数据读取速度是否异常。https://github.com/PaddlePaddle/PaddleClas/blob/622a94eea97442ea23e0f0535378dc09c866b5ac/deploy/python/predict_rec.py#L111
