### ISSUE TITLE
动态图repo导入不了预训练模型

### ISSUE THREAD

**Issue by luuuyi** [PaddlePaddle/PaddleClas#249]
请问一下动态图的分支不能load预训练的模型么，ppcls/utils/save_load.py 135行这里未实现报错

**Comment by littletomatodonkey** [comment]
可以参考这里的写法，动态图加载静态图模型的时候需要转换一下名字

https://github.com/PaddlePaddle/PaddleClas/blob/dygraph/tools/infer/infer.py

**Comment by luuuyi** [comment]
@littletomatodonkey 好的 感谢你这么快回复，其实话说你们有没有考虑在tools下面提供一个脚本，将最早的tar预训练模型转为最新支持的pdparams和pdopt这种文件，这样会方便很多

**Comment by littletomatodonkey** [comment]
你好
1. 目前需要转换的话，只能转换为pdparams文件，pdopt里面是训练时的优化器等信息，对于预测是不需要的
2. 目前pdparams文件和零散文件所在的文件夹都可以加载的，不知道你希望只用pdparams是有什么特殊的需求吗？
3. 如果希望转换的话，可以在tools/infer/infer.py中，加载模型之后，使用`fluid.load`接口保存即可。

**Comment by luuuyi** [comment]
@littletomatodonkey 上面那个建议只是因为动态图直接用tools/train训练会带来错误想出来的。目前我按你的说法借鉴了infer.py文件里面的写法，发现一个奇怪的现象，我在shell里面进入到python中执行fluid.load_program_state(args.pretrained_model)不会有问题，权重都能看到，预训练模型都能正常导入，但是在init_model这个方法中改写引入了这种导入方式以后，load_program_state函数会报错paddle.fluid.core_avx.VarBase object has no attribute 'desc'。这个是有什么解决方法么

**Comment by luuuyi** [comment]
@littletomatodonkey 我验证了一下 按30分钟快速入门那种方式执行tools/train，无论在哪fluid.load_program_state(args.pretrained_model)都会报这个错。。。在Linux终端里面打开python就不会

**Comment by luuuyi** [comment]
@littletomatodonkey 尝试了一下。。。动态图分支这个写法fluid.load_program_state(args.pretrained_model)不能放在fluid.dygraph.guard(place):里面，不然会报错。。。期待你们动态图分支训练代码完善得更好

**Comment by littletomatodonkey** [comment]
你是要在动态图分支下面跑30分钟快速入门的教程嘛？这块我们还没验证，近期验证一下~之前使用infer.py和eval.py是没问题的

**Comment by luuuyi** [comment]
@littletomatodonkey 是的 动态图30分钟快速入门还是有一些问题的，期待你们近期的排查
