### ISSUE TITLE
index_operation为append时，要遍历整个相册的图片抽取特征

### ISSUE THREAD

**Issue by jeomincham** [PaddlePaddle/PaddleClas#2500]
[         gallery_features = self._extract_features(gallery_images, config)](https://github.com/PaddlePaddle/PaddleClas/blob/622a94eea97442ea23e0f0535378dc09c866b5ac/deploy/python/build_gallery.py#L67)

配置中index_operation为append添加新类时，要遍历抽取相册的特征，如果特征图像比较多，这样每添加新类非常耗时 @JonhSilver， @HydrogenSulfate

**Comment by RainFrost1** [comment]
如果使用build gallery代码，进行数据append，那么image list应该只写append的数据list就好，这样的话，就只提取了新加的图像特征。如果使用库管理工具的话，应该会自动判断有差异的图像来提取特征

**Comment by jeomincham** [comment]
@RainFrost1 目前取list文件的最后一行，只写append的数据list会存在重复添加到文件的情况

**Comment by RainFrost1** [comment]
只写append的数据list会存在重复添加到文件的情况，能否具体一点？我们这边复现一下

**Comment by jeomincham** [comment]
https://github.com/PaddlePaddle/PaddleClas/blob/622a94eea97442ea23e0f0535378dc09c866b5ac/deploy/python/build_gallery.py#L131

这行代码每次添加新类都会执行，也就是把list文件的图片的特征抽取又写了一遍

**Comment by RainFrost1** [comment]
> https://github.com/PaddlePaddle/PaddleClas/blob/622a94eea97442ea23e0f0535378dc09c866b5ac/deploy/python/build_gallery.py#L131
> 
> 这行代码每次添加新类都会执行，也就是把list文件的图片的特征抽取又写了一遍

目前是这样的，在append的时候，list中只是存在了append的图像。在build_gallery中没有存储每张图像的id，所有没法判读哪张图像是新添的。在新的建库工具中，额外存储了图像的id，是可以判读哪些图是新添的
