### ISSUE TITLE
pip install paddleclas报错

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PaddleClas#2514]
64位,windows10系统,cuda10.5,cudnn7.6.5,飞桨2.4GPU版本,python3.10.8
1.官网的安装教程中,git clone https://github.com/PaddlePaddle/PaddleClas.git -b release/2.4,现在已经是2.5了,应该更新一下
2.使用pip install paddleclas语句安装paddleclas报错.我看原因,好像是faiss_cpu库的问题.
报错信息如下:Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting dill>=0.3.6
  Using cached dill-0.3.6-py3-none-any.whl (110 kB)
Requirement already satisfied: idna<4,>=2.5 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from requests->visualdl>=2.2.0->paddleclas) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from requests->visualdl>=2.2.0->paddleclas) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from requests->visualdl>=2.2.0->paddleclas) (2022.9.24)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from requests->visualdl>=2.2.0->paddleclas) (2.1.1)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.1-cp310-cp310-win_amd64.whl (17 kB)
Installing collected packages: wcwidth, pytz, faiss-cpu, easydict, ujson, threadpoolctl, scipy, PyYAML, python-dateutil, pyparsing, pycryptodome, prettytable, opencv-python, MarkupSafe, kiwisolver, joblib, itsdangerous, gast, future, fonttools, dill, cycler, contourpy, colorama, Babel, Werkzeug, tqdm, scikit-learn, pandas, packaging, multiprocess, Jinja2, click, bce-python-sdk, matplotlib, flask, Flask-Babel, visualdl, paddleclas
  DEPRECATION: faiss-cpu is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for faiss-cpu ... error
  error: subprocess-exited-with-error

  × Running setup.py install for faiss-cpu did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running install
      C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running build_ext
      building 'faiss._swigfaiss' extension
      swigging faiss\faiss\python\swigfaiss.i to faiss\faiss\python\swigfaiss_wrap.cpp
      swig.exe -python -c++ -Doverride= -I/usr/local/include -Ifaiss -DSWIGWIN -o faiss\faiss\python\swigfaiss_wrap.cpp faiss\faiss\python\swigfaiss.i
      error: command 'swig.exe' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> faiss-cpu

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

希望paddleclas官方尽快修复bug,但我也不敢保证不是因为飞桨2.4太新了导致的错误,其实我用飞桨2.4安装一些其他的飞桨官方套件,也会有问题.所以我不确定是faiss_cpu库的问题,还是clas还没有适配飞桨2.4的问题

**Comment by zengshao0622** [comment]
建议尝试一下先pip install安装faiss库，安装成功后，再安装paddleclas

**Comment by yuwoyizhan** [comment]
@zengshao0622 我按照你说的,先用pip install安装faiss库,安装成功后,pip install paddleclas,还是相同的报错,而且安装的faiss是1.7.3版本

**Comment by GreatV** [comment]
同样的问题，直接使用`pip install paddleclas`无法安装。手动安装faiss后，注释掉requirements.txt中的faiss-cpu，使用`python setup.py install`就可以安装了。

**Comment by GreatV** [comment]
升级到`faiss-cpu 1.7.3`能解决问题

**Comment by xxcoco763** [comment]
> 同样的问题，直接使用`pip install paddleclas`无法安装。手动安装faiss后，注释掉requirements.txt中的faiss-cpu，使用`python setup.py install`就可以安装了。

谢谢，解决了

**Comment by cobaltautomationdev** [comment]
> 同样的问题，直接使用`pip install paddleclas`无法安装。手动安装faiss后，注释掉requirements.txt中的faiss-cpu，使用`python setup.py install`就可以安装了。
现在不提示faiss错误，但是又提示需要安装Microsoft c++ building tools.
