### ISSUE TITLE
推理报错

### ISSUE THREAD

**Issue by BoragoCode** [PaddlePaddle/PaddleClas#2519]
推理代码如下：
import paddleclas
model = paddleclas.PaddleClas(model_name="person_exists")
result = model.predict(input_data="./mask_4.jpg")
print(next(result))

报错如下：
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1669866144 (unix time) try "date -d @1669866144" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 14863 (TID 0x7fa5085260c0) from PID 0 ***]

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by cuicheng01** [comment]
您好，问下paddle和paddleclas的版本分别是多少呢？以及你用的是docker还是物理机呢？
