### ISSUE TITLE
'ImageService' object has no attribute 'run_server'

### ISSUE THREAD

**Issue by deep-practice** [PaddlePaddle/PaddleClas#253]
命令
python tools/serving/image_service_gpu.py inference/serving/ResNet50_vd/ppcls_model workdir 9292

**Comment by littletomatodonkey** [comment]
你好，serving部署可以参考这个文档，哪个步骤出现问题可以贴下更详细的报错信息：https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/zh_CN/extension/paddle_serving.md
