### ISSUE TITLE
分类不准确问题

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleClas#2531]
每个文件夹的图片尺寸都是一样的

有以下的图片尺寸
214 * 54
150 * 50
41 * 44
26 * 26

训练是224*224

但是发现识别效果 惨不忍睹
训练 精确度也只有60%

这种是不是需要原图全部调整为224 * 224
还是怎么样
需要怎么样调整

**Comment by cuicheng01** [comment]
这些图人眼好区分吗？
