### ISSUE TITLE
label smoothing在config文件中怎么设置呢

### ISSUE THREAD

**Issue by deep-practice** [PaddlePaddle/PaddleClas#254]

**Comment by littletomatodonkey** [comment]
你好，可以在yaml文件中添加`ls_epsilon`这个字段，大于0，小于1即可，表示label smoothing的eps

https://github.com/PaddlePaddle/PaddleClas/blob/162281e7d6c6b7c0fd226c704c14bb5968c6c052/configs/ResNet/ResNet50_vd.yaml#L17

**Comment by deep-practice** [comment]
明白了，谢谢

**Comment by deep-practice** [comment]
有focal loss吗 或者加权的ce？ @littletomatodonkey

**Comment by deep-practice** [comment]
多标签分类的例子有吗

**Comment by littletomatodonkey** [comment]
你好，目前没有提供focal loss吗 或者加权的ce，你可以自己按照目前的loss实现方式，在这里添加新的loss：https://github.com/PaddlePaddle/PaddleClas/blob/master/ppcls/modeling/loss.py

PaddleClas目前没有提供多标签分类的demo，我们之后会添加对多标签分类的支持~
