### ISSUE TITLE
PPShitu中主体检测如何实现为单主体检测

### ISSUE THREAD

**Issue by harhar539** [PaddlePaddle/PaddleClas#2541]
PPShitu部署时候，主体检测那一部分，代码里头做的应该是多主体检测。
对于类似生鲜、果蔬的场景，待测目标都是单一品类，能否实现成单主体检测，类似百度云里头的业务。https://ai.baidu.com/tech/imagerecognition/object_detect
是用同一个模型，修改代码部分，还是要替换成专门的单主体检测模型

**Comment by zengshao0622** [comment]
可以通过设置配置文件字段Global.max_det_results实现，这样主体检测部分将返回置信度最高的检测框。
