### ISSUE TITLE
请问检索中用到的主题检测模型picodet支持onnx导出吗

### ISSUE THREAD

**Issue by Twilight89** [PaddlePaddle/PaddleClas#2549]
请问检索中用到的主题检测模型picodet支持onnx导出吗，我直接用推理模型倒出会报错
![image](https://user-images.githubusercontent.com/60816348/208255081-f75daa03-cb6c-4269-812c-40c089bbc9cf.png)

**Comment by RainFrost1** [comment]
可以参考这个 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/picodet，应该是python版本onnxruntime是支持的。提供一下运行环境，我们测试一下？
