### ISSUE TITLE
动态图加载预训练模型

### ISSUE THREAD

**Issue by lwbmowgli** [PaddlePaddle/PaddleClas#255]
目前，paddle放出来的预训练模型都是静态图的，如何在动态图模式中加载预训练模型?或者说有没有什么方法能把预训练模型转换为.pdparams 或 .pdopt文件？

**Comment by littletomatodonkey** [comment]
你好，可以参考动态图中tools/infer/infer.py点的写法，可以正常加载静态图的pretrain

https://github.com/PaddlePaddle/PaddleClas/blob/95ed78e2a68a51cea1af0d1e07a9ef0fe15d054e/tools/infer/infer.py#L73
