### ISSUE TITLE
服务化部署过程中始终报错 error_msg: invalid arg list: ['fetch_list']

### ISSUE THREAD

**Issue by sunetic** [PaddlePaddle/PaddleClas#2552]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：PaddleClas release/2.5
 2. 涉及的其他产品使用的版本号：
 ```
paddle-bfloat         0.1.7
paddle-serving-app    0.9.0
paddle-serving-client 0.9.0
paddle-serving-server 0.9.0
paddle2onnx           1.0.5
paddleclas            2.5.1
paddlefsl             1.1.0
paddlehub             2.3.1
paddlenlp             2.4.3
paddlepaddle          2.4.1
```
 3. 训练环境信息：
  a. 具体操作系统: Linux, registry.baidubce.com/paddlepaddle/serving:0.9.0-devel
  b. Python版本号: Python3.6
  c. CUDA/cuDNN版本: cpu
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

根据文档：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/deployment/image_classification/paddle_serving.md

使用自己训练的模型，验证了下是可以跑的
```
python3 python/predict_cls.py -c configs/sun.yaml

2022-12-19 20:02:54 INFO:         ToCHWImage : None
E1219 20:02:54.029156 21438 analysis_config.cc:96] Please compile with gpu to EnableGpu()
IMG_8512.JPG:	class id(s): [0, 4, 1, 3, 5], score(s): [0.62, 0.18, 0.14, 0.03, 0.02], label_name(s): ['optometry-0', 'eye-axis-2', 'optometry-1', 'eye-axis-1', 'eye-axis-3']
```

服务化部署的时候始终报错：
```
{'err_no': 5000, 'err_msg': '[imagenet] failed to predict. Log_id: 2  Raise_msg:  invalid arg list  ClassName: Op.process.<locals>.feed_fetch_list_check_helper  FunctionName: feed_fetch_list_check_helper. Please check the input dict and checkout PipelineServingLogs/pipeline.log for more details.', 'key': [], 'value': [], 'tensors': []}
```
PipelineServingLogs/pipeline.log
```
ERROR 2022-12-19 19:54:52,613 [error_catch.py:106]
Log_id: 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/paddle_serving_server/pipeline/error_catch.py", line 97, in wrapper
    res = func(*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/paddle_serving_server/pipeline/error_catch.py", line 160, in wrapper
    raise CustomException(CustomExceptionCode.INPUT_PARAMS_ERROR, "invalid arg list: {}".format(invalid_argument_list), True)
paddle_serving_server.pipeline.error_catch.CustomException:
	exception_code: 5000
	exception_type: INPUT_PARAMS_ERROR
	error_msg: invalid arg list: ['fetch_list']
	is_send_to_user: True
```

serving_server_conf.prototxt
```
feed_var {
  name: "inputs"
  alias_name: "inputs"
  is_lod_tensor: false
  feed_type: 1
  shape: 3
  shape: 224
  shape: 224
}
fetch_var {
  name: "softmax_1.tmp_0"
  alias_name: "prediction"
  is_lod_tensor: false
  fetch_type: 1
  shape: 1000
}
```

**Comment by HydrogenSulfate** [comment]
能麻烦提供一下模型吗，我们这边复现一下问题

**Comment by HydrogenSulfate** [comment]
如果不方便提供模型的话，有以下几点建议可以重点检查一下
1. 导出serving模型的`serving_server_conf.prototxt`和`serving_client_conf.prototxt`内的`alias_name`**都要**修改为`prediction`
2. 保证serving的python代码中，与输入名称（变量名叫feed_dict或者feed_list之类的）相关的key与`prototxt`文件内的一致，与输出名称（变量名叫fetch_dict或者fetch_list之类的）相关的key与`prototxt`文件内的一致。

**Comment by 2018-Summer** [comment]
自己训练模型在部署pdserving 报错，请大神解决一下
`Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle_serving_server/pipeline/error_catch.py", line 97, in wrapper
    res = func(*args, **kw)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle_serving_server/pipeline/error_catch.py", line 160, in wrapper
    raise CustomException(CustomExceptionCode.INPUT_PARAMS_ERROR, "invalid arg list: {}".format(invalid_argument_list), True)
paddle_serving_server.pipeline.error_catch.CustomException: 
	exception_code: 5000
	exception_type: INPUT_PARAMS_ERROR
	error_msg: invalid arg list: ['feed_batch']
	is_send_to_user: True
Classname: Op.process.<locals>.feed_fetch_list_check_helper
FunctionName: feed_fetch_list_check_helper
Args: ([{'x': array([[[[-1.0904187 , -1.0904187 , -1.0904187 , ..., -0.439678  ,
          -0.439678  , -0.439678  ],
         [-1.0732939 , -1.0732939 , -1.0732939 , ..., -0.439678  ,
          -0.439678  , -0.439678  ],
         [-1.0390444 , -1.0390444 , -1.0390444 , ..., -0.439678  ,
          -0.439678  , -0.42255327],
         ...,
         [-0.35405427, -0.35405427, -0.35405427, ..., -0.19993149,
          -0.11430772, -0.11430772],
         [-0.11430772, -0.11430772, -0.11430772, ..., -0.21705623,
          -0.13143247, -0.13143247],
         [-0.11430772, -0.09718297, -0.09718297, ..., -0.21705623,
          -0.14855723, -0.13143247]],

        [[-1.0903361 , -1.0903361 , -1.0903361 , ..., -0.12745096,
          -0.12745096, -0.12745096],
         [-1.0728291 , -1.0728291 , -1.0728291 , ..., -0.16246496,
          -0.16246496, -0.16246496],
         [-1.0378151 , -1.0378151 , -1.0378151 , ..., -0.19747896,
          -0.21498597, -0.21498597],
         ...,
         [-0.460084  , -0.442577  , -0.442577  , ..., -0.81022406,
          -0.652661  , -0.60014004],
         [-0.21498597, -0.21498597, -0.21498597, ..., -0.827731  ,
          -0.687675  , -0.60014004],
         [-0.24999997, -0.23249297, -0.23249297, ..., -0.827731  ,
          -0.705182  , -0.617647  ]],

        [[-0.8458388 , -0.8458388 , -0.8458388 , ...,  0.26962963,
           0.26962963,  0.26962963],
         [-0.8284096 , -0.8284096 , -0.8284096 , ...,  0.23477125,
           0.23477125,  0.23477125],
         [-0.7935512 , -0.7935512 , -0.7935512 , ...,  0.19991288,
           0.19991288,  0.19991288],
         ...,
         [-0.27067533, -0.27067533, -0.27067533, ..., -0.7064052 ,
          -0.61925924, -0.61925924],
         [-0.02666664, -0.02666664, -0.02666664, ..., -0.72383446,
          -0.61925924, -0.61925924],
         [-0.06152503, -0.04409584, -0.04409584, ..., -0.72383446,
          -0.6366884 , -0.61925924]]]], dtype=float32)}], ['multiclass_nms3_0.tmp_0', 'multiclass_nms3_0.tmp_2'])
ERROR 2023-06-28 10:07:53,042 [operator.py:1079] [det] failed to predict. Log_id: 0  Raise_msg:  invalid arg list  ClassName: Op.process.<locals>.feed_fetch_list_check_helper  FunctionName: feed_fetch_list_check_helper. Please check the input dict and checkout PipelineServingLogs/pipeline.log for more details.
INFO 2023-06-28 10:07:53,042 [operator.py:1454] prometheus inf count +1
ERROR 2023-06-28 10:07:53,044 [dag.py:420] (data_id=0 log_id=0) Failed to predict: [det] failed to predict. Log_id: 0  Raise_msg:  invalid arg list  ClassName: Op.process.<locals>.feed_fetch_list_check_helper  FunctionName: feed_fetch_list_check_helper. Please check the input dict and checkout PipelineServingLogs/pipeline.log for more details.
`

**Comment by liangasheng** [comment]
> 自己训练模型在部署pdserving 报错，请大神解决一下 `Traceback (most recent call last): File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle_serving_server/pipeline/error_catch.py", line 97, in wrapper res = func(*args, **kw) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle_serving_server/pipeline/error_catch.py", line 160, in wrapper raise CustomException(CustomExceptionCode.INPUT_PARAMS_ERROR, "invalid arg list: {}".format(invalid_argument_list), True) paddle_serving_server.pipeline.error_catch.CustomException: exception_code: 5000 exception_type: INPUT_PARAMS_ERROR error_msg: invalid arg list: ['feed_batch'] is_send_to_user: True Classname: Op.process..feed_fetch_list_check_helper FunctionName: feed_fetch_list_check_helper Args: ([{'x': array([[[[-1.0904187 , -1.0904187 , -1.0904187 , ..., -0.439678 , -0.439678 , -0.439678 ], [-1.0732939 , -1.0732939 , -1.0732939 , ..., -0.439678 , -0.439678 , -0.439678 ], [-1.0390444 , -1.0390444 , -1.0390444 , ..., -0.439678 , -0.439678 , -0.42255327], ..., [-0.35405427, -0.35405427, -0.35405427, ..., -0.19993149, -0.11430772, -0.11430772], [-0.11430772, -0.11430772, -0.11430772, ..., -0.21705623, -0.13143247, -0.13143247], [-0.11430772, -0.09718297, -0.09718297, ..., -0.21705623, -0.14855723, -0.13143247]],
> 
> ```
>     [[-1.0903361 , -1.0903361 , -1.0903361 , ..., -0.12745096,
>       -0.12745096, -0.12745096],
>      [-1.0728291 , -1.0728291 , -1.0728291 , ..., -0.16246496,
>       -0.16246496, -0.16246496],
>      [-1.0378151 , -1.0378151 , -1.0378151 , ..., -0.19747896,
>       -0.21498597, -0.21498597],
>      ...,
>      [-0.460084  , -0.442577  , -0.442577  , ..., -0.81022406,
>       -0.652661  , -0.60014004],
>      [-0.21498597, -0.21498597, -0.21498597, ..., -0.827731  ,
>       -0.687675  , -0.60014004],
>      [-0.24999997, -0.23249297, -0.23249297, ..., -0.827731  ,
>       -0.705182  , -0.617647  ]],
> 
>     [[-0.8458388 , -0.8458388 , -0.8458388 , ...,  0.26962963,
>        0.26962963,  0.26962963],
>      [-0.8284096 , -0.8284096 , -0.8284096 , ...,  0.23477125,
>        0.23477125,  0.23477125],
>      [-0.7935512 , -0.7935512 , -0.7935512 , ...,  0.19991288,
>        0.19991288,  0.19991288],
>      ...,
>      [-0.27067533, -0.27067533, -0.27067533, ..., -0.7064052 ,
>       -0.61925924, -0.61925924],
>      [-0.02666664, -0.02666664, -0.02666664, ..., -0.72383446,
>       -0.61925924, -0.61925924],
>      [-0.06152503, -0.04409584, -0.04409584, ..., -0.72383446,
>       -0.6366884 , -0.61925924]]]], dtype=float32)}], ['multiclass_nms3_0.tmp_0', 'multiclass_nms3_0.tmp_2'])
> ```
> 
> ERROR 2023-06-28 10:07:53,042 [operator.py:1079] [det] failed to predict. Log_id: 0 Raise_msg: invalid arg list ClassName: Op.process..feed_fetch_list_check_helper FunctionName: feed_fetch_list_check_helper. Please check the input dict and checkout PipelineServingLogs/pipeline.log for more details. INFO 2023-06-28 10:07:53,042 [operator.py:1454] prometheus inf count +1 ERROR 2023-06-28 10:07:53,044 [dag.py:420] (data_id=0 log_id=0) Failed to predict: [det] failed to predict. Log_id: 0 Raise_msg: invalid arg list ClassName: Op.process..feed_fetch_list_check_helper FunctionName: feed_fetch_list_check_helper. Please check the input dict and checkout PipelineServingLogs/pipeline.log for more details. `
我也遇到这个问题，请问怎么解决
