### ISSUE TITLE
paddleClas 数据增强：旋转

### ISSUE THREAD

**Issue by happybear1015** [PaddlePaddle/PaddleClas#2556]
您好，请问一下，paddleclas数据增强的配置策略有以下几种：
![图片](https://user-images.githubusercontent.com/66996161/209065813-ed7d1579-d1c3-4006-b3cd-9657129fc2b0.png)
这里面没有包含图像的旋转，请问一下，如何配置图像的旋转策略？

**Comment by TingquanGao** [comment]
支持的，可以参考这个配置：
https://github.com/paddlepaddle/paddleclas/blob/develop/ppcls/configs/GeneralRecognitionV2/GeneralRecognitionV2_PPLCNetV2_base.yaml#L117-L120
