### ISSUE TITLE
支持windows/cpu训练评估？

### ISSUE THREAD

**Issue by key-1994** [PaddlePaddle/PaddleClas#256]
看到更新日志支持windows和cpu环境下的训练评估，直接调用train.py训练can't find PADDLE_TRAINER_ENDPOINTS

**Comment by key-1994** [comment]
另外想用预训练模型通过paddlelite进行移动端性能评估，mobilenetV3_small系列的预训练模型没法用export_model.py进行固化，该怎么做？

**Comment by littletomatodonkey** [comment]
你好，需要使用` tools/train_multi_platform.p`和`tools/eval_multi_platform.py`，可以参考这个PR: #159

**Comment by key-1994** [comment]
问题解决了，非常感谢！
