### ISSUE TITLE
OSError: (External) CUDA error(719), unspecified launch failure.

### ISSUE THREAD

**Issue by w863071864** [PaddlePaddle/PaddleClas#2571]
版本：paddlepaddle-gpu             2.4.1.post117
错误信息：OSError: (External) CUDA error(719), unspecified launch failure. 
  [Hint: Please search for the error code(719) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:259)
随机性出现---

**Comment by weisy11** [comment]
![image](https://user-images.githubusercontent.com/19523330/210310481-d5840921-a879-4ce6-9c18-99f1d049de36.png)
根据NV官网介绍，可能是代码问题（包括指针异常内存越界等），也可能是系统问题。如果有资源，可以换台机器跑下，看是否会报错。
