### ISSUE TITLE
人体属性识别示例后处理结果有问题

### ISSUE THREAD

**Issue by EscaticZheng** [PaddlePaddle/PaddleClas#2574]
1. PaddleClas版本以及PaddlePaddle版本：
 2.5.1
 2.4.1
 
 2. 训练环境信息：
  a. 具体操作系统
Ubuntu20.04
  b. Python版本号
Python3.8
  c. CUDA/cuDNN版本
无，用的cpu版本
 3. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log
 
![image](https://user-images.githubusercontent.com/107376080/210523819-a15b1251-ce6f-4e10-8c1a-fa5cecc590e4.png)
下载的是PULC的人体属性识别模型，自定义路径放进去跑示例的时候发现输出不对：
![image](https://user-images.githubusercontent.com/107376080/210524070-9f74ef00-18ce-45a6-9c01-74cb68d15510.png)
但如果不自定义路径，使用模型名字来识别自动下载同样的模型，出来的输出是对的：
![image](https://user-images.githubusercontent.com/107376080/210524283-7730d721-a7ae-49bd-a576-63a6df8f8b1a.png)
![image](https://user-images.githubusercontent.com/107376080/210524405-10229c46-70bd-4736-840b-a497190f3551.png)
推测原因是针对人体属性识别有特殊的后处理对应，如果不写名字则无法对应，使用了默认的后处理。这点能否改进？

**Comment by zengshao0622** [comment]
由于代码中会根据model_name判断配置文件类型，如果使用自定义模型进行预测，会读取一般的分类任务配置文件，所以导致出现使用自定义模型进行预测时输出结果不是人体属性识别的结果。后续我们会考虑增加字段选择自定义模型的对应任务，感谢建议！
