### ISSUE TITLE
slim不能量化Deit，Deit不属于TheseusLayer？

### ISSUE THREAD

**Issue by wangzihanxmu** [PaddlePaddle/PaddleClas#2575]
release2.5：PaddleClas/ppcls/arch/__init__.py的第54行
“if isinstance(arch, TheseusLayer): ”
resnet就符合条件，但Deit就不符合条件，请问为什么呀

**Comment by zengshao0622** [comment]
目前仅有部分模型使用TheseusLayer实现，这部分模型主要是经典的骨干网络模型：PaddleClas/ppcls/arch/backbone/legendary_models

**Comment by wangzihanxmu** [comment]
哦哦这样，那不好意思请问一下如果想利用slim量化deit的话大概要怎么操作啊；
我试了下把vit的代码“class VisionTransformer(nn.Layer):”这里的nn.Layer换成了TheseusLayer，预训练模型精度是正常的，但用slim量化之后精度又变成从0开始了；
（我是一名大四本科生，毕设在做跟这个有关的东西，在这个位置卡了很久了，谢谢您）

**Comment by TingquanGao** [comment]
我们没有试过DeiT的量化，Swin之前试过用paddleslim的PACT，精度损失不大。训练配置和日志可以参考这里：
[train.log](https://github.com/PaddlePaddle/PaddleClas/files/10371639/train.log)
