### ISSUE TITLE
利用图像检索a类物体，检索库中包括了a类物体，然后检索的时候排除掉a，看看a和那些类的物体最相似

### ISSUE THREAD

**Issue by Firestick-Xia** [PaddlePaddle/PaddleClas#2576]
我遇到一个问题，利用图像检索a类物体，检索库中包括了a类物体，我想在检索的时候排除掉a，看看a和那些类的物体最相似？
如果建立一个不包含a的图像检索库，再去检索，感觉好繁琐，不知道有没有什么更好的方法，请求大佬支援

**Comment by RainFrost1** [comment]
可以使用原来的检索库，得到检索结果后，利用query的类别过滤一遍就好

**Comment by Firestick-Xia** [comment]
用a类检索，检索结果取top-n，排除掉是a类的结果，是这个意思吗？
 @RainFrost1

**Comment by Firestick-Xia** [comment]
> 可以使用原来的检索库，得到检索结果后，利用query的类别过滤一遍就好
用a类检索，检索结果取top-n，排除前x个都是a类的结果，是这个意思吗？

**Comment by RainFrost1** [comment]
> 用a类检索，检索结果取top-n，排除掉是a类的结果，是这个意思吗？ @RainFrost1

对的
