### ISSUE TITLE
安卓demo中VectorSearch.h中faiss报错导致无法运行

### ISSUE THREAD

**Issue by Satsna** [PaddlePaddle/PaddleClas#2593]
PaddleClas-release-2.5\deploy\shitu_android_demo路径下的安卓demo在WIN11中AndroidStudio运行报错
报错信息如下:

shitu_android_demo\app\src\main\cpp\VectorSearch.h:22:10: fatal error: 'include/faiss/Index.h' file not found

版本及环境如下:
1.win11系统
2.AndroidStudio版本:Chipmunk
3.PaddleClas版本:PaddleClas-release-2.5
4.Python版本: 3.9.13

**Comment by HydrogenSulfate** [comment]
请确认`include文件夹`路径是否严格按照文档里放置
![image](https://user-images.githubusercontent.com/23737287/211967791-e028fd02-705b-4a6a-92e6-b180a4c41626.png)

**Comment by Satsna** [comment]
刚开始研究, 不是很熟悉, 能提供一个完整能运行的demo吗?
我这边被这个问题困扰了3天,也没解决

**Comment by HydrogenSulfate** [comment]
> 刚开始研究, 不是很熟悉, 能提供一个完整能运行的demo吗? 我这边被这个问题困扰了3天,也没解决

显然Demo运行需要依赖于你的电脑和手机软硬件环境，我们这边无法直接提供

请参照[Demo文档](https://github.com/PaddlePaddle/PaddleClas/tree/develop/deploy/shitu_android_demo#demo%E5%BC%80%E5%8F%91%E4%BB%8B%E7%BB%8D)在Android Studio里操作就能在手机上运行一个完整的程序，建议仔细严格参照文档步骤进行操作，本文档有其他用户验证过是可以跑通运行的。

**Comment by Satsna** [comment]
┭┮﹏┭┮

**Comment by Satsna** [comment]
closed

**Comment by dlaoy** [comment]
> 请确认`include文件夹`路径是否严格按照文档里放置 ![image](https://user-images.githubusercontent.com/23737287/211967791-e028fd02-705b-4a6a-92e6-b180a4c41626.png)

[faiss1.5.3.tar.gz](https://paddle-inference-dist.bj.bcebos.com/faiss1.5.3.tar.gz)下载链接已失效

**Comment by dlaoy** [comment]
> 请确认`include文件夹`路径是否严格遵循文档里放置 ![图像](https://user-images.githubusercontent.com/23737287/211967791-e028fd02-705b-4a6a-92e6-b180a4c41626.png)

@HydrogenSulfate [faiss1.5.3.tar.gz](https://paddle-inference-dist.bj.bcebos.com/faiss1.5.3.tar.gz)下载链接已失效
