### ISSUE TITLE
couldn't find "libNative.so"

### ISSUE THREAD

**Issue by Satsna** [PaddlePaddle/PaddleClas#2594]
PaddleClas-release-2.5\deploy\shitu_android_demo安卓设备报错
报错信息如下:
2023-01-12 14:31:19.038 3597-3597/com.baidu.paddle.lite.demo.pp_shitu E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.baidu.paddle.lite.demo.pp_shitu, PID: 3597
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.baidu.paddle.lite.demo.pp_shitu-1/base.apk"],nativeLibraryDirectories=[/data/app/com.baidu.paddle.lite.demo.pp_shitu-1/lib/arm, /system/lib, /vendor/lib]]] couldn't find "libNative.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:984)
        at java.lang.System.loadLibrary(System.java:1562)
        at com.baidu.paddle.lite.demo.pp_shitu.Native.<clinit>(Native.java:26)
        at com.baidu.paddle.lite.demo.pp_shitu.MainActivity.<init>(MainActivity.java:112)

![1](https://user-images.githubusercontent.com/28588015/211996823-78a525d0-8261-47f1-b781-958718a137b6.png)

版本及环境如下:
安卓系统:7.1.2
设备芯片:Rockchip RK3288

**Comment by HydrogenSulfate** [comment]
本地没有遇到过这个问题，可以尝试使用Android Studio自动修复功能
![image](https://user-images.githubusercontent.com/23737287/212015220-a1e1c65d-7d11-47e0-af18-53f284b2a87f.png)
或者搜索引擎搜索解决方案

**Comment by Satsna** [comment]
AndroidStudio运行正常, 
打包可以正常运行在安卓手机上,安卓手机配置如下:安卓7.0系统,高通骁龙650处理器
但是无法运行在收银机机上,收银机上报错闪退无法打开,收银机配置如下安卓系统:7.1.2,设备芯片:Rockchip RK3288
收银机照片:

![7937921d063b9b11718908b0808dbb5](https://user-images.githubusercontent.com/28588015/212026420-891a5e09-9837-4b4a-8c40-bcfc59cb318f.jpg)

**Comment by HoneyLoveven** [comment]
请问一下如何处理这个问题的
