### ISSUE TITLE
export_model

### ISSUE THREAD

**Issue by key-1994** [PaddlePaddle/PaddleClas#260]
MobileNetV3系列的预训练模型格式不太一样，如何转为预测部署的固化模型

**Comment by littletomatodonkey** [comment]
你说的预训练模型格式不同指的是什么呢？

**Comment by key-1994** [comment]
自己训练的MobileNetV2_x0_25模型在export_model.py时报错
Error: Tensor not initialized yet when Tensor::type() is called.
  [Hint: holder_ should not be null.] at (D:\1.8.4\paddle\paddle/fluid/framework/tensor.h:140)
  [operator < save_combine > error]

**Comment by littletomatodonkey** [comment]
> 自己训练的MobileNetV2_x0_25模型在export_model.py时报错
> Error: Tensor not initialized yet when Tensor::type() is called.
> [Hint: holder_ should not be null.] at (D:\1.8.4\paddle\paddle/fluid/framework/tensor.h:140)
> [operator < save_combine > error]

麻烦发下你的导出模型的脚本和预训练模型的地址吧，看着是模型没有载入成功，导致导出失败
