### ISSUE TITLE
PaddleClas怎么没有像PaddleDetection和PaddleSeg类似的自制数据集划分工具

### ISSUE THREAD

**Issue by D-ai-Y** [PaddlePaddle/PaddleClas#2608]
PaddleClas缺乏自制数据集划分工具，无法让使用者快速开展自身数据集的训练及评估工作

**Comment by D-ai-Y** [comment]
作为PaddleDetection和PaddleSeg都使用过的用户，感觉PaddleClas现有使用指引在自定义数据集上不是很顺畅

**Comment by cuicheng01** [comment]
这里数据集制作相对容易，所以一直没有增加该模块，不过您的建议很重要，后续我们会考虑添加
