### ISSUE TITLE
静态图训练接口，不支持swin transformer训练

### ISSUE THREAD

**Issue by xiaolaoshu156** [PaddlePaddle/PaddleClas#2622]
tags: v2.5.1
使用ppcls/static/train.py训练swin transformer报错，修改后训练不收敛。
主要修改代码：
swin_transformer.py:

- self.register_buffer("relative_position_index",  relative_position_index) 改为 self.relative_position_index = relative_position_index
- self.register_buffer("relative_position_bias", relative_position_bias) 改为 self.relative_position_bias = relative_position_bias
- self.register_buffer("attn_mask", attn_mask) 改为 self.attn_mask = attn_mask

vision_transformer.py:

- keep_prob = paddle.to_tensor(1 - drop_prob) 改为 keep_prob = paddle.ones(shape=[1]).astype(x.dtype) * (1 - drop_prob)
修改后可以训练，但是模型不收敛。

**Comment by cuicheng01** [comment]
目前这个static分支不支持新模型了，只在维护老模型，如果希望使用静态图训练，可以在config中`Global`下添加字段`to_static`，设置为`True`即可。
