### ISSUE TITLE
paddlecls 训练出的模型可以用paddlex的C#部署API接口加载吗? 

### ISSUE THREAD

**Issue by dongyangli-del** [PaddlePaddle/PaddleClas#2630]
# 环境
 1. PaddleClas == release/2.5
 2. PaddlePaddle-gpu==2.3.2
 3. Paddlex==2.1.0
# 训练环境信息：
  a. 具体操作系统，Ubuntu20.0.4
  b. Python版本号，Python==3.9
  c. CUDA/cuDNN版本， CUDA==11.6, cuDNN==8.6.5

# 问题
paddlecls 训练出的模型可以用paddlex的C#部署API接口加载吗? 如果需要转换格式该如何转换呢?

这个是paddlex训练出的模型文件夹:

![a2](https://user-images.githubusercontent.com/62006079/216964544-b9b5f9e5-b05f-434f-8cf0-a900f04f62b3.png)

这个是paddlecls训练出的模型文件夹:

![a3](https://user-images.githubusercontent.com/62006079/216964620-7601bbc9-7cbd-4e85-8541-4de448c566fa.png)

怎么进行模型格式的转换才能满足pddlex的C# API所要求的模型格式呢?(带model.yml的那种) 不知道我的描述是否清楚.

**Comment by RainFrost1** [comment]
PaddleClas和PaddleX有些许不同，PaddleClas的模型定义是基于网络的定义代码，模型保存了模型权重（.pdparams)、优化器状态（.pdopt)和模型训练的一些状态（.pdstates)，而PaddleX保存了模型的定义（model.yml）。PaddleClas中model.yml这个不太好添加转化。具体可以将PaddleClas中模型定义的py文件迁移到PaddleX中，导出一个model.yml文件，再结合paddleClas的权重，进行尝试
