### ISSUE TITLE
具体代码

### ISSUE THREAD

**Issue by stu977** [PaddlePaddle/PaddleClas#2639]
想问一下论文中的代码具体在哪一部分

**Comment by zengshao0622** [comment]
请问你指的论文是？

**Comment by stu977** [comment]
Implicit Sample Extension for Unsupervised Person Re-Identification这一篇

**Comment by stu977** [comment]
Implicit Sample Extension for Unsupervised Person Re-Identification这一篇

**Comment by stu977** [comment]
> 请问你指的论文是？

Implicit Sample Extension for Unsupervised Person Re-Identification这一篇

**Comment by zengshao0622** [comment]
Paddle训练代码作者暂时还未公布，具体文档可参考：https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/algorithm_introduction/ISE_ReID.md
