### ISSUE TITLE
灰度图可以训练么

### ISSUE THREAD

**Issue by key-1994** [PaddlePaddle/PaddleClas#264]
可以使用灰度图像库训练么

**Comment by littletomatodonkey** [comment]
你好，可以的，不过数据预处理那块可能需要适配一下，之前的增广都是默认RGB图像训练的，你可以先把灰度图像扩充一个3通道的，预处理完成之后再变为单通道图像，同时image shape这块也需要修改为`[1, 224, 224]`

https://github.com/PaddlePaddle/PaddleClas/blob/162281e7d6c6b7c0fd226c704c14bb5968c6c052/configs/ResNet/ResNet50.yaml#L14
