### ISSUE TITLE
关于RandomApply的问题。

### ISSUE THREAD

**Issue by AllenWrong** [PaddlePaddle/PaddleClas#2645]
PaddleClas的develop分支。
[代码链接](https://github.com/PaddlePaddle/PaddleClas/blob/develop/ppcls/data/preprocess/ops/randaugment.py#L160)

这里的RandomApply好像并没有用到`self.p`。

**Comment by zengshao0622** [comment]
感谢反馈！我们后续会进行修改。

**Comment by zengshao0622** [comment]
#2648

**Comment by zh-hike** [comment]
> PaddleClas的develop分支。 [代码链接](https://github.com/PaddlePaddle/PaddleClas/blob/develop/ppcls/data/preprocess/ops/randaugment.py#L160)
> 
> 这里的RandomApply好像并没有用到`self.p`。

最新的develop分支已修复这个问题。
