### ISSUE TITLE
PULC train vehicle_attribute脚本出错

### ISSUE THREAD

**Issue by zhanglei-rlsd-vip** [PaddlePaddle/PaddleClas#2646]
你好：
运行环境如下：
硬件平台 Jetson AGX Orin
操作系统 ubuntu20.04
CUDA 11.4.239
PaddlePaddle 2.4
我参考https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/training/PULC.md
进行自定义数据集分类训练，
python脚本
python3 -m paddle.distributed.launch --gpus="0" -c ./ppcls/configs/PULC/vehicle_attribute/PPLCNet_x1_0.yaml
运行时报错如下：
  File "./ppcls/configs/PULC/vehicle_attribute/PPLCNet_x1_0.yaml", line 2
    Global:
          ^
SyntaxError: invalid syntax

请问如何解决，谢谢

**Comment by zh-hike** [comment]
> 
从报错信息来看，应该是.yaml文件的格式不对，方便提供一下.yaml文件么

**Comment by zhanglei-rlsd-vip** [comment]
感谢回复，我是从github上直接下载的
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/ppcls/configs/PULC/vehicle_attribute/PPLCNet_x1_0.yaml
本地开发环境截图如下：
<img width="557" alt="1676271098789" src="https://user-images.githubusercontent.com/121075017/218390339-73a2828e-e512-4c1c-873e-3c6f7c9e8bd4.png">
训练报错会和文件本身的格式有关吗？
谢谢

**Comment by zh-hike** [comment]
> 

这么看格式应该是没问题的，可以提供一下完整的报错信息么
