### ISSUE TITLE
分类模型是否支持再训练

### ISSUE THREAD

**Issue by xujiang1** [PaddlePaddle/PaddleClas#2647]
我使用分类模型训练了一个模型，效果为top1:0.9 在使用过程中我收集了识别错误的数据 进行再次训练，对老数据的识别降低了，请问我是过拟合了吗，另外这种提高精度的方法可取吗，需要注意什么

**Comment by zh-hike** [comment]
> 我使用分类模型训练了一个模型，效果为top1:0.9 在使用过程中我收集了识别错误的数据 进行再次训练，对老数据的识别降低了，请问我是过拟合了吗，另外这种提高精度的方法可取吗，需要注意什么

感觉这种方式不太可取，识别错误的数据按理说是较难识别的样本，在训练过程中应该更加注意这些样本的识别才能提高模型的泛化能力，如果不断地移除识别错误的样本（对于模型来说较难识别的样本），那么只剩余简单的样本，这样在测试阶段稍微遇到一些难样本可能就会识别错误。建议观察数据集的特征，选择合适的数据增强。

**Comment by zh-hike** [comment]
> 我使用分类模型训练了一个模型，效果为top1:0.9 在使用过程中我收集了识别错误的数据 进行再次训练，对老数据的识别降低了，请问我是过拟合了吗，另外这种提高精度的方法可取吗，需要注意什么

算是过拟合，如果再次训练只针对识别错误的样本，那么很有可能会让那些本来就识别准确的样本变成识别错误。如果你想让模型放低对识别正确样本的关注的话，FocalLoss也许是你想要的。
