### ISSUE TITLE
关于主体检测

### ISSUE THREAD

**Issue by Jeling-W** [PaddlePaddle/PaddleClas#2650]
请问我用Paddledetection训练完主体检测后，进行推理，并对结果可视化，然后导出模型用于paddleclass，设置
                      rec_nms_thresold: 1
主体检测的：threshold: 与paddledetection中可视化的阈值是一样的，设为0.2
                      max_det_results: 100
paddleclass: return_k: 100
                    score_thres: 0.1
底库数据也没有问题，但这样输出的结果只有图像最外围的边框，本该主体检测能检测出的边框都没有，是什么原因呢

**Comment by RainFrost1** [comment]
建议先debug一下，查看一下检测部分的输出。检测部分输出后，默认会加上一个全图的逻辑，然后各bbox提取特征后进行检索结果排序。可以查看哪一步把数据过滤掉了，根据自己的需求修改下逻辑
