### ISSUE TITLE
模型配置yml文件中的参数有相关完整文档来解析的吗

### ISSUE THREAD

**Issue by anheidadi** [PaddlePaddle/PaddleClas#2651]
模型的配置里面的参数有什么可选项和相关文档来解释。例如PaddleClas\ppcls\configs\PULC\vehicle_attribute下的PPLCNet_x1_0.yaml中
“
Loss:
  Train:
    - MultiLabelLoss:
        weight: 1.0
        weight_ratio: True
        size_sum: True
  Eval:
    - MultiLabelLoss:
        weight: 1.0
        weight_ratio: True
        size_sum: True

”
我不太清楚loss有哪些可选的。希望能得到帮助

**Comment by RainFrost1** [comment]
https://github.com/PaddlePaddle/PaddleClas/tree/release/2.5/docs/zh_CN/training/config_description，可以看下config说明
loss：具体可以看下https://github.com/PaddlePaddle/PaddleClas/tree/release/2.5/ppcls/loss
