### ISSUE TITLE
如何直接拿预训练模型进行预测？ --m参数应该填什么？

### ISSUE THREAD

**Issue by Derek-Kun** [PaddlePaddle/PaddleClas#266]
我看有一个10万分类的预训练模型，下载下来以后里面是一个ResNet50_vd_10w_pretrained文件夹，里面都是weights,mean,variance等文件，下载的其它ResNet50_vd_pretrained预训练模型里面也是这样， 看教程说分类预测框架有三种，下载的哪些预训练模型都没有MODEL文件，所以我猜应该是persistable 模型，可是不管是模型转换然后再预测还是直接 “训练引擎 + persistable 模型预测”，都有一个  “--m=模型名称 “参数，我填了ResNet50_vd_10w_pretrained就报错说KEY错误，里面的介绍是”model_file(简写 m)：模型文件路径，如 ./resnet50-vd/model“，可是persistable 模型里面根本就没有MODEL文件，要转换的还还是要输入
python tools/export_model.py \
    --m=模型名称 \
    --p=persistable 模型路径 \
    --o=model和params保存路径

我真不知道该怎么用预训练模型预测了。有大神来讲一下吗？

**Comment by littletomatodonkey** [comment]
你好，可以先导出模型，以resnet50为例

```
python tools/export_model.py
--m=ResNet50
--p=./pretrained_models/ResNet50_pretrained  # 这个就是你下载的文件路径
--o=./inference
```
之后使用predict.py进行预测：
```
python tools/infer/predict.py -i ./xxx.jpg -m ./inference/model -p ./inference/params
```

**Comment by Derek-Kun** [comment]
你好，我用RESNET50是正常的，也可以先导出模型，问题就是个ResNet50_vd_10w_pretrained的--m名字不知道填啥，我填ResNet50_vd_10w就会报keyerror,如果我填ResNet50或者ResNet50_vd就会报别的错误，比方下面这行命令
python tools/export_model.py --m=ResNet50_vd --p=/home/PaddleClas/pretrained/ResNet50_vd_10w_pretrained --o=/home/PaddleClas/ResNet50_vd_10w_pretrained
就会报错：
Error: Tensor not initialized yet when Tensor::type() is called.
  [Hint: holder_ should not be null.] at (/paddle/paddle/fluid/framework/tensor.h:140)
  [operator < save_combine > error]

![图片](https://user-images.githubusercontent.com/57475881/92443164-b41ea980-f1e3-11ea-8520-a48a4007348e.png)

**Comment by littletomatodonkey** [comment]
你好，这个模型属于ResNet50_vd，但是它没有提供fc层，所以没法用来预测，只能用来finetune~

**Comment by Derek-Kun** [comment]
好的收到，非常感谢~
