### ISSUE TITLE
PPLCNet-2.5的ReID模型训练有配置文件吗？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleClas#2665]
我在PaddleDetection上看到
![image](https://user-images.githubusercontent.com/26297768/221106387-61023e30-db5d-4db2-a36f-604aff5ae340.png)

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/configs/mot/deepsort/reid/README_cn.md

但是行人重识别的我只看到这三个：
https://github.com/PaddlePaddle/PaddleClas/tree/release/2.5/ppcls/configs/reid/strong_baseline

**Comment by zengshao0622** [comment]
这里的模型应该指的是ResNet101和PPLCNet-2.5x两个骨干模型由PaddleClas提供，具体可参考：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/models/ImageNet1k/ResNet.md 和https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/models/ImageNet1k/PP-LCNet.md
