### ISSUE TITLE
Engine.infer()方法的行为很奇怪

### ISSUE THREAD

**Issue by parap1uie-s** [PaddlePaddle/PaddleClas#2688]
Engine.infer()方法没有返回值，而是将预测结果print至控制台，甚至没有使用logger等常用的日志工具。详见：

https://github.com/PaddlePaddle/PaddleClas/blob/4cd9dc0e057331a65257d53938f64804fca020ac/ppcls/engine/engine.py#L539-L544

**Comment by RainFrost1** [comment]
欢迎提pr，修复一下~
