### ISSUE TITLE
A UnicodeDecodeError when run the code:

### ISSUE THREAD

**Issue by qingweihk** [PaddlePaddle/PaddleClas#269]
The error are as flowing:

UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-13-b251ca09833e> in <module>()
     18 fnames = os.listdir(imgs_dir)
     19 for f in fnames:
---> 20     data = open(os.path.join(imgs_dir, f)).read()
     21     img = transform(data, ops)

/usr/lib/python3.6/codecs.py in decode(self, input, final)
    319         # decode input (taking the buffer into account)
    320         data = self.buffer + input
--> 321         (result, consumed) = self._buffer_decode(data, self.errors, final)
    322         # keep undecoded input until the next call
    323         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by littletomatodonkey** [comment]
你好，可以试着把`open(os.path.join(imgs_dir, f)).read()`改为`open(os.path.join(imgs_dir, f), 'rb').read()`试下，或者拉下最新的代码
