### ISSUE TITLE
按照教程数据增广后，图片没有变化？

### ISSUE THREAD

**Issue by qingweihk** [PaddlePaddle/PaddleClas#270]
按照教程如下的代码，对图像进行变换：但变换完的图像无变化喔
from ppcls.data.imaug import DecodeImage
from ppcls.data.imaug import ResizeImage
from ppcls.data.imaug import ToCHWImage
from ppcls.data.imaug import GridMask
from ppcls.data.imaug import transform

size = 224
# 图像解码
decode_op = DecodeImage()
# 图像随机裁剪
resize_op = ResizeImage(size=(size, size))
# 图像数据的重排
tochw_op = ToCHWImage()
# 使用GridMask图像增广方法
gridmask_op = GridMask(d1=96, d2=224, rotate=1, ratio=0.6, mode=1, prob=0.8)

ops = [decode_op, resize_op, tochw_op, gridmask_op]
# 图像路径
imgs_dir = '/content/yolov5/inference/images'
fnames = os.listdir(imgs_dir)
for f in fnames:
    data = open(os.path.join(imgs_dir, f),'rb').read()
    img = transform(data, ops)
    img = img.transpose((1, 2, 0))

**Comment by littletomatodonkey** [comment]
你好，gridmask是根据epoch的数量逐渐增加增广的概率的，你自己尝试的时候，可以将这个`CURR_EPOCH `值修改为240(和NUM_EPOCHS保持一致)，这样真实的概率就变为0.8（设置的默认值）

https://github.com/PaddlePaddle/PaddleClas/blob/162281e7d6c6b7c0fd226c704c14bb5968c6c052/ppcls/data/imaug/grid.py#L22

**Comment by qingweihk** [comment]
> 你好，gridmask是根据epoch的数量逐渐增加增广的概率的，你自己尝试的时候，可以将这个`CURR_EPOCH `值修改为240(和NUM_EPOCHS保持一致)，这样真实的概率就变为0.8（设置的默认值）
> 
> https://github.com/PaddlePaddle/PaddleClas/blob/162281e7d6c6b7c0fd226c704c14bb5968c6c052/ppcls/data/imaug/grid.py#L22

谢谢，另外想问下：按照以上gridmask数据增广后，数据量是变成原来的2倍还是数据量不变？如果变成两倍的话，那新生成的图片所对应的标签是系统自动生成么？

**Comment by littletomatodonkey** [comment]
数据量是不变的，新生成的图片对应的标签和原始图片是一样的
