### ISSUE TITLE
paddleclas前向推理的时候遇到的问题，deploy/python/predict_cls运行报错

### ISSUE THREAD

**Issue by qumoy** [PaddlePaddle/PaddleClas#2702]
from .ppcls.arch import backbone
ImportError: attempted relative import with no known parent package

**Comment by qumoy** [comment]
版本release/2.5

**Comment by zhanghangzzz** [comment]
请问你是怎么解决这个问题的？是需要将paddleclas的版本设置为2.5吗？能否详细讲讲，谢谢

**Comment by Quentin-Song** [comment]
> 版本release/2.5
请问是怎么解决的
