### ISSUE TITLE
动态图中加载模型报错

### ISSUE THREAD

**Issue by lwbmowgli** [PaddlePaddle/PaddleClas#272]
![image](https://user-images.githubusercontent.com/32731935/92579338-a6d6ed00-f2bf-11ea-8234-74ab58996234.png)
报错信息如上图所示，采用的模型是飞桨官方下载的模型，未进行任何改动，尝试了HRNet以及Resnet，均出现如上报错。
[这个是我在aistudio平台上的项目地址](https://aistudio.baidu.com/bdvgpu32g/user/228777/883366/notebooks/883366.ipynb)
加载模型的方法我参考了[paddleclas](https://gitee.com/paddlepaddle/PaddleClas/blob/dygraph/tools/infer/infer.py)中加载的方法。请您看一下，谢谢。

**Comment by littletomatodonkey** [comment]
你好，你使用的Paddle版本是多少呢？建议使用Paddle2.0或者Paddle-latest的版本~
