### ISSUE TITLE
细粒度的分类的模型选择

### ISSUE THREAD

**Issue by happybear1015** [PaddlePaddle/PaddleClas#2771]
请问：要进行细粒度的分类（就是特别难分类的），采用哪种模型比较好呢？

**Comment by zengshao0622** [comment]
可以参考[文档](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/models/ImageNet1k/ResNet.md)选择符合要求的模型，通常来说ImageNet上表现较好的模型在细粒度分类任务也能有较好的表现。不过，也有一部分工作会针对细粒度分类任务进行特殊的模型设计，例如加入高阶特征建模等。

**Comment by happybear1015** [comment]
收到

**Comment by happybear1015** [comment]
ok
