### ISSUE TITLE
请问这个ResNet50_vd_ssld_v2模型的配置文件在哪里呢？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleClas#279]
预训练模型中提供了 ResNet50_vd_ssld_v2 模型，但是我在配置文件夹中找不到这个文件。

**Comment by littletomatodonkey** [comment]
你好，可以在这里下载：https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_v2_pretrained.tar

**Comment by yeyupiaoling** [comment]
@littletomatodonkey 你好，我问的是配置文件yaml，不是预训练文件

**Comment by littletomatodonkey** [comment]
这个配置文件没有提供的，你是要训蒸馏模型吗？

**Comment by yeyupiaoling** [comment]
@littletomatodonkey 不用，我用的是量化训练，蒸馏还没搞懂

**Comment by littletomatodonkey** [comment]
哦哦，这个ssld_v2模型文件的配置没有提供，超参配置的话可以参考蒸馏文档

**Comment by yeyupiaoling** [comment]
好的，谢谢
