### ISSUE TITLE
请问 dygraph 用的paddle版本是什么呐，必须使用编译版本的么？

### ISSUE THREAD

**Issue by ARQlalala** [PaddlePaddle/PaddleClas#280]
hi，问个简单的问题，用develop和paddle 1.8.4 时候LinearLrWarmup这些 paddle.optimizer.lr_scheduler还有ParallelEnv都没有呐，必须要使用编译版本的paddle么

**Comment by littletomatodonkey** [comment]
你好，可以试下2.0.0b0的paddle版本哈，这里都是有的, `pip install paddlepaddle-gpu==2.0.0b0`即可

**Comment by ARQlalala** [comment]
嗯嗯 环境准备好了，
对于单机多卡来说，运行指令如下：
python3 -m paddle.distributed.launch \
    --selected_gpus="0,1,2,3" \
    tools/train.py \
        -c ./configs/ResNet/ResNet50.yaml \
        -o print_interval=10
~

然后错误如下：
Please make sure the version is good with your code.
INFO 2020-09-17 14:11:16,592 utils.py:269] terminate all the procs
ERROR 2020-09-17 14:11:16,593 utils.py:439] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] was aborted. Please check its log.
INFO 2020-09-17 14:11:19,593 utils.py:269] terminate all the procs

请问这个是需要修改什么参数呐

**Comment by littletomatodonkey** [comment]
> 嗯嗯 环境准备好了，
> 对于单机多卡来说，运行指令如下：
> python3 -m paddle.distributed.launch
> --selected_gpus="0,1,2,3"
> tools/train.py
> -c ./configs/ResNet/ResNet50.yaml
> -o print_interval=10
> ~
> 
> 然后错误如下：
> Please make sure the version is good with your code.
> INFO 2020-09-17 14:11:16,592 utils.py:269] terminate all the procs
> ERROR 2020-09-17 14:11:16,593 utils.py:439] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] was aborted. Please check its log.
> INFO 2020-09-17 14:11:19,593 utils.py:269] terminate all the procs
> 
> 请问这个是需要修改什么参数呐

你好，这个是版本check出现问题了，因为现在发布的2.0.0b0版本，所以check会失败，你可以拉下最新的clas代码，或者修改下代码的这里

https://github.com/PaddlePaddle/PaddleClas/blob/39c24c1cb61c9fb46bc78ce3debf845164f5f569/ppcls/utils/check.py#L40

**Comment by ARQlalala** [comment]
嗯嗯好的，请教下，在paddle-gpu 2.0-beta版本中使用paddle.randperm函数，报错
----------------------
Error Message Summary:
----------------------
UnimplementedError: Place CUDAPlace(0) is not supported. Please check that your paddle compiles with WITH_GPU or WITH_XPU option or check that your train process hold the correct gpu_id if you use Executor. (at /paddle/paddle/fluid/platform/device_context.cc:67)
  [operator < randperm > error]

这个是数据的操作要转成cuda模式么，在paddle中需要怎么转呢，谢谢~

**Comment by littletomatodonkey** [comment]
> ## 嗯嗯好的，请教下，在paddle-gpu 2.0-beta版本中使用paddle.randperm函数，报错
> ## Error Message Summary:
> UnimplementedError: Place CUDAPlace(0) is not supported. Please check that your paddle compiles with WITH_GPU or WITH_XPU option or check that your train process hold the correct gpu_id if you use Executor. (at /paddle/paddle/fluid/platform/device_context.cc:67)
> [operator < randperm > error]
> 
> 这个是数据的操作要转成cuda模式么，在paddle中需要怎么转呢，谢谢~

你是怎么使用的呢？应该不用转成cuda模式的，看着是你的Paddle安装的不是gpu版本的
```
import paddle
paddle.disable_static()
out1 = paddle.randperm(5)
```
