### ISSUE TITLE
Provide full log of DyGraph Mobilenet training on flowers dataset

### ISSUE THREAD

**Issue by arlesniak** [PaddlePaddle/PaddleClas#282]
@littletomatodonkey  Could you provide full log of DyGraph Mobilenet training on flowers dataset as mentioned in https://github.com/PaddlePaddle/models/issues/4849 for download ? We are interested in MobilenetV1 but also other versions.

**Comment by littletomatodonkey** [comment]
Thanks for your attention, the full log will be offered and uploaded here in this weekend.

**Comment by littletomatodonkey** [comment]
> @littletomatodonkey Could you provide full log of DyGraph Mobilenet training on flowers dataset as mentioned in [PaddlePaddle/models#4849](https://github.com/PaddlePaddle/models/issues/4849) for download ? We are interested in MobilenetV1 but also other versions.

Hi, the log is as followes, the backbone is MobileNetV3_large_x1_0. The config file I used is this: https://github.com/PaddlePaddle/PaddleClas/blob/dygraph/configs/quick_start/MobileNetV3_large_x1_0_finetune.yaml
The ImageNet pretrained weights are used for better performance.

[train_flowers102_mv3_large_x1_0.log](https://github.com/PaddlePaddle/PaddleClas/files/5244800/train_flowers102_mv3_large_x1_0.log)
