### ISSUE TITLE
Mixup报错

### ISSUE THREAD

**Issue by youwei2567** [PaddlePaddle/PaddleClas#2821]
use_mix: True是在yaml里面配置吗，我配置完了，然后出现下面错误：
ValueError: (InvalidArgument) ShapeError: label's dimensions of AccuracyOp must be 2. But received label's dimensions = 1, label's shape = [64]
  [Hint: Expected label_dim.size() == 2, but received label_dim.size():1 != 2:2.] (at ..\paddle\phi\infermeta\ternary.cc:44)
  [operator < accuracy > error]

**Comment by cuicheng01** [comment]
这个是哪个版本的PaddleClas呢

**Comment by youwei2567** [comment]
2.2版本的，我刚换了2.5，就没这个问题了

**Comment by youwei2567** [comment]
不过2.5需要设置use_mix？

**Comment by cuicheng01** [comment]
不需要，在数据增强处增加相关的mixup的预处理就好了

**Comment by youwei2567** [comment]
好的，谢谢
