### ISSUE TITLE
如何自定义自己的dataloader？

### ISSUE THREAD

**Issue by 0-LL-0** [PaddlePaddle/PaddleClas#2870]
1：能否提供自定义的dataloader官方教程或者示例文档？
2：dataset中name除了ImageNetDataset，还有哪些？能否提供一下示例指引？

![image](https://github.com/PaddlePaddle/PaddleClas/assets/12853603/52994e1a-808d-44be-95c4-549c971e8873)

**Comment by TingquanGao** [comment]
可以参考这个文件中的 ***Dataset 类，如 ImageNetDataset，MultiLabelDataset 等。

https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/ppcls/data/dataloader/__init__.py

**Comment by Li-Lai** [comment]
@TingquanGao 感谢上述回复。我的网络有
