### ISSUE TITLE
警告:Warning:Tensor.numpy()[0]' to 'float(Tensor)' 在哪里改呢应该？

### ISSUE THREAD

**Issue by Zhw1997** [PaddlePaddle/PaddleClas#2881]
环境如下：
 1. PaddleClas release/2.5 paddlepaddle2.5.0
 3. 训练环境信息：
  a. 操作系统 Windows11
  b. Python版本号=Python3.7
  c. CUDA/cuDNN版本， 如CUDA11.6
具体报警如下：I0723 10:43:00.096150 18988 eager_method.cc:140] Warning:: 0D Tensor cannot be used as 'Tensor.numpy()[0]' . In order to avoid this problem, 0D Tensor will be changed to 1D numpy currently, but it's not correct and will be removed in release 2.6. For Tensor contain only one element, Please modify 'Tensor.numpy()[0]' to 'float(Tensor)' as soon as possible, otherwise 'Tensor.numpy()[0]' will raise error in release 2.6.
应该是需要改为float(Tensor)就可以了，但是并不知道在哪里修改？

**Comment by TingquanGao** [comment]
运行命令是什么？我们复现一下

**Comment by Zhw1997** [comment]
> 运行命令是什么？我们复现一下

就很简单的 ：-c  ppcls/configs/Vehicle/ResNet50_ReID.yaml

**Comment by Zhw1997** [comment]
> 运行命令是什么？我们复现一下

就很简单的 ：python tools/train.py -c ppcls/configs/Vehicle/ResNet50_ReID.yaml

**Comment by awarebayes** [comment]
Same here, with -c ./ppcls/configs/reid/strong_baseline/softmax_triplet_with_center.yaml
Paddle release is 2.6

**Comment by ShawnNew** [comment]
you may refer to https://github.com/PaddlePaddle/PaddleClas/pull/2891/files

**Comment by Zhw1997** [comment]
> you may refer to https://github.com/PaddlePaddle/PaddleClas/pull/2891/files

Thank you! 
I solved my problem. 解决了，谢谢！

**Comment by hzauliutingting** [comment]
> 谢

您好，请问这个ppcles在哪呀

**Comment by hzauliutingting** [comment]
> > you may refer to https://github.com/PaddlePaddle/PaddleClas/pull/2891/files
> 
> Thank you! I solved my problem. 解决了，谢谢！

您好，请问这个ppcls在哪里呀

**Comment by ChnIRuI** [comment]
> > > you may refer to https://github.com/PaddlePaddle/PaddleClas/pull/2891/files
> > 
> > 
> > Thank you! I solved my problem. 解决了，谢谢！
> 
> 您好，请问这个ppcls在哪里呀

有找到ppcls嘛
