### ISSUE TITLE
加载预训练参数（ghostnet）

### ISSUE THREAD

**Issue by kymoran3169** [PaddlePaddle/PaddleClas#289]
我最近在使用ghostnet网络模型的时候，加载预训练参数一直出现问题。
预训练参数是 GhostNet_x1_3 下载位置在： https://github.com/PaddlePaddle/PaddleClas
使用的代码来自 https://github.com/PaddlePaddle/PaddleClas/tree/master/ppcls/modeling/architectures
1. 对照修改 了 scale , 尝试修改 了 gn 或者bn ,
2. 之后又修改了加载方式，尝试了包括 load_vars ,和load 函数，因为是二进制.pdparams文件还修改了 filename参数

问题是，上述修改方式均无效，无论怎么修改，所有训练参数包括 ‘’开头的 一个单卷积‘’ 都加载不进去
希望能够提供一些帮助，或者将预训练参数改为文件夹形式，但文件参数确实不好加载

**Comment by littletomatodonkey** [comment]
你好，GhostNet的下载地址在这里：https://paddle-imagenet-models-name.bj.bcebos.com/GhostNet_x1_3_pretrained.pdparams

预测命令为

```
python3.7 tools/infer/infer.py -i test.jpg -m GhostNet_x1_3 -p GhostNet_x1_3_pretrained
```

你按照这个试下呢？

**Comment by kymoran3169** [comment]
您好，
&nbsp; &nbsp; &nbsp; 你这里提供的下载地址和我之前的下载地址是一样的。而且不好意思的是，我是做分割的。
&nbsp; &nbsp; &nbsp; 使用ghost 也是为了做骨干网进行训练，现在重新搭建分类代码也比较慢。
&nbsp; &nbsp; &nbsp; 随邮件附上报错截图，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleClas"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月23日(星期三) 中午11:17
收件人:&nbsp;"PaddlePaddle/PaddleClas"<PaddleClas@noreply.github.com&gt;;
抄送:&nbsp;"赵开元"<1205029393@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleClas] 加载预训练参数（ghostnet） (#289)





 
你好，GhostNet的下载地址在这里：https://paddle-imagenet-models-name.bj.bcebos.com/GhostNet_x1_3_pretrained.pdparams
 
预测命令为
 python3.7 tools/infer/infer.py -i test.jpg -m GhostNet_x1_3 -p GhostNet_x1_3_pretrained  
你按照这个试下呢？

**Comment by littletomatodonkey** [comment]
这地方显示不了截图，你可以去PaddleSeg图像分割库提一个issue
