### ISSUE TITLE
推理报错

### ISSUE THREAD

**Issue by umie0128** [PaddlePaddle/PaddleClas#2900]
![image](https://github.com/PaddlePaddle/PaddleClas/assets/49420977/70ea56cc-673e-45ec-adac-f95a8d472095)
ubuntu 18.04版本 物理机

**Comment by umie0128** [comment]
@cuicheng01

**Comment by TingquanGao** [comment]
运行命令是什么？

**Comment by umie0128** [comment]
> 
是集成在一个推理脚本里面 但是同一份代码 同事的环境可以运行 我的就报这个错误

**Comment by TingquanGao** [comment]
你这个截图的报错信息上没看出具体问题，看起来是做onnx部署？可以试试重新配置onnx的环境。
