### ISSUE TITLE
PP-ShiTu V2主体检测静态图模型无法转成ONNX

### ISSUE THREAD

**Issue by Zheng-Bicheng** [PaddlePaddle/PaddleClas#2919]
## 设备开发环境

* PaddleClas版本型号: develop
* CPU架构: Arm aarch64
* 部署设备: RKNPU2

## 需求说明

Paddle模型在国内各大厂商的设备上部署很大一部分依赖 ONNX -> Deivece Model的模式，PP-ShiTu V2主体检测静态图模型无法转成ONNX意味着无法在很多设备上实现部署，有考虑优化后处理，改成ONNX兼容的格式吗？

## 个人思路

我的理解上用现在最新的PaddleDetection重新训练一次就行，本来是自己动手训练的，但是我没有处理好的数据集。

**Comment by Zheng-Bicheng** [comment]
@TingquanGao

**Comment by cuicheng01** [comment]
这块是可以导出的，不知道遇到了什么问题呢
