### ISSUE TITLE
ESE 的术语全名是什么呢？

### ISSUE THREAD

**Issue by thsno02** [PaddlePaddle/PaddleClas#2923]
PPHGNet 中有一个 ESE Module，该模块使用自适应卷积操作固定输出大小。我不是很清楚 ESE 表示什么意思呢？

https://github.com/PaddlePaddle/PaddleClas/blob/9984080a3d7ca52dd9044afaae1df1bed676fd1c/ppcls/arch/backbone/legendary_models/pp_hgnet.py#L74-L91

**Comment by cuicheng01** [comment]
Efficient Squeeze-and-Excitation
