### ISSUE TITLE
图像增广方式太少了

### ISSUE THREAD

**Issue by Smalltiger729** [PaddlePaddle/PaddleClas#293]
8个图像增广方式会不会比较少。可不可以用albumentations的方式去进行增广

**Comment by littletomatodonkey** [comment]
你好，是可以的，按照这里的方式添加一个图片预处理或者增广的类即可。

https://github.com/PaddlePaddle/PaddleClas/blob/4714c71a593bb767e24449f628316ccea4295f49/ppcls/data/imaug/operators.py#L65
