### ISSUE TITLE
PaddleClas/ppcls/loss/tripletangularmarginloss.py中的输入参数target维度代表什么呢？

### ISSUE THREAD

**Issue by zhishao** [PaddlePaddle/PaddleClas#2930]
可否举例说明 谢谢。
![image](https://github.com/PaddlePaddle/PaddleClas/assets/18610954/4aa01126-c899-40ea-82f1-5375f47a00f9)

**Comment by HydrogenSulfate** [comment]
input是指Batchsize个样本经过模型提取出来的特征，形状是[B,F]，target是指batchsize个样本各自的标签，形状应该是[B,]或者[B,1]，这里看起来应该是文档写错了，num_classes的意思是说标签的范围是[0, num_classes)

**Comment by zhishao** [comment]
@HydrogenSulfate 非常感谢您。是的我测试时发现target只有维度为(bs)时可以执行。
但是我测试时发现这个loss会报错，也可能是我使用的问题，我的测试代码如下：
    import paddle
    import numpy as np
    # classes 1000 #
    paddle.set_device("cpu")
    loss = TripletAngularMarginLosspp()
    # t = TripletLossV2()
    for i in range(100):
        # print(i)
        data = np.random.random((32, 512)).astype('float32')
        # print(i, data.shape)
        lab = np.random.randint(0, 1000, (32,)).astype('float32')
        data = paddle.to_tensor(data).cpu()
        lab = paddle.to_tensor(lab).cpu()
        res = loss(data, lab)
![image](https://github.com/PaddlePaddle/PaddleClas/assets/18610954/252fb12b-d4f2-47b1-865b-335a53579e11)

执行时会报错：
Traceback (most recent call last):
  File "E:/Project/Reid_2021/loss.py", line 491, in <module>
    res = loss(data, lab)
  File "D:\Software\Miniconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:/Project/Reid_2021/loss.py", line 200, in forward
    paddle.masked_select(dist, is_pos), (bs, -1)),
  File "D:\Software\Miniconda3\lib\site-packages\paddle\tensor\manipulation.py", line 1443, in reshape
    return paddle.fluid.layers.reshape(x=x, shape=shape, name=name)
  File "D:\Software\Miniconda3\lib\site-packages\paddle\fluid\layers\nn.py", line 6121, in reshape
    out, _ = core.ops.reshape2(x, 'shape', shape)
ValueError: (InvalidArgument) The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [40], X's size = 40, 'shape' is [32, -1], known capacity of 'shape' is -32.
  [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:-32 != -in_size:-40.] (at D:\2.0.0rc1\paddle\paddle\fluid\operators\reshape_op.cc:208)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
  [operator < reshape2 > error]
推测应该是
paddle.masked_select返回得是一个一维不定长tensor，无法被reshape为（bs, -1）导致。因为masked_select返回的不是原始shape的数据。

**Comment by HydrogenSulfate** [comment]
> @HydrogenSulfate 非常感谢您。是的我测试时发现target只有维度为(bs)时可以执行。 但是我测试时发现这个loss会报错，也可能是我使用的问题，我的测试代码如下： import paddle import numpy as np # classes 1000 # paddle.set_device("cpu") loss = TripletAngularMarginLosspp() # t = TripletLossV2() for i in range(100): # print(i) data = np.random.random((32, 512)).astype('float32') # print(i, data.shape) lab = np.random.randint(0, 1000, (32,)).astype('float32') data = paddle.to_tensor(data).cpu() lab = paddle.to_tensor(lab).cpu() res = loss(data, lab) ![image](https://user-images.githubusercontent.com/18610954/264202262-252fb12b-d4f2-47b1-865b-335a53579e11.png)
> 
> 执行时会报错： Traceback (most recent call last): File "E:/Project/Reid_2021/loss.py", line 491, in res = loss(data, lab) File "D:\Software\Miniconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 884, in **call** outputs = self.forward(*inputs, **kwargs) File "E:/Project/Reid_2021/loss.py", line 200, in forward paddle.masked_select(dist, is_pos), (bs, -1)), File "D:\Software\Miniconda3\lib\site-packages\paddle\tensor\manipulation.py", line 1443, in reshape return paddle.fluid.layers.reshape(x=x, shape=shape, name=name) File "D:\Software\Miniconda3\lib\site-packages\paddle\fluid\layers\nn.py", line 6121, in reshape out, _ = core.ops.reshape2(x, 'shape', shape) ValueError: (InvalidArgument) The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [40], X's size = 40, 'shape' is [32, -1], known capacity of 'shape' is -32. [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:-32 != -in_size:-40.] (at D:\2.0.0rc1\paddle\paddle\fluid\operators\reshape_op.cc:208) [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.] [operator < reshape2 > error] 推测应该是 paddle.masked_select返回得是一个一维不定长tensor，无法被reshape为（bs, -1）导致。因为masked_select返回的不是原始shape的数据。

这个损失函数是基于TripletLoss改进的，这是一种对比学习的损失函数，所以想正常使用有一个要求：batch size是同类样本数的整数倍，
![image](https://github.com/PaddlePaddle/PaddleClas/assets/23737287/fba002da-232e-4efd-8ae8-a6bfed489d6a)
如上图所示，batch_size是256，而类内样本数sample_per_id是4，表示256个样本被划分为256/4=64个类别，每个类别内均有4个样本。看你的报错可能是Dataloader这块没设置对，尤其是上图的两个参数，导致正负样本用mask选择的时候报错了

**Comment by zhishao** [comment]
@HydrogenSulfate 明白了 非常感谢！
