### ISSUE TITLE
多标签使用 mixup 或 cutmix 皆报错

### ISSUE THREAD

**Issue by thsno02** [PaddlePaddle/PaddleClas#2942]
1. PaddleClas版本以及PaddlePaddle版本：PaddleClas release/2.5和PaddlePaddle 2.3.0
2. 涉及的其他产品使用的版本号：
3. 训练环境信息：
a. 具体操作系统，如Linux
b. Python版本号，如Python3.9
c. CUDA/cuDNN版本， CUDA11.7/cuDNN 8.1.0

4. 详细的错误信息及相关log

在 config.yml 中按照 https://github.com/PaddlePaddle/PaddleClas/blob/9984080a3d7ca52dd9044afaae1df1bed676fd1c/docs/en/advanced_tutorials/DataAugmentation_en.md#1.8 中的 

```
      batch_transform_ops:
        - MixupOperator:
            alpha: 0.2
```

分别配置了 cutmix 或者 mixup。但是在训练加载数据的时候在此处报错：

https://github.com/PaddlePaddle/PaddleClas/blob/9984080a3d7ca52dd9044afaae1df1bed676fd1c/ppcls/data/preprocess/batch_ops/batch_operators.py#L51

如果不使用 cutmix 或者 mixup 模型能正常训练，但是一旦加上就会报错。

我打印了 targets 中的内容，发现不是单纯的 labels，label.txt 中 label 加上一个长度相同的向量。

**Comment by thsno02** [comment]
修改 https://github.com/PaddlePaddle/PaddleClas/blob/9984080a3d7ca52dd9044afaae1df1bed676fd1c/ppcls/data/preprocess/batch_ops/batch_operators.py#L36-L48

为 

```
    def _unpack(self, batch):
        """ _unpack """
        assert isinstance(batch, list), \
                'batch should be a list filled with tuples (img, label)'
        bs = len(batch)
        assert bs > 0, 'size of the batch data should > 0'
        #imgs, labels = list(zip(*batch))
        imgs = []
        labels = []
        for item in batch:
            imgs.append(item[0])
            labels.append(item[1][0])
        return np.array(imgs), np.array(labels, dtype=int), bs
```

后不报错了，但我不确定是否正确调用了 mixup 或者 cutmix 方法。

**Comment by cuicheng01** [comment]
可以发一下报错信息吗

**Comment by thsno02** [comment]
> 可以发一下报错信息吗

`IndexError: arrays used as indices must be of integer (or boolean) type` 应该是 labels 解析的时候数据结构有点问题，我之前逐一打印过。

**Comment by cuicheng01** [comment]
哦哦，多标签目前还是不支持mixup的操作
