### ISSUE TITLE
多标签 weight loss 的疑惑

### ISSUE THREAD

**Issue by thsno02** [PaddlePaddle/PaddleClas#2951]
在 _Rethinking of Pedestrian Attribute Recognition: Realistic Datasets with Efficient Method_ 这篇论文中提到了三种 weight loss 的方法，

![image](https://github.com/PaddlePaddle/PaddleClas/assets/103615460/557396ca-00b2-4259-89ae-f8f519ba11bd)

实验结果如下：

![image](https://github.com/PaddlePaddle/PaddleClas/assets/103615460/e7de5c03-800f-4a77-9124-fae4e0824176)

PaddleClas 在多标签中仅包含了 https://github.com/PaddlePaddle/PaddleClas/blob/9984080a3d7ca52dd9044afaae1df1bed676fd1c/ppcls/loss/multilabelloss.py#L6-L14 WF1 这一种，请问这里是有什么考量吗？比如基于实验，WF2 和 WF3 的表现不如 WF1？还是说目前没有官方支持？

REF: https://arxiv.org/abs/2107.03576

**Comment by thsno02** [comment]
对多标签感兴趣的朋友可以试试这两个 weight function，在我的任务上，有显著提升。

**Comment by cuicheng01** [comment]
@thsno02 目前没有支持，欢迎提PR给PaddleClas～
