### ISSUE TITLE
按文档“预测引擎 + inference 模型预测”执行core dump了

### ISSUE THREAD

**Issue by xieliang** [PaddlePaddle/PaddleClas#297]
按  https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/zh_CN/extension/paddle_inference.md  文档：
python tools/export_model.py --m=ResNet50_vd --p=./pretrained/ResNet50_vd_pretrained --o=model/ResNet50_vd  执行是成功的，生成了相应文件
但接下来：

(pytorch_latest_p36) ubuntu@ip-172-19-14-95:~/PaddleClas$ python tools/infer/predict.py -i=./dataset/flowers102/jpg/image_08186.jpg -m=./model/ResNet50_vd/model -p=./model/ResNet50_vd/params --use_gpu=1  --use_tensorrt=True
Traceback (most recent call last):
  File "tools/infer/predict.py", line 156, in <module>
    main()
  File "tools/infer/predict.py", line 110, in main
    predictor = create_predictor(args)
  File "tools/infer/predict.py", line 66, in create_predictor
    predictor = create_paddle_predictor(config)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::framework::ir::PassRegistry::Get(std::string const&) const
3   paddle::inference::analysis::IRPassManager::CreatePasses(paddle::inference::analysis::Argument*, std::vector<std::string, std::allocator<std::string> > const&)
4   paddle::inference::analysis::IRPassManager::IRPassManager(paddle::inference::analysis::Argument*)
5   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
7   paddle::AnalysisPredictor::OptimizeInferenceProgram()
8   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
9   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
10  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
11  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)

----------------------
Error Message Summary:
----------------------
Error: Pass tensorrt_subgraph_pass has not been registered at (/paddle/paddle/fluid/framework/ir/pass.h:201)

如果把use_tensorrt设为False则core dump

(pytorch_latest_p36) ubuntu@ip-172-19-14-95:~/PaddleClas$ python tools/infer/predict.py -i=./dataset/flowers102/jpg/image_08186.jpg -m=./model/ResNet50_vd/model -p=./model/ResNet50_vd/params --use_gpu=1  --use_tensorrt=False
Segmentation fault (core dumped)

请教下如何能完成文档示例呢，谢谢。  如果需要更多信息，请明示

**Comment by xieliang** [comment]
这个文档后面的 用训练引擎 ＋  两种模型的是可以运行成功的;
(pytorch_latest_p36) ubuntu@ip-172-19-14-95:~/PaddleClas$ python tools/infer/infer.py -i=./dataset/flowers102/jpg/image_08186.jpg -m=ResNet50_vd -p=./pretrained/ResNet50_vd_pretrained --use_gpu=True
2020-09-29 08:10:05,236-WARNING: ./pretrained/ResNet50_vd_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
W0929 08:10:05.288385 19735 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.0, Runtime API Version: 10.0
W0929 08:10:05.297749 19735 device_context.cc:260] device: 0, cuDNN Version: 7.6.
current image: ./dataset/flowers102/jpg/image_08186.jpg
	class id: 985, probability: 0.7393
	class id: 309, probability: 0.0701
	class id: 308, probability: 0.0135
	class id: 310, probability: 0.0122
	class id: 325, probability: 0.0056



(pytorch_latest_p36) ubuntu@ip-172-19-14-95:~/PaddleClas$ python tools/infer/py_infer.py --i=./dataset/flowers102/jpg/image_08186.jpg -d ./model/ResNet50_vd -m ./model/ResNet50_vd/model --p=./model/ResNet50_vd/params --use_gpu=True
W0929 08:13:20.394726 19868 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.0, Runtime API Version: 10.0
W0929 08:13:20.398609 19868 device_context.cc:260] device: 0, cuDNN Version: 7.6.
class id: 985, probability: 0.7393
class id: 309, probability: 0.0701
class id: 308, probability: 0.0135
class id: 310, probability: 0.0122
class id: 325, probability: 0.0056

另外请教一下：我怎么查class id 985这个对应的是什么label物体呢，谢谢

**Comment by littletomatodonkey** [comment]
这个需要知道label对应的具体类别，我们之后会开放出imagenet1k的映射文件，感谢反馈～

**Comment by littletomatodonkey** [comment]
label list也可以在这里查看：https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleCV/image_classification/utils/tools/readable_label.txt
