### ISSUE TITLE
如何直接用预训练模型resnet50_vd_ssld进行评估（eval.py）

### ISSUE THREAD

**Issue by yhhu99** [PaddlePaddle/PaddleClas#298]
下载预训练模型之后想要修改eval.py直接评估预训练模型，看它在ImageNet上的准确率，但是运行过程中发现文件夹下没有.pdparams文件，所以想问下要怎么把预训练模型tar转换成.pdparams。
    还是说Resnet50_vd系列的预训练模型只能finetune，不能转换成.pdparams进行预测或评估。谢谢

**Comment by littletomatodonkey** [comment]
你好，可以将tar文件解压，指定预训练模型路径为解压之后的文件夹路径即可进行评估

**Comment by yhhu99** [comment]
> 你好，可以将tar文件解压，指定预训练模型路径为解压之后的文件夹路径即可进行评估

感谢，之前这样做过但是报了错，现在又能运行了，谢谢解答
