### ISSUE TITLE
How to visualize PPHGNet multi-label model?

### ISSUE THREAD

**Issue by thsno02** [PaddlePaddle/PaddleClas#3012]
Is there a tutorial on how to utilize [InterpretDL](https://github.com/PaddlePaddle/InterpretDL) to visualize the PPHGNet multi-label model?

**Comment by cuicheng01** [comment]
why multi-label？

**Comment by thsno02** [comment]
I need that🥹

**Comment by cuicheng01** [comment]
We have not used it, you can try to write an issue to the InterpretDL repo.
