### ISSUE TITLE
paddleclas怎么进行单卡训练呢？

### ISSUE THREAD

**Issue by terryluzhenfeng** [PaddlePaddle/PaddleClas#302]
我在服务器终端跑flowers102数据集。
export PYTHONPATH=$PWD:$PYTHONPATH
python -m paddle.distributed.launch \
    --selected_gpus="0" \
    tools/train.py \
        -c ./configs/quick_start/ResNet50_vd.yaml
输入这样的代码后出现：

----------------------
Error Message Summary:
----------------------
PreconditionNotMetError: The third-party dynamic library (libnccl.so) that Paddle depends on is not configured correctly. (error code is libnccl.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; at (/paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:194)
  [operator < gen_nccl_id > error]
INFO 2020-10-10 14:20:43,709 utils.py:269] terminate all the procs
ERROR 2020-10-10 14:20:43,710 utils.py:413] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2020-10-10 14:20:46,713 utils.py:269] terminate all the procs
我查了一下，可能需要我下载nccl。

不过我其实只要单卡训练就好了，我该输入什么样的代码，或者进行怎么样的设置呢？

**Comment by littletomatodonkey** [comment]
如果是在没有安装nccl的机器上运行，可以使用`tools/eval_multi_platform.py`，具体使用方法可以参考这里：https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/zh_CN/tutorials/getting_started.md#1-windows%E6%88%96%E8%80%85cpu%E4%B8%8A%E8%AE%AD%E7%BB%83%E4%B8%8E%E8%AF%84%E4%BC%B0

**Comment by terryluzhenfeng** [comment]
hi，非常感谢你的回答。没想到这么快就受到回复了 。
不过在使用如下代买后：
python tools/train_multi_platform.py \
    -c configs/ResNet/ResNet50.yaml \
    -o model_save_dir=./output/ \
    -o use_gpu=True


还是：
----------------------
Error Message Summary:
----------------------
PreconditionNotMetError: The third-party dynamic library (libnccl.so) that Paddle depends on is not configured correctly. (error code is libnccl.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; at (/paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:194)


我的目的是用单卡的gpu训练，麻烦了.

**Comment by littletomatodonkey** [comment]
感觉是paddle安装问题，你可以先试下
```
import paddle.fluid
paddle.fluid.install_check.run_check()
```
确认一下paddle是否安装成功
