### ISSUE TITLE
How to set "color jitter" in the yaml file for data augmentation.

### ISSUE THREAD

**Issue by ZhengyuXia** [PaddlePaddle/PaddleClas#3033]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：PaddleClas release/2.5 和 PaddlePaddle 2.4.2
 2. 涉及的其他产品使用的版本号：PaddleSeg 2.7
 3. 训练环境信息：
  a. 具体操作系统，Ubuntu 18.04
  b. Python版本号，Python 3.7
  c. CUDA/cuDNN版本，CUDA11.6 cuDNN 8.4.0 & NCCL 2.7
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

----

Hey, thanks for the excellent work. I am looking for the "color jitter" data augmentation for image classification. For example, in the paper "MixFormer," the authors adopt the color jitter with 0.4 weight for data augmentation.

Paper Link: https://arxiv.org/abs/2204.02557 (Table 17 shows the detailed hyperparameters for MixFormer using PaddleClas)

However, when I checked the official configure files (*.yaml) for this paper, I could not locate the hyperparameters for color jitter 

Code Link: https://github.com/PaddlePaddle/PaddleClas/pull/1820/files#diff-5c766eb92d812786d833a369132d7a2caa62b1eef57bfdf263640b2209cb84c3

Therefore, I would like to know how to set the "color jitter" in the yaml files. Thanks.

**Comment by TingquanGao** [comment]
please refer: https://github.com/PaddlePaddle/PaddleClas/blob/27b3591b36f5def1f8a385f9fadfbcd2e4741431/ppcls/configs/metric_learning/adaface_ir18.yaml#L69-L74

**Comment by ZhengyuXia** [comment]
> please refer:
> 
> https://github.com/PaddlePaddle/PaddleClas/blob/27b3591b36f5def1f8a385f9fadfbcd2e4741431/ppcls/configs/metric_learning/adaface_ir18.yaml#L69-L74

Thanks. It resolves the issue. For those who try to use "ColorJitter" for data augmentation, please pay attention that it should be set ahead of "Normalization" since "ColorJitter" only works on uint type. "Normalization" changes the data type to float and results in error messages when using "ColorJitter."
