### ISSUE TITLE
在PULC语种分类模型基础上训练成手写中文和印刷体中文的分类模型是否可行

### ISSUE THREAD

**Issue by TOMORINAONAO** [PaddlePaddle/PaddleClas#3048]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：paddle2.5.2  paddleclas2.5
 2. 涉及的其他产品使用的版本号：paddleocr2.7

在使用paddleocr的时候混合手写体和印刷体训练了一个ocr模型，但实际上印刷体的准确率有下降，现在想在ocr的检测模型和识别模型之间加一个分类模型，根据分类的类别是印刷体或手写体选择对应的识别模型。

目前在PULC语种分类模型的基础上使用了一百多万的手写数据和印刷体数据，得到的模型效果是有的但不是特别好，不知道是否和背景有关，从某一张文档上截的文本行就会分类错误率很高。

现在是有两个问题：
1.以ocr识别模型的训练数据作为训练集，能否达成我想要的印刷体和手写体分类的效果？
2.下面有几张数据样例，目前我手上的ocr识别模型的训练数据，由于是分开收集的开源数据，**印刷体数据的背景颜色明暗不一致，手写体数据的背景全是亮白色**。印刷体和手写体的训练数据的背景不一致是否影响分类模型的效果？
![20436312_1683447152](https://github.com/PaddlePaddle/PaddleClas/assets/51530060/88de370c-8324-4aa4-9e9b-7ed946d69a2a)
![20436421_2900540980](https://github.com/PaddlePaddle/PaddleClas/assets/51530060/3385adab-f576-4f8a-8f2d-c5f8036d00fd)
![0](https://github.com/PaddlePaddle/PaddleClas/assets/51530060/c2ae90fc-4d34-414b-b942-d00a5a0c2935)
![001-P16_0](https://github.com/PaddlePaddle/PaddleClas/assets/51530060/ece512c9-2f22-4f5e-8a13-87f9a1344fa1)

**Comment by cuicheng01** [comment]
关于这个问题，有两个小建议哈：
1.OCR的手写和印刷体可以一起训练，这样就没必要使用分类模型了，事实上，我们也这样训练过，效果还不错；
2.如果确实想训练一个这样的分类器，需要比较大的图像数量，分辨率可以尝试48*320
