### ISSUE TITLE
PaddleClas是否倒闭了,没人管

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleClas#3078]
PaddleClas是否倒闭了,没人管

**Comment by happybear1015** [comment]
确实，文档也很久没更新了，新的算法也没有人来集成进来

**Comment by imyhxy** [comment]
fork一下

**Comment by imyhxy** [comment]
还真的没人管，连PaddlePaddle官网的文档页面都卡的要死，更别说框架优化了

**Comment by choipd** [comment]
Oh, it works when I changed in my requirements.txt like this:
```
paddleclas @ git+https://github.com/PaddlePaddle/PaddleClas.git
```

**Comment by cuicheng01** [comment]
> 确实，文档也很久没更新了，新的算法也没有人来集成进来

感谢关注，新算法可以关注develop分支哈，比如LaCLIP、RAM等模型都有再添加，也欢迎大佬新增新算法，共建开源社区～

**Comment by cuicheng01** [comment]
> 还真的没人管，连PaddlePaddle官网的文档页面都卡的要死，更别说框架优化了

可以说下您具体遇到的情况呢？

**Comment by cuicheng01** [comment]
> PaddleClas是否倒闭了,没人管

Hello，感谢关注PaddleClas套件，套件我们还在正常建设哈，仓库里如果有bug等我们还是会修复和跟进的。如果想获得更及时的实时反馈，也可以在PaddleX的频道中讨论：https://aistudio.baidu.com/community/channel/610
