### ISSUE TITLE
人体属性分类模型是否支持单属性训练？即一张图像只有一个属性的标签

### ISSUE THREAD

**Issue by gsx1378** [PaddlePaddle/PaddleClas#3081]
您好，训练人体属性识别模型，需要添加自己的一部分数据，每一张图像把所有属性都标注比较困难，且难做到类别均衡。当前工程是否支持一张图仅负责一个属性的训练方式呢？即仍是多标签分类模型，但是训练时不同图像负责不同的属性。若有的话，请问训练标签应该是什么样子的？

**Comment by cuicheng01** [comment]
目前不支持，建议每一个属性单独训练一个模型，然后将所有图片过每一个属性模型重新打标签，然后再统一训练
