### ISSUE TITLE
How to use trained Resnet classification model in python code

### ISSUE THREAD

**Issue by lokeycookie** [PaddlePaddle/PaddleClas#3086]
Hi there,

I have trained a classification model using this: https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/quick_start/quick_start_classification_new_user.md

However, I do not know how to call the trained model in python code as I wanted to use this model in my existing code.
I do not want to run inference on an image using terminal.

Does anyone know how to do this?

**Comment by cuicheng01** [comment]
Hello, you can use the command here to train. https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/quick_start/quick_start_classification_new_user.md#412-%E4%BD%BF%E7%94%A8%E9%A2%84%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B

**Comment by lokeycookie** [comment]
I have trained finished the model. However, how do I use this trained model for inference and how do I integrate this model into my existing codebase?
Is there a function (for example, model.predict(img_array)) in paddleclas that I can call my trained model using python code?

**Comment by a31413510** [comment]
you can refer to "4.3 使用本地模型文件预测" in https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/deployment/image_classification/whl.md

**Comment by TingquanGao** [comment]
Yes. You can refer to here(https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/ppcls/engine/engine.py#L362) to code.

**Comment by lokeycookie** [comment]
thank you! the code works
