### ISSUE TITLE
如何进行分类大模型的训练，并应用到下游任务。

### ISSUE THREAD

**Issue by ChenjieXu** [PaddlePaddle/PaddleClas#3089]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如Linux/Windows/MacOS
  b. Python版本号，如Python3.6/7/8
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

我现在想用PaddleClas的分类模型进行自监督训练一个分类大模型，然后用这个大模型作为骨干网络应用到分类或者分割网络中进行微调，请问我应该如何做？

**Comment by cuicheng01** [comment]
您好，具体想用什么自监督方法呢？建议使用PASSL训练自监督模型呢

**Comment by ChenjieXu** [comment]
对具体自监督算法没有太多了解，需求是工业质量检测，所以mae可能不太适用。大模型的话是否会支持swin transformer？-------- 原始邮件 --------发件人： cuicheng01 ***@***.***>日期： 2024年2月10日周六 下午4:50收件人： PaddlePaddle/PaddleClas ***@***.***>抄送： Chenjie Xu ***@***.***>, Author ***@***.***>主    题： Re: [PaddlePaddle/PaddleClas] 如何进行分类大模型的训练，并应用到下游任务。 (Issue #3089)
您好，具体想用什么自监督方法呢？

**Comment by ChenjieXu** [comment]
> 您好，具体想用什么自监督方法呢？建议使用PASSL训练自监督模型呢

好的，感谢。邮件里面只看到前一句。
