### ISSUE TITLE
解压后的预训练模型怎么转inference模型呢？

### ISSUE THREAD

**Issue by yhhu99** [PaddlePaddle/PaddleClas#309]
[预训练模型好像是参数模型，我按照教程的方式转换模型，但是报错：没有.pdparams文件，要怎么解决呢？谢谢]
![error](https://user-images.githubusercontent.com/69721135/95965985-2f0b5d80-0e3d-11eb-99f4-e31cd68d0a4a.png)

**Comment by littletomatodonkey** [comment]
你好，如果best_model文件夹下有ppcls.pdparams的文件的话，pretrain路径应该指定为`$your_path/ppcls`

**Comment by yhhu99** [comment]
> 你好，如果best_model文件夹下有ppcls.pdparams的文件的话，pretrain路径应该指定为`$your_path/ppcls`

感谢答复！已经成功运行了，另外想问下预训练模型可以直接用这种方法转换成inference模型吗？（解压后预训练模型的文件夹下好像没有.pdparams文件）

**Comment by littletomatodonkey** [comment]
可以的，不过零散文件和pdparams文件都是预训练模型，inference模型指的是通过`tools/export_model.py`导出之后生成的模型
可以参考这里
https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/zh_CN/tutorials/getting_started.md

![image](https://user-images.githubusercontent.com/14270174/96116164-9ba85a00-0f1a-11eb-9f6f-03325b4912c1.png)

**Comment by yhhu99** [comment]
> 可以的，不过零散文件和pdparams文件都是预训练模型，inference模型指的是通过`tools/export_model.py`导出之后生成的模型
> 可以参考这里
> https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/zh_CN/tutorials/getting_started.md
> 
> ![image](https://user-images.githubusercontent.com/14270174/96116164-9ba85a00-0f1a-11eb-9f6f-03325b4912c1.png)

成功了，谢谢解答！！
