### ISSUE TITLE
缺少PULC_table_attribute.md文档

### ISSUE THREAD

**Issue by icedream2linxi** [PaddlePaddle/PaddleClas#3105]
docs/zh_CN/models/PULC/model_list.md 中列了PULC_table_attribute.md（[PULC表格属性识别](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/models/PULC/PULC_table_attribute.md)），但并不存在，无法打开。

**Comment by changdazhou** [comment]
好的，问题已记录哈

**Comment by TingquanGao** [comment]
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5.1/docs/zh_CN/models/PULC/PULC_table_attribute.md
