### ISSUE TITLE
release/2.5 ModuleNotFoundError: No module named 'ppcls'

### ISSUE THREAD

**Issue by xuehy** [PaddlePaddle/PaddleClas#3129]
1. PaddleClas: release/2.5 
 2. 参考文档：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/models/PP-ShiTu/README.md
 3. 构建索引库：
 ```
paddleclas --build_gallery=True --model_name="PP-ShiTuV2" \
-o IndexProcess.image_root=./drink_dataset_v2.0/gallery/ \
-o IndexProcess.index_dir=./drink_dataset_v2.0/index \
-o IndexProcess.data_file=./drink_dataset_v2.0/gallery/drink_label.txt
```
   或者执行预测：
`python3.7 python/predict_system.py -c configs/inference_general.yaml -o Global.infer_imgs="./drink_dataset_v2.0/test_images/100.jpeg" -o Global.use_gpu=False`

都报错：ModuleNotFoundError: No module named 'ppcls'

**Comment by changdazhou** [comment]
pip list 中是否存在paddleclas呢，另外需保证不要在PaddleClas源码目录中执行上述命令哈，会有歧义导致找不到ppcls，建议到其他目录当中执行建库命令哈

**Comment by xuehy** [comment]
> pip list 中是否存在paddleclas呢，另外需保证不要在PaddleClas源码目录中执行上述命令哈，会有歧义导致找不到ppcls，建议到其他目录当中执行建库命令哈

![image](https://github.com/PaddlePaddle/PaddleClas/assets/2055701/53e05666-8a14-4c40-a952-3db0d187ec31)
paddleclas安装成功了，命令也不是在PaddleClas源码目录里面执行的。
具体错误是：
```

/path/to/miniconda3/envs/PPShitu/lib/python3.8/site-packages/paddleclas-2.5.2-py3.8.egg/paddleclas/ppcls/optimizer/__init__.py", line 23, in <module>
    from ppcls.utils import logger
ModuleNotFoundError: No module named 'ppcls'
```

**Comment by changdazhou** [comment]
建议下载源码从源码安装，python setup.py install

**Comment by chinesejunzai12** [comment]
> 建议下载源码从源码安装，python setup.py install

我也遇到同样的问题, 然后重新执行了此命令, 可以, 好用了, 感谢

**Comment by chinesejunzai12** [comment]
我之前下载的2.5.2使用的pip install -v -e .进行安装的, 会报之前ppcls不存在的问题

**Comment by timelovery** [comment]
为什么我从下载源码从源码安装，python setup.py install，仍然报错，    
from ppcls.utils import config
ModuleNotFoundError: No module named 'ppcls'

**Comment by Toomooyaa** [comment]
我尝试了以上的方法，还是报错  
    from ppcls.engine.train.utils import type_name
ModuleNotFoundError: No module named 'ppcls'
