### ISSUE TITLE
在训练结束后，添加一个softmax输出的结果是BOOL？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleClas#313]
```python
    print(out)
    out = fluid.layers.softmax(out)
    print(out)
```

输出结果如下，前面一个是模型的输出，后是我添加的一个softmax，为啥softmax输出会变成这样子呢？不应该是更fc输出的维度和类型一样的吗？
```
name: "fc_0.tmp_1"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 7
    }
    lod_level: 0
  }
}
persistable: false

name: "softmax_0.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: BOOL
      dims: 0
    }
    lod_level: 0
  }
}
persistable: false
```

**Comment by littletomatodonkey** [comment]
发一下你的paddle版本吧，和使用的命令吧，我这边paddle2.0.0b0，版本的paddle，输出没有问题

![image](https://user-images.githubusercontent.com/14270174/96416727-f4316d00-1222-11eb-8569-7e7a0a42dea3.png)

**Comment by yeyupiaoling** [comment]
@littletomatodonkey 可能咱们添加的地方不一样，我在这里添加的 ：https://github.com/yeyupiaoling/PaddlePaddle-Classification/blob/8eeb64956fe173259b27c12c32392c2c97397314/train.py#L168


 - Python3.7
 - PaddlePaddle-GPU  1.8.4 / 2.0.0b0

**Comment by littletomatodonkey** [comment]
哦哦 你这个是量化的模型训练吧，这个是在编译时生成的shape和dtype，如果需要看它在真实运行时的shape和dtype，可以使用
`fluid.layers.Print(out)`这个函数查看

**Comment by Margrate** [comment]
请问你们找到HS-ResNet了吗？

**Comment by yeyupiaoling** [comment]
@littletomatodonkey 前面是PaddleCls的正常训练，后面才是量化训练。根据你的代码打印，还是BOOL类型的，这样我就没法保存模型，
```
name: "print_softmax_0.tmp_0_0.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: BOOL
      dims: 0
    }
    lod_level: 0
  }
}
persistable: false

```

保存模型报错：
```
Traceback (most recent call last):
  File "train.py", line 180, in <module>
    main(args)
  File "train.py", line 175, in main
    params_filename='__params__')
  File "/home/fg007/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddle/fluid/io.py", line 1201, in save_inference_model
    var, 1., name="save_infer_model/scale_{}".format(i))
  File "/home/fg007/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 12317, in scale
    ], "scale")
  File "/home/fg007/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 81, in check_variable_and_dtype
    check_dtype(input.dtype, input_name, expected_dtype, op_name, extra_message)
  File "/home/fg007/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 116, in check_dtype
    extra_message))
TypeError: The data type of 'x' in scale must be ['float16', 'float32', 'float64', 'int8', 'int16', 'int32', 'int64', 'uint8'], but received bool. 

```

**Comment by baiyfbupt** [comment]
out = fluid.layers.softmax(out) 把这句放在量化训练之前试试呢，因为量化过程会对program有改变

**Comment by yeyupiaoling** [comment]
@littletomatodonkey 放在这个位置都不行：https://github.com/yeyupiaoling/PaddlePaddle-Classification/blob/8eeb64956fe173259b27c12c32392c2c97397314/train.py#L86

只有放在这下面才可以：https://github.com/yeyupiaoling/PaddlePaddle-Classification/blob/8eeb64956fe173259b27c12c32392c2c97397314/utils/program.py#L86

但是放在这里就影响了正常的训练，正常的是没有softmax的，如果在这里加上了softmax会影响训练的精度

**Comment by baiyfbupt** [comment]
>放在这个位置都不行：https://github.com/yeyupiaoling/PaddlePaddle-Classification/blob/8eeb64956fe173259b27c12c32392c2c97397314/train.py#L86

说明这个问题与量化无关，可能是paddle版本的问题

>只有放在这下面才可以：https://github.com/yeyupiaoling/PaddlePaddle-Classification/blob/8eeb64956fe173259b27c12c32392c2c97397314/utils/program.py#L86

这里加一行softmax_out = fluid.layers.softmax(out)就可以，return的还是softmax之前的应该不会影响精度，可以试试

**Comment by yeyupiaoling** [comment]
@baiyfbupt 好的，我试试

**Comment by yeyupiaoling** [comment]
@baiyfbupt 解决了，谢谢。换个思路解决问题
