### ISSUE TITLE
怎么训练出不带reshape2算子的general_PPLCNetV2_base模型？

### ISSUE THREAD

**Issue by lemon3853** [PaddlePaddle/PaddleClas#3142]
训练步骤：
1.  使用配置文件进行训练`ppcls/configs/GeneralRecognitionV2/GeneralRecognitionV2_PPLCNetV2_base.yaml`
2.  导出推理模型 `python tools/export_model.py`
3.  使用`Paddle-Lite`的`opt`工具统计模型算子信息发现带有`arm`架构不支持的`reshape2`算子
![image](https://github.com/PaddlePaddle/PaddleClas/assets/59115919/af790f85-e114-4ac3-8f3c-6b0a5de668b7)
4.  使用`Paddle-Lite`的`opt`工具统计`shitu_android_demo`自带模型算子信息
`https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/lite/ppshituv2_lite_models_v1.0.tar`
![image](https://github.com/PaddlePaddle/PaddleClas/assets/59115919/382742c4-2d38-4747-aece-475359cc00f7)

 1. PaddleClas版本以及PaddlePaddle版本：PaddlePaddle release/2.5.2 PaddleClas develop
 4. 涉及的其他产品使用的版本号：Paddle-Lite develop
 6. 训练环境信息：
  a. 具体操作系统，Linux
  b. Python版本号，如Python3.8
  c. CUDA/cuDNN版本， 如CUDA11.7
 7. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

**Comment by cuicheng01** [comment]
这个主要是导出的问题，你可以尝试使用其他paddle版本导出试试

**Comment by lemon3853** [comment]
> 这个主要是导出的问题，你可以尝试使用其他paddle版本导出试试

已解决，降级到PaddlePaddle 2.4版本，谢谢大佬
