### ISSUE TITLE
clarity_assessment_infer.tar 下载链接不存在

### ISSUE THREAD

**Issue by Carious-ads** [PaddlePaddle/PaddleClas#3195]
PULC 清晰度评估模型
'''
cd deploy/models
# 下载 inference 模型并解压
wget https://paddleclas.bj.bcebos.com/models/PULC/clarity_assessment_infer.tar && tar -xf clarity_assessment_infer.tar
'''
下载时模型不存在：
![1721789951289](https://github.com/user-attachments/assets/9aa8f6ce-8145-487e-84e6-5292b477bb05)

文档地址：
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5.2/docs/zh_CN/models/PULC/PULC_clarity_assessment.md#6.1.2

**Comment by TingquanGao** [comment]
该问题已修复， https://paddleclas.bj.bcebos.com/models/PULC/clarity_assessment_infer.tar 恢复正常
