### ISSUE TITLE
模型clarity_assessment不存在

### ISSUE THREAD

**Issue by syge** [PaddlePaddle/PaddleClas#3202]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如Linux/Windows/MacOS
  b. Python版本号，如Python3.6/7/8
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

paddleclas.paddleclas.InputModelError: clarity_assessment is not provided by PaddleClas.
Maybe you want the : [CSWinTransformer_base_224, CSWinTransformer_base_384, CSWinTransformer_small_224, CSWinTransformer_large_224, CSWinTransformer_large_384, person_exists, safety_helmet, car_exists, person_attribute, vehicle_attribute].
If you want to use your own model, please specify inference_model_dir!

**Comment by cuicheng01** [comment]
您好，执行的什么命令呢？

**Comment by syge** [comment]
paddleclas --model_name=clarity_assessment --infer_imgs=pulc_demo_imgs/clarity_assessment/blured_demo.jpg

**Comment by TingquanGao** [comment]
该问题已修复，由于尚未发布新的paddleclas whl包，建议参考[文档](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5.2/docs/zh_CN/models/PULC/PULC_clarity_assessment.md#6-%E6%A8%A1%E5%9E%8B%E6%8E%A8%E7%90%86%E9%83%A8%E7%BD%B2)这样使用：

```bash
cd PaddleClas/deploy
mkdir models && cd models
wget https://paddleclas.bj.bcebos.com/models/PULC/clarity_assessment_infer.tar && tar -xf clarity_assessment_infer.tar
cd ..
python python/predict_cls.py -c configs/PULC/clarity_assessment/inference_clarity_assessment.yaml
```

**Comment by kerry-weic** [comment]
configs/PULC/clarity_assessment/inference_clarity_assessment.yaml
配置文件好像不存在
