### ISSUE TITLE
PP-ShiTu V2图像识别系统存在内存泄漏问题

### ISSUE THREAD

**Issue by tianjiahao** [PaddlePaddle/PaddleClas#3204]
pp-shitu 中向量检索faiss search内存增加很快，不知道有没有人遇到这个问题

**Comment by zhangyubo0722** [comment]
请问索引库中的数据量大概多少呢

**Comment by tianjiahao** [comment]
数据量不大，只有几百条，问题解决了，是faiss中search方法多线程的问题，每次搜索会生成 max_threads 个线程，会产生内存问题，当设置为单线程模式：faiss.omp_set_num_threads(1)，问题就解决了
