### ISSUE TITLE
按照文档 使用 paddle_serving 部署 PLUC 的clarity_assessment 清晰度检测模型，接口调用报错

### ISSUE THREAD

**Issue by syge** [PaddlePaddle/PaddleClas#3206]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如Linux/Windows/MacOS
  b. Python版本号，如Python3.6/7/8
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

{
    "err_no": 5,
    "err_msg": "(log_id=19) imagenet failed to predict.",
    "key": [],
    "value": [],
    "tensors": []
}

**Comment by cuicheng01** [comment]
您好，使用最新的develop代码试试呢？

**Comment by syge** [comment]
paddleClas的develop分支代码么

**Comment by TingquanGao** [comment]
请参考这个：https://github.com/PaddlePaddle/PaddleClas/issues/3202#issuecomment-2261963463

**Comment by cuicheng01** [comment]
> paddleClas的develop分支代码么

是的

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
