### ISSUE TITLE
请问PP-Shitu v2是不是不支持Windows下的C++调用？

### ISSUE THREAD

**Issue by tangfengray** [PaddlePaddle/PaddleClas#3207]
在项目中找了很久，也没有找到Windows下C++的demo。
cpp-shitu 好像也只是提供了 Linux 的编译教程。
因为技术水平很菜，所以直接过来问一下是不是不支持Windows下的C++调用，还是我没找对地方。

**Comment by cuicheng01** [comment]
确实没有提供windows的，这块应该可以改着试试

**Comment by tangfengray** [comment]
好，我再琢磨下吧，感谢

**Comment by tangfengray** [comment]
https://github.com/tangfengray/PaddleClas/blob/release/2.5.2/docs/zh_CN/deployment/PP-ShiTu/cpp.md#5
已经解决了，解决的步骤简单的写了下，已经提交了合并请求。

**Comment by JianDan0212** [comment]
好的
