### ISSUE TITLE
行人属性检测的C++部署代码是哪个？

### ISSUE THREAD

**Issue by gouzigege** [PaddlePaddle/PaddleClas#3213]
你好，
我在使用PaddleClas想对行人的属性检测模型进行C++的部署。使用 PaddleClas-release-2.5.2/deploy/cpp 里面的代码成功构建出clas_system可执行文件，然后使用命令 ./build/clas_system -c ./tools/inference_person_attribute.yaml 
配置文件如下：
![cfg](https://github.com/user-attachments/assets/54026fe5-daec-44cb-a212-da3788e913be)

运行后报错误如下：
![error](https://github.com/user-attachments/assets/7e353616-8aee-4409-a129-0bf625197c41)

问题：行人的属性识别C++代码是否为 PaddleClas-release-2.5.2/deploy/cpp 里的代码？如果不是，是否支持行人识别的C++代码，具体的位置？

**Comment by cuicheng01** [comment]
目前这里C++只支持单标签部署，多标签部署需要自己改写下

**Comment by gouzigege** [comment]
感谢回复：
那我是能够根据这份C++代码，修改后处理相关操作得到行人属性识别的是么？还是需要自己重新写呢？

**Comment by JianDan0212** [comment]
改写C++代码应该就可以，稍等我跟相关同学确认下后回复你

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
