### ISSUE TITLE
度量学习nan是不是单纯是召回没命中？

### ISSUE THREAD

**Issue by kkpssr** [PaddlePaddle/PaddleClas#3229]
![image](https://github.com/user-attachments/assets/df587f59-bd24-4196-ade3-981367f95987)

**Comment by cuicheng01** [comment]
看着更像是训练出问题了，你使用的是什么Loss呢

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
