### ISSUE TITLE
PaddleClas是否支持多标签

### ISSUE THREAD

**Issue by yazone** [PaddlePaddle/PaddleClas#323]
PaddleClas是否支持多标签，有没有示例

**Comment by littletomatodonkey** [comment]
你好，目前PaddleClas还不支持多标签的训练哈~

**Comment by yazone** [comment]
> 你好，目前PaddleClas还不支持多标签的训练哈~

是否有计划呢？

**Comment by littletomatodonkey** [comment]
你好，短期内可能没有这个计划哈，你如果有这方面的想法的话，欢迎向我们贡献代码~
