### ISSUE TITLE
建议支持PaddlePaddle 3.0

### ISSUE THREAD

**Issue by mikezhuang2022** [PaddlePaddle/PaddleClas#3230]
在使用PaddlePaddle 3.0的时候出现[#3127](https://github.com/PaddlePaddle/PaddleClas/issues/3127)的问题。报错信息和#3127一样，都是cudnn报错

**Comment by Bobholamovic** [comment]
你好，这个看起来是Paddle和cuDNN版本匹配的问题，不是PaddleClas的问题。PaddleClas本身是支持Paddle 3.0的。如果可能的话，推荐使用Docker环境安装。

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
