### ISSUE TITLE
下载EfficientNetV2_S模型时报错

### ISSUE THREAD

**Issue by wwma** [PaddlePaddle/PaddleClas#3233]
```
RuntimeError: Downloading from https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/EfficientNetV2_S_pretrained.pdparams failed with code 404!
```
在使用EfficientNetV2_S模型进行微调时，预训练好的模型参数无法下载，网页提示错误信息。
![image](https://github.com/user-attachments/assets/6ac75fa0-e4d3-4ce2-aabf-4d5cc6f34a5f)

**Comment by JianDan0212** [comment]
这个模型是因为我们更换过模型地址，我咨询下更新的模型地址稍后发给你

**Comment by JianDan0212** [comment]
你好，这个我们已经检查过了这个模型没了，目前我们正在重新转换模型的权重，等处理好之后我给你回复

**Comment by wwma** [comment]
请问整个模型权重什么时间能处理好呢？

**Comment by cuicheng01** [comment]
目前看模型确实丢失了，需要重新训练，在排期中了，稍安勿躁哈，你可以先用其他优秀分类模型替换，比如ConvNeXt、PP-HGNetV2等

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by YOIMIYA66** [comment]
截止现在还是不能顺利下载预训练模型😭
