### ISSUE TITLE
swin_transformer_v2.py中第689行output_dimensions未定义

### ISSUE THREAD

**Issue by luwei-nuaa** [PaddlePaddle/PaddleClas#3235]
paddleclas-release-2.5.2

**Comment by zhangyubo0722** [comment]
感谢反馈，我们会尽快修复这个问题

**Comment by YAwei666** [comment]
请问
解决了吗

**Comment by zhangyubo0722** [comment]
最近事情比较多，大概30号解决

**Comment by zhangyubo0722** [comment]
https://github.com/PaddlePaddle/PaddleClas/pull/3272

**Comment by zhangyubo0722** [comment]
https://github.com/PaddlePaddle/PaddleClas/pull/3272
问题在这个pr已修复
