### ISSUE TITLE
PPShitu python3.12 构建索引后识别接口返回结果全是空的

### ISSUE THREAD

**Issue by LeanFly** [PaddlePaddle/PaddleClas#3247]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：paddlepaddle-gpu==2.6.1.post120，paddleclas==2.5.2
 
2. 训练环境信息：
  a. Linux，Ubuntu2404-desktop
  b. Python3.12
  c. CUDA12/cuDNN 8.9.7.29
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log
     `/home/paddle/venv-paddleclas/lib/python3.8/site-packages/paddleclas/deploy/python/predict_rec.py:93: RuntimeWarning: invalid value encountered in divide
  batch_output = np.divide(batch_output, feas_norm)`
5. `{
    "err_no": 0,
    "err_msg": "",
    "key": [
        "result"
    ],
    "value": [
        "[]"
    ],
    "tensors": []
}`

**Comment by Bobholamovic** [comment]
看起来可能是特征中包含零值，可以断点打印`feats_norm`的值确认这一点。如果确实如此，建议首先确认模型给出的结果是符合预期的，然后可以考虑在`feas_norm`的基础上加上一个小偏置以避免除0错误。

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
