### ISSUE TITLE
paddleclas 构建索引停在写入

### ISSUE THREAD

**Issue by LeanFly** [PaddlePaddle/PaddleClas#3249]
![image](https://github.com/user-attachments/assets/394e378a-6232-4692-abd2-a21ee31d3119)

索引进度跑完之后在最后一步停住不动了，30分钟了都没结束。

Ubuntu 2404
cuda 12
python    3.8
paddleclas          2.5.2
paddlepaddle-gpu    2.6.1.post120

**Comment by Bobholamovic** [comment]
建议可以按 Ctrl+C 终止程序，根据报错信息看看卡在哪一步了

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
