### ISSUE TITLE
paddleclas build_gallery 最后没有保存 index.vetor id_map.pkl 文件

### ISSUE THREAD

**Issue by LeanFly** [PaddlePaddle/PaddleClas#3252]
windwos 11
python310

paddleclas                       2.5.2
paddlepaddle                     2.6.2

```
paddleclas --build_gallery=True --model_name="PP-ShiTuV2" -o IndexProcess.image_root="C:\\Users\\ningm\\Documents\\python\\youpingjiu\\crop_2024-09-09" -o IndexProcess.index_dir="C:\\Users\\ningm\\Documents\\python\\youpingjiu\\2024-09-09_fix" -o IndexProcess.data_file="C:\\Users\\ningm\\Documents\\python\\youpingjiu\\2024
-09-09_wb_query_index.txt"
```

![image](https://github.com/user-attachments/assets/e7ca76a9-61be-4951-b693-da22bf019983)

**Comment by LeanFly** [comment]
同样的环境换用paddlepaddle-gpu 的2.5.2、2.6.0、2.6.1版本都在运行完成后没有生成 index.vetor id_map.pkl 文件

**Comment by RillMa** [comment]
一样 不知道为啥生成不出来

**Comment by liu-jiaxuan** [comment]
已收到反馈，我们复现下

**Comment by RillMa** [comment]
> 已收到反馈，我们复现下

复现出来了吗，用别的数据集也没有生成出来索引文件

**Comment by WR-CREATOR** [comment]
我也遇到了这个问题

**Comment by RillMa** [comment]
> 我也遇到了这个问题

windows上有这个问题，我后来换linux跑，就可以生成出来了

**Comment by WR-CREATOR** [comment]
> > 我也遇到了这个问题
> 
> windows上有这个问题，我后来换linux跑，就可以生成出来了

我之前使用win10可以，最近换电脑用win11不行

**Comment by RillMa** [comment]
> > > 我也遇到了这个问题
> > 
> > 
> > windows上有这个问题，我后来换linux跑，就可以生成出来了
> 
> 我之前使用win10可以，最近换电脑用win11不行

可能是win11的问题？不知道，反正linux没问题

**Comment by WR-CREATOR** [comment]
> > > > 我也遇到了这个问题
> > > 
> > > 
> > > windows上有这个问题，我后来换linux跑，就可以生成出来了
> > 
> > 
> > 我之前使用win10可以，最近换电脑用win11不行
> 
> 可能是win11的问题？不知道，反正linux没问题

oh，刚才用之前的电脑win10发现不行，win11也不行。才发现之前使用的是autodl，估计是需要linux才行
