### ISSUE TITLE
模型训练过程中eval指标没有变化

### ISSUE THREAD

**Issue by wwma** [PaddlePaddle/PaddleClas#3258]
使用ppcls\configs\ImageNet\DeiT_base_distilled_patch16_384.yaml中的参数对自己的模型进行二分类训练，其中仅仅更改了数据的路径以及分类个数，一共1000张图片，train：eval=2：1。训练过程中使用一张GPU，其余条件无更改。

从结果来看，评价集的指标从第一个epoch开始没有任何变化，目前已经训练到了第35个epoch，请问有什么改进的建议吗？
![image](https://github.com/user-attachments/assets/3896e867-77b1-4b1f-9732-03c9429c19f3)
![image](https://github.com/user-attachments/assets/f7e87d05-103d-4a20-badc-710624cb4e50)

**Comment by zhang-prog** [comment]
可以调大一点学习率试试

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
