### ISSUE TITLE
tensorrt报错

### ISSUE THREAD

**Issue by sunny0414** [PaddlePaddle/PaddleClas#326]
这个错误是怎么解决

TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure TensorRT dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)

**Comment by littletomatodonkey** [comment]
你好，首先需要基于Paddle源码编译Paddle whl包，加上`TENSORRT_ROOT`的选项（下面是我的编译方法），编译安装完成之后，需要将tensortRT的lib路径添加到`LD_LIBRARY_PATH`中去，export LD_LIBRARY_PATH=${your_trt_lib_path}:$LD_LIBRARY_PATH

```
cmake  .. \
        -DWITH_CONTRIB=OFF \
        -DWITH_MKL=ON \
        -DWITH_MKLDNN=ON  \
        -DWITH_TESTING=OFF \
        -DCMAKE_BUILD_TYPE=Release \
        -DWITH_INFERENCE_API_TEST=OFF \
        -DON_INFER=ON \
        -DWITH_DISTRIBUTE=ON \
        -DWITH_PYTHON=ON \
        -DPY_VERSION=3.7 \
        -DCUDA_TOOLKIT_ROOT_DIR=/paddle/libs/trt6/cuda-10.1 \
        -DCUDNN_ROOT=/paddle/libs/trt6/cudnn_v7.6_cuda10.1 \
        -DTENSORRT_ROOT=/paddle/libs/trt6/TensorRT-6.0.1.5

make -j32
make inference_lib_dist
```

**Comment by wangludewdrop** [comment]
> 你好，首先需要基于Paddle源码编译Paddle whl包，加上`TENSORRT_ROOT`的选项（下面是我的编译方法），编译安装完成之后，需要将tensortRT的lib路径添加到`LD_LIBRARY_PATH`中去，export LD_LIBRARY_PATH=${your_trt_lib_path}:$LD_LIBRARY_PATH
> 
> ```
> cmake  .. \
>         -DWITH_CONTRIB=OFF \
>         -DWITH_MKL=ON \
>         -DWITH_MKLDNN=ON  \
>         -DWITH_TESTING=OFF \
>         -DCMAKE_BUILD_TYPE=Release \
>         -DWITH_INFERENCE_API_TEST=OFF \
>         -DON_INFER=ON \
>         -DWITH_DISTRIBUTE=ON \
>         -DWITH_PYTHON=ON \
>         -DPY_VERSION=3.7 \
>         -DCUDA_TOOLKIT_ROOT_DIR=/paddle/libs/trt6/cuda-10.1 \
>         -DCUDNN_ROOT=/paddle/libs/trt6/cudnn_v7.6_cuda10.1 \
>         -DTENSORRT_ROOT=/paddle/libs/trt6/TensorRT-6.0.1.5
> 
> make -j32
> make inference_lib_dist
> ```

小白问一下，这个Paddle whl包在哪里，遇到了同样的问题，还没有解决，你写的答案没有看懂，哭。。。

**Comment by littletomatodonkey** [comment]
编译完Paddle之后，会在`build/python/dist`目录下面生成`paddlepaddle_gpu-0.0.0-cp37-cp37m-linux_x86_64.whl`这样的whl包,使用pip install进行安装即可

**Comment by chlyzzo** [comment]
那如果是cpu版本呢？该怎么编译？使用python3 -m pip install paddlepaddle==1.8.5 -i https://mirror.baidu.com/pypi/simple安装后该怎么操作，因为没有paddle的源代码呀

**Comment by littletomatodonkey** [comment]
tensorRT只支持在GPU上面使用哈
