### ISSUE TITLE
windows + vs2019 + paddleclas-2.5 +faiss 编译成功后，pp-shitu没有输出

### ISSUE THREAD

**Issue by xcjcb001** [PaddlePaddle/PaddleClas#3263]
我按照说明将paddleclas release2.5 （cpu版）在windows进行编译现在遇到一个问题，编译成功后运行的时候，没有任何输出，检查到可能是在paddle_infer::Config config出现问题，不知道怎么解决了，如下图：
我用到的版本：
paddleclas 2.5 /2.3
paddle-inference 2.2/2.3/2.5(cpu版的)
faiss-master/faiss-1.7
openblas
vs2019 
windows 10
![image](https://github.com/user-attachments/assets/73f436bc-8ca6-437f-95b0-463cd06c72ee)

**Comment by cuicheng01** [comment]
linux会有问题吗？

**Comment by xcjcb001** [comment]
没有试过，主要是没有linux 编程经验

**Comment by xcjcb001** [comment]
@cuicheng01 没有试过诶，主要是没有liunx经验

**Comment by cuicheng01** [comment]
可以看看其他issue有没有类似的情况呢，寻找寻找解决方案，我们的设备主要是linux，windows可能需要你们来研究适配下

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
