### ISSUE TITLE
使用opt转换的nb格式主体模型 picodet运行就报错 使用yolo模型就会只能识别出一个主体

### ISSUE THREAD

**Issue by zoelulur** [PaddlePaddle/PaddleClas#3270]
使用opt转换的nb格式主体模型 picodet运行就报错 使用yolo模型就可以运行 但是只会识别出一个主体
目前比较倾向于使用picodet模型 但是一到主体识别那步的predictor_->Run()这步 就会崩溃
怀疑过是自己训练的模型有问题 也直接下载过官方版本的模型 
也调整过尺寸 也调整过ops和paddlelite的版本 
也尝试换过不同设备 

安卓demo使用的是官方paddleclas里的android-demo
ops尝试过各个版本 paddlelite也是
非常需要帮助

**Comment by liu-jiaxuan** [comment]
Hi，请放一下picodet模型到主体识别那步的predictor_->Run()这步会崩溃的具体报错，方面我们排查问题~

**Comment by zoelulur** [comment]
> 你好，请放一下picodet模型到主体识别那步的预测器_->Run()这一步会崩溃的具体报错，方面我们排查问题~

已查出问题 是与paddlelite不兼容 以及导出模型需要调整 你们可以自己尝试下 去下载paddleDetection提供的主体nb模型 也一样运行不了的

**Comment by liu-jiaxuan** [comment]
好的，问题已记录，感谢反馈！
