### ISSUE TITLE
pp-shituv2 使用自己训练后导出的模型，再使用hubserving时，无法配置class_id_map_file，生成模型的文件中没有对应文件，

### ISSUE THREAD

**Issue by dlli** [PaddlePaddle/PaddleClas#3271]
pp-shituv2 使用自己训练后导出的模型，再使用hubserving时，无法配置class_id_map_file，生成模型的文件中没有对应文件，

详细参考hubserving/clas/params.py 配置文件

**Comment by liuhongen1234567** [comment]
您好，请问官方默认的预训练模型可以正常配置吗？

**Comment by dlli** [comment]
预训练模型可以正常配置，正常训练，正常导出，页可以用于推理。但是导出的模型文件中没有infer_cfg.yml文件，所以无法用于Paddle inference 和 Paddle Fast Deploy

**Comment by dlli** [comment]
paddle Serving

**Comment by liuhongen1234567** [comment]
您好，可以在导出时加入  -o Global.export_for_fd=True 参数，来生成yml文件，也可以直接到paddlex中去训练和导出，那个导出应该都会生成yml文件。
 python tools/export_model.py -c ./ppcls/configs/GeneralRecognitionV2/GeneralRecognitionV2_PPLCNetV2_base.yaml -o Global.pretrained_model="https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/rec/models/pretrain/PPShiTuV2/general_PPLCNetV2_base_pretrained_v1.0.pdparams" -o Global.save_inference_dir=deploy/models/GeneralRecognitionV2_PPLCNetV2_base  -o Global.export_for_fd=True

**Comment by dlli** [comment]
非常感谢
