### ISSUE TITLE
HSB-ResNet的问题

### ISSUE THREAD

**Issue by lxk767363331** [PaddlePaddle/PaddleClas#329]
论文和公众号已经发出来链接了，是不是应该把模型发出来了

**Comment by littletomatodonkey** [comment]
你好，感谢关注，我们本周会开源模型结构和代码，敬请期待！

**Comment by MARD1NO** [comment]
> 你好，感谢关注，我们本周会开源模型结构和预训练模型参数，敬请期待！

期待公布，看上去没用很多trick，但是准确率和推理时间都很惊人！
