### ISSUE TITLE
按照https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/models/PULC/PULC_text_image_orientation.md  教程运行，安装了Paddleplas后运行对应代码显示报错

### ISSUE THREAD

**Issue by kafukaf325** [PaddlePaddle/PaddleClas#3292]
安装后运行代码结果如下：
<img width="854" alt="4666e9762cc6f9ea41295d541fdc6f0" src="https://github.com/user-attachments/assets/d209b161-4d4d-4895-a14b-73c69b61612b">
python版本是3.8.20
文件的目录结构如下：
![image](https://github.com/user-attachments/assets/81c51499-bb65-4736-a141-12c0c9d8bc69)

**Comment by changdazhou** [comment]
通过log看出未正确安装GPU驱动，请确paddle正常加载GPU后测试

**Comment by byte-hzzh** [comment]
![image](https://github.com/user-attachments/assets/9c7941fe-4464-420b-ab50-5f4859988550)
我也遇到了上述问题，设置指定模型路径，没出现上述报错
