### ISSUE TITLE
使用自定义数据微调GeneralRecognitionV2_PPLCNetV2_base.yaml

### ISSUE THREAD

**Issue by chen1234520** [PaddlePaddle/PaddleClas#3297]
使用自定的数据微调GeneralRecognitionV2_PPLCNetV2_base.yaml特征提取模型，里面有两个参数
relabel: True
sampler:
    id_list: [50030, 80700, 92019, 96015] # be careful when set relabel=True
使用自定义的数据集，类别有17000类，请问上面两个参数是什么含义？需要根据自己的数据集类别数量更改吗？另外请问哪里能找到参考文档。https://paddleclas.readthedocs.io/zh-cn/latest/这个地址上看不到所有的参数信息。

**Comment by TingquanGao** [comment]
建议优先使用 PaddleX 进行模型开发，PaddleX 大幅简化了模型的训练参数配置，相关[文档](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/module_usage/tutorials/cv_modules/image_feature.md)。使用 PaddleClas 的话，相关[文档](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.6/docs/zh_CN/training/PP-ShiTu/feature_extraction.md)。你这个需求的话，建议用大一点的模型：[GeneralRecognitionV2_CLIP_vit_base](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.6/ppcls/configs/GeneralRecognitionV2/GeneralRecognitionV2_CLIP_vit_base.yaml)


关于两个参数：
1. `relabel `：对class id从0重新开始排序，适用于当id不是从0开始或是非连续的情况，通常置为False即可，只有当起始id远大于0，或是严重的不连续时建议设置为True；
2. `id_list`：只在PKSampler中会用到，是用来调整数据解决样本不均衡问题的，就是将id_list[0]~id_list[1]之间的类别的数据重复采样ratio[0]倍。

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
