### ISSUE TITLE
Nccl error, unhandled cuda error

### ISSUE THREAD

**Issue by ARQlalala** [PaddlePaddle/PaddleClas#330]
您好，请教一下，在初始化分布式训练中报错如下，用的是最新的2.0beta版本的paddle：
有遇到同样的错误嘛，有什么解决办法吗
----------------------
Error Message Summary:
----------------------
ExternalError:  Nccl error, unhandled cuda error  (at /paddle/paddle/fluid/platform/collective_helper.cc:83)

Traceback (most recent call last):
  File "./thirdparty/paddle_moco_dygraph/tools/train.py", line 160, in <module>
    main(args)
  File "./thirdparty/paddle_moco_dygraph/tools/train.py", line 112, in main
    strategy = paddle.distributed.init_parallel_env()
  File "/opt/_internal/cpython-2.7.15-ucs4/lib/python2.7/site-packages/paddle/distributed/parallel.py", line 134, in init_parallel_env
    parallel_helper._init_parallel_ctx()
  File "/opt/_internal/cpython-2.7.15-ucs4/lib/python2.7/site-packages/paddle/fluid/dygraph/parallel_helper.py", line 42, in _init_parallel_ctx
    __parallel_ctx__clz__.init()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::NCCLParallelContext::Init()
1   paddle::platform::NCCLCommContext::CreateNCCLComm(ncclUniqueId*, int, int, int, int)
2   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
3   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
4   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
ExternalError:  Nccl error, unhandled cuda error  (at /paddle/paddle/fluid/platform/collective_helper.cc:83)

**Comment by littletomatodonkey** [comment]
你好，请确保机器上已经正确安装cuda、cudnn和nccl库，如果nccl无法安装，可以使用`tools/train_multi_platform.py`脚本，可以参考这里的教程：[非nccl环境训练与评估](https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/zh_CN/tutorials/getting_started.md#1-windows%E6%88%96%E8%80%85cpu%E4%B8%8A%E8%AE%AD%E7%BB%83%E4%B8%8E%E8%AF%84%E4%BC%B0)

**Comment by ARQlalala** [comment]
好的谢谢，请教您一个其他的paddle问题：

初始化tensor：
self.register_buffer("queue", paddle.randn([128, 65536]))
self.queue = nn.functional.normalize(self.queue, axis=0)

后续训练每个进程进行分片赋值，我看paddle不支持，用numpy模式：
queue = self.queue.numpy()
queue[:, ptr:ptr + batch_size] = keys.numpy().T
self.queue = paddle.to_tensor(queue)

但这样self.queue 总是会新开内存，有什么办法能共享原来的内存吗？
之前有试过fluid.layers.assign，会报错说[128, 65536]这个size太大，求指教，谢谢~~

**Comment by littletomatodonkey** [comment]
> 好的谢谢，请教您一个其他的paddle问题：
> 
> 初始化tensor：
> self.register_buffer("queue", paddle.randn([128, 65536]))
> self.queue = nn.functional.normalize(self.queue, axis=0)
> 
> 后续训练每个进程进行分片赋值，我看paddle不支持，用numpy模式：
> queue = self.queue.numpy()
> queue[:, ptr:ptr + batch_size] = keys.numpy().T
> self.queue = paddle.to_tensor(queue)
> 
> 但这样self.queue 总是会新开内存，有什么办法能共享原来的内存吗？
> 之前有试过fluid.layers.assign，会报错说[128, 65536]这个size太大，求指教，谢谢~~

您好，这个问题可以在Paddle repo中提个issue，查看一下解决方案~https://github.com/PaddlePaddle/Paddle/issues
