### ISSUE TITLE
我训练的图片多标签识别模型，使用paddleserving部署模型，预测结果和在本地使用命令行预测结果不一致

### ISSUE THREAD

**Issue by syge** [PaddlePaddle/PaddleClas#3300]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如Linux/Windows/MacOS
  b. Python版本号，如Python3.6/7/8
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

PaddleClas：2.5.2       PaddleServing：paddlepaddle/serving：0.7.0-devel
以下是classification_web_service.py脚本内容

class ImagenetOp(Op):
    def init_op(self):
        self.seq = Sequential([
            Resize(256), CenterCrop(224), RGB2BGR(), Transpose((2, 0, 1)),
            Div(255), Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225],
                                True)
        ])
        self.label_dict = {}
        label_idx = 0
        with open("gas.label") as fin:
            for line in fin:
                self.label_dict[label_idx] = line.strip()
                label_idx += 1

    def preprocess(self, input_dicts, data_id, log_id):
        (_, input_dict), = input_dicts.items()
        batch_size = len(input_dict.keys())
        imgs = []
        for key in input_dict.keys():
            data = base64.b64decode(input_dict[key].encode('utf8'))
            data = np.fromstring(data, np.uint8)
            im = cv2.imdecode(data, cv2.IMREAD_COLOR)
            img = self.seq(im)
            imgs.append(img[np.newaxis, :].copy())
        input_imgs = np.concatenate(imgs, axis=0)
        return {"x": input_imgs}, False, None, ""

    def postprocess(self, input_dicts, fetch_dict, data_id, log_id):
        score_list = fetch_dict["prediction"]
        result = {"scores": str(score_list)}
        return result, None, ""

class ImageService(WebService):
    def get_pipeline_response(self, read_op):
        image_op = ImagenetOp(name="imagenet", input_ops=[read_op])
        return image_op

uci_service = ImageService(name="imagenet")
uci_service.prepare_pipeline_config("config.yml")
uci_service.run_service()

**Comment by zhangyubo0722** [comment]
推荐使用PaddleX进行服务化部署哈，PaddleX提供了比较完备的部署功能，可以参考https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/pipeline_usage/tutorials/cv_pipelines/image_multi_label_classification.md

**Comment by syge** [comment]
那使用paddleserving不能部署多标签识别模型？

**Comment by zhangyubo0722** [comment]
PaddleServing很久没有维护了，可以去 https://github.com/PaddlePaddle/Serving/issues 下提issue问问

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
