### ISSUE TITLE
numpy版本与最新的PaddleOCR=2.9.1冲突

### ISSUE THREAD

**Issue by WangYP90** [PaddlePaddle/PaddleClas#3303]
[PaddleClas](https://github.com/PaddlePaddle/PaddleClas) 中的numpy版本与最新的PaddleOCR=2.9.1冲突:
1.  依赖如下:
python = ">=3.9,<3.13"
paddlepaddle = "3.0.0b1"
paddleocr = "2.9.1"
paddleclas = "2.6.0"
2.  简要的依赖安装时报错:
"""
And because opencv-python-headless (4.10.0.84) depends on numpy (>=1.26.0)
and paddleclas (2.6.0) depends on numpy (1.24.4), paddleclas (2.6.0) is incompatible with opencv-python-headless (>=4.9.0.80).
"""
3.  建议将[PaddleClas](https://github.com/PaddlePaddle/PaddleClas)的requirements.txt修改为 如下:
numpy<2.0
4.  运行操作系统: Windows11

5. 完整的安装依赖错误:
"""
Because opencv-python-headless (4.9.0.80) depends on numpy (>=1.26.0)
and no versions of opencv-python-headless match >4.9.0.80,<4.10.0.82 || >4.10.0.82,<4.10.0.84 || >4.10.0.84, opencv-python-headless (>=4.9.0.80,<4.10.0.82 || >4.10.0.82,<4.10.0.84 || >4.10.0.84) requires numpy (>=1.26.0).
And because opencv-python-headless (4.10.0.82) depends on numpy (>=1.26.0), opencv-python-headless (>=4.9.0.80,<4.10.0.84 || >4.10.0.84) requires numpy (>=1.26.0).
And because opencv-python-headless (4.10.0.84) depends on numpy (>=1.26.0)
and paddleclas (2.6.0) depends on numpy (1.24.4), paddleclas (2.6.0) is incompatible with opencv-python-headless (>=4.9.0.80).
And because paddleocr (2.9.1) depends on albucore (0.0.13) which depends on opencv-python-headless (>=4.9.0.80), paddleclas (2.6.0) is incompatible with paddleocr (2.9.1).
So, because paddle-ocr-work-ticket depends on both paddleocr (2.9.1) and paddleclas (2.6.0), version solving failed.
"""

**Comment by zhangyubo0722** [comment]
感谢反馈，我们会验证并修改
