### ISSUE TITLE
代码中存在循环引用bug

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleClas#3304]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，MacOS
  b. Python版本号，python3.10
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log
当使用本地编辑安装paddleclas后，运行项目时就会出现循环应用的bug

![image](https://github.com/user-attachments/assets/92fbc144-6c0d-478d-8ecf-758111c2728f)

**Comment by liu-jiaxuan** [comment]
您使用[PaddleX](https://github.com/PaddlePaddle/PaddleX)试下，PaddleX修复了各套件中存在的潜在问题

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
