### ISSUE TITLE
训练时如何加载下载好的预训练模型

### ISSUE THREAD

**Issue by daiwei377** [PaddlePaddle/PaddleClas#3306]
你好，我在训练时终端打印的内容会一直卡在这个网址：
https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/legendary_models/PPLCNet_x1_0_ssld_pretrained.pdparams

我想是因为我当前网络原因，请问如何加载下载好的PPLCNet_x1_0_ssld_pretrained.pdparams，而不让它自动去上面那个网址下载呢？

**Comment by Bobholamovic** [comment]
可以将模型手动下载后，存放到这个目录：`~/.paddleclas/weights`

**Comment by daiwei377** [comment]
> 可以将模型手动下载后，存放到这个目录：`~/.paddleclas/weights`

感谢答复，请问Windows的话，对应的是c盘用户目录下该路径吗？

**Comment by Bobholamovic** [comment]
是的
