### ISSUE TITLE
PULC 找不到模型文件

### ISSUE THREAD

**Issue by szwlh-c** [PaddlePaddle/PaddleClas#3311]
paddlepaddle=2.6.2   paddleclas=2.6.0
Windows
python=3.8.20

按照教程复现时，会报找不到相应模型文件

from paddleclas import PaddleClas
model = PaddleClas(model_name="text_image_orientation")
result = model.predict(input_data=r"C:\ocr\imgs\test.jpg")
print(next(result))

RuntimeError: (NotFound) Cannot open file C:\Users\1212/.paddleclas/inference_model\PULC\text_image_orientation, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at ..\paddle\fluid\inference\api\analysis_predictor.cc:2577)

**Comment by TingquanGao** [comment]
看起来是windows下路径分隔符错误导致的，我们看下。

**Comment by wqw547243068** [comment]
> 看起来是windows下路径分隔符错误导致的，我们看下。

有什么快捷解法吗？改源码？

**Comment by TingquanGao** [comment]
可以参考这个PR #3313 改下，主要是[这里](https://github.com/PaddlePaddle/PaddleClas/pull/3313/files#diff-ec1929489cfb6c31676cc84204c6d9e6905a9c809e03d06a32422c230fa64684L49)

**Comment by wqw547243068** [comment]
> 可以参考这个PR #3313 改下，主要是[这里](https://github.com/PaddlePaddle/PaddleClas/pull/3313/files#diff-ec1929489cfb6c31676cc84204c6d9e6905a9c809e03d06a32422c230fa64684L49)

正解，感谢解答！

**Comment by TingquanGao** [comment]
感谢对PaddleClas的关注。那该issue就先关闭了，有问题可以reopen或new issue~
