### ISSUE TITLE
Cannot open file C:\Users\wqw/.paddleclas/inference_model\PULC\language_classification, please confirm whether the file is normal.

### ISSUE THREAD

**Issue by wqw547243068** [PaddlePaddle/PaddleClas#3317]
系统
- windows 10, 64位
- Python 3.11
- CPU only

工具包
- paddleclas                               2.6.0
- paddleocr                                2.9.1
- paddlepaddle                             2.6.2

功能：
- 输入图片，识别语种

代码：

```py
import paddleclas

file_name = r"E:\ocr\data\hand\3.jpg"

lang_model = paddleclas.PaddleClas(model_name="language_classification")
result = lang_model.predict(input_data=file_name)
result = list(result)
lang_type = result[0][0]['label_names'][0]
print('语言类型为：',lang_type)
```

错误信息

```
RuntimeError: (NotFound) Cannot open file C:\Users\wqw/.paddleclas/inference_model\PULC\language_classification, please confirm whether the file is normal.
 [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at ..\paddle\fluid\inference\api\analysis_predictor.cc:2577)
```

路径: 文件存在，只是路径名中的斜线异常
- `C:\Users\wqw/.paddleclas/inference_model\PULC\language_classification`
- 
![image](https://github.com/user-attachments/assets/d8f95465-7ac6-42ba-8d8f-5b6b0d335f75)

看到别的issue里 #3311 ，提到是windows下的路径名问题

于是，我修改源码，C:\Users\wqw\AppData\Roaming\Python\Python311\site-packages\paddleclas\paddleclas.py, 49行

```py
# BASE_DIR = os.path.expanduser("~/.paddleclas/") # 原代码
BASE_DIR = os.path.join(os.path.expanduser('~'), '.paddleclas') # 新代码
```

验证发现，路径矫正后，错误依然存在....

**Comment by GreatV** [comment]
试试 `set FLAGS_enable_pir_api=0`

**Comment by wqw547243068** [comment]
> 试试 `set FLAGS_enable_pir_api=0`

cmd中试了，老样子，不管用

另一个帖子里解答了，参考这个PR https://github.com/PaddlePaddle/PaddleClas/pull/3313 改下，主要是[这里](https://github.com/PaddlePaddle/PaddleClas/pull/3313/files#diff-ec1929489cfb6c31676cc84204c6d9e6905a9c809e03d06a32422c230fa64684L49)，验证有效
