### ISSUE TITLE
请问有MobileNetV4预训练模型吗

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleClas#3321]
请问有MobileNetV4预训练模型吗

**Comment by Bobholamovic** [comment]
你好，如下：
https://paddle-model-ecology.bj.bcebos.com/paddlex/official_inference_model/paddle3.0b2/MobileNetV4_conv_large_infer.tar
https://paddle-model-ecology.bj.bcebos.com/paddlex/official_inference_model/paddle3.0b2/MobileNetV4_conv_medium_infer.tar
https://paddle-model-ecology.bj.bcebos.com/paddlex/official_inference_model/paddle3.0b2/MobileNetV4_conv_small_infer.tar

**Comment by Dandelion111** [comment]
> 你好，如下： https://paddle-model-ecology.bj.bcebos.com/paddlex/official_inference_model/paddle3.0b2/MobileNetV4_conv_large_infer.tar https://paddle-model-ecology.bj.bcebos.com/paddlex/official_inference_model/paddle3.0b2/MobileNetV4_conv_medium_infer.tar https://paddle-model-ecology.bj.bcebos.com/paddlex/official_inference_model/paddle3.0b2/MobileNetV4_conv_small_infer.tar

谢谢，这个是推理模型，有没有imagenet的预训练权重，用来迁移训练
