### ISSUE TITLE
加载你们发布的预训练的模型来训练我的数据

### ISSUE THREAD

**Issue by ZhouBay-TF** [PaddlePaddle/PaddleClas#3331]
按照文档成功训练我的模型“ python -m paddle.distributed.launch --gpus="0,1" tools/train.py -c ./ppcls/configs/ImageNet/SwinTransformer/SwinTransformer_base_patch4_window7_224.yaml”，我认为它是从头开始训练的，我的数据有限，所以想实现加载预训练模型进行训练。
**我参考了“PaddleClas/blob/release/2.0/docs/zh_CN/tutorials/quick_start.md”这个里的加载和不加载的两条指令，我在MobileNetV3_large_x1_0_CIFAR100_finetune.yaml并没有发现加载或者下载预训练的key值，你可以详细解答吗？或者我在“SwinTransformer_base_patch4_window7_224.yaml”这个yaml中如何加载你们预训练的模型，谢谢。

**Comment by changdazhou** [comment]
建议直接使用PaddleX进行训练，PaddleX中已经自动加载预训练权重了哈

**Comment by ZhouBay-TF** [comment]
> 建议直接使用PaddleX进行训练，PaddleX中已经自动加载预训练权重了哈

好的谢谢。
