### ISSUE TITLE
HS-ResNet的问题

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleClas#338]
HS-ResNet模型开源了吗，我在model文件里面没有找到，希望说明一下

**Comment by littletomatodonkey** [comment]
你好，感谢关注，目前还没有开源，我们近期会开源，敬请期待～

**Comment by qdd1234** [comment]
还有一些论文的细节问题请教一下
![image](https://user-images.githubusercontent.com/68497831/96948911-415e5900-1519-11eb-8081-c98b6cdebb3f.png)
就是HS模块中conv全是1✖1卷积吗，还有就是卷积的通道数是不是和输入图像通道数相同？

**Comment by qdd1234** [comment]
还有一个问题想请教一下
![image](https://user-images.githubusercontent.com/68497831/96980945-1512fe80-1552-11eb-9514-a4221196bda8.png)
以黄色的split为例，可不可以将后面的那个黄色块和下面部分进行拼接，前面的进行最后的concat，就是和下面快进行拼接时候究竟选择前面的黄色块还是后面的黄色块这个你们做过实验吗

**Comment by cuicheng01** [comment]
> HS-ResNet模型开源了吗，我在model文件里面没有找到，希望说明一下

@qdd1234 下游实验全部ready后会开源，现在骨干网络层数更多的模型还在实验中，感谢关注~

**Comment by cuicheng01** [comment]
> 还有一个问题想请教一下
> ![image](https://user-images.githubusercontent.com/68497831/96980945-1512fe80-1552-11eb-9514-a4221196bda8.png)
> 以黄色的split为例，可不可以将后面的那个黄色块和下面部分进行拼接，前面的进行最后的concat，就是和下面快进行拼接时候究竟选择前面的黄色块还是后面的黄色块这个你们做过实验吗

这个没有看太懂，总之前边的黄色块和后边的黄色块是等价的，拼接哪个都是可以的~

**Comment by qdd1234** [comment]
HS可以用在下采样的3✖3卷积上吗

**Comment by cuicheng01** [comment]
> HS可以用在下采样的3✖3卷积上吗

没有做过尝试，你可以试一下哦~

**Comment by Margrate** [comment]
您好，您说上周开源，请问可以把HS-ResNet的model分享出来吗

**Comment by qdd1234** [comment]
model啥时候能开源？

**Comment by cuicheng01** [comment]
> 您好，您说上周开源，请问可以把HS-ResNet的model分享出来吗

非常抱歉哈，需要进一步验证其他设置的精度，ready后会开源~

**Comment by cuicheng01** [comment]
> model啥时候能开源？

非常抱歉哈，需要进一步验证其他设置的精度，ready后会开源~

**Comment by qdd1234** [comment]
![image](https://user-images.githubusercontent.com/68497831/97538472-695b2a00-19fb-11eb-98f4-93767c459ab7.png)
您好，可以讲解一下，PARAMnormal的公式以及PARAMhs的参数公式分别怎么计算得到的，谢谢

**Comment by qdd1234** [comment]
请问HS-ResNet开源了吗

**Comment by qdd1234** [comment]
有一个问题，你们在论文中说HSB的计算复杂度是比标准卷积少的，但你们在表1中给出的实验结果却显示了PARAM数比普通ResNet还要多，推理速度也要慢，这是为何，可以解释一下吗
![Uploading image.png…]()
