### ISSUE TITLE
Windows下使用c++预测库，cpu无法完成预测，mkldnn

### ISSUE THREAD

**Issue by Attackzzw** [PaddlePaddle/PaddleClas#359]
win下用c++的预测库，是不是不弄用cpu预测，生成exe后使用cpu预测，只提示两个加速，但是没有结果

![0Q}41%$0GP MLAIJJCDED_O](https://user-images.githubusercontent.com/49190204/97827269-b93d3800-1cfe-11eb-9a65-403601636296.png)

**Comment by littletomatodonkey** [comment]
你好，可以提供下预测库版本，windows机器的环境吗？

**Comment by Attackzzw** [comment]
预测库是beta2.0 cuda10， Windows cpu i79750h gpu1650 4g

**Comment by Attackzzw** [comment]
![Uploading 9~Z$%301S22ORNXQ_KF8A%2.png…]()

**Comment by Attackzzw** [comment]
![9~Z$%301S22ORNXQ_KF8A%2](https://user-images.githubusercontent.com/49190204/97844785-99216f00-1d26-11eb-92c0-e2d2710fd742.png)

**Comment by Attackzzw** [comment]
cpu预测 这里使用mkldnn就不可以，但是不使用就行
gpu没问题~
![9~Z$%301S22ORNXQ_KF8A%2](https://user-images.githubusercontent.com/49190204/97844842-ab031200-1d26-11eb-8361-55b01de2473d.png)

**Comment by Attackzzw** [comment]
经过大佬指导，把 PaddleClas/deploy/cpp_infer/src/cls.cpp 文件的第44行（config.DisableGlogInfo();）注释掉后，分别是
使用mkldnn(未出现预测结果)：
![1](https://user-images.githubusercontent.com/49190204/97858779-a0527800-1d3a-11eb-9d31-39812a9d16af.png)

![2](https://user-images.githubusercontent.com/49190204/97858789-a34d6880-1d3a-11eb-99c5-21407537fdbc.png)

未使用mkldnn（出现预测结果）：

![3](https://user-images.githubusercontent.com/49190204/97859033-f9baa700-1d3a-11eb-9c0e-a695708b7103.png)

![4](https://user-images.githubusercontent.com/49190204/97859038-fc1d0100-1d3a-11eb-8294-8c81e69d16aa.png)

**Comment by jiachen0212** [comment]
有没有大佬在ubunt下c++推理编译成功啊 ？
collect2: error: ld returned 1 exit status
CMakeFiles/clas_system.dir/build.make:202: recipe for target 'clas_system' failed
make[2]: *** [clas_system] Error 1
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/clas_system.dir/all' failed
make[1]: *** [CMakeFiles/clas_system.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
这种问题无从下手解决啊....

**Comment by jiachen0212** [comment]
linux下 不使用gpu 推理速度惊人的慢。有大佬知道咋回事吗  一个图耗时6s+

**Comment by jiachen0212** [comment]
你好，我有类似的问题，
linux下，开启mkldnn后我的速度基本没提升。cpu型号为： 4 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
mkldnn 0 1  速度差不多了。 然后 cpu_math_library_num_threads 也是开启为 1 最快 。use_zero_copy_run 0 1 无差别。
