### ISSUE TITLE
训练自己的backbone

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleClas#366]
paddleclas如何训练自己的backbone？

**Comment by littletomatodonkey** [comment]
已resnet为例，你可以在`ppcls/modeling/architectures/`文件夹下新建一个自己的模型结构文件，即你自己的backbone，然后在`ppcls/modeling/__init__.py`中添加一下import，最后写一个自己的配置文件就可以了`configs/ResNet/ResNet50.yaml`

这里需要改成自己的backbone名称

https://github.com/PaddlePaddle/PaddleClas/blob/bd18a2542e6cce84b7e6d5a6e3caebcfaf26bac3/configs/ResNet/ResNet50.yaml#L3
