### ISSUE TITLE
AttributeError: module 'paddle' has no attribute 'enable_static'

### ISSUE THREAD

**Issue by p1n0cch10** [PaddlePaddle/PaddleClas#367]
Hi,

I followed the tutorial here
[https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/en/tutorials/quick_start_en.md](url)

When I executed 
`export CUDA_VISIBLE_DEVICES=0
python -m paddle.distributed.launch \
    --selected_gpus="0" \
    tools/train.py \
        -c ./configs/quick_start/ResNet50_vd_finetune.yaml`

It shows paddle has no attribute enable_static. 

I am on Python 3.6.11 and Paddle 1.8.4. It seems that the piece of code is whin Paddle 2.0.

I would like to program in Paddle 1.8, but there no corresponding branch in repo. Is there some codes written in Paddle 1.8? Many thanks

```
cluster_node_ips: 127.0.0.1
log_dir: None
log_level: 20
node_ip: 127.0.0.1
print_config: True
selected_gpus: 0
started_port: None
training_script: tools/train.py
training_script_args: ['-c', './configs/quick_start/ResNet50_vd_finetune.yaml']
use_paddlecloud: False

INFO 2020-11-04 23:34:17,991 launch.py:210] get cluster from args:job_server:None pods:["rank:0 id:None addr:127.0.0.1 port:None visible_gpu:[] trainers:['gpu:[0] endpoint:127.0.0.1:55899 rank:0']"] job_stage_flag:None hdfs:None
INFO 2020-11-04 23:34:17,992 utils.py:367] start trainer proc:['/home/ecom/liuxiang12/env/tf_yolo/bin/python', '-u', 'tools/train.py', '-c', './configs/quick_start/ResNet50_vd_finetune.yaml'] env:{'FLAGS_selected_gpus': '0', 'PADDLE_TRAINER_ID': '0', 'PADDLE_CURRENT_ENDPOINT': '127.0.0.1:55899', 'PADDLE_TRAINERS_NUM': '1', 'PADDLE_TRAINER_ENDPOINTS': '127.0.0.1:55899'}
Traceback (most recent call last):
  File "tools/train.py", line 158, in <module>
    paddle.enable_static()
AttributeError: module 'paddle' has no attribute 'enable_static'
INFO 2020-11-04 23:34:24,005 utils.py:269] terminate all the procs
ERROR 2020-11-04 23:34:24,005 utils.py:413] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2020-11-04 23:34:27,008 utils.py:269] terminate all the procs
```

**Comment by littletomatodonkey** [comment]
You should use Paddle2.0.0-rc0, if not, you should comment out this line: `paddle.enable_static()`.

**Comment by p1n0cch10** [comment]
Awesome, you replied before I completed the post..

But.. is there any code written in Paddle 1.8?

**Comment by littletomatodonkey** [comment]
All codes in master branch are writen in Paddle1.8, you need just comment out this line: `paddle.enable_static()` to use PaddleClas in Paddle1.8, the changes are done in #347 to apapt to the PaddlePaddle-2.0rc.

**Comment by p1n0cch10** [comment]
Cool. Thx.

**Comment by littletomatodonkey** [comment]
You are welcome, enjoy PaddleClas and have a nice day!
