### ISSUE TITLE
How can I load ppcls.pdmodel, ppcls.pdopt, and ppcls.pdparams for prediction for a single image.

### ISSUE THREAD

**Issue by p1n0cch10** [PaddlePaddle/PaddleClas#368]
Hi,
I finished finetuing a classification network following here
[https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/en/tutorials/quick_start_en.md](url)
with the command
```
export CUDA_VISIBLE_DEVICES=0
python -m paddle.distributed.launch \
    --selected_gpus="0" \
    tools/train.py \
        -c ./configs/quick_start/ResNet50_vd_finetune.yaml
```

The outputs are three ppcls files. 

Then I would like to predict the class of a single test image, but did not find an example for it.
The tutorial here shows how to use the ppcls files as checkpoint for finetuning, and use the pretrained model for prediction.
[https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/en/extension/paddle_inference_en.md](url)

As I only have the ppcls files, how can I use it for prediction? Many thanks

**Comment by littletomatodonkey** [comment]
1. You may look for  the script `tools/infer/infer.py`. 
2. What's more, export the using the inference model to predict is also a good choice. See here for more details: 
https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/en/tutorials/getting_started_en.md#3-model-inference

**Comment by p1n0cch10** [comment]
Hi thanks for you help.

I read the tools/infer/infer.py. It seems that it only need the model_name (i.e. GoogLeNet) and the pretrained_model.

I think the pretrained_model is some thing like 
```
bn2a_branch1_mean
bn4a_branch1_offset
bn5b_branch2a_scale
...
```

I am a little confused that how can I use the resultant ppcls.pdmodel, ppcls.pdopt, and ppcls.pdparams.

Do you mean I need the export_model.py to export ppcls files?
```
python tools/export_model.py \
    --m=the name of model \
    --p=the path of persistable model\
    --o=the saved path of model and params
```
But the ppcls files are not in the persistable model format.

**Comment by littletomatodonkey** [comment]
You are directly use infer.py, the model(`-m`) should be same as yours.
```
python tools/infer/infer.py \
    -m MobileNetV3_large_x1_0 \
    -i ./my.jpg \
    -p ./output/MobileNetV3_large_x1_0/ppcls
```

**Comment by p1n0cch10** [comment]
Thx. will try then.

**Comment by p1n0cch10** [comment]
Awesome. That works. Thanks again.
