### ISSUE TITLE
finetune训练时，节点初始化问题

### ISSUE THREAD

**Issue by junjun210** [PaddlePaddle/PaddleClas#374]
InvalidArgumentError: The Tensor in the conv2d Op's Input Variable Input(feed_image) is not initialized.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] at (/paddle/paddle/fluid/framework/operator.cc:1289)
该怎么解决呢？

**Comment by littletomatodonkey** [comment]
可以试着获取下最新代码，这个应该是feed data构建的时候，名字不一样导致的
