### ISSUE TITLE
Do I need to revise the field total_images?

### ISSUE THREAD

**Issue by p1n0cch10** [PaddlePaddle/PaddleClas#375]
Hi I am using ResNet50_vd_finetune.yaml for finetuning my data.

My data has two classes, 10K images for training and 1K images for val.

I change the classes_num to 2. And do I need to revised the field total_images?

If so, is the value to be 11K or 10K? Many thanks.

**Comment by p1n0cch10** [comment]
The flowers102 example has 8189 images. But the total_images field is 1020.

**Comment by littletomatodonkey** [comment]
1. Yes, you should  set the field total_images corresponding to your dataset.
2. The field total_images is the number of the training set, and the flowers102 training set image number is 1020.

**Comment by p1n0cch10** [comment]
thx
