### ISSUE TITLE
我想添加自己的loss函数

### ISSUE THREAD

**Issue by dearsar** [PaddlePaddle/PaddleClas#381]
假设alpha是[0.1, 0.6, 0.3]的list，shape=[3]
而idx是paddle静态图的tensor--[ [2], [0], [1] ],shape=[-1, 1]
我想生成一个新的list，用普通python或者numpy的话，语法是beta = alpha[ idx ] = [ [0.3], [0.1], [0.6] ]
而用paddle应该怎么处理呢？ 生成的beta可以是paddle.tensor类型，shape=[-1, 1]

**Comment by littletomatodonkey** [comment]
你好，可以使用gather这个api进行实现，不过更推荐使用动态图进行实现

```
import paddle
a = paddle.to_tensor([3,4,5])
t_idx = paddle.to_tensor([2,1,0])
b = a.gather(t_idx)
print(b)
```
