### ISSUE TITLE
HS-ResNet中HSB计算复杂度问题

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleClas#383]
![image](https://user-images.githubusercontent.com/68497831/98561922-678b4380-22e4-11eb-8c08-243e89029a57.png)

> 您好，我想问一下，你这边推导计算是不是有错误，是不是括号部分是不是应该是如下图所示这个？您证明了计算复杂度低于普通卷积但你的最终Params却比ResNet还要高？
![image](https://user-images.githubusercontent.com/68497831/98561809-462a5780-22e4-11eb-8584-e37544d260a0.png)

**Comment by cuicheng01** [comment]
hi，您好，感谢关注HS-ResNet，上边的推导有一点点误差，之后我们会在正式的paper上勘误，谢谢~

**Comment by qdd1234** [comment]
您好，就是我自己的一篇论文中用到了HSB模块，现在也需要证明计算复杂度，可不可以交流一下，您那边正确的推导过程可以给我看一下吗，谢谢



---原始邮件---
发件人: "cuicheng01"<notifications@github.com&gt;
发送时间: 2020年11月10日(周二) 下午3:25
收件人: "PaddlePaddle/PaddleClas"<PaddleClas@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"qdd1234"<1752465993@qq.com&gt;;
主题: Re: [PaddlePaddle/PaddleClas] HS-ResNet中HSB计算复杂度问题 (#383)




 
hi，您好，感谢关注HS-ResNet，上边的推导有一点点误差，之后我们会在正式的paper上勘误，谢谢~

**Comment by cuicheng01** [comment]
> 您好，就是我自己的一篇论文中用到了HSB模块，现在也需要证明计算复杂度，可不可以交流一下，您那边正确的推导过程可以给我看一下吗，谢谢
> […](#)
> ---原始邮件--- 发件人: "cuicheng01"<notifications@github.com&gt; 发送时间: 2020年11月10日(周二) 下午3:25 收件人: "PaddlePaddle/PaddleClas"<PaddleClas@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"qdd1234"<1752465993@qq.com&gt;; 主题: Re: [PaddlePaddle/PaddleClas] HS-ResNet中HSB计算复杂度问题 (#383) hi，您好，感谢关注HS-ResNet，上边的推导有一点点误差，之后我们会在正式的paper上勘误，谢谢~ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可以，我们可以直接邮件交流哈~

**Comment by qdd1234** [comment]
我是直接发您的github邮箱吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "cuicheng01"<notifications@github.com&gt;; 
发送时间: 2020年11月17日(星期二) 下午5:35
收件人: "PaddlePaddle/PaddleClas"<PaddleClas@noreply.github.com&gt;; 
抄送: "周昆阳"<1752465993@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleClas] HS-ResNet中HSB计算复杂度问题 (#383)





  
您好，就是我自己的一篇论文中用到了HSB模块，现在也需要证明计算复杂度，可不可以交流一下，您那边正确的推导过程可以给我看一下吗，谢谢
 …
 ---原始邮件--- 发件人: "cuicheng01"<notifications@github.com&gt; 发送时间: 2020年11月10日(周二) 下午3:25 收件人: "PaddlePaddle/PaddleClas"<PaddleClas@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"qdd1234"<1752465993@qq.com&gt;; 主题: Re: [PaddlePaddle/PaddleClas] HS-ResNet中HSB计算复杂度问题 (#383) hi，您好，感谢关注HS-ResNet，上边的推导有一点点误差，之后我们会在正式的paper上勘误，谢谢~ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
可以，我们可以直接邮件交流哈~

**Comment by cuicheng01** [comment]
可以~

**Comment by qdd1234** [comment]
您好，我通过邮件已经发到您的邮箱了，您查收一下

**Comment by cuicheng01** [comment]
邮件没有收到，我们单独邮件联系吧



在 2020-11-18 10:52:19，"qdd1234" <notifications@github.com> 写道：

您好，我通过邮件已经发到您的邮箱了，您查收一下

**Comment by qdd1234** [comment]
我是通过邮件单独发到您的邮箱里面，您看一下这下有没有收到，谢谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleClas"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月19日(星期四) 下午3:26
收件人:&nbsp;"PaddlePaddle/PaddleClas"<PaddleClas@noreply.github.com&gt;;
抄送:&nbsp;"周昆阳"<1752465993@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleClas] HS-ResNet中HSB计算复杂度问题 (#383)





 邮件没有收到，我们单独邮件联系吧
 
 
 
 在 2020-11-18 10:52:19，"qdd1234" <notifications@github.com&gt; 写道：
 
 您好，我通过邮件已经发到您的邮箱了，您查收一下

**Comment by qdd1234** [comment]
您好，这是我的邮箱：1752465993@qq.com   可否将您那边正确的推导公式和我分享一下，我论文就差这个模块了，谢谢了

**Comment by cuicheng01** [comment]
已回复邮件~

**Comment by qdd1234** [comment]
您好，我给您邮箱发了几个我的困惑点，您看一下，谢谢~
