### ISSUE TITLE
loss更改

### ISSUE THREAD

**Issue by jasonlove521** [PaddlePaddle/PaddleClas#388]
如何在配置文件或者train.py里修改loss函数，指定loss函数类型

**Comment by littletomatodonkey** [comment]
你好，首先需要在ppcls/modeling/loss.py中添加自己的loss实现，然后再修改tools/program.py中的create_loss函数～

**Comment by jasonlove521** [comment]
谢谢 @littletomatodonkey

**Comment by ITerydh** [comment]
> 你好，首先需要在ppcls/modeling/loss.py中添加自己的loss实现，然后再修改tools/program.py中的create_loss函数～

在2.2版本中没有program.py该如何更改呢？
