### ISSUE TITLE
数据格式问题Error: Variable value (label) of OP(fluid.layers.cross_entropy) expected >= 0 and < 5, but got 5.

### ISSUE THREAD

**Issue by nihuizhidao** [PaddlePaddle/PaddleClas#389]
OS：Windows
paddlepaddle-gpu：2.0.0rc0.post100

数据集：
![image](https://user-images.githubusercontent.com/26674015/98880566-feadf200-24c2-11eb-9be0-6b1b161b963e.png)

train_list.txt

> 1_0.jpg 1
> 1_1.jpg 1
> 1_10.jpg 1
> 1_100.jpg 1
> 1_101.jpg 1
> 1_102.jpg 1
> 1_104.jpg 1
> ...

val_list:

> 1_124.jpg 1
> 1_30.jpg 1
> 1_106.jpg 1
> 1_202.jpg 1
> 1_8.jpg 1
> 1_2.jpg 1
> 1_6.jpg 1
> ...

config.yaml

> mode: 'train'
> use_gpu: false
> ARCHITECTURE:
>     name: "MobileNetV2_x0_5"
> 
> pretrained_model: "./models/MobileNetV2_x0_5_pretrained"
> model_save_dir: "./output/"
> classes_num: 5
> total_images: 1832
> save_interval: 1
> validate: True
> valid_interval: 1
> epochs: 10
> topk: 3
> image_shape: [3, 224, 224]
> 
> 
> LEARNING_RATE:
>     function: 'Cosine'
>     params:
>         lr: 0.005
> 
> OPTIMIZER:
>     function: 'Momentum'
>     params:
>         momentum: 0.9
>     regularizer:
>         function: 'L2'
>         factor: 0.00003
> 
> TRAIN:
>     batch_size: 8
>     num_workers: 2
>     file_list: "./dataset/20201111/train_list.txt"
>     data_dir: "./dataset/20201111/full"
>     shuffle_seed: 0
>     transforms:
>         - DecodeImage:
>             to_rgb: True
>             to_np: False
>             channel_first: False
>         - RandCropImage:
>             size: 224
>             ratio: [1.0, 1.0]
>         - RandFlipImage:
>             flip_code: 1
>         - NormalizeImage:
>             scale: 1./255.
>             mean: [0.485, 0.456, 0.406]
>             std: [0.229, 0.224, 0.225]
>             order: ''
>         - ToCHWImage:
> 
> 
> 
> VALID:
>     batch_size: 4
>     num_workers: 1
>     file_list: "./dataset/20201111/val_list.txt"
>     data_dir: "./dataset/20201111/full"
>     shuffle_seed: 0
>     transforms:
>         - DecodeImage:
>             to_rgb: True
>             to_np: False
>             channel_first: False
>         - ResizeImage:
>             resize_short: 256
>         - CropImage:
>             size: 224
>         - NormalizeImage:
>             scale: 1.0/255.0
>             mean: [0.485, 0.456, 0.406]
>             std: [0.229, 0.224, 0.225]
>             order: ''
>         - ToCHWImage:

报错：

> !!! The CPU_NUM is not specified, you should set CPU_NUM in the environment variable list.
> CPU_NUM indicates that how many CPUPlace are used in the current task.
> And if this parameter are set as N (equal to the number of physical CPU core) the program may be faster.
> 
> export CPU_NUM=8 # for example, set CPU_NUM as number of physical CPU core which is 8.
> 
> !!! The default number of CPU_NUM=1.
> 2020-11-12 08:32:27 INFO: Loading parameters from ./models/MobileNetV2_x0_5_pretrained...
> 2020-11-12 08:32:27 WARNING: variable fc10_offset is already excluded automatically
> 2020-11-12 08:32:27 WARNING: variable fc10_weights is already excluded automatically
> 2020-11-12 08:32:27 INFO: Finish initing model from ['./models/MobileNetV2_x0_5_pretrained']
> W1112 08:32:28.292935 17236 build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
> 2020-11-12 08:32:30 INFO: epoch:0   train step:0    loss:  2.1282 top1: 0.1250 top3: 0.3750 lr: 0.005000 elapse: 2.833s
> Traceback (most recent call last):
>   File "train_multi_platform.py", line 169, in <module>
>     main(args)
>   File "train_multi_platform.py", line 133, in main
>     epoch_id, 'train', config, vdl_writer)
>   File "D:\AAS_Projects\Paddlejs4ARmodel\program.py", line 435, in run
>     metrics = exe.run(program=program, feed=batch, fetch_list=fetch_list)
>   File "D:\Anaconda3\envs\paddle20\lib\site-packages\paddle\fluid\executor.py", line 1107, in run
>     six.reraise(*sys.exc_info())
>   File "D:\Anaconda3\envs\paddle20\lib\site-packages\six.py", line 703, in reraise
>     raise value
>   File "D:\Anaconda3\envs\paddle20\lib\site-packages\paddle\fluid\executor.py", line 1105, in run
>     return_merged=return_merged)
>   File "D:\Anaconda3\envs\paddle20\lib\site-packages\paddle\fluid\executor.py", line 1242, in _run_impl
>     return_merged=return_merged)
>   File "D:\Anaconda3\envs\paddle20\lib\site-packages\paddle\fluid\executor.py", line 910, in _run_parallel
>     tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
> paddle.fluid.core_avx.EnforceNotMet:
> 
>   Compile Traceback (most recent call last):
>     File "train_multi_platform.py", line 169, in <module>
>       main(args)
>     File "train_multi_platform.py", line 80, in main
>       is_distributed=False)
>     File "D:\AAS_Projects\Paddlejs4ARmodel\program.py", line 354, in build
>       use_distillation=use_distillation)
>     File "D:\AAS_Projects\Paddlejs4ARmodel\program.py", line 233, in create_fetchs
>       use_distillation)
>     File "D:\AAS_Projects\Paddlejs4ARmodel\program.py", line 162, in create_loss
>       return loss(out, target)
>     File "D:\AAS_Projects\Paddlejs4ARmodel\ppcls\modeling\loss.py", line 82, in __call__
>       cost = self._crossentropy(input, target)
>     File "D:\AAS_Projects\Paddlejs4ARmodel\ppcls\modeling\loss.py", line 52, in _crossentropy
>       input=softmax_out, label=target, soft_label=self._label_smoothing)
>     File "D:\Anaconda3\envs\paddle20\lib\site-packages\paddle\fluid\layers\loss.py", line 260, in cross_entropy
>       return cross_entropy2(input, label, ignore_index)
>     File "D:\Anaconda3\envs\paddle20\lib\site-packages\paddle\fluid\layers\loss.py", line 298, in cross_entropy2
>       attrs=attrs)
>     File "D:\Anaconda3\envs\paddle20\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
>       return self.main_program.current_block().append_op(*args, **kwargs)
>     File "D:\Anaconda3\envs\paddle20\lib\site-packages\paddle\fluid\framework.py", line 2917, in append_op
>       attrs=kwargs.get("attrs", None))
>     File "D:\Anaconda3\envs\paddle20\lib\site-packages\paddle\fluid\framework.py", line 2014, in __init__
>       for frame in traceback.extract_stack():
> 
> --------------------------------------
> C++ Traceback (most recent call last):
> --------------------------------------
> Not support stack backtrace yet.
> 
> ----------------------
> Error Message Summary:
> ----------------------
> Error: Variable value (label) of OP(fluid.layers.cross_entropy) expected >= 0 and < 5, but got 5. Please check label value. (at D:\2.0.0-rc0\paddle\paddle/fluid/operators/cross_entropy_op.h:175)
>   [operator < cross_entropy2 > error]

请问这个会是什么原因呢？感觉像是数据标注文件的格式问题，但是这格式应该是对的吧？

**Comment by littletomatodonkey** [comment]
你的class num是5，标注文件中应该是从0开始，最大值为4，但是出现了5，所以报错了

**Comment by nihuizhidao** [comment]
哦哦，懂了，这个最好是加到数据准备的文档里吧。。。谢谢你！
