### ISSUE TITLE
Can I program multiple models in one code script?

### ISSUE THREAD

**Issue by p1n0cch10** [PaddlePaddle/PaddleClas#394]
Hi,

I would like to detect the person in an image and classify the person(i.e. chef, soldier, ...).

So, I firstly use a pp-yolo for detection. Then get the patch based on the person's bbox. At last, I use a resnet50_vd for classification.

Currently I completed the training for the classification. But do not know how to put the detection model and the classification model in one piece of code.

Are there any examples for the application? Many thanks.

**Comment by littletomatodonkey** [comment]
For this case, it may be a better solution for you to export the pretrained weights to `infernce models`. And then you just need to extract the pre-process codes and post-process codes from the repos, therefore you can avoid defining so many models for the actual  inference process.
