### ISSUE TITLE
注意力机制

### ISSUE THREAD

**Issue by Ryan906k9** [PaddlePaddle/PaddleClas#401]
请问有没有带有注意力机制的预训练模型，比如CBAM+ResNet 这种？

**Comment by cuicheng01** [comment]
目前带注意力机制的只有SE和split-attention，CBAM还没有呢，如果你实现了并且训练出了pretrained model，欢迎提PR哈~

**Comment by Ryan906k9** [comment]
请问 SE和split-attention 的在哪里可以看到？

**Comment by cuicheng01** [comment]
可以查看SE-ResNet或者ResNeSt的实现哈~

**Comment by Ryan906k9** [comment]
好的，谢谢
