### ISSUE TITLE
Does the validation process update the model weights?

### ISSUE THREAD

**Issue by p1n0cch10** [PaddlePaddle/PaddleClas#415]
Hi,

I am using the sample code here for training, https://github.com/PaddlePaddle/PaddleClas/blob/master/tools/train.py

with the configure file configs/quick_start/ResNet50_vd_finetune.yaml

I would like to know does the validation process update the model weights?

Many thanks.

**Comment by littletomatodonkey** [comment]
Thanks for your attention. During the validation process, the weights will be not updated.
