### ISSUE TITLE
预测支持中文标签吗？

### ISSUE THREAD

**Issue by fish-hello** [PaddlePaddle/PaddleClas#418]
预测支持中文标签吗？，发现旧版本不支持。

**Comment by cuicheng01** [comment]
hi，您是说ImageNet的中文标签还是自己定义的呢？这个可以在预测的时候做一个映射处理。

**Comment by fish-hello** [comment]
> hi，您是说ImageNet的中文标签还是自己定义的呢？这个可以在预测的时候做一个映射处理。

应该是我自定义数据集中文路径导致报错，影响不大
