### ISSUE TITLE
'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by qingweihk** [PaddlePaddle/PaddleClas#421]
I try the girdmask, got an error like:
'utf-8' codec can't decode byte 0xff in position 0: invalid start byte'

then I use the mothod form stackoverflow :add the 'rb' to the read line like:
for f in fnames:
    data = open(os.path.join(imgs_dir, f)**,'rb'**).read()

then got another error:
'NoneType' object has no attribute 'shape'

any help?Thanks

**Comment by cuicheng01** [comment]
Can you tell us the python version and paddlepaddle version? Let us try to reproduce your problem.

**Comment by littletomatodonkey** [comment]
> 'NoneType' object has no attribute 'shape'

You should check whether the image path is right. It seems that the images can not be read rightly.
