### ISSUE TITLE
question about xception-deeplab

### ISSUE THREAD

**Issue by CoinCheung** [PaddlePaddle/PaddleClas#422]
Hi,

Thanks for sharing this !!!

Would you tell me from where can we find the xception model architecture details, and the training hyper-parameters ?

**Comment by cuicheng01** [comment]
You can view the network structure for the details you mentioned, and refer to this link for training hyperparameters: https://github.com/PaddlePaddle/PaddleClas/blob/master/configs/Xception/Xception65_deeplab.yaml.

**Comment by CoinCheung** [comment]
Thanks for telling this !! 
I found this line: 
https://github.com/PaddlePaddle/PaddleClas/blob/d454a22e2c93182ed3b875ef6ced90b948eff91a/ppcls/modeling/architectures/xception_deeplab.py#L240
It means that no matter whether the output stride is 32 or 16, the dilation rate is always 2. However, if the backbone is resnet, the dilation rate only changes when the output stride is changed. For example, when the output stride is 16, the last stage of resnet will enlarge its dilateion rate from 1 to 2. Is xception different from resnet in this ?

**Comment by CoinCheung** [comment]
Thanks for telling this !! 
I found this line: 
https://github.com/PaddlePaddle/PaddleClas/blob/d454a22e2c93182ed3b875ef6ced90b948eff91a/ppcls/modeling/architectures/xception_deeplab.py#L240
It means that no matter whether the output stride is 32 or 16, the dilation rate is always 2. However, if the backbone is resnet, the dilation rate only changes when the output stride is changed. For example, when the output stride is 16, the last stage of resnet will enlarge its dilateion rate from 1 to 2. Is xception different from resnet in this ?

**Comment by cuicheng01** [comment]
This backbone is just a pretrained model trained for classification. Other tasks need to determine the dilation rate according to the specific output stride. You can temporarily change some codes according to your specific needs.

**Comment by CoinCheung** [comment]
Thanks for replying !! I am trying.
