### ISSUE TITLE
部署时GPU预测比CPU慢，GPU大于1000ms，CPU大约50ms

### ISSUE THREAD

**Issue by zhouyuxixixi** [PaddlePaddle/PaddleClas#425]
经过分析，发现是cls.cpp文件中的input_t->copy_from_scpu(input.data());代码执行太慢，需要大约1s。
请问这是为什么？是我电脑的原因？

**Comment by zhouyuxixixi** [comment]
经过尝试。paddleclas的源编译码，是不支持批量图片预测的。可自行修改程序，使其可以预测图片集，会发现，仅仅钱几次预测较慢，后续都是比CPU快的。

**Comment by zhouyuxixixi** [comment]
input_t->copy_from_scpu(input.data());这个函数不仅仅使复制内存到显存，还包括一开始的显存初始化等操作，也就是这个模型第一次执行这个函数的时候，会去初始化显存和其他操作，第二次就不会了，所以当预测数据集的时候，明显能够发现还是GPU快

**Comment by littletomatodonkey** [comment]
嗯嗯，GPU预测的话，初始化需要耗费比较多的时间，所以统计时间的话，一般都会去除前几次预测的时间统计
