### ISSUE TITLE
部署服务有时间要做一下了，我都是自己接入PaddleHub的

### ISSUE THREAD

**Issue by fish-hello** [PaddlePaddle/PaddleClas#429]
主要是版本不对应，与Serving。不过Serving也没怎么维护起来，sad！

**Comment by littletomatodonkey** [comment]
你好，可以在动态图分支下面看到我们的hubserving demo哈：https://github.com/PaddlePaddle/PaddleClas/blob/dygraph/deploy/hubserving/readme.md

Paddle2.0以后，我们主要会基于动态图去开发
