### ISSUE TITLE
can't find PADDLE_TRAINER_ENDPOINTS

### ISSUE THREAD

**Issue by ybxbupt** [PaddlePaddle/PaddleClas#437]
使用提供的flowers102数据集训练，出现下列错误：

Hey! Looks like you accidentally pulled in an incorrect dependency. This can bork your software supply chain in all sorts of ways, so it's very important to be careful with what you're pulling in. Read more about software supply chain security here: https://www.usenix.org/conference/usenixsecurity19/presentation/torres-arias
Traceback (most recent call last):
  File "H:/yuanbaoxi/test_code/paddlepaddle-PaddleClas-master/PaddleClas/train_flower.py", line 178, in <module>
    main(args)
  File "H:/yuanbaoxi/test_code/paddlepaddle-PaddleClas-master/PaddleClas/train_flower.py", line 66, in main
    fleet.init(role)
  File "C:\ProgramData\Anaconda3\envs\paddleCls\lib\site-packages\paddle\fluid\incubate\fleet\base\fleet_base.py", line 219, in init
    self._role_maker.generate_role()
  File "C:\ProgramData\Anaconda3\envs\paddleCls\lib\site-packages\paddle\fluid\incubate\fleet\base\role_maker.py", line 539, in generate_role
    assert self._worker_endpoints is not None, "can't find PADDLE_TRAINER_ENDPOINTS"
AssertionError: can't find PADDLE_TRAINER_ENDPOINTS

配置文件如下
mode: 'train'
ARCHITECTURE:
    name: 'ResNet50'

pretrained_model: ""
model_save_dir: "./output/"
classes_num: 1000
total_images: 1281167
save_interval: 1
validate: True
valid_interval: 1
epochs: 120
topk: 5
image_shape: [3, 224, 224]

use_mix: False
ls_epsilon: -1

LEARNING_RATE:
    function: 'Piecewise'          
    params:                   
        lr: 0.1               
        decay_epochs: [30, 60, 90] 
        gamma: 0.1 

OPTIMIZER:
    function: 'Momentum'
    params:
        momentum: 0.9
    regularizer:
        function: 'L2'
        factor: 0.000100

TRAIN:
    batch_size: 16
    num_workers: 4
    file_list: "./dataset/flowers102/train_list.txt"
    data_dir: "./dataset/flowers102/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            to_np: False
            channel_first: False
        - RandCropImage:
            size: 224
        - RandFlipImage:
            flip_code: 1
        - NormalizeImage:
            scale: 1./255.
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:

VALID:
    batch_size: 4
    num_workers: 4
    file_list: "./dataset/flowers102/val_list.txt"
    data_dir: "./dataset/flowers102/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            to_np: False
            channel_first: False
        - ResizeImage:
            resize_short: 256
        - CropImage:
            size: 224
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:

**Comment by littletomatodonkey** [comment]
你好，`tools/train.py`是基于fleet训练的，支持单机单卡、多卡或者多机多卡，但是需要nccl库，如果不希望使用gpu或者GPU进行训练的话，可以使用`tools/train_multi_platform.py`哈

**Comment by ybxbupt** [comment]
单机单卡也需要nccl库吗？
