### ISSUE TITLE
请问，根据不同缺陷类别之间的区别有做一些预处理的工作吗？

### ISSUE THREAD

**Issue by xuanwdx** [PaddlePaddle/PaddleClas#438]

**Comment by littletomatodonkey** [comment]
你好，目前PaddleClas除了随机裁剪、随机翻转等水平变换之外，也提供了8种数据增广和预处理的方式：
https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/zh_CN/advanced_tutorials/image_augmentation/ImageAugment.md
但是具体场景可能还是需要选择最适合的预处理方法
