### ISSUE TITLE
PaddleClas输入图片大小

### ISSUE THREAD

**Issue by Qggg** [PaddlePaddle/PaddleClas#448]
PaddleClas默认的配置是image_shape: [3, 224, 224]，我注意到Paddle的文档上写着，InceptionV4和Xception采用的输入图像的分辨率为299x299，DarkNet53为256x256，Fix_ResNeXt101_32x48d_wsl为320x320，其余模型使用的分辨率均为224x224。
我想训练的样本是大都是细长的，大都是高度30-100，长度50-200这样的小图片，假如我使用Resnet101_vd，请问是否需要调整image_shape，如果不调整，是否会浪费很多显存，影响训练速度和推理速度？如果调整该如何调整？

谢谢

**Comment by littletomatodonkey** [comment]
1. shape为[3,224,224]的话，是不会浪费很多显存的，因为所有图像都会被resize到这个尺度，
2. 大部分骨干网络在设计的时候，都会降采样32倍，最后做一次avg pooling，因此，如果修改你的图像尺度是可以的，但是建议图像的高度和宽度都是32的倍数

**Comment by Qggg** [comment]
> 1. shape为[3,224,224]的话，是不会浪费很多显存的，因为所有图像都会被resize到这个尺度，
> 2. 大部分骨干网络在设计的时候，都会降采样32倍，最后做一次avg pooling，因此，如果修改你的图像尺度是可以的，但是建议图像的高度和宽度都是32的倍数

您好
我训练的应用是对法文和日文等7个语种语种识别，7分类x5万样本。样本是一些屏幕截图做的文本行切片，由于样本本身分辨率就很低，就算resize到[3,224,224]，再降低采样率到1/32，那图片中的文本会不会变成一个小黑点，网络也学习不到文字的特征了吧？
我目前使用ResNet101_vd，和其对应ImageNet的默认配置参数，结果感人。

2020-12-08 07:25:45 INFO: END eval loss_avg:  0.3104 top1_avg: 0.4279 top5_avg: 0.4287 elapse_sum: 28.089ss

尝试过调整image_shape到 [3,50,50]，RandCropImage到50，增加或者去掉Mix，可最终结果相同：Loss到0.31 0.32就无法下降了，top1_avg在0.42左右无法提升。

希望得到您的指教。
