### ISSUE TITLE
动态图分支用的paddle1.8还是2.0

### ISSUE THREAD

**Issue by liguoyu666** [PaddlePaddle/PaddleClas#453]
另外，训练时的-o参数，看了半天没在代码里找到是哪里来的，文档里对config参数的说明不全，有不有个类似padseg的包含所有参数的config.py的文件

**Comment by liguoyu666** [comment]
动态图使用2.0环境报错：
`2020-12-07 16:58:57 INFO: Load weight: bn5c_branch2b_variance, shape: (512,)
2020-12-07 16:58:57 INFO: Load weight: res5c_branch2c_weights, shape: (2048, 512, 1, 1)
2020-12-07 16:58:57 INFO: Load weight: bn5c_branch2c_scale, shape: (2048,)
2020-12-07 16:58:57 INFO: Load weight: bn5c_branch2c_offset, shape: (2048,)
2020-12-07 16:58:57 INFO: Load weight: bn5c_branch2c_mean, shape: (2048,)
2020-12-07 16:58:57 INFO: Load weight: bn5c_branch2c_variance, shape: (2048,)
2020-12-07 16:58:57 INFO: Load weight: fc_0.w_0, shape: (2048, 1000)
2020-12-07 16:58:57 INFO: Load weight: fc_0.b_0, shape: (1000,)
/home/user/.conda/envs/paddle2.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1175: UserWarning: Skip loading for out.weight. out.weight receives a shape [2048, 1000], but the expected shape is [2048, 2].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/user/.conda/envs/paddle2.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1175: UserWarning: Skip loading for out.bias. out.bias receives a shape [1000], but the expected shape is [2].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/user/.conda/envs/paddle2.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1175: UserWarning: Skip loading for out.weight. out.weight receives a shape [2048, 1000], but the expected shape is [2048, 2].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/user/.conda/envs/paddle2.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1175: UserWarning: Skip loading for out.bias. out.bias receives a shape [1000], but the expected shape is [2].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
2020-12-07 16:58:57 INFO: Finish initing model from ./pretrained/ResNet50_vd_ssld_pretrained
2020-12-07 16:58:57 ERROR: DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "tools/train.py", line 117, in <module>
    main(args)
  File "tools/train.py", line 90, in main
    epoch_id, 'train')
  File "/home/user/Projects/lgy/PaddleClas/tools/program.py", line 300, in run
    for idx, batch in enumerate(dataloader()):
  File "/home/user/.conda/envs/paddle2.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 743, in __next__
    data = self._reader.read_next_var_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::_M_run()
1   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
2   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
5   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:154)

2020-12-07 16:58:57 ERROR: DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "tools/train.py", line 117, in <module>
    main(args)
  File "tools/train.py", line 90, in main
    epoch_id, 'train')
  File "/home/user/Projects/lgy/PaddleClas/tools/program.py", line 300, in run
    for idx, batch in enumerate(dataloader()):
  File "/home/user/.conda/envs/paddle2.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 743, in __next__
    data = self._reader.read_next_var_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::_M_run()
1   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
2   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
5   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:154)

2020-12-07 16:58:57 ERROR: DataLoader reader thread raised an exception!
2020-12-07 16:58:57 ERROR: DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "tools/train.py", line 117, in <module>
    main(args)
  File "tools/train.py", line 90, in main
    epoch_id, 'train')
  File "/home/user/Projects/lgy/PaddleClas/tools/program.py", line 300, in run
    for idx, batch in enumerate(dataloader()):
  File "/home/user/.conda/envs/paddle2.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 743, in __next__
    data = self._reader.read_next_var_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::_M_run()
1   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
2   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
5   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:154)

Traceback (most recent call last):
  File "tools/train.py", line 117, in <module>
    main(args)
  File "tools/train.py", line 90, in main
    epoch_id, 'train')
  File "/home/user/Projects/lgy/PaddleClas/tools/program.py", line 300, in run
    for idx, batch in enumerate(dataloader()):
  File "/home/user/.conda/envs/paddle2.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 743, in __next__
    data = self._reader.read_next_var_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::_M_run()
1   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
2   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
5   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:154)

INFO 2020-12-07 16:59:01,928 utils.py:275] terminate all the procs
ERROR 2020-12-07 16:59:01,929 utils.py:445] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] was aborted. Please check its log.
INFO 2020-12-07 16:59:04,932 utils.py:275] terminate all the procs
`

**Comment by littletomatodonkey** [comment]
配置可以参考这里：https://github.com/PaddlePaddle/PaddleClas/blob/dygraph/docs/zh_CN/tutorials/config.md
