### ISSUE TITLE
二分类，产品好坏分类的，优化问题

### ISSUE THREAD

**Issue by zhouyuxixixi** [PaddlePaddle/PaddleClas#454]
一个二分类问题，我的数据集是1000张好的，和1000张坏的，对其进行分类
**正常流程结果**
识别率在90%，有很多坏的被识别成好的了
**希望结果**
我想达到，坏的被识别为坏的的准确率是100%，好的也能容忍被识别为坏的
请问，我该如何修改，我目前能想到的是：
1、减少好的图像数量
2、对loss值进行修改

**Comment by TingquanGao** [comment]
比较简单的方法，可以调整score的阈值试一下。如果是0.5做阈值：`result = 好 if score > 0.5 else 坏`，可以试一下把score改为0.6 ？甚至0.7 ？
