### ISSUE TITLE
如何对C++部署时config文件中的resize_short_size进行修改

### ISSUE THREAD

**Issue by zhouyuxixixi** [PaddlePaddle/PaddleClas#456]
我在AIstudio上进行二分类问题
由于我的数据集图像大小位置都很固定，不需要进行数据增强，所以我对configs/resnet34_vd文件的transform部分进行了修改
**修改前**
![image](https://user-images.githubusercontent.com/65207014/101454758-72c9a180-396c-11eb-82a8-9194a7c11e0d.png)

**修改后**
![image](https://user-images.githubusercontent.com/65207014/101454788-7a894600-396c-11eb-8585-846810a09de3.png)

首先，我不知道我这种修改是否有问题，至少从训练结果上来看，效果是变好了
简单的二分类问题，显示的识别准确率达到了100%， 这是断点续训的log
![image](https://user-images.githubusercontent.com/65207014/101454298-b4a61800-396b-11eb-9fdb-ce990fd41a9e.png)

但是当我导出模型，对其进行预测，**预测的数据集我才用的是训练的数据集**，理论上模型应该能够完美识别的，但是现实却出现了很多的识别错误

后来经过对比，发现，在C++部署的过程中，需要用到一个config.txt文件，其内容如下
![image](https://user-images.githubusercontent.com/65207014/101454878-98ef4180-396c-11eb-8a11-304968307737.png)

这个里面**resize_short_size 256**和我训练的时候**resize_size 224**是不一样的，所以我就想应该是这个原因导致的
我尝试修改**resize_short_size 256**为**resize_size 224**，在载入模型的过程中直接报错了

我的训练过程中使用的使Resize_size，不是resize_short_size，因为我并不想让图像受到任何的裁切
我个人的理解，原来的操作是，比如500X800的图像，先使用resize-short-size缩放为256X(800X244除500)，然后random-crop为224X224的图像送入训练，我不想如此，我想只是将图像进行缩放成224X224，不进行任何裁切，但是我直接屏蔽crop-image的时候，又会提示我送入训练的shape不对

请问如何将**resize_short_size 256**修改为**resize_size 224**？

**Comment by littletomatodonkey** [comment]
直接把256改为224应该就可以的，前面的字段不能改动哈

**Comment by zhouyuxixixi** [comment]
> 直接把256改为224应该就可以的，前面的字段不能改动哈

resize_short_size是将图像缩放，比如原来是500*800，这个会缩放成224*800
resize_size也是将图像缩放，比如原来是500*800，这个会缩放成224*224

**Comment by zhouyuxixixi** [comment]
后续还发现，当我手动将原图压缩成224X224，然后送进去预测，此时完全可以保证了图像未收到任何的裁切，但是仍然出现了很多的预测错误

**Comment by zhouyuxixixi** [comment]
又发现，二分类问题，log日志显示的TOP1=100%，代表的是召回率，就是0类被完美识别了，但是1类也被全部识别为了0类，此时TOP1是等于100%的，但是，这明显是有问题的，是不被接受的。我再看看是因为啥

**Comment by littletomatodonkey** [comment]
> 500X800

resize short为256指的是将图片长宽比保持不变，缩放到短边256（长边不定），然后再做center crop，裁剪出中心区域的224x224

**Comment by littletomatodonkey** [comment]
> 又发现，二分类问题，log日志显示的TOP1=100%，代表的是召回率，就是0类被完美识别了，但是1类也被全部识别为了0类，此时TOP1是等于100%的，但是，这明显是有问题的，是不被接受的。我再看看是因为啥

top1打印出来得是class id和置信度，不会打印出评估指标的
