### ISSUE TITLE
怎么在配置文件当中,配置最后一层, 不用softmax 而是用sigmoid, 多个类别 类间独立的

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/PaddleClas#463]
怎么在配置文件当中,配置最后一层, 不用softmax 而是用sigmoid, 多个类别 类间独立的

**Comment by habout632** [comment]
yaml文件

**Comment by littletomatodonkey** [comment]
目前还不支持哈，您可以在这里参考CELoss，添加自己的一个loss类，然后调用它：
https://github.com/PaddlePaddle/PaddleClas/blob/79a3dbc3e08b026a61eb3c324d6a7c942bc66323/ppcls/modeling/loss.py#L73

**Comment by zrl4836** [comment]
> 怎么在配置文件当中,配置最后一层, 不用softmax 而是用sigmoid, 多个类别 类间独立的
你好，你是想进行多标签分类吗？有没改成功
