### ISSUE TITLE
请问如何在pytorch上加载预训练模型？

### ISSUE THREAD

**Issue by Yvonne0413** [PaddlePaddle/PaddleClas#466]
您好，首先感谢您优秀的工作！
我下载了您的HRNet ssld 的model，想将它load进我的pytorch构建的网络里作为backbone 的pretrained model，想知道是否有方法可以正确load这个模型的参数呢？
因为下载后是tar文件，我是否需要解压，或者在load的代码里增加哪些预处理，才能正确load呢？我目前torch.load() tar文件的话会报错，而且我使用先open gzip open 后再pickle.load也会报错，错误是这样的：

`  File "/miniconda/envs/py37/lib/python3.7/site-packages/torch/serialization.py"
, line 564, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x1f'.
`
如果是我哪里load 模型出了问题，还请指教！谢谢！

**Comment by littletomatodonkey** [comment]
你好，这块需要先将其转化为torch的模型才可以，可能需要参考下x2paddle等工具，这块我们也没尝试过~
