### ISSUE TITLE
关于ResNet_ACNet模型deploy时的权重转换

### ISSUE THREAD

**Issue by backtime92** [PaddlePaddle/PaddleClas#467]
请问一下，可以提供一下ResNet_ACNet权重参数合并的转换code吗？

**Comment by littletomatodonkey** [comment]
你好，可以参考这个脚本哈

https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/utils/acnet/convert_model.sh

**Comment by backtime92** [comment]
@littletomatodonkey 好的，非常感谢
