### ISSUE TITLE
export_model导出的模型用inter/predit推理精度下降严重

### ISSUE THREAD

**Issue by DavidLeeDVD** [PaddlePaddle/PaddleClas#471]
自己训练的模型，用eval.yaml准确率在92%
使用python tools/export_model.py --model=ResNet50_vd --pretrained_model=output/ResNet50_vd/best_model/ppcls --output_path=inference/ResNet50_vd --class_dim=2，生成ResNet50_vd.pdiparams、ResNet50_vd.pdiparams.info、ResNet50_vd.pdmodel3个文件
然后使用python ./tools/infer/predict.py -i=./dataset/battery/binary_1/123(7)19_1.jpg --model_file=./inference/ResNet50_vd.pdmodel --params_file=./inference/ResNet50_vd.pdiparams --use_gpu=1 批量测试整体准确率只有72%，请问是什么问题？

**Comment by littletomatodonkey** [comment]
1. 可以先测试下单张图片infer.py和predict.py结果是否相同（top1-score和class id）
2. 根据你下面的命令，应该只是测了单张图片，批量测试应该设置为文件夹

**Comment by DavidLeeDVD** [comment]
> 1. 可以先测试下单张图片infer.py和predict.py结果是否相同（top1-score和class id）
> 2. 根据你下面的命令，应该只是测了单张图片，批量测试应该设置为文件夹

运行./tools/infer/infer.py -i=./dataset/battery/binary_1/ --model_file=./inference/ResNet50_vd.pdmodel --params_file=./inferen
ce/ResNet50_vd.pdiparams --use_gpu=1 --model=ResNet50_vd
执行报错：Traceback (most recent call last):
  File "./tools/infer/infer.py", line 102, in <module>
    main()
  File "./tools/infer/infer.py", line 69, in main
    load_dygraph_pretrain(net, args.pretrained_model, args.load_static_weights)
  File "C:\Users\Administrator\Desktop\PaddleClas-dygraph\ppcls\utils\save_load.py", line 50, in load_dygraph_pretrain
    if not (os.path.isdir(path) or os.path.exists(path + '.pdparams')):
TypeError: _isdir: path should be string, bytes or os.PathLike, not NoneType
因为这边export_model.py生成的模型后缀是.pdiparams、.pdiparams.info、.pdmodel

**Comment by littletomatodonkey** [comment]
你要是用导出模型的话，需要使用predict.py，使用pretrain model的话，需要使用ninfer.py，可以参考开始使用教程

https://github.com/PaddlePaddle/PaddleClas/blob/dygraph/docs/zh_CN/tutorials/getting_started.md
