### ISSUE TITLE
HS block在stride=2的时候要如何实现？

### ISSUE THREAD

**Issue by LaserLV52** [PaddlePaddle/PaddleClas#472]
你好，

resnet原始的Bottleneck模块中的3*3卷积是有一个可以自定义步长参数stride的，可以实现下采样的功能。且resnet原网络中，layer2-4的stride都为2。

而你们的HSblock如果也用到stride=2的情况时，在拼接特征图的时候就会出现分辨率不匹配的情况。

比如HS block的输入是10,100,64,64的特征图，经过第一个split，输入被分成5个10,20,64,64的特征图，其中第一个直接送到HS block的输出。从第二个开始会经过一个（卷积+bn+relu）的组合，因为stride=2，经过卷积后会变成10,20,32,32的特征图，再把这个特征图一分为二变成2个10,10,32,32，其中一个送到HS block的输出，另一个跟第三组10,20,64,64的特征图拼接。

这个时候HS block输出的第一组是64,64的的分辨率，而第二组是32,32的分辨率，无法拼接。并且第三组10,20,64,64的特征图要和第二组10,10,32,32的特征图拼接也无法拼接。

请问相关模块是如何实现下采样的呢？如果相关模块无法实现下采样，那么在你们的网络中下采样是在哪一步完成的呢？谢谢。

**Comment by cuicheng01** [comment]
Hi~你好，下采样的时候我们没有使用级联的split和add的方式组合，而是用到了stride为2的pool层和stride为2的conv层，对其结果进行了拼接，具体可以参考下面这张图：
<img width="662" alt="HS-ResNet" src="https://user-images.githubusercontent.com/45199522/102059974-912c1300-3e2c-11eb-8aed-3b46b8bc9aea.png">

**Comment by cuicheng01** [comment]
Hi~你好，下采样的时候我们没有使用级联的add方式，而是用到了stride为2的pool层和stride为2的conv层，对其结果进行了拼接，具体可以参考下面这张图：
<img width="656" alt="HS-ResNet-stride-2" src="https://user-images.githubusercontent.com/45199522/102060890-b79e7e00-3e2d-11eb-9505-1ba300fa922c.png">

**Comment by LaserLV52** [comment]
> Hi~你好，下采样的时候我们没有使用级联的add方式，而是用到了stride为2的pool层和stride为2的conv层，对其结果进行了拼接，具体可以参考下面这张图：
> <img alt="HS-ResNet-stride-2" width="656" src="https://user-images.githubusercontent.com/45199522/102060890-b79e7e00-3e2d-11eb-9505-1ba300fa922c.png">

谢谢。那如果同一个网络里面同时存在stride=1和stride=2的情况时，你们是在stride=1的时候用论文中级联的add的方式，然后stride=2的时候用上面这张图的方式。还是说只要有同时存在stride=1和stride=2的情况，网络中所有的block都是上面这张图的方式只是stride的值不一样呢？

**Comment by cuicheng01** [comment]
在stride为1的时候采用论文图中级联add的方式，stride为2的时候采用上图这种方式。

**Comment by LaserLV52** [comment]
> 在stride为1的时候采用论文图中级联add的方式，stride为2的时候采用上图这种方式。

明白了，我尝试一下！pool层你们用的是max还是avg呢

**Comment by cuicheng01** [comment]
3x3的avg pool，网络结构是用netron做的可视化

**Comment by LaserLV52** [comment]
> 3x3的avg pool，网络结构是用netron做的可视化

非常感谢！
