### ISSUE TITLE
Train paddlepaddle，报错AssertionError: can't find PADDLE_TRAINER_ENDPOINTS

### ISSUE THREAD

**Issue by yimintao** [PaddlePaddle/PaddleClas#487]
报错背景:
自制数据集，用带GPU服务器训练时报错

在train时报错:
train命令:
python tools/train.py -c ./configs/MobileNetV3/MobileNetV3_small_x1_0.yaml -o pretrained_model="./pretrained/MobileNesdftV3_small_x1_0_pretrained" -o use_gpu=True

报错信息：
![报错](https://user-images.githubusercontent.com/39506711/102321927-4c81b280-3fb9-11eb-8d50-a463c971a740.png)

请问该怎么解决呢

**Comment by yimintao** [comment]
Traceback (most recent call last):
  File "tools/train.py", line 180, in <module>
    main(args)
  File "tools/train.py", line 66, in main
    fleet.init(role)
  File "E:\Anaconda3\envs\ocr\lib\site-packages\paddle\fluid\incubate\fleet\base\fleet_base.py", line 218, in init
    self._role_maker.generate_role()
  File "E:\Anaconda3\envs\ocr\lib\site-packages\paddle\fluid\incubate\fleet\base\role_maker.py", line 539, in generate_role
    assert self._worker_endpoints is not None, "can't find PADDLE_TRAINER_ENDPOINTS"
AssertionError: can't find PADDLE_TRAINER_ENDPOINTS

**Comment by littletomatodonkey** [comment]
可以参考这篇文档，直接启动的话，需要使用`tools/train_multi_platform.py`，distributed launch启动的话，需要使用`tools/train.py`

https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/zh_CN/tutorials/getting_started.md#11-%E6%A8%A1%E5%9E%8B%E8%AE%AD%E7%BB%83

**Comment by yimintao** [comment]
> 
> 
> 可以参考这篇文档，直接启动的话，需要使用`tools/train_multi_platform.py`，distributed launch启动的话，需要使用`tools/train.py`
> 
> https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/zh_CN/tutorials/getting_started.md#11-%E6%A8%A1%E5%9E%8B%E8%AE%AD%E7%BB%83

已解决，谢谢
