### ISSUE TITLE
ResNet50_vd_10w_pretrained 模型解压模型文件异常

### ISSUE THREAD

**Issue by stopit** [PaddlePaddle/PaddleClas#499]
参考：PaddleClas/docs/zh_CN/application/transfer_learning.md  中的描述，下载ResNet50_vd_10w_pretrained.tar模型，该模型解压后只有一个文件：ResNet50_vd_10w_pretrained，并非常用的模型结构。并且使用export导出模型命令报错。感觉这个模型文件是否存在异常。

**Comment by littletomatodonkey** [comment]
解压之后应该是一个文件夹，里面有很多参数文件，这个没有fc的参数，所以只能用来finetune，没法用来导出

**Comment by TingquanGao** [comment]
> 参考：PaddleClas/docs/zh_CN/application/transfer_learning.md 中的描述，下载ResNet50_vd_10w_pretrained.tar模型，该模型解压后只有一个文件：ResNet50_vd_10w_pretrained，并非常用的模型结构。并且使用export导出模型命令报错。感觉这个模型文件是否存在异常。

是用Windows的解压软件解压的吗？

**Comment by stopit** [comment]
> > 参考：PaddleClas/docs/zh_CN/application/transfer_learning.md 中的描述，下载ResNet50_vd_10w_pretrained.tar模型，该模型解压后只有一个文件：ResNet50_vd_10w_pretrained，并非常用的模型结构。并且使用export导出模型命令报错。感觉这个模型文件是否存在异常。
> 
> 是用Windows的解压软件解压的吗？

是的  使用winrar工具解压的

**Comment by TingquanGao** [comment]
第三方解压软件确实存在类似问题，建议使用Linux命令解压，`tar -xvf`
