### ISSUE TITLE
HSresnet

### ISSUE THREAD

**Issue by wangsun1996** [PaddlePaddle/PaddleClas#501]
Hello，in your paper, you propose that: Unlike Res2Net[9], we avoid producing the abundant and even redundant information contained in the feature maps and the network can learn richer feature representation.请问这个如何理解呢？从哪个角度说明新的HS网络能够避免提取冗余信息呢？感谢

**Comment by cuicheng01** [comment]
Hi，您好，在HS-block中，有很多split操作（层级的split），部分通道split后不做任何需要参数和计算的操作，这样就避免了产生冗余的信息，而HS-block较Res2Net中的block更为复杂，这样更多的参数就学习了图像更多非冗余的特征。
