### ISSUE TITLE
GhostNet_x1_0.yaml加载预训练模型训练，报错

### ISSUE THREAD

**Issue by yy11223** [PaddlePaddle/PaddleClas#504]
配置文件：!export CUDA_VISIBLE_DEVICES=0
!cd work/PaddleClass && python -m paddle.distributed.launch \
--selected_gpus="0" tools/train.py \
-c ./configs/GhostNet/GhostNet_x1_0.yaml
报错：Architecture [GhostNet_x1_0] is not exist! Maybe you want: [ShuffleNetV2_x1_0, MobileNetV1_x0_5, MobileNetV1_x1_0, MobileNetV2_x1_0, MobileNetV1_x0_25, MobileNetV1_x0_75, ShuffleNetV2_x0_5, ShuffleNetV2_x1_5, ShuffleNetV2_x2_0, SE_HRNet_W18_C]

**Comment by littletomatodonkey** [comment]
你好，可以试着拉下最新代码，同时看下`ppcls/modeling/architectures/__init__.py`这个文件里是否有对应的GhostNet_x1_0引用

https://github.com/PaddlePaddle/PaddleClas/blob/d4e7878d53ad5c61bfa87827ad9a7a2cb7a4fae8/ppcls/modeling/architectures/__init__.py#L31

**Comment by yy11223** [comment]
> 你好，可以试着拉下最新代码，同时看下`ppcls/modeling/architectures/__init__.py`这个文件里是否有对应的GhostNet_x1_0引用
> 
> https://github.com/PaddlePaddle/PaddleClas/blob/d4e7878d53ad5c61bfa87827ad9a7a2cb7a4fae8/ppcls/modeling/architectures/__init__.py#L31

用了最新的代码，运行又出现这个问题：
 File "tools/train.py", line 30, in <module>
    from ppcls.data import Reader
  File "/home/aistudio/external-libraries/ppcls/__init__.py", line 15, in <module>
    from . import optimizer
  File "/home/aistudio/external-libraries/ppcls/optimizer/__init__.py", line 15, in <module>
    from . import optimizer
  File "/home/aistudio/external-libraries/ppcls/optimizer/optimizer.py", line 22, in <module>
    import paddle.regularizer as regularizer
ModuleNotFoundError: No module named 'paddle.regularizer'
2020-12-21 22:07:41,880-ERROR: ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
ERROR 2020-12-21 22:07:41,880 launch.py:284] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.

**Comment by cuicheng01** [comment]
Hi，可以说一下您的paddlepaddle版本号以及您拉取的branch吗？

**Comment by yy11223** [comment]
> 拉取的branch
PaddleClas-release-2.0-rc1
fc84d99

**Comment by littletomatodonkey** [comment]
你好，需要安装paddlepaddle的2.0rc1版本
