### ISSUE TITLE
非动物的分类是如何实现的？

### ISSUE THREAD

**Issue by fish-hello** [PaddlePaddle/PaddleClas#510]
使用教程里的ResNet50_vd_ssld_random_erasing_finetune.yaml做训练，使用自定义数据集，在预测时，发现类似的图，识别度高，但不相干的图误识别很严重，而且分值都很高，不清楚原因，并想了解学习一下百度识别里的非动物是如何实现的。

**Comment by littletomatodonkey** [comment]
方便说下训练集和测试集是什么呢？你是不是没有设置背景类别的图片呢？

**Comment by fish-hello** [comment]
> 方便说下训练集和测试集是什么呢？你是不是没有设置背景类别的图片呢？

自己整理的数据集，背景类别怎么设置？能具体说下吗？

**Comment by littletomatodonkey** [comment]
你好，可以参考这里的FAQ：

https://github.com/PaddlePaddle/PaddleClas/blob/dygraph/docs/zh_CN/faq_series/faq_2020_s1.md#q65-%E6%9E%84%E5%BB%BA%E5%88%86%E7%B1%BB%E6%95%B0%E6%8D%AE%E9%9B%86%E6%97%B6%E5%A6%82%E4%BD%95%E6%9E%84%E5%BB%BA%E8%83%8C%E6%99%AF%E7%B1%BB%E5%88%AB%E7%9A%84%E6%95%B0%E6%8D%AE

![image](https://user-images.githubusercontent.com/14270174/103971919-c5ce8880-51a6-11eb-8ab2-07544de0a1f5.png)

**Comment by fish-hello** [comment]
感谢
