### ISSUE TITLE
你好，想问下，用MobileNetV3-large预训练模型做分类，MobileNetV3没有softmax层，网络是怎么样进行分类的呢？

### ISSUE THREAD

**Issue by yy11223** [PaddlePaddle/PaddleClas#511]

**Comment by littletomatodonkey** [comment]
你好，计算loss的时候，cross entropy中包含了softmax

https://github.com/PaddlePaddle/PaddleClas/blob/aa655564331e7e61e5b9347105562b2e291acd1f/ppcls/modeling/loss.py#L51

**Comment by yy11223** [comment]
谢谢
