### ISSUE TITLE
10w分类的labels对照表在哪里可以查到？

### ISSUE THREAD

**Issue by xxyliuyang** [PaddlePaddle/PaddleClas#516]
ResNet50_vd, 百度开源了自研的大规模分类预训练模型，其中训练数据为10万个类别，4300万张图片。

- 这个模型只提供了下载链接，在模型预测的只会给出预测的label索引（例如：6），以及对应的概率分数，我想知道lable的对应表在哪里可以查到。（例如，6代表苹果）。

**Comment by littletomatodonkey** [comment]
你好，10W个类别的模型我们只开源了不包含FC层的10W类预训练模型哈，只能用来finetune，无法用来直接预测

**Comment by xxyliuyang** [comment]
那你们开源训练数据吗？

**Comment by littletomatodonkey** [comment]
训练数据没有开源哈，提供的预训练是希望大家在自己的任务或者数据集里收敛得更好
