### ISSUE TITLE
关于训练好的PaddleClas模型转换nb模型时遇到的问题

### ISSUE THREAD

**Issue by ChaunceySun7** [PaddlePaddle/PaddleClas#519]
首先，我按照教程将训好的模型文件导出，得到pdmodel、pdiparams、以及pdiparams.info三个文件，之后将这三个文件转nb文件时的指令时这样的：
paddle_lite_opt --model_file=/home/HwHiAiUser/Paddle-Lite/models/light_clas/air_light.pdmodel --param_file=/home/HwHiAiUser/Paddle-Lite/models/air_light/air_light.pdiparams --optimize_out=./models/light_clas --optimize_out_type=naive_buffer --valid_targets=arm
结果报错是读取不了参数文件，之前转过PaddleDetection的nb模型没有遇到这种情况
![微信图片_20201228143619](https://user-images.githubusercontent.com/55674601/103194331-41fcdc80-491a-11eb-967f-33aaec05b6a4.png)

请问是哪里的问题，PaddleClas和PaddleDetection导出的模型文件格式也不一样，是这个原因吗

**Comment by littletomatodonkey** [comment]
看着是路径不对，`optimize_out `中的`models`这个目录是存在的吗？

**Comment by ChaunceySun7** [comment]
[](url)

> 看着是路径不对，`optimize_out `中的`models`这个目录是存在的吗？

路径是存在的，主要是pdiparams文件读取不了，因为之前paddledetection的参数文件是__params__没有遇到问题，但是换成pdiparams文件就读取不了了

**Comment by littletomatodonkey** [comment]
可以上传一份inference model吗？我们复现下，pdiparams和__params__只是名字不一样

**Comment by ChaunceySun7** [comment]
> 可以上传一份inference model吗？我们复现下，pdiparams和__params__只是名字不一样



[export.zip](https://github.com/PaddlePaddle/PaddleClas/files/5746186/export.zip)
谢谢，是不是可能是我导出模型那一步出错了？

**Comment by TingquanGao** [comment]
使用以下命令未能复现问题：

```paddle_lite_opt --model_file ./export/air_light.pdmodel --param_file ./export/air_light.pdiparams --optimize_out ./export/air_light --optimize_out_type=naive_buffer --valid_targets=arm```

**Comment by ChaunceySun7** [comment]
> 可以上传一份inference model吗？我们复现下，pdiparams和__params__只是名字不一样

谢谢，问题已解决，还有一个问题是我在paddlelite环境下调用nb模型时，ouput是一个1000维的list，请问这个list是softmax后得到的结果吗，还有就是我训练的是一个4分类模型，输出是一个1000维list这正常吗？

**Comment by TingquanGao** [comment]
看了一下你提供的模型的网络结构，是经过softmax后的结果：

<img width="1136" alt="截屏2020-12-29 下午2 42 09" src="https://user-images.githubusercontent.com/12560511/103264316-4e01a080-49e5-11eb-8375-155927678fb5.png">


训练4分类模型的话，需要改一下配置文件，然后开始训练，或者基于预训练模型finetuning，可以参考[quick_start](https://github.com/PaddlePaddle/PaddleClas/blob/dygraph/docs/zh_CN/tutorials/quick_start.md)

**Comment by Liys0558** [comment]
我也出现了， opt 转换问题， 我按照教程将训好的模型文件导出，得到pdmodel、pdiparams、以及pdiparams.info三个文件，之后将这三个文件转nb文件出现下面问题：
命令：./opt --model_file=inference/mv3.pdmodel --param_file= inference/mv3.pdiparams  --valid_targets=arm --optimize_out_type=naive_buffer --optimize_out=inference/mv3
错误：[F  3/29  9:40:34.810 ...Paddle-Lite/lite/model_parser/base/io.cc:46 BinaryFileReader] Check failed: file_: Unable to open file: /__model__

**Comment by Liys0558** [comment]
我遇到楼主同样的问题paddle_lite_opt: error: unrecognized arguments: inference/mv3.pdiparams，请问是怎么解决的？
