### ISSUE TITLE
快速开始的示例参数有误。

### ISSUE THREAD

**Issue by AlexDish** [PaddlePaddle/PaddleClas#532]
如以下地址，PaddleClas/docs/zh_CN/tutorials/getting_started.md，我参考《3. 使用预训练模型进行模型预测》和《4. 使用inference模型模型推理》时发现，数据集是使用flowers102，一直不能预测出正确的结果，而且出现了几百的类id，如下。
        top1, class id: 223, probability: 0.0025
        top2, class id: 921, probability: 0.0023
        top3, class id: 498, probability: 0.0022
        top4, class id: 286, probability: 0.0021
        top5, class id: 565, probability: 0.0021
阅读代码发现默认的输出层是1000！
所以《3. 使用预训练模型进行模型预测》里的原执行
`python tools\infer\infer.py -i .\dataset\flowers102\jpg\image_00001.jpg --model ResNet50_vd --pretrained_model .\output\ResNet50_vd\best_model\ppcls --use_gpu True --load_static_weights False`
改为↓↓↓↓↓↓↓↓↓，加多class_num选项。
`python tools\infer\infer.py -i .\dataset\flowers102\jpg\image_00001.jpg --model ResNet50_vd --pretrained_model .\output\ResNet50_vd\best_model\ppcls --use_gpu True --load_static_weights False --class_num 102`
所以《4. 使用inference模型模型推理》里的生成模型原执行
`python tools\export_model.py --model ResNet50_vd --pretrained_model .\output\ResNet50_vd\best_model\ppcls --output_path .\inference`
改为↓↓↓↓↓↓↓↓↓，加多class_dim选项。
`python tools\export_model.py --model ResNet50_vd --pretrained_model .\output\ResNet50_vd\best_model\ppcls --output_path .\inference --class_dim 102 `

劳烦确认一下是否正确。

**Comment by littletomatodonkey** [comment]
你好，感谢反馈，这块是因为class dim默认值为1000，如果类别数不对，的确是需要手动指定class dim的参数的哈

https://github.com/PaddlePaddle/PaddleClas/blob/bcfe353db163bb17b91cba7c15f5306febce8c4b/tools/infer/utils.py#L56
