### ISSUE TITLE
Dataloader总是报进程错误，我用的是快速开始的案例

### ISSUE THREAD

**Issue by lliony** [PaddlePaddle/PaddleClas#537]
ERROR: DataLoader reader thread raised an exception! Traceback (most recent call last):   File "tools/train.py", line 118, in <module>     main(args)   File "tools/train.py", line 90, in main     epoch_id, 'train')   File "/home/aistudio/PaddleClas/tools/program.py", line 300, in run     for idx, batch in enumerate(dataloader()):   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 771, in __next__ Exception in thread Thread-1: Traceback (most recent call last):   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 676, in _get_data     data = self._data_queue.get(timeout=self._timeout)   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 105, in get     raise Empty _queue.Empty  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner     self.run()   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run     self._target(*self._args, **self._kwargs)   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 608, in _thread_loop     batch = self._get_data()   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 692, in _get_data     "pids: {}".format(len(failed_workers), pids)) RuntimeError: DataLoader 4 workers exit unexpectedly, pids: 9264, 9265, 9266, 9267      data = self._reader.read_next_var_list() SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.   [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:154)   [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]

**Comment by wangjiawei04** [comment]
同求 一样的错误
```
Traceback (most recent call last):
  File "tools/train.py", line 118, in <module>
    main(args)
  File "tools/train.py", line 90, in main
    epoch_id, 'train')
  File "/paddleclas/tools/program.py", line 300, in run
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 676, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/usr/local/python3.5.1/lib/python3.5/multiprocessing/queues.py", line 105, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3.5.1/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/python3.5.1/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 608, in _thread_loop
    batch = self._get_data()
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 692, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 3 workers exit unexpectedly, pids: 8653, 8654, 8656

    for idx, batch in enumerate(dataloader()):
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 771, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:154)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
```

**Comment by littletomatodonkey** [comment]
1. 需要看下数据路径是否有问题
2. 如果没问题的话，可以看下/dev/shm的大小，如果只有64M的话，需要把dataloader的num worker设置为0（Dataloader需要较大的共享内存）

**Comment by linhandev** [comment]
建议像paddleseg一样出一个单进程的io，mpio会压下各种报错，跑起来快但是感觉debug很不方便

**Comment by littletomatodonkey** [comment]
你好，单卡的时候，把num_worker设置为0，就是单进程哈

**Comment by linhandev** [comment]
是这样，高级！

**Comment by littletomatodonkey** [comment]
你好，没什么其他问题的话，我们就先关闭卡片了哈，后续有什么问题欢迎提ISSUE，感谢你的关注~
