### ISSUE TITLE
resnet50基于10万数据的预训练模型无法加载

### ISSUE THREAD

**Issue by githubWXB** [PaddlePaddle/PaddleClas#553]
paddlepaddle：2.0版本
使用paddle_clas无法加载resnet50基于10万数据的预训练模型，提示ResNet50_vd_10w_pretrained.pdparams不存在，因为这个预训练模型确实不是pdparams文件，请问应该如何解决呢？

**Comment by littletomatodonkey** [comment]
这个是静态图模型，在加载的时候，需要指定`-o load_static_weights=True`哈，表示加载的静态图的预训练模型

**Comment by bityigoss** [comment]
@littletomatodonkey 执行quick_start_professional中cifar100，使用ResNet50_vd_10w_pretrained加载，加了-o load_static_weights=True也是提示ResNet50_vd_10w_pretrained.pdparams不存在，同时也加了-o Global.checkpoints=xxx/ResNet50_vd_10w_pretrained，请问还需要如何修改？
