### ISSUE TITLE
关于训练数据的不同尺寸差异较大的问题

### ISSUE THREAD

**Issue by ChaunceySun7** [PaddlePaddle/PaddleClas#557]
你好，我在用MobileNetV3_large_x1_0模型训练自己的分类模型时，发现识别的准确率并不理想，猜想可能我使用的训练数据的尺寸差异较大是其中一个原因，有的小的不到100 * 100，大的会到1000 * 1000多，请问这种情况对于分类效果会有影响吗？
如果有影响的话，是否需要我对该网络结构进行修改？或者是否支持多尺度训练？

**Comment by littletomatodonkey** [comment]
你好，
1. 目前还不支持多尺度训练，训练的时候会做resize，前景所占原图比例差异太大的话，尺度确实会有一定影响
2. 如果机器允许的话，可以尝试一下hrnet、se-resnext这些结构，或者试着在你的网络里面加上一些attention结构

**Comment by littletomatodonkey** [comment]
clas里面也总结了一些训练预测方面的faq，可以参考一下

https://github.com/PaddlePaddle/PaddleClas/blob/dygraph/docs/zh_CN/faq_series.md

**Comment by ChaunceySun7** [comment]
> 你好，
> 
> 1. 目前还不支持多尺度训练，训练的时候会做resize，前景所占原图比例差异太大的话，尺度确实会有一定影响
> 2. 如果机器允许的话，可以尝试一下hrnet、se-resnext这些结构，或者试着在你的网络里面加上一些attention结构

谢谢建议，请问hrnet、se-resnet结构是否支持端侧部署？

**Comment by littletomatodonkey** [comment]
hrnet静态图是支持的，动态图目前有一个op还不支持，预计下个月就会支持
