### ISSUE TITLE
您好，请问训练模型时，怎样在transforms中禁掉RandCropImage、RandFlipImage操作，需要怎样修改配置文件？

### ISSUE THREAD

**Issue by yanqing013** [PaddlePaddle/PaddleClas#563]

**Comment by CZH-TOP** [comment]
您好！请您在config文件中对应的地方注释掉即可。值得注意的是，要尽可能保证transforms之后的image_size符合规范。

**Comment by yanqing013** [comment]
好的，谢谢，我本来担心在config中注释掉RandCropImage、RandFlipImage后，训练时，代码会自动为这两个操作分配默认参数执行呢

**Comment by littletomatodonkey** [comment]
不会的，会根据config中的配置去创建对应的预处理操作的

**Comment by wa3926** [comment]
@yanqing013  请问你你删掉 随机剪裁和翻转 参数 训练不报错吗
