### ISSUE TITLE
知识蒸馏过程中遇到的问题

### ISSUE THREAD

**Issue by githubWXB** [PaddlePaddle/PaddleClas#574]
问题一：
教师模型：使用基于10w类的resnet50_vd预训练模型在目标数据集上微调后作为教师模型
学生模型：使用基于1000类的mobilenetV2预训练模型作为学生模型
上述模型添加后运行报错，原因是名字冲突，问题如下：
1. 在知识蒸馏文档的“3.4.2 模型名字冲突问题的解决办法”中介绍了两个模型变量冲突时的解决办法，但我在蒸馏模型的定义文件“ppcls/modeling/architectures/distillation_models.py”中按照3.4.2文档内容做修改，但运行报错，提示没有postfix_name这个变量，看了学生网络的init函数，确实没有这个参数，而且distillation_models.py中网络的定义方式与3.4.2中给出的不同，请问这个是我改错了位置还是新版做了修改？

问题二：
教师模型：使用基于10w类的resnet50_vd预训练模型在目标数据集上微调后作为教师模型
学生模型：使用基于1000类的mobilenetV3预训练模型作为学生模型
使用这个组合没有出现变量名冲突的问题，且成功训练出模型，但通过predict.py测试时给出了警告“UserWarning:Skip loading for last_second_conv.bn._mean. last_second_con.bn._mean is not found in the provided dict.”，之后得到的测试准确率（用验证集数据测的）只有10%左右，且6个类别基本都识别成了第4和第5类，与训练时验证集的准确率80%严重不一致，怀疑是警告中的问题导致，请问这个应该如何解决？

**Comment by littletomatodonkey** [comment]
麻烦提供一下你导出模型的命令、具体的预测命令以及报错信息吧

**Comment by githubWXB** [comment]
问题2我用flowers数据集测试了一下，结果也是一样的错误（之前以为是predict.py报错，后来发现是导出模型报的错）；
导出模型命令：
python3 export_model.py 
    --model MobileNetV3_large_x1_0 
    --pretrined_model  /paddle/PaddleClas/output/flowers/ResNet50_vd_distill_MobileNetV3_large_x1_0/best_model/ppcls 
    --output_path 
 /paddle/PaddleClas/output/flowers/ResNet50_vd_distill_MobileNetV3_large_x1_0/inference_model/ResNet50_vd_distill_MobileNetV3_large_x1_0_finetune 
    --class_dim 102
导出模型错误信息：
    warnings.warn(("Skip loading for {}".format(key) + str(err)))
/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/dygraph/layers.py:1246: UserWarning:Skip loading for conv1.conv.weight. conv1.conv.weight is not found in the provided dict.
    warnings.warn(("Skip loading for {}".format(key) + str(err)))
/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/dygraph/layers.py:1246: UserWarning:Skip loading for conv1.bn.weight. conv1.bn.weight is not found in the provided dict.
    warnings.warn(("Skip loading for {}".format(key) + str(err)))
/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/dygraph/layers.py:1246: UserWarning:Skip loading for conv1.bn.bias. conv1.bn.bias is not found in the provided dict.
    warnings.warn(("Skip loading for {}".format(key) + str(err)))
/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/dygraph/layers.py:1246: UserWarning:Skip loading for conv1.bn._mean. conv1.bn._mean is not found in the provided dict.
    warnings.warn(("Skip loading for {}".format(key) + str(err)))
/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/dygraph/layers.py:1246: UserWarning:Skip loading for conv1.bn._variance. conv1.bn._variance is not found in the provided dict.
    warnings.warn(("Skip loading for {}".format(key) + str(err)))
/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/dygraph/layers.py:1246: UserWarning:Skip loading for conv2.expand_conv.conv.weight. conv2.expand_conv.conv.weight is not found in the provided dict.
.............
    warnings.warn(("Skip loading for {}".format(key) + str(err)))
/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/dygraph/layers.py:1246: UserWarning:Skip loading for out.weight. out.weight is not found in the provided dict.
    warnings.warn(("Skip loading for {}".format(key) + str(err)))
/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/dygraph/layers.py:1246: UserWarning:Skip loading for out.bias. out.bias is not found in the provided dict.
预测命令：
python3 tools/infer/predict.py 
    -i /paddle/PaddleClas/dataset/flowers102/test.txt 
    --model_file /paddle/PaddleClas/output/flowers/ResNet50_vd_distill_MobileNetV3_large_x1_0/inference_model/ResNet50_vd_distill_MobileNetV3_large_x1_0_finetune.pdmodel
    --params_file /paddle/PaddleClas/output/flowers/ResNet50_vd_distill_MobileNetV3_large_x1_0/inference_model/ResNet50_vd_distill_MobileNetV3_large_x1_0_finetune.pdiparams
    --use_gpu True
    --use_tensorrt False

**Comment by littletomatodonkey** [comment]
你好，感谢反馈，之前蒸馏得时候，是同时保存了学生和教师模型，导出得时候不太方便，这个PR添加了同时保存学生模型得功能，方便导出： 

https://github.com/PaddlePaddle/PaddleClas/pull/578

**Comment by githubWXB** [comment]
> 你好，感谢反馈，之前蒸馏得时候，是同时保存了学生和教师模型，导出得时候不太方便，这个PR添加了同时保存学生模型得功能，方便导出：
> 
> #578
好的，问题2已解决，非常感谢！

另外就是关于问题1，用Resnet50_vd蒸馏mobileNetV2出现变量名冲突的问题，报错为“ValueError：parameter name [conv1_1_weights] have be been used. In dygraph mode, the name of parameter can't be same.  Please check the parameter attr value passed to self.create_parameter or constructor of dygraph Layers”；
于是我用知识蒸馏文档的“3.4.2 模型名字冲突问题的解决办法”中介绍的方法，在ppcls/modeling/architectures/distillation_models.py文件中做了如下修改：
class ResNet50_vd_distill_MobileNetV2(nn.Layer):
    def __init__(self, class_dim=1000, **args):
        super(ResNet50_vd_distill_MobileNetV2, self).__init__()

        self.teacher = ResNet50_vd(class_dim=class_dim, **args)
        self.student = MobileNetV2(postfix_name="_student", class_dim=class_dim, **args)
    def forward(self, x):
        teacher_label = self.teacher(x)
        teacher_label.stop_gradient = True
        student_label = self.student(x)
        return teacher_label, student_label
修改后执行报错：“TypeError：__init__() got an unexpected keyword argument 'postfix_name'”

**Comment by littletomatodonkey** [comment]
是的，当时以r50vd和mv3为例做的蒸馏，r50vd和mv2确实会有名字冲突的问题，这块我添加一个postfix_name的参数吧，

**Comment by littletomatodonkey** [comment]
你好，已经添加了，prefix_name这个参数，下面这样即可


```
class R50_vd_distill_mv2(nn.Layer):
    def __init__(self, class_dim=1000, freeze_teacher=True, **args):
        super(R50_vd_distill_mv2, self).__init__()

        self.teacher = ResNet50_vd(class_dim=class_dim, **args)
        self.student = MobileNetV2(class_dim=class_dim, prefix_name="student_", **args)

        if freeze_teacher:
            for param in self.teacher.parameters():
                param.trainable = False

    def forward(self, x):
        teacher_label = self.teacher(x)
        student_label = self.student(x)
        return teacher_label, student_label
```

**Comment by littletomatodonkey** [comment]
关于第二个问题，导出的时候，model name只需要设置为student的model name，pretrain地址为student.pdparams即可，
