### ISSUE TITLE
灰度图使用哪个预训练模型，预测效果会更好？

### ISSUE THREAD

**Issue by fish-hello** [PaddlePaddle/PaddleClas#577]
识别黑白照里的动物，是夜晚相机拍的，都是黑白灰，也不算灰度图吧，发现使用ResNet50_vd_ssld效果不好，有什么好办法吗？下图是示例。
![image](https://user-images.githubusercontent.com/72905070/105679646-b6cb3280-5f29-11eb-86a0-18cb66f22ee0.png)

**Comment by littletomatodonkey** [comment]
像这种需要在自己的数据集上finetune，效果会更好一些，之前训练集中，对于这种全灰的图像样本相对较少

**Comment by fish-hello** [comment]
是自定义数据集的，样本比较少，不过，发现基本是对比颜色，没有形状对比，导致识别不对。简单说就是，环境的灰色与动物身上的灰色辨别不出，随便搞张灰图也识别为那个分类了。
是现在的分类技术不检测形状吗？

**Comment by littletomatodonkey** [comment]
会检测形状的，不过你这种场景的话，感觉需要用带注意力机制的模型，比如SENet或者ResNeSt等，可能效果会相对好一些
