### ISSUE TITLE
How to use PaddleClas to extract image feature

### ISSUE THREAD

**Issue by lun-lun-byte** [PaddlePaddle/PaddleClas#589]
你好，请问如何用 PaddleClas 来提取图片特征，并用于相似图像计算呢？看了很久，只发现 predictor，好像并没有看见文档怎么样提取中间层的特征，请问这个要怎么做呢？Thanks

**Comment by littletomatodonkey** [comment]
你好，网络是在这里引出来最后的输出的，如果需要拿到其他的feature的话，把这里的其他特征输出即可

https://github.com/PaddlePaddle/PaddleClas/blob/114b1e3b3b77c346009da8628cca4e225227fbfd/ppcls/modeling/architectures/resnet.py#L286

**Comment by lun-lun-byte** [comment]
谢谢，如果我要在这个 predict.py 基础上修改，如何做呢？

https://github.com/PaddlePaddle/PaddleClas/blob/114b1e3b3b77c346009da8628cca4e225227fbfd/tools/infer/predict.py#L57

就是怎么样得到更多的 output_tensor？

**Comment by littletomatodonkey** [comment]
在export model的时候，需要把中间层的feature map返回，这里默认是输出的fc之后的

https://github.com/PaddlePaddle/PaddleClas/blob/378ed96095169e58d3b2c08d9046fd3ac0257169/tools/export_model.py#L51

**Comment by lun-lun-byte** [comment]
有没有可能帮忙写一个稍微完整的例子呢？相信会对很多人有帮助，感谢感谢！

**Comment by littletomatodonkey** [comment]
好的，稍后我提供一个demo，最迟明天发出来哈

**Comment by wind2008hxy** [comment]
请问，目前是否有demo

**Comment by yanchaoguo** [comment]
> 好的，稍后我提供一个demo，最迟明天发出来哈

同求 【如何使用paddle获取vgg16 的池化层输出】

**Comment by yanchaoguo** [comment]
> 好的，稍后我提供一个demo，最迟明天发出来哈

@littletomatodonkey Demo呢
