### ISSUE TITLE
why not provide ssld config files?

### ISSUE THREAD

**Issue by MagicCodess** [PaddlePaddle/PaddleClas#596]

**Comment by littletomatodonkey** [comment]
Thanks for your attention.
1. The ssld models are all traind using 5M images, which are not public now, but you can see all the hyper-parameters here: https://github.com/PaddlePaddle/PaddleClas/blob/dygraph/docs/en/advanced_tutorials/distillation/distillation_en.md
2. Two files are provided here, you can directly experience the ssld methods using your own dataset: https://github.com/PaddlePaddle/PaddleClas/tree/dygraph/configs/Distillation

**Comment by zhanghang1989** [comment]
Are the 5M images publicly available?
