### ISSUE TITLE
How to deduplicate the ImageNet22k dataset and the ImageNet1k validation set?

### ISSUE THREAD

**Issue by Ema1997** [PaddlePaddle/PaddleClas#600]
Hi, I have a problem about the method to deduplicate the ImageNet22k dataset and the ImageNet1k validation set.
![image](https://user-images.githubusercontent.com/19912756/106898246-e6025080-672e-11eb-80ff-789bb2c9aeb8.png)
In your doc, you said that you achieved this goal through using the sift feature similarity matching method, and it would be very kind of you to tell me the detailed informations about this method.
I intend to generate the SIFT features of all the images in ImageNet1k validation set and compare the outputs with the SIFT features of pictures which are with the same labels in ImageNet22k dataset one by one. Is the deduplication method same with yours?

Thanks,
Ema1997

**Comment by littletomatodonkey** [comment]
Thanks for your attention, yes the method you said is the same ours~

**Comment by Ema1997** [comment]
Thanks.

**Comment by Ema1997** [comment]
Hi,
would you please tell me the threshold you use to define the similar images and dissimilar images? Also, you said that you selected 4M images from imagenet 22k, and I am wondering the technique you use to pick out the 4M images.

Thanks, 
Ema1997.
