### ISSUE TITLE
paddle.distributed.spawn 单机多卡训练报错

### ISSUE THREAD

**Issue by linan142857** [PaddlePaddle/PaddleClas#609]
![image](https://user-images.githubusercontent.com/3764907/107610666-14c37e00-6c7d-11eb-9f09-9c61e4f8fba9.png)
![image](https://user-images.githubusercontent.com/3764907/107610494-ad0d3300-6c7c-11eb-80f3-bc63c3f37e44.png)

**Comment by littletomatodonkey** [comment]
你好，这是什么代码呢？clas库目前还没添加对spawn启动的支持哈，可以使用distributed.launch
