### ISSUE TITLE
在容器当中使用 运行报如下的错误

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/PaddleClas#611]
我运行predict.py 在容器当中出错了。

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1613725844 (unix time) try "date -d @1613725844" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x8) received by PID 1 (TID 0x7f145b6ac740) from PID 8 ***]

**Comment by habout632** [comment]
直接在本上运行就可以 但是在容器当中运行就报错  这个容器 我运行paddle detection predict没有错误

**Comment by habout632** [comment]
![Screenshot from 2021-02-19 17-13-28](https://user-images.githubusercontent.com/3166070/108483933-43bd9d80-72d6-11eb-8bf7-45df620e22dd.png)

**Comment by habout632** [comment]
![Screenshot from 2021-02-19 17-17-42](https://user-images.githubusercontent.com/3166070/108484049-6354c600-72d6-11eb-83c8-f8c7877aeb99.png)

**Comment by habout632** [comment]
没有使用tensorrt

**Comment by TingquanGao** [comment]
您好，请问是用的那个容器呢？GCC版本是多少呢？

**Comment by zq-2021** [comment]
> 您好，请问是用的那个容器呢？GCC版本是多少呢？

gcc版本5.4
