### ISSUE TITLE
“30分钟玩转PaddleClas”可否做成Ai Studio项目，便于学习和模仿？

### ISSUE THREAD

**Issue by A-Pai** [PaddlePaddle/PaddleClas#612]
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.0/docs/zh_CN/tutorials/quick_start.md
“30分钟玩转PaddleClas”可否做成Ai Studio项目，便于学习和模仿？

按照要求安装和克隆后，在本地pc的CMD上运行，前边的正常，到这来报错：

![image](https://user-images.githubusercontent.com/5112397/108581886-fa6b5d80-736a-11eb-8ae9-de5ef1e064b3.png)

是在linux下运行？我的是win10

**Comment by littletomatodonkey** [comment]
你好，aistudio上面有这个项目，可以参考下：https://aistudio.baidu.com/aistudio/projectdetail/428501?channelType=0&channel=0

**Comment by A-Pai** [comment]
> 你好，aistudio上面有这个项目，可以参考下：https://aistudio.baidu.com/aistudio/projectdetail/428501?channelType=0&channel=0

这个是2.0的？

**Comment by littletomatodonkey** [comment]
不好意思，上面的是1.8的

下面这个是2.0的
教程：https://www.paddlepaddle.org.cn/tutorials/projectdetail/1499123
aistudio：https://aistudio.baidu.com/aistudio/projectdetail/1557913

**Comment by A-Pai** [comment]
> aistudio：https://aistudio.baidu.com/aistudio/projectdetail/1557913

---该项目暂未公开

**Comment by TingquanGao** [comment]
您好，可以参考一下该教程说明：https://www.paddlepaddle.org.cn/tutorials/projectdetail/1499123#anchor-7
