### ISSUE TITLE
关于模型参数量的问题

### ISSUE THREAD

**Issue by zhugailin** [PaddlePaddle/PaddleClas#620]
在paddleclas中训练得到的模型文件中包含ppcls.pdparams不就是模型参数的大小么？
为什么实际训练得到模型参数大小与官方公布的不一致啊？就比如

模型         | Top-1 Acc | Top-5 Acc | Params(M) 
ResNet18 | 0.7098      | 0.8992       | 11.69M

而我实际训练得到的ResNet18 ppcls.pdparams是64.3M

**Comment by TingquanGao** [comment]
官方公布的Params是指模型参数量，而非模型文件的存储空间大小。例如ResNet18模型的参数数量为11.69M，表示参数数量的多少，该指标主要取决于算法模型。而64.3M则是该模型文件占用存储空间的大小，单位为MB，兆字节。

**Comment by zhugailin** [comment]
> 官方公布的Params是指模型参数量，而非模型文件的存储空间大小。例如ResNet18模型的参数数量为11.69M，表示参数数量的多少，该指标主要取决于算法模型。而64.3M则是该模型文件占用存储空间的大小，单位为MB，兆字节。

感谢回复，那么我如何去计算自己修改网络后的真实参数量呢，这个怎么输出得到呢

**Comment by TingquanGao** [comment]
paddle提供了这个接口：`paddle.flops `，可以查看一下。
