### ISSUE TITLE
此处的import会造成某些场景无法正确import

### ISSUE THREAD

**Issue by mikeshi80** [PaddlePaddle/PaddleClas#629]
https://github.com/PaddlePaddle/PaddleClas/blob/955adcf7a4b618d789b97d978a05ec9cd8dc151e/paddleclas.py#L39

如果import 该包的项目已有tools目录，或者引入的其他包也有tools目录（如PaddleOCR），则这样会造成无法import包。

建议修改为

```python
from .tools.infer import utils
```

**Comment by TingquanGao** [comment]
谢谢反馈！我们会确认并修复该问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleClas"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月8日(星期一) 下午4:57
收件人:&nbsp;"PaddlePaddle/PaddleClas"<PaddleClas@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[PaddlePaddle/PaddleClas] 此处的import会造成某些场景无法正确import (#629)





 
https://github.com/PaddlePaddle/PaddleClas/blob/955adcf7a4b618d789b97d978a05ec9cd8dc151e/paddleclas.py#L39
 
如果import 该包的项目已有tools目录，或者引入的其他包也有tools目录（如PaddleOCR），则这样会造成无法import包。
 
建议修改为
 from .tools.infer import utils
