### ISSUE TITLE
直接使用pip安装的paddleclas包，无法直接用作已读取的opencv image的预测

### ISSUE THREAD

**Issue by mikeshi80** [PaddlePaddle/PaddleClas#630]
目前你们提供的paddleclas中，生成`PaddleClas`对象后，直接传入一个opencv的图像数据，即numpy数组后，是无法正确预测的。原因在于`paddleclas.py`的代码中，只有判断传入的参数为`str`后，才会进行图像的读取，BGR->RGB操作，并且进行utils.preprocess和np.expand_dims操作，但是如果参数类型本身为`ndarray`时，则直接使用。

这样，用户试图直接传入一个未进行预处理的图像数据，就会出错，而如果用户想自行进行这些预处理时，会发现整个包，只export了`PaddleClas`这一个类，tools目录并未export出来，所以试图引入时会报错说tools module未在`__init__.py`中找到，造成即使用户想自行预处理都做不到。

能想到的方法有以下几个：

 1. 可以增加参数类型，传入file like object对象，这样就可以直接读取该图像并进行预处理
 2. 添加predict的参数`is_preprocessed`，示意是否是已预处理的图像，如果不是则可以进行预处理
 3. 在`__init__.py`的`__all__`中开放tools模块，让用户可以自行预处理

**Comment by littletomatodonkey** [comment]
好的，感谢反馈！我们近期内添加下该功能
