### ISSUE TITLE
请问下图像分类新增分类应该如何冻结？

### ISSUE THREAD

**Issue by yangy996** [PaddlePaddle/PaddleClas#634]

**Comment by littletomatodonkey** [comment]
指的是冻结参数还是模型finetune呢？

1. 冻结参数的话，可以使用xxx.trainable=False 实现参数冻结，具体实现可以参考：https://github.com/PaddlePaddle/PaddleClas/blob/423e29ef04448132b64d52f422417140b5430ea0/ppcls/modeling/architectures/distillation_models.py#L43

2. 模型finetune的话，修改配置中的类别数，加载pretrain model，就可以finetune

**Comment by yangy996** [comment]
> 指的是冻结参数还是模型finetune呢？
> 
> 1. 冻结参数的话，可以使用xxx.trainable=False 实现参数冻结，具体实现可以参考：https://github.com/PaddlePaddle/PaddleClas/blob/423e29ef04448132b64d52f422417140b5430ea0/ppcls/modeling/architectures/distillation_models.py#L43
> 2. 模型finetune的话，修改配置中的类别数，加载pretrain model，就可以finetune

大佬，请问下之前训练好的分类模型，如何要新增一个分类，如何只训练新增的分类数据呢？

**Comment by littletomatodonkey** [comment]
目前PaddleClas中还没有支持增量式训练，建议将之前的数据和新增的数据融合在一起，重新训练一下哈
