### ISSUE TITLE
PaddleClas中怎么使用visualdl工具

### ISSUE THREAD

**Issue by CoIorfu1** [PaddlePaddle/PaddleClas#637]
请问在哪个文件中加入visualdl命令呢

**Comment by littletomatodonkey** [comment]
你好，动态图的visualdl，目前我们正在集成哈，预计下周ready~感谢关注

**Comment by skywalk163** [comment]
期待啊

**Comment by skywalk163** [comment]
已经看到
requirements.txt 文件里有visualdl啦，继续期待

**Comment by TingquanGao** [comment]
已经可以了呀。
https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/extension/VisualDL.md

**Comment by skywalk163** [comment]
太棒了，谢谢！
我看了下，应该是在develop里已经加进去了！
