### ISSUE TITLE
backbone的增加

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleClas#640]
Paddlecls现在有RepVGG这个backbone吗，我没找到，没有的话可不可以考虑添加一下？谢谢

**Comment by TingquanGao** [comment]
您好，在develop分支已经添加了。
https://github.com/PaddlePaddle/PaddleClas/tree/develop#RepVGG
https://github.com/PaddlePaddle/PaddleClas/blob/develop/ppcls/modeling/architectures/repvgg.py
