### ISSUE TITLE
配置文件中的file_list和data_dir

### ISSUE THREAD

**Issue by duohappy** [PaddlePaddle/PaddleClas#645]
在训练模型的配置文件中都有`file_list`和`data_dir`字段
`file_list`：训练文件或者测试文件的路径
`data_dir`：数据集的路径

以训练文件 train.txt为例
每一行是 **图片的路径 类别**，那么图片的绝对路径：
``` python
os.path.join(data_dir, 图片的路径)
```

如果是这样的话，file_list可以用绝对路径么？

train.txt中图片的路径，直接用绝对路径可以么？data_dir字段就没有用了

在现实情况中，图片并不是存在一个文件夹里的，而是存在多个文件夹里的，train.txt中图片的路径，填写绝对路径更符合**图片分散在多个文件夹的情形**

**Comment by TingquanGao** [comment]
你好！首先，`file_list`可以用绝对路径。其次，如果`train.txt`中为图片的绝对路径，那么config文件中的`data_dir`字段可以为空（`""`）或根路径（`"/"`），这样`os.path.join()`后仍为图片的绝对路径。
具体代码可以看这里：
https://github.com/PaddlePaddle/PaddleClas/blob/d7f611d31a57b4c087fefda43f97b09473cd22e9/ppcls/data/reader.py#L187

**Comment by duohappy** [comment]
> 
> 
> 你好！首先，`file_list`可以用绝对路径。其次，如果`train.txt`中为图片的绝对路径，那么config文件中的`data_dir`字段可以为空（`""`）或根路径（`"/"`），这样`os.path.join()`后仍为图片的绝对路径。
> 具体代码可以看这里：
> 
> https://github.com/PaddlePaddle/PaddleClas/blob/d7f611d31a57b4c087fefda43f97b09473cd22e9/ppcls/data/reader.py#L187

明白了，感谢，:smile:
