### ISSUE TITLE
load的inference模型怎么判断是resnet50还是res2net50，又或者resnet50_vd

### ISSUE THREAD

**Issue by IamMegatron2025** [PaddlePaddle/PaddleClas#655]
hello，我load了一个inference接口保存的模型，现在有两个疑问：
1.怎么判断我load的这个模型是resnet50还是101
2.怎么判断我load的这个模型是resnet50还是res2net50，又或者resnet50_vd

**Comment by TingquanGao** [comment]
你好！可以通过Netron或VisualDL将网络结构可视化。

**Comment by IamMegatron2025** [comment]
@TingquanGao 谢谢回复，Netron不能打开inference接口保存的model文件啊

**Comment by TingquanGao** [comment]
直接将inference保存的文件`inference.pdmodel`重命名为`__model__`即可
