### ISSUE TITLE
DataLoader reader thread raised an exception

### ISSUE THREAD

**Issue by wa3926** [PaddlePaddle/PaddleClas#657]
W0330 17:35:59.417029  1669 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 10.2
W0330 17:35:59.422202  1669 device_context.cc:372] device: 0, cuDNN Version: 7.6.
2021-03-30 17:36:23,905 - WARNING - DataLoader reader thread raised an exception.
Traceback (most recent call last):
  File "tools/train.py", line 117, in <module>
    main(args)
  File "tools/train.py", line 90, in main
    epoch_id, 'train')
  File "/paddle/PaddleClas/tools/program.py", line 301, in run
    for idx, batch in enumerate(dataloader()):
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 351, in __next__
    return self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)
paddle-gpu 2.0.1   paddleclas 使用的是 develop  切换其他分支也不行   
用的是ResNet50_vd 快速开始里面的yaml 文件改的 因为不想使用随机剪裁和反转 就把 train 里面 
        - RandCropImage:
            size: 224
        - RandFlipImage:
            flip_code: 1   这几行删除了  结果就报错了   

想问一下 怎么关掉训练集的数据增强   或者想单独使用  随机改变颜色 亮度 该怎么配置        

第二个问题    VALID里面 使用了 缩放     - ResizeImage:
            resize_short: 256    那训练集里面为什么不使用呢

**Comment by TingquanGao** [comment]
你好，目前PaddleClas暂不支持通过单独改变颜色、亮度实现数据增强。可以将config配置文件中`RandFlipImage`与`RandCropImage `字段删除，并设置`ResizeImage`字段设置输入网络图像的resize大小：
```yaml
        - ResizeImage:
            size: 224
```
具体可参考：
https://github.com/PaddlePaddle/PaddleClas/blob/725a8ffda618eb8da16171a6b2006f6ab85e9928/ppcls/data/imaug/operators.py#L65

**Comment by TingquanGao** [comment]
VALID中使用了`resize_short`设置缩放，TRAIN中使用如下方式缩放并裁剪图像为224大小。
```yaml
        - RandCropImage:
            size: 224
```
具体可参考代码：
https://github.com/PaddlePaddle/PaddleClas/blob/725a8ffda618eb8da16171a6b2006f6ab85e9928/ppcls/data/imaug/operators.py#L117

**Comment by wa3926** [comment]
@TingquanGao  mode: 'train'
ARCHITECTURE:
    name: 'ResNet50_vd'

checkpoints: ""
pretrained_model: ""
use_gpu: True
model_save_dir: "./output/ocrcls/"
classes_num: 4
total_images: 8047
save_interval: 1
validate: True
valid_interval: 1
epochs: 1
topk: 1
image_shape: [3, 224, 224]

LEARNING_RATE:
    function: 'Cosine'          
    params:                   
        lr: 0.0125

OPTIMIZER:
    function: 'Momentum'
    params:
        momentum: 0.9
    regularizer:
        function: 'L2'
        factor: 0.00001

TRAIN:
    batch_size: 128
    num_workers: 0
    file_list: "./dataset/ocrcls/train.txt"
    data_dir: "./dataset/ocrcls/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            to_np: False
            channel_first: False
        - ResizeImage:
            resize_short: 256
        - NormalizeImage:
            scale: 1./255.
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:

VALID:
    batch_size: 88
    num_workers: 0
    file_list: "./dataset/ocrcls/test.txt"
    data_dir: "./dataset/ocrcls/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            to_np: False
            channel_first: False
        - ResizeImage:
            resize_short: 256
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:
我配置文件改成这样 还是报错
1-03-31 08:34:50,543 - WARNING - DataLoader reader thread raised an exception.
Traceback (most recent call last):
  File "tools/train.py", line 117, in <module>
    main(args)
  File "tools/train.py", line 90, in main
    epoch_id, 'train')
  File "/paddle/PaddleClas/tools/program.py", line 301, in run
    for idx, batch in enumerate(dataloader()):
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 351, in __next__
    return self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)      恢复原来的配置就没问题

**Comment by wa3926** [comment]
主要就是把 TRAIN 里面的 随机剪裁和翻转 删除了 替换成 - ResizeImage:
resize_short: 256   224我也试过也不行       然后VALID 里面把剪裁给删除了     就一直报错   求指导大佬

**Comment by wa3926** [comment]
@TingquanGao  大佬你意思 train 里面 是 - ResizeImage:
            size: 224       valid 里面是         - ResizeImage:
            resize_short: 224    好无语啊  参数名称文字 找了好长时间

**Comment by TingquanGao** [comment]
要保证输入图像的尺寸为`224`，所以如果使用`ResizeImage-resize_short:256`的话，需要配合`CropImage-size:224`，或者`RandCropImage-size:224`一起使用，`CropImage`为center crop，不会有随机：
```yaml
        - ResizeImage:
            resize_short: 256
        - CropImage:
            size: 224
```
或者直接使用`ResizeImage-resize:224`:
```yaml
        - ResizeImage:
            size: 224
```

**Comment by wa3926** [comment]
@TingquanGao  你意思是valid 里面一定要配置  CropImage-size:224 是吗    因为我训练的 是4分类 整图图像文字方向分类    有一些图像里面文字是 最上面 只有一行   CropImage 这个担心影响 所以我就把去掉了    然后就发现 训练到验证的时候 一直报错

**Comment by wa3926** [comment]
@TingquanGao  明白了 我试试 - ResizeImage:
            size: 224

**Comment by TingquanGao** [comment]
不是，如果直接用ResizeImage的话，size要设为224

**Comment by wa3926** [comment]
@TingquanGao  终于跑成功了  感谢指导  train 和valid 2个里面 size 都写224 好了
