### ISSUE TITLE
关于训练中断后恢复训练

### ISSUE THREAD

**Issue by darkestcoding** [PaddlePaddle/PaddleClas#658]
中断训练后如何基于这个checkpoint再继续模型训练呢，在一轮训练后已获得了.pdopt和.pdparams这两个模型文件。
![image](https://user-images.githubusercontent.com/35415263/113004171-fe7a6e80-91a5-11eb-8b3a-84d1511a5cd7.png)

**Comment by TingquanGao** [comment]
你好！可以先参考一下这个文档，有问题可以随时向我们反馈。谢谢！
https://github.com/paddlepaddle/paddleclas/blob/release%2F2.0/docs/zh_CN/tutorials/getting_started.md#13-%E6%A8%A1%E5%9E%8B%E6%81%A2%E5%A4%8D%E8%AE%AD%E7%BB%83

**Comment by darkestcoding** [comment]
非常感谢！
