### ISSUE TITLE
python infer.py 的时候分类数不对

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/PaddleClas#661]
用的develop版本。
在aistudio项目里：

使用命令：
!python tools/infer/infer.py \
    -i ~/work/test \
    --model ResNet50_vd \
    --pretrained_model "output/ResNet50_vd/0/ppcls" \
    # --use_gpu True \
    --load_static_weights False \
    --class_num 2

输出：
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
W0401 10:35:47.180687  5868 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.0, Runtime API Version: 10.1
W0401 10:35:47.185531  5868 device_context.cc:372] device: 0, cuDNN Version: 7.6.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1303: UserWarning: Skip loading for out.weight. out.weight receives a shape [2048, 2], but the expected shape is [2048, 1000].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1303: UserWarning: Skip loading for out.bias. out.bias receives a shape [2], but the expected shape is [1000].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
File:neg_1.png, Top-1 result: class id(s): [928], score(s): [0.00]
File:pos_1.png, Top-1 result: class id(s): [131], score(s): [0.00]
File:pos_2.png, Top-1 result: class id(s): [861], score(s): [0.00]
File:neg_3.png, Top-1 result: class id(s): [496], score(s): [0.00]

打印argv参数，发现class_num在设置为2的时候，系统的数值还是1000

Namespace(batch_size=1, class_num=1000, cpu_num_threads=10, enable_benchmark=False, enable_mkldnn=False, enable_profile=False, gpu_mem=8000, hubserving=False, image_file='/home/aistudio/work/test', ir_optim=True, load_static_weights=False, model='ResNet50_vd', model_file=None, normalize=True, params_file=None, pre_label_image=False, pre_label_out_idr=None, pretrained_model='output/ResNet50_vd/0/ppcls', resize=224, resize_short=256, server_url=None, top_k=1, use_fp16=False, use_gpu=True, use_tensorrt=False)

**Comment by TingquanGao** [comment]
你好，请尝试如下方式输入命令：
```shell
python tools/infer/infer.py -i ~/work/test --model ResNet50_vd --pretrained_model "output/ResNet50_vd/0/ppcls" --load_static_weights False --class_num 2
```
或
```shell
python tools/infer/infer.py \
-i ~/work/test \
--model ResNet50_vd \
--pretrained_model "output/ResNet50_vd/0/ppcls" \
# --use_gpu True \
--load_static_weights False \
--class_num 2
```

**Comment by skywalk163** [comment]
使用上面那样一行命令，OK
使用下面这样换行的，没起作用。

经过观察，在多行命令的时候，如果中间有注释语句，则后面的语句失效。大约是我在命令语句错误的使用python语法造成的。

**Comment by Gavinic** [comment]
遇到同样的问题，但是没看出来推荐的命令和您自己使用的命令的区别
