### ISSUE TITLE
图像处理 随机改变色彩

### ISSUE THREAD

**Issue by wa3926** [PaddlePaddle/PaddleClas#662]
请问一下  我想在 operators.py 加上一段图像处理  除了 operators这个里面加一段  然后 yaml 里面加一下   还有其他地方地方需要修改吗
# 随机改变亮暗、对比度和颜色等
class Distort(object):
    """ crop image """

    def __call__(self, img):
        # 随机改变亮度
        def random_brightness(img, lower=0.5, upper=1.5):
            e = np.random.uniform(lower, upper)
            return ImageEnhance.Brightness(img).enhance(e)
        # 随机改变对比度
        def random_contrast(img, lower=0.5, upper=1.5):
            e = np.random.uniform(lower, upper)
            return ImageEnhance.Contrast(img).enhance(e)
        # 随机改变颜色
        def random_color(img, lower=0.5, upper=1.5):
            e = np.random.uniform(lower, upper)
            return ImageEnhance.Color(img).enhance(e)

        ops = [random_brightness, random_contrast, random_color]
        np.random.shuffle(ops)

        img = Image.fromarray(img)
        img = ops[0](img)
        img = ops[1](img)
        img = ops[2](img)
        img = np.asarray(img)

        return img

**Comment by TingquanGao** [comment]
还需要在这里`import`一下
https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.0/ppcls/data/imaug/__init__.py#L23-L29

**Comment by wa3926** [comment]
@TingquanGao  感谢指导！

**Comment by wa3926** [comment]
@

**Comment by wa3926** [comment]
@TingquanGao  不好意思 大佬又打扰了  
按你指导   我想使用图像增强 扩大训练集   使用随机改变和 亮暗的   
训练配置如下
TRAIN:
    batch_size: 128
    num_workers: 0
    file_list: "./dataset/ocrcls3/train_2.txt"
    data_dir: "./dataset/ocrcls3/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            to_np: False
            channel_first: False
        - ResizeImage:
            size: 224
        - NormalizeImage:
            scale: 1./255.
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:
        - Distort:

operators 里面添加 
# 随机改变亮暗、对比度和颜色等
class Distort(object):
    """ crop image """
    def __init__(self):
        pass
    def __call__(self, img):
        # 随机改变亮度
        def random_brightness(img, lower=0.5, upper=1.5):
            e = np.random.uniform(lower, upper)
            return ImageEnhance.Brightness(img).enhance(e)
        # 随机改变对比度
        def random_contrast(img, lower=0.5, upper=1.5):
            e = np.random.uniform(lower, upper)
            return ImageEnhance.Contrast(img).enhance(e)
        # 随机改变颜色
        def random_color(img, lower=0.5, upper=1.5):
            e = np.random.uniform(lower, upper)
            return ImageEnhance.Color(img).enhance(e)

        ops = [random_brightness, random_contrast, random_color]
        np.random.shuffle(ops)

        img = Image.fromarray(img)
        img = ops[0](img)
        img = ops[1](img)
        img = ops[2](img)
        img = np.asarray(img)

        return img

_init_py 里面添加 

from .operators import Distort

结果训练报错 
Traceback (most recent call last):
  File "tools/train.py", line 117, in <module>
    main(args)
  File "tools/train.py", line 90, in main
    epoch_id, 'train')
  File "/paddle/PaddleClas/tools/program.py", line 301, in run
    for idx, batch in enumerate(dataloader()):
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 351, in __next__
    return self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)  

配置文件里面去掉  - Distort:  就没问题   有点疑问 比如训练集1000张图片  使用图像增强  total_images 这个是 2000吗？  2个问题求大佬知道下  报错和 total_images  问题

**Comment by littletomatodonkey** [comment]
你好
1. 关于数据异常的问题，可以使用下面的代码捕捉更加具体的异常，对应的函数是reader.py中的`__getitem__`

https://github.com/PaddlePaddle/PaddleClas/blob/725a8ffda618eb8da16171a6b2006f6ab85e9928/ppcls/data/reader.py#L184

```
    def __getitem__(self, idx):
        try:
            line = self.full_lines[idx]
            img_path, label = line.split(self.delimiter)
            img_path = os.path.join(self.params['data_dir'], img_path)
            with open(img_path, 'rb') as f:
                img = f.read()
            return (transform(img, self.ops), int(label))
        except Exception as e:
            logger.error("data read faild: {}, exception info: {}".format(line,
                                                                          e))
            return self.__getitem__(random.randint(0, len(self)))
```

2. 使用图像增强，total_images不用改，它是在线增广，相当于1个epoch还是训练这么多条数据，不过加上数据增广之后，可以适当扩大训练的epoch数量。

**Comment by wa3926** [comment]
@littletomatodonkey  感谢大佬指点  大概明白了  我之前理解错了
