### ISSUE TITLE
怎么获取输出节点

### ISSUE THREAD

**Issue by IamMegatron2025** [PaddlePaddle/PaddleClas#666]
请问，从这行代码`exe, program, feed_names, fetch_lists = create_predictor(args)` 中，怎么获取输出节点呢？

**Comment by littletomatodonkey** [comment]
可以在这里获取输出节点

https://github.com/PaddlePaddle/PaddleClas/blob/794caef23b49b821d52a68a713b49d8fb75f445b/tools/infer/predict.py#L38
