### ISSUE TITLE
报错为segmentation fault, 应为out of memory!

### ISSUE THREAD

**Issue by imchinfei** [PaddlePaddle/PaddleClas#672]
W0409 14:41:11.130335  5046 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.0, Runtime API Version: 10.2
W0409 14:41:11.133520  5046 device_context.cc:372] device: 0, cuDNN Version: 8.0.
2021-04-09 14:41:14,308 - INFO - In distillation mode, teacher model will be loaded firstly before student model.
2021-04-09 14:41:15,061 - INFO - Finish initing teacher model from ['./ResNet50_vd_ssld_v2_pretrained']

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1617950478 (unix time) try "date -d @1617950478" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 5046 (TID 0x7fb4a88fb740) from PID 0 ***]

Segmentation fault (core dumped)

以上, 请问能看出是什么问题吗?
我初始时候batchsize有意识设小, 但事实上还是不够小.
segmentation fault会让人以为是环境问题, 我前后装了n多次paddlepaddle.
曾有幸在百度实习过, 我记得paddle1.x的时代, 是有out of memory的报错呀, 咋现在是segmentation fault了?

另外, docker的层数能不能合并一下, 别那么多, 有些公司(匿了)的镜像构建平台会限制层数, paddle release版本的66层, 远超了.

哎, 气死我了, 必须吐槽一下Segmentation fault, 作为曾经百度的一员对百度还是有感情的, paddle推广过程中要注意细节啊!!! 细节!!!

**Comment by TingquanGao** [comment]
你好，可以贴一下运行的命令吗？以及Paddle版本和PaddleClas分支分别是哪个呢？

**Comment by imchinfei** [comment]
> 你好，可以贴一下运行的命令吗？

paddlepaddle==2.0.1, paddleclas==最新release

唉
不用了, 我找到原因了, 问题已经解决了.
就是batchsize设大了
你可能没看懂, 我其实是在提建议, batchsize太大应该报out of memory而不是segmentation fault
paddleclas或者是paddlepaddle框架的报错机制有问题
