### ISSUE TITLE
whl包部署使用resnet模型，返回result中的class_ids对应的实际枚举类在哪里可以查看

### ISSUE THREAD

**Issue by whz11** [PaddlePaddle/PaddleClas#675]
top-1 result: {'filename': '/Users/apple/Downloads/11.jpg', 'class_ids': array([975]), 'scores': array([0.47659966], dtype=float32), 'label_names': ['lakeside, lakeshore']}

class_ids是数字，无法明确含义

**Comment by littletomatodonkey** [comment]
你好，label_names返回的就是实际枚举类，更多类别可以在这里查看：

https://github.com/PaddlePaddle/PaddleClas/blob/develop/ppcls/utils/imagenet1k_label_list.txt
