### ISSUE TITLE
如何利用提供的10万分类模型的预训练静态图权重获得图像的embedding特征？

### ISSUE THREAD

**Issue by nihuizhidao** [PaddlePaddle/PaddleClas#682]
想请教下，如何加载10万分类模型的预训练静态图权重，同时跑一遍前向计算得到图片的特征向量呢？我的目的是希望把这个么模型得到的特征向量作为图片相似度的计算。或者如果有更好的计算图片相似度的方式么？

谢谢！

**Comment by littletomatodonkey** [comment]
10w类模型用的是resnet50vd，使用的时候可以将这个2048维的feature输出来，用于计算图像之间的相似度，因为10W类模型是静态图模型，在加载时，需要指定`-o load_static_weights=True`

https://github.com/PaddlePaddle/PaddleClas/blob/c3d401b7eae1caffa63860b07763cd3b82ce296b/ppcls/modeling/architectures/resnet_vd.py#L322

**Comment by who0sy** [comment]
@littletomatodonkey weigths>>>>>>>>>weights  单词拼错了，昨天因为这个找了一下午bug.....

**Comment by littletomatodonkey** [comment]
好的，多谢反馈~已更正
