### ISSUE TITLE
关于训练完成的模型动态图转化

### ISSUE THREAD

**Issue by WangRongsheng** [PaddlePaddle/PaddleClas#684]
我已经利用PaddleClas完成了我的图像分类任务，并且得到了`best_model` 
![cgSDFf.png](https://z3.ax1x.com/2021/04/14/cgSDFf.png)
接下来我希望把模型部署在安卓端/IOS端，但我不知道该如何转化我的动态图模型或者设置怎么样的参数重新训练得到静态图模型，以便我完成端侧的部署工作

**Comment by littletomatodonkey** [comment]
1. 可以将动态图模型使用动转静的方式转化为静态图模型：https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/tutorials/getting_started.md#4-%E4%BD%BF%E7%94%A8inference%E6%A8%A1%E5%9E%8B%E8%BF%9B%E8%A1%8C%E6%A8%A1%E5%9E%8B%E6%8E%A8%E7%90%86
2. 如果希望部署在ios或者安卓端，可以使用PaddleLite，参考该文档：https://github.com/PaddlePaddle/PaddleClas/blob/develop/deploy/lite/readme.md
