### ISSUE TITLE
速度慢

### ISSUE THREAD

**Issue by tuotuowj** [PaddlePaddle/PaddleClas#687]
用paddleClas的flower的数据集，大概12ms处理一帧。
但是在参数不变的情况，换成一个比较大一点的数据集大概15000张图片分类，大概56ms处理一帧。
yaml中的参数只有数据地址换了，size，thread等参数都不变，为什么速度变慢了呢。。。
而且感觉paddleClas处理的速度也比之前paddlepaddle/models/PaddleCV/image_classification速度慢好多

**Comment by hysunflower** [comment]
您好，请问您用的哪个模型呢?
辛苦贴下模型训练命令 参数文件，你那边的环境信息哈

**Comment by hysunflower** [comment]
> 用paddleClas的flower的数据集，大概12ms处理一帧。
> 但是在参数不变的情况，换成一个比较大一点的数据集大概15000张图片分类，大概56ms处理一帧。
> yaml中的参数只有数据地址换了，size，thread等参数都不变，为什么速度变慢了呢。。。
> 而且感觉paddleClas处理的速度也比之前paddlepaddle/models/PaddleCV/image_classification速度慢好多

您好，请问您训练的哪个模型呢？
辛苦贴一下命令 参数 以及您那边的环境信息
