### ISSUE TITLE
HS-ResNet

### ISSUE THREAD

**Issue by zzl-997** [PaddlePaddle/PaddleClas#689]
您好，想问一下HS-ResNet的代码公布了吗。论文中讲解Hierarchical-Split Block我还不是太明白，想要看一下代码。

**Comment by cuicheng01** [comment]
Hi，代码目前不太方便开源，具体可以看下这个图，有疑问可以邮件交流~
![image](https://user-images.githubusercontent.com/45199522/117637675-9f504680-b1b4-11eb-9fbe-4777e3229aa4.png)

**Comment by wangsun1996** [comment]
您好，想问下HS的这篇文章今年已经被收录了吗？
