### ISSUE TITLE
MobileNetV3_large_x0.5

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleClas#691]
请问这个后缀X0.5是什么意思呢？

**Comment by TingquanGao** [comment]
表示在标准MobileNetV3_large的基础上，将网络规模缩小0.5倍，具体就是中间feature map的通道数为0.5倍。

**Comment by zcswdt** [comment]
> 表示在标准MobileNetV3_large的基础上，将网络规模缩小0.5倍，具体就是中间feature map的通道数为0.5倍。

好的，谢谢回复，刚才看了源码，理解了。

**Comment by zcswdt** [comment]
> 表示在标准MobileNetV3_large的基础上，将网络规模缩小0.5倍，具体就是中间feature map的通道数为0.5倍。

请问一下ResNet34_vd？后面加个vd这个和resnet34有什么区别吗？

**Comment by TingquanGao** [comment]
可以参考这个：
https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.0/docs/zh_CN/faq_series/faq_2020_s1.md#q13-resnet_vd%E5%92%8Cresnetresnet_vc%E7%BB%93%E6%9E%84%E6%9C%89%E4%BB%80%E4%B9%88%E5%8C%BA%E5%88%AB%E5%91%A2

**Comment by zcswdt** [comment]
> 可以参考这个：
> https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.0/docs/zh_CN/faq_series/faq_2020_s1.md#q13-resnet_vd%E5%92%8Cresnetresnet_vc%E7%BB%93%E6%9E%84%E6%9C%89%E4%BB%80%E4%B9%88%E5%8C%BA%E5%88%AB%E5%91%A2

谢谢了哟，懂了。
