### ISSUE TITLE
whl的"经过预处理的np.ndarray形式输入"

### ISSUE THREAD

**Issue by lbb1993** [PaddlePaddle/PaddleClas#693]
请问，请问base64编码的图片或者cv2的图像怎么做才能符合paddleclas的“经过预处理的np.ndarray形式输入”，如何做这种预处理呢，找了2天了没找到任何参考实例

**Comment by TingquanGao** [comment]
预处理主要包括`crop`，`resize` ，`normalize `等，代码实现可以参考
https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.0/tools/infer/utils.py#L147-L188

并且PaddleClas的whl包也提供的预处理功能，对于常规的预处理操作，可以直接使用PaddleClas实现，代码可以参考：
https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.0/paddleclas.py#L309-L318

**Comment by lbb1993** [comment]
感谢您的及时回复，我的确在utils中找到了相关代码，再次感谢~
