### ISSUE TITLE
预训练模型加载

### ISSUE THREAD

**Issue by zhijiejia** [PaddlePaddle/PaddleClas#694]
请问，我在 https://github.com/PaddlePaddle/PaddleClas/blob/release/static/docs/zh_CN/models/models_intro.md 这里下载VGG19的预训练模型，可是下载下来是tar文件，这个如果自己写代码加载权重，该怎么加载啊，我只知道paddle.load()加载的是pdparams类型的文件。

**Comment by littletomatodonkey** [comment]
你好，那个是静态图的预训练，动态图的话，可以在这里下载pdparams文件

https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.0/README_cn.md

vgg19的的链接为：https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/VGG19_pretrained.pdparams

**Comment by zhijiejia** [comment]
ok 原来是这样，感谢
