### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/PaddleClas#702]
![image](https://user-images.githubusercontent.com/53975909/116086656-9c445900-a6d2-11eb-89d1-f0037ecf360f.png)

**Comment by TingquanGao** [comment]
你好，请提供以下信息方便定位问题。PaddleClas哪个分支，启动命令，修改过代码哪部分？

**Comment by Monday-Leo** [comment]
已经解决，batch_size修改小一点就可以运行，请问现在可以训练rexnet吗

**Comment by TingquanGao** [comment]
目前已上传了rexnet代码：
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.1/ppcls/modeling/architectures/rexnet.py

**Comment by Monday-Leo** [comment]
有没有rexnet的预训练模型呢？

**Comment by TingquanGao** [comment]
你好，rexnet预训练模型有提供的：
https://github.com/PaddlePaddle/PaddleClas#rexnet
