### ISSUE TITLE
MixNet的config没有放出来吗？这里的transformer能转成paddlelite吗？

### ISSUE THREAD

**Issue by Liys0558** [PaddlePaddle/PaddleClas#706]
如上

**Comment by littletomatodonkey** [comment]
你好，感谢反馈，mixnet这些配置都在这个pr里，之后会合入：#718 

此外，transoformer目前是可以转化成inference model的，不过还没试过是否可以转成lite，因为这个模型都比较大，更建议在服务器端使用
