### ISSUE TITLE
flowers102,fc.weight receives a shape [512, 102], but the expected shape is [512, 1000].

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleClas#728]
python tools/infer/infer.py --model ShuffleNetV2_x0_25 -i dataset/flowers102/jpg/image_00001.jpg --pretrained_model output/ShuffleNetV2_x0_25/best_model/ppcls  --use_gpu True

W0516 21:46:54.029057 29512 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.0
W0516 21:46:54.030537 29512 device_context.cc:372] device: 0, cuDNN Version: 8.0.
/home/mm/anaconda3/envs/PaddleClas/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1303: UserWarning: Skip loading for _fc.weight. _fc.weight receives a shape [512, 102], but the expected shape is [512, 1000].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/home/mm/anaconda3/envs/PaddleClas/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py:1303: UserWarning: Skip loading for _fc.bias. _fc.bias receives a shape [102], but the expected shape is [1000].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
File:image_00001.jpg, Top-1 result: class id(s): [497], score(s): [0.02]

----------------
flowers102演示 按照官方文档操作  报错

**Comment by littletomatodonkey** [comment]
你好，需要指定class_num参数哈，flowers中是102

https://github.com/PaddlePaddle/PaddleClas/blob/release/2.1/docs/zh_CN/tutorials/getting_started.md

![image](https://user-images.githubusercontent.com/14270174/118433097-d1a9f880-b70c-11eb-86c8-dd91d6c970db.png)
