### ISSUE TITLE
我用hub部署分类模型时,调用就出现这个问题

### ISSUE THREAD

**Issue by intjun** [PaddlePaddle/PaddleClas#732]
./tools/infer/utils.py:227: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  data = np.fromstring(data, dtype).reshape(shape)

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1621321952 (unix time) try "date -d @1621321952" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 1516 (TID 0x7f41fab9f700) from PID 0 ***]

段错误

**Comment by TingquanGao** [comment]
你好！这个报错是客户端还是服务器端呢？可以把启动服务的命令和调用的命令截图一下吗？

**Comment by intjun** [comment]
> 你好！这个报错是客户端还是服务器端呢？可以把启动服务的命令和调用的命令截图一下吗？

启动服务的命令:hub serving start -c deploy/hubserving/clas/config.json
调用服务的命名:python tools/test_hubserving.py --server_url http://127.0.0.1:8888/predict/clas_system --image_file xx.jpg
调用的时候就出现这个问题:

**Comment by TingquanGao** [comment]
在完成安装`hub install deploy/hubserving/clas`后，在PaddleClas根目录运行命令`python deploy/hubserving/clas/test.py`，看一下是否可以打印出结果。

**Comment by intjun** [comment]
> 在完成安装`hub install deploy/hubserving/clas`后，在PaddleClas根目录运行命令`python deploy/hubserving/clas/test.py`，看一下是否可以打印出结果。
也是这个错误:
FatalError: Segmentation fault is detected by the operating system.
[TimeInfo: *** Aborted at 1621321952 (unix time) try "date -d @1621321952" if you are using GNU date ***]
[SignalInfo: *** SIGSEGV (@0x0) received by PID 1516 (TID 0x7f41fab9f700) from PID 0 ***]

段错误

**Comment by TingquanGao** [comment]
请检查一下`PaddleClas/deploy/hubserving/clas/params.py`与`PaddleClas/deploy/hubserving/clas/config.json`中的配置是否正确。

另外，可以使用以下命令，看一下是否可以正常打印出结果：
```python
python tools/infer/predict.py \
    --image_file "./deploy/hubserving/ILSVRC2012_val_00006666.JPEG" \
    --model_file "./inference/inference.pdmodel" \
    --params_file "./inference/inference.pdiparams" 
```

**Comment by intjun** [comment]
> 请检查一下`PaddleClas/deploy/hubserving/clas/params.py`与`PaddleClas/deploy/hubserving/clas/config.json`中的配置是否正确。
> 
> 另外，可以使用以下命令，看一下是否可以正常打印出结果：
> 
> ```python
> python tools/infer/predict.py \
>     --image_file "./deploy/hubserving/ILSVRC2012_val_00006666.JPEG" \
>     --model_file "./inference/inference.pdmodel" \
>     --params_file "./inference/inference.pdiparams" 
> ```
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1621404923 (unix time) try "date -d @1621404923" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 23095 (TID 0x7f4e282d2700) from PID 0 ***]

段错误

**Comment by TingquanGao** [comment]
可以运行以下命令，检查Paddle安装是否正常。
```shell
python
import paddle
paddle.utils.install_check.run_check()
```

**Comment by intjun** [comment]
> 可以运行以下命令，检查Paddle安装是否正常。
> 
> ```shell
> python
> import paddle
> paddle.utils.install_check.run_check()
> ```

Running verify PaddlePaddle program ... 
W0519 15:04:58.333796 21247 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.0, Runtime API Version: 10.2
W0519 15:04:58.334928 21247 device_context.cc:372] device: 0, cuDNN Version: 8.0.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

**Comment by TingquanGao** [comment]
> ./tools/infer/utils.py:227: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
> data = np.fromstring(data, dtype).reshape(shape)
> 
> ## C++ Traceback (most recent call last):
> 0 paddle::framework::SignalHandle(char const*, int)
> 1 paddle::platform::GetCurrentTraceBackStringabi:cxx11
> 
> ## Error Message Summary:
> FatalError: `Segmentation fault` is detected by the operating system.
> [TimeInfo: *** Aborted at 1621321952 (unix time) try "date -d @1621321952" if you are using GNU date ***]
> [SignalInfo: *** SIGSEGV (@0x0) received by PID 1516 (TID 0x7f41fab9f700) from PID 0 ***]
> 
> 段错误

上述的报错用的是什么模型呢？是自己训练的？还是下载了我们提供的呢？

**Comment by gaoyuchris** [comment]
> > ./tools/infer/utils.py:227: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
> > data = np.fromstring(data, dtype).reshape(shape)
> > ## C++ Traceback (most recent call last):
> > 0 paddle::framework::SignalHandle(char const*, int)
> > 1 paddle::platform::GetCurrentTraceBackStringabi:cxx11
> > ## Error Message Summary:
> > FatalError: `Segmentation fault` is detected by the operating system.
> > [TimeInfo: *** Aborted at 1621321952 (unix time) try "date -d @1621321952" if you are using GNU date ***]
> > [SignalInfo: *** SIGSEGV (@0x0) received by PID 1516 (TID 0x7f41fab9f700) from PID 0 ***]
> > 段错误
> 
> 上述的报错用的是什么模型呢？是自己训练的？还是下载了我们提供的呢？

你好，我按这个教程https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/en/tutorials/quick_start_recognition_en.md。 进行推理也出现了同样的错误。但是使用cpu版本是没有问题的。paddle.utils.install_check.run_check()这个也是正常的。paddle version是'2.1.0'。用的你们提供的官方模型。 @TingquanGao
