### ISSUE TITLE
可以实现在原有的模型上新增分类，但不重新训练所有数据？

### ISSUE THREAD

**Issue by lmmir** [PaddlePaddle/PaddleClas#734]
可以实现在原有的模型上新增分类，但不重新训练所有数据？

**Comment by TingquanGao** [comment]
所有数据是什么意思呢？
可以使用我们提供的预训练模型，分类数量后，在特定数据集上进行迁移学习。

**Comment by littletomatodonkey** [comment]
1. 在最开始训练的时候，可以预留一些class id，比如说有100类，那可以训一个包含200类的模型，后面100类可以用于后续的扩展
2. 对于最后的fc层，其实是一个C1 x C2的tensor，可以load 之前的pretrain，手动修改其为`C1 x (C2+k)`的tensor，k是你要新增的类别，添加的数值可以随机初始化，之后再保存下这些模型参数即可
