### ISSUE TITLE
支持指定层特征输出吗

### ISSUE THREAD

**Issue by yanchaoguo** [PaddlePaddle/PaddleClas#747]
分类模型支持指定一个CNN网络层 并获取该层的特征输出吗
像keras那样 获取vgg16最后一次池化层的结果 或者 FC2的全连接结果

**Comment by littletomatodonkey** [comment]
可以在这里直接返回，默认是返回logits

https://github.com/PaddlePaddle/PaddleClas/blob/a759ba8bea343da7c2c3bdd336611b604b4fb517/ppcls/modeling/architectures/vgg.py#L124

**Comment by yanchaoguo** [comment]
> 可以在这里直接返回，默认是返回logits
> 
> https://github.com/PaddlePaddle/PaddleClas/blob/a759ba8bea343da7c2c3bdd336611b604b4fb517/ppcls/modeling/architectures/vgg.py#L124

这么改的话 模型是不是需要重新训练 有没有一个image extraction的例子

**Comment by littletomatodonkey** [comment]
不需要重新训练，这里只是中间层的返回，特征可以直接用的
