### ISSUE TITLE
The relationship between models/PaddleCV/image_classification and this repo

### ISSUE THREAD

**Issue by miraclebiu** [PaddlePaddle/PaddleClas#84]
Some models'speed are different

**Comment by cuicheng01** [comment]
We used different types of  GPUs to test inference speed in two code repositories. In PaddleClas, we used a single v100 card to test the inference speed of all models. However, we used a single p4 card to test the inference speed of the models in PaddleCV/image_classification. In the future, we will use more types of GPUs to test inference speed.

**Comment by cuicheng01** [comment]
@miraclebiu We used different GPUs to test inference speed in two code repositories. In PaddleClas, we used a single v100 card to test the inference speed of all models. However, we used a single p4 card to test the inference speed of the models in PaddleCV/image_classification. In the future, we will use more types of GPUs to test inference speed.

**Comment by dyning** [comment]
This repo upgrades from models/PaddleCV/image_classification. The repo 'models/PaddleCV/image_classification' will be disclaimed.

**Comment by miraclebiu** [comment]
> This repo upgrades from models/PaddleCV/image_classification. The repo 'models/PaddleCV/image_classification' will be disclaimed.

I think maybe adding a description is a better choice. Besides, the deploy speed test on P4/T4 is more suitable for services. While for research, V100 is more suitable.

**Comment by dyning** [comment]
> > This repo upgrades from models/PaddleCV/image_classification. The repo 'models/PaddleCV/image_classification' will be disclaimed.
> 
> I think maybe adding a description is a better choice. Besides, the deploy speed test on P4/T4 is more suitable for services. While for research, V100 is more suitable.

Thanks for your suggestions. We will declare in the old repo. Besides, we will add the speed test on P4/T4，FP16，different batch size recently。

**Comment by dyning** [comment]
@miraclebiu 我们已经更新了不同batchsize，T4上，FP16和FP32的预测速度，感谢关注。
