### ISSUE TITLE
AttributeError: module 'paddle.fluid.core_avx' has no attribute 'get_cuda_device_count'

### ISSUE THREAD

**Issue by wishgale** [PaddlePaddle/PaddleClas#90]
在windows10，cpu环境下运行下面的命令出现上面的错误
python -m paddle.distributed.launch     tools/train.py        -c ./configs/quick_start/ResNet50_vd.yaml

PaddleClas能否提供对cpu的支持呢？

**Comment by cuicheng01** [comment]
目前不支持windows和cpu，调试中，即将支持~

**Comment by wishgale** [comment]
> 目前不支持windows和cpu，调试中，即将支持~

Thanks~~

**Comment by littletomatodonkey** [comment]
我们已经添加了对windows和cpu的训练与评估支持，可以参考这个PR： #159
