### ISSUE TITLE
关于主体检测模型的训练

### ISSUE THREAD

**Issue by xyc2690** [PaddlePaddle/PaddleClas#902]
表格里用了几个大数据集的子集，
那请问主体检测模型训练数据该如何选择呢。训练集会发布吗？
下载的预训练模型比较大，如果换更小的模型精度会下降很多吗？

**Comment by littletomatodonkey** [comment]
1. 训练数据是随机抽取的
2. 小模型的话，精度会有一些损失，不过这块没有训练过，具体的下降幅度不太好评估，后续我们尝试下更小的检测模型~
