### ISSUE TITLE
CPU 运行 `图像识别快速开始` 文档教程报错

### ISSUE THREAD

**Issue by mrbulb** [PaddlePaddle/PaddleClas#912]
您好，我在机器上按照 [图像识别快速开始](https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/tutorials/quick_start_recognition.md) 来尝试运行，但发现会报错，没有输出文档中所显示预测结果

我的运行脚本是
```shell
python3.7 python/predict_system.py -c configs/inference_product.yaml -o Global.use_gpu=False
```
输出的错误信息如下
> 2021-06-19 01:38:18 INFO: DetPostProcess :
2021-06-19 01:38:18 INFO: DetPreProcess :
2021-06-19 01:38:18 INFO:     transform_ops :
2021-06-19 01:38:18 INFO:         DetResize :
2021-06-19 01:38:18 INFO:             interp : 2
2021-06-19 01:38:18 INFO:             keep_ratio : False
2021-06-19 01:38:18 INFO:             target_size : [640, 640]
2021-06-19 01:38:18 INFO:         DetNormalizeImage :
2021-06-19 01:38:18 INFO:             is_scale : True
2021-06-19 01:38:18 INFO:             mean : [0.485, 0.456, 0.406]
2021-06-19 01:38:18 INFO:             std : [0.229, 0.224, 0.225]
2021-06-19 01:38:18 INFO:         DetPermute :
2021-06-19 01:38:18 INFO: Global :
2021-06-19 01:38:18 INFO:     batch_size : 1
2021-06-19 01:38:18 INFO:     cpu_num_threads : 100
2021-06-19 01:38:18 INFO:     det_inference_model_dir : ./models/ppyolov2_r50vd_dcn_mainbody_v1.0_infer
2021-06-19 01:38:18 INFO:     enable_benchmark : True
2021-06-19 01:38:18 INFO:     enable_mkldnn : True
2021-06-19 01:38:18 INFO:     enable_profile : False
2021-06-19 01:38:18 INFO:     gpu_mem : 8000
2021-06-19 01:38:18 INFO:     image_shape : [3, 640, 640]
2021-06-19 01:38:18 INFO:     infer_imgs : ./dataset/product_demo_data_v1.0/query/wangzai.jpg
2021-06-19 01:38:18 INFO:     ir_optim : True
2021-06-19 01:38:18 INFO:     labe_list : ['foreground']
2021-06-19 01:38:18 INFO:     max_det_results : 1
2021-06-19 01:38:18 INFO:     rec_inference_model_dir : ./models/product_ResNet50_vd_aliproduct_v1.0_infer
2021-06-19 01:38:18 INFO:     threshold : 0.2
2021-06-19 01:38:18 INFO:     use_fp16 : False
2021-06-19 01:38:18 INFO:     use_gpu : False
2021-06-19 01:38:18 INFO:     use_tensorrt : False
2021-06-19 01:38:18 INFO: IndexProcess :
2021-06-19 01:38:18 INFO:     dist_type : IP
2021-06-19 01:38:18 INFO:     index_path : ./dataset/product_demo_data_v1.0/index
2021-06-19 01:38:18 INFO:     return_k : 5
2021-06-19 01:38:18 INFO:     search_budget : 100
2021-06-19 01:38:18 INFO: RecPostProcess : None
2021-06-19 01:38:18 INFO: RecPreProcess :
2021-06-19 01:38:18 INFO:     transform_ops :
2021-06-19 01:38:18 INFO:         ResizeImage :
2021-06-19 01:38:18 INFO:             size : 224
2021-06-19 01:38:18 INFO:         NormalizeImage :
2021-06-19 01:38:18 INFO:             mean : [0.485, 0.456, 0.406]
2021-06-19 01:38:18 INFO:             order :
2021-06-19 01:38:18 INFO:             scale : 0.00392157
2021-06-19 01:38:18 INFO:             std : [0.229, 0.224, 0.225]
2021-06-19 01:38:18 INFO:         ToCHWImage : None
I0619 01:38:18.619588 18272 analysis_config.cc:424] use_dlnne_:0
I0619 01:38:18.619627 18272 analysis_config.cc:424] use_dlnne_:0
I0619 01:38:18.619647 18272 analysis_config.cc:424] use_dlnne_:0
I0619 01:38:18.619679 18272 analysis_config.cc:424] use_dlnne_:0
I0619 01:38:18.619697 18272 analysis_config.cc:424] use_dlnne_:0
I0619 01:38:18.619716 18272 analysis_config.cc:424] use_dlnne_:0
---    Fused 0 subgraphs into layer_norm op.
---    fused 0 scale with matmul
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with transpose's xshape
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape with transpose's xshape
---    Fused 0 MatmulTransposeReshape patterns
---    fused 0 batch norm with relu activation
---    Fused 0 subgraphs into layer_norm op.
---    fused 0 scale with matmul
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with transpose's xshape
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape with transpose's xshape
---    Fused 0 MatmulTransposeReshape patterns
---    fused 3 batch norm with relu activation
Inference: 3576.298713684082 ms per batch image
> 
> 
> --------------------------------------
> C++ Traceback (most recent call last):
> --------------------------------------
> 0   search_mobius_index
> 1   paddle::framework::SignalHandle(char const*, int)
> 2   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()
> 
> ----------------------
> Error Message Summary:
> ----------------------
> FatalError: `Illegal instruction` is detected by the operating system.
>   [TimeInfo: *** Aborted at 1624037903 (unix time) try "date -d @1624037903" if you are using GNU date ***]
>   [SignalInfo: *** SIGILL (@0x7fb3b59a9b81) received by PID 18272 (TID 0x7fb3cb139700) from PID 18446744072461392769 ***]
> 
> Illegal instruction (core dumped)

系统信息
* Linux amax-22 4.15.0-142-generic #146~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz

相同情况也可以在colab上复现，链接如下：https://colab.research.google.com/drive/1A66d2yRl--VUtpi323rlqXfnfeeOX-a0?usp=sharing

**Comment by weisy11** [comment]
看起来是mkldnn的问题，可以先试下把configs/inference_product.yaml 里面的use_mkl_dnn改成False
https://github.com/PaddlePaddle/PaddleClas/blob/713b47e510c3f1e9a053db146e8e2db1bb12452a/deploy/configs/inference_product.yaml#L14

**Comment by weisy11** [comment]
现在默认的配置改成False了

**Comment by mrbulb** [comment]
> 现在默认的配置改成False了

哇，感谢您这么晚还回应，但我在colab上用新版代码跑了一下，显示mkl设置为False，还是出现了同样的错误，链接在右边：https://colab.research.google.com/drive/1AjbmHQDliJQ_GgJWmrrUvq5zdh0TpBQ6?usp=sharing
明天有空我再我的本地机器上看一下能不能复现。
要是您之后工作日有空的话，再麻烦帮忙看看

错误报告如下
> 2021-06-18 18:27:21 INFO: DetPostProcess : 
> 2021-06-18 18:27:21 INFO: DetPreProcess : 
> 2021-06-18 18:27:21 INFO:     transform_ops : 
> 2021-06-18 18:27:21 INFO:         DetResize : 
> 2021-06-18 18:27:21 INFO:             interp : 2
> 2021-06-18 18:27:21 INFO:             keep_ratio : False
> 2021-06-18 18:27:21 INFO:             target_size : [640, 640]
> 2021-06-18 18:27:21 INFO:         DetNormalizeImage : 
> 2021-06-18 18:27:21 INFO:             is_scale : True
> 2021-06-18 18:27:21 INFO:             mean : [0.485, 0.456, 0.406]
> 2021-06-18 18:27:21 INFO:             std : [0.229, 0.224, 0.225]
> 2021-06-18 18:27:21 INFO:         DetPermute : 
> 2021-06-18 18:27:21 INFO: Global : 
> 2021-06-18 18:27:21 INFO:     batch_size : 1
> 2021-06-18 18:27:21 INFO:     cpu_num_threads : 100
> 2021-06-18 18:27:21 INFO:     det_inference_model_dir : ./models/ppyolov2_r50vd_dcn_mainbody_v1.0_infer
> 2021-06-18 18:27:21 INFO:     enable_benchmark : True
> 2021-06-18 18:27:21 INFO:     enable_mkldnn : False
> 2021-06-18 18:27:21 INFO:     enable_profile : False
> 2021-06-18 18:27:21 INFO:     gpu_mem : 8000
> 2021-06-18 18:27:21 INFO:     image_shape : [3, 640, 640]
> 2021-06-18 18:27:21 INFO:     infer_imgs : ./dataset/product_demo_data_v1.0/query/wangzai.jpg
> 2021-06-18 18:27:21 INFO:     ir_optim : True
> 2021-06-18 18:27:21 INFO:     labe_list : ['foreground']
> 2021-06-18 18:27:21 INFO:     max_det_results : 1
> 2021-06-18 18:27:21 INFO:     rec_inference_model_dir : ./models/product_ResNet50_vd_aliproduct_v1.0_infer
> 2021-06-18 18:27:21 INFO:     threshold : 0.2
> 2021-06-18 18:27:21 INFO:     use_fp16 : False
> 2021-06-18 18:27:21 INFO:     use_gpu : False
> 2021-06-18 18:27:21 INFO:     use_tensorrt : False
> 2021-06-18 18:27:21 INFO: IndexProcess : 
> 2021-06-18 18:27:21 INFO:     dist_type : IP
> 2021-06-18 18:27:21 INFO:     index_path : ./dataset/product_demo_data_v1.0/index
> 2021-06-18 18:27:21 INFO:     return_k : 5
> 2021-06-18 18:27:21 INFO:     search_budget : 100
> 2021-06-18 18:27:21 INFO: RecPostProcess : None
> 2021-06-18 18:27:21 INFO: RecPreProcess : 
> 2021-06-18 18:27:21 INFO:     transform_ops : 
> 2021-06-18 18:27:21 INFO:         ResizeImage : 
> 2021-06-18 18:27:21 INFO:             size : 224
> 2021-06-18 18:27:21 INFO:         NormalizeImage : 
> 2021-06-18 18:27:21 INFO:             mean : [0.485, 0.456, 0.406]
> 2021-06-18 18:27:21 INFO:             order : 
> 2021-06-18 18:27:21 INFO:             scale : 0.00392157
> 2021-06-18 18:27:21 INFO:             std : [0.229, 0.224, 0.225]
> 2021-06-18 18:27:21 INFO:         ToCHWImage : None
> I0618 18:27:21.102766   174 analysis_config.cc:424] use_dlnne_:0
> I0618 18:27:21.102820   174 analysis_config.cc:424] use_dlnne_:0
> I0618 18:27:21.102854   174 analysis_config.cc:424] use_dlnne_:0
> I0618 18:27:21.102874   174 analysis_config.cc:424] use_dlnne_:0
> I0618 18:27:21.102896   174 analysis_config.cc:424] use_dlnne_:0
> ---    Fused 0 subgraphs into layer_norm op.
> ---    Fused 0 subgraphs into layer_norm op.
> Inference: 3209.63454246521 ms per batch image
> 

> -> -------------------------------------
> C++ Traceback (most recent call last):
> --------------------------------------
> 0   _ctypes_callproc
> 1   search_mobius_index
> 2   paddle::framework::SignalHandle(char const*, int)
> 3   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()
> 
-> ---------------------
> Error Message Summary:
> ----------------------
> FatalError: `Illegal instruction` is detected by the operating system.
>   [TimeInfo: *** Aborted at 1624040846 (unix time) try "date -d @1624040846" if you are using GNU date ***]
>   [SignalInfo: *** SIGILL (@0x7fedee932b81) received by PID 174 (TID 0x7fee0f369780) from PID 18446744073417206657 ***]
>

**Comment by weisy11** [comment]
有试过重新编译检索模块吗？https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/deploy/vector_search/README.md

**Comment by weisy11** [comment]
也可以试下这个tuto，看下单独的检测或者提特征能不能正常运行：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/zh_CN/inference.md

**Comment by mrbulb** [comment]
> 有试过重新编译检索模块吗？https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/deploy/vector_search/README.md

嗯嗯，按照 [Linux上编译生成库文件](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/deploy/vector_search/README.md#22-linux%E4%B8%8A%E7%BC%96%E8%AF%91%E7%94%9F%E6%88%90%E5%BA%93%E6%96%87%E4%BB%B6) 重新编译了向量检索库文件就可以了，谢谢您的解答 😄 

感觉是不是可以再这个文档的环境安装部分补上这个，因为刚接触的话不大知道项目里面的一些依赖关系来着

**Comment by weisy11** [comment]
好的，我们补充一下
