### ISSUE TITLE
动漫人物识别任务的测试数据集标签有误

### ISSUE THREAD

**Issue by mrbulb** [PaddlePaddle/PaddleClas#921]
您好，在文档 [图像识别快速开始](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/zh_CN/tutorials/quick_start_recognition.md) 中提供了动漫人物识别任务的 [测试数据集](https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/rec/data/cartoon_demo_data_v1.0.tar)

但我看了一下里面的标签文件 `cartoon_demo_data_v1.0/data_file.txt`  是错误的，具体可以参见右边：[data_file.txt](https://gist.github.com/mrbulb/f1f1d84171081652be227fea99274770)

这些标签文件应该是来源于测试集合的，原始地址在：https://github.com/luxiangju-PersonAI/iCartoonFace#dataset

> - The iCartoonFace recognition personid infomations: [爱奇艺网盘](https://fft.cloud.iqiyi.com/s/cji77eS) (密码: N163o4)or [Google Drive](https://drive.google.com/file/d/1rOmoseZXAKG5y7mkEsVAoaWan2dIrMzD/view?usp=sharing)

但 `cartoon_demo_data_v1.0/gallery` 中的图片确实来自训练集的，因此造成了图片和标签的不匹配

我根据文件夹中的图片在搜图网站上找了相关的图片，并更新了一版新的标签文件：[data_file_update.txt](https://gist.github.com/mrbulb/c7bb7359f4156509a828d03bb60fe039)
您可以根据这个更新到数据集中，并重新计算相关索引文件，各个标签和人物的对应关系可以参考下面的引用

> 0： [黑犀侠_百度百科 (baidu.com)](https://baike.baidu.com/item/黑犀侠/1596669?fr=aladdin)
>
> 1：[文斯莫克·尼治_百度百科 (baidu.com)](https://baike.baidu.com/item/文斯莫克·尼治/19845408?fr=aladdin)
>
> 2：[莱德（动画《汪汪队立大功》角色）_百度百科 (baidu.com)](https://baike.baidu.com/item/莱德/22241187)
>
> 3：[小克（动画片《汪汪队立大功》中的角色）_百度百科 (baidu.com)](https://baike.baidu.com/item/小克/22908522)
>
> 4：[布鲁奥特曼_百度百科 (baidu.com)](https://baike.baidu.com/item/布鲁奥特曼/22537165?fr=aladdin)
>
> 5：[罗索奥特曼_百度百科 (baidu.com)](https://baike.baidu.com/item/罗索奥特曼/22549428?fr=aladdin)
>
> 6：[松坂梅_百度百科 (baidu.com)](https://baike.baidu.com/item/松坂梅)
>
> 7：[石井健太郎_百度百科 (baidu.com)](https://baike.baidu.com/item/石井健太郎/118858?fr=aladdin)
>
> 8：[李莓铃_百度百科 (baidu.com)](https://baike.baidu.com/item/李莓铃/1522475?fr=aladdin)
>
> 9：[假面骑士王蛇_百度百科 (baidu.com)](https://baike.baidu.com/item/假面骑士王蛇)
>
> 10：[艾斯德斯_百度百科 (baidu.com)](https://baike.baidu.com/item/艾斯德斯)  [#アカメが斬る! エスデス様 - さなえ的插画 - pixiv](https://www.pixiv.net/artworks/45398302)

**Comment by weisy11** [comment]
感谢，demo准备的有些仓促，最近会更新一次gallery和标签。
