### ISSUE TITLE
SSLD蒸馏问题

### ISSUE THREAD

**Issue by pawopawo** [PaddlePaddle/PaddleClas#947]
![image](https://user-images.githubusercontent.com/38682321/122893270-c172e200-d378-11eb-8a8e-cc3b49374cbc.png)
请问第4步的蒸馏和第5步的蒸馏有什么区别吗？

第4步的蒸馏包含ImageNet1K数据吗？

**Comment by pawopawo** [comment]
大模型在500M数据上预训练，作为老师。然后，在500M数据上蒸馏小模型。 最后，在1M数据上蒸馏finetune 小模型？
请问是这样吗？

**Comment by littletomatodonkey** [comment]
步骤如下
1. 基于facebook开源的resnext101_32x16d_wsl模型 去蒸馏得到了resnet50vd模型
2. 用这个resnet50vd，在500W数据集上去蒸馏mobilentv3
3. 考虑到500W的数据集的分布和100W的数据分布不完全一致，所以这块，在100W上的数据上又finetune了一下，精度有微弱的提升。

**Comment by pawopawo** [comment]
谢谢你的帮助～

第1步基于resnext101_32x16d_wsl的蒸馏，是在500w的数据上吗？ 蒸馏前，resnet50vd有在100w数据上预训练吗？

**Comment by littletomatodonkey** [comment]
是的，也是在500W数据上蒸馏的，然后在100W上面finetune，是从头训练的，没有用预训练模型

**Comment by pawopawo** [comment]
请问最后在1k数据上，蒸馏finetune的时候，整个网络参数都更新吗？还是只更新最后的linear层？

**Comment by cuicheng01** [comment]
> 请问最后在1k数据上，蒸馏finetune的时候，整个网络参数都更新吗？还是只更新最后的linear层？

目前使用的是小的学习率更新所有的层，当然只更新最后的层也是可以的
