### ISSUE TITLE
如何独立引用主体检测，特征抽取相关的模块

### ISSUE THREAD

**Issue by yanchaoguo** [PaddlePaddle/PaddleClas#954]
你好我想在自己的项目中使用主体检测或图片特征抽取输出的结果， 如何操作呢，有没有相关demo可以了解一下

**Comment by Intsigstephon** [comment]
独立检测可以参考： PaddleClas/deploy/python/predict_det.py

**Comment by Intsigstephon** [comment]
特征抽取可以参考： PaddleClas/deploy/python/predict_rec.py

**Comment by weisy11** [comment]
预测可以参考：
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/zh_CN/inference.md
检测模块的训练请参考PaddleDetection，特征提取模块的训练可以参考：
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/zh_CN/tutorials/getting_started_retrieval.md
