### ISSUE TITLE
PaddleClas-release-2.2\deploy\vector_search\index.dll with msg [WinError 126] 找不到指定的模块。,

### ISSUE THREAD

**Issue by 140ai** [PaddlePaddle/PaddleClas#955]
你好，我试过已有的index.dll和重新编译（没有报错），运行都找不到模块，但是文件的确存在，请问要怎么做

**Comment by 140ai** [comment]
已关闭杀毒软件

**Comment by Intsigstephon** [comment]
系统环境变量里面，有没有设置对应的目录？

**Comment by 140ai** [comment]
> 系统环境变量里面，有没有设置对应的目录？

C:\TDM-GCC-64\bin
有的

**Comment by oneoneling** [comment]
> > 系统环境变量里面，有没有设置对应的目录？
> 
> C:\TDM-GCC-64\bin
> 有的

你是说E:\workspace\classification\PaddleClas-release-2.2\deploy\vector_search吗？也没用

**Comment by hablee** [comment]
我在win10下也遇到这个问题，已经重新生成了index.dll，但是还是报找不到index.dll的错

**Comment by hablee** [comment]
请问楼主解决了吗

**Comment by littletomatodonkey** [comment]
是在deplpy目录下执行的不？

**Comment by littletomatodonkey** [comment]
编译完成之后，需要返回deploy目录执行哈

**Comment by steinvenic** [comment]
有同样的问题

**Comment by cuicheng01** [comment]
方便把系统的版本，cuda的版本，cudnn的版本，paddle版本都说一下吗

**Comment by TingquanGao** [comment]
可将此处代码[](https://github.com/PaddlePaddle/PaddleClas/blob/4cc1b004525fc0607f998ba0276242763d765079/deploy/vector_search/interface.py#L33)
该问题已修复，详见 #966

**Comment by TingquanGao** [comment]
由于Python从3.8起，更改了Windows平台上dll的默认加载规则。因此对于Windows平台，Python版本>=3.8的情况，可以尝试更换Python3.7，或尝试将此处代码
https://github.com/PaddlePaddle/PaddleClas/blob/4cc1b004525fc0607f998ba0276242763d765079/deploy/vector_search/interface.py#L33
修改为：
```python
    lib = ctypes.cdll.LoadLibrary(so_path, winmode=0x8)
```

该问题已提PR修复，#966 。

**Comment by lazyn1997** [comment]
index.dll with msg LoadLibrary() got an unexpected keyword argument 'winmode'，修改后会有这样的错误
