### ISSUE TITLE
predict_det.py中self.paddle_predictor.run()执行耗时问题

### ISSUE THREAD

**Issue by yanchaoguo** [PaddlePaddle/PaddleClas#957]
使用predict_det.py中的方式去检测一张普通的图片就需要等2s 有没有什么优化的空间啊

**Comment by yanchaoguo** [comment]
predict中这个方法比较耗时
self.paddle_predictor.run()

**Comment by cuicheng01** [comment]
这个2s是怎么测试出来的？

**Comment by yanchaoguo** [comment]
> 这个2s是怎么测试出来的？

在方法中加打点
t1 = time.time()
        self.paddle_predictor.run()
        t2 = time.time()
        output_names = self.paddle_predictor.get_output_names()
        
        boxes_tensor = self.paddle_predictor.get_output_handle(output_names[0])
        
        np_boxes = boxes_tensor.copy_to_cpu()
         

        print("Inference: {} ms per batch image".format((t2 - t1) * 1000.0))
@cuicheng01

**Comment by yanchaoguo** [comment]
img = cv2.resize(img, (int(h*0.5), int(w*0.5)), interpolation=cv2.INTER_CUBIC)
output = det_predictor.predict(img)

这里对图片进行压缩后 发现耗时并没有减少  说明self.paddle_predictor.run()这里有一些非图片处理部分是比较耗时的

**Comment by cuicheng01** [comment]
这边没有复现你的问题，可以再说下其他信息吗，比如gpu型号，paddle版本。

**Comment by weisy11** [comment]
由于模型比较大，在cpu上执行的速度确实比较慢，不过应该没有这么慢。
可能是由于第一张图需要初始化，你可以多跑几张图试试。

**Comment by yanchaoguo** [comment]
> 这边没有复现你的问题，可以再说下其他信息吗，比如gpu型号，paddle版本。

@cuicheng01 我这边paddle '2.1.0' 在windows cpu(i7)环境下运行的

**Comment by yanchaoguo** [comment]
> 由于模型比较大，在cpu上执行的速度确实比较慢，不过应该没有这么慢。
> 可能是由于第一张图需要初始化，你可以多跑几张图试试。

我把初始化提出来了 能够节省1s predict部分还是很慢 1.3s @weisy11

**Comment by yanchaoguo** [comment]
`---    Fused 0 subgraphs into layer_norm op.
Inference: 1247.1392154693604 ms per batch image
[{'class_id': 0, 'score': 0.7452156, 'bbox': array([ 42.56198, 138.99658, 262.18896, 204.30203], dtype=float32), 'label_name': 'foreground'}]`

非GPU环境下 这个时间仅仅是预测的时间  生产环境用有点不能接受

**Comment by weisy11** [comment]
目前的速度确实有些慢。不过也想了解一下您能接受的底线预测速度是多少？

**Comment by yanchaoguo** [comment]
> 目前的速度确实有些慢。不过也想了解一下您能接受的底线预测速度是多少？

400-500ms吧 ，至少在其它深度学习框架上是可以做到的 而且是多目标检测

**Comment by njustczr** [comment]
图片预处理部分特别耗时，
![image](https://user-images.githubusercontent.com/30426320/154475823-c0ffe610-97fe-49da-abb1-cfe2da0a3b35.png)
比模型推理还要耗时
