### ISSUE TITLE
这个是什么问题?

### ISSUE THREAD

**Issue by intjun** [PaddlePaddle/PaddleClas#962]
C++ Traceback (most recent call last):
--------------------------------------
0   search_mobius_index
1   paddle::framework::SignalHandle(char const*, int)
2   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Illegal instruction` is detected by the operating system.
  [TimeInfo: *** Aborted at 1624503311 (unix time) try "date -d @1624503311" if you are using GNU date ***]
  [SignalInfo: *** SIGILL (@0x7f6c43eb3b81) received by PID 1766 (TID 0x7f6cb0dea700) from PID 1139489665 ***]

非法指令
(paddleclas

**Comment by steinvenic** [comment]
docker环境的话，检查一下，`df -h` 查看一下shm-size大小是多少，设置大一点，官方建议64G

**Comment by TingquanGao** [comment]
尝试重新编译`.dll`或`.so`，具体参考：[重新编译](https://github.com/PaddlePaddle/PaddleClas/blob/develop/deploy/vector_search/README.md#22-linux%E4%B8%8A%E7%BC%96%E8%AF%91%E7%94%9F%E6%88%90%E5%BA%93%E6%96%87%E4%BB%B6)

**Comment by zq-2021** [comment]
> docker环境的话，检查一下，`df -h` 查看一下shm-size大小是多少，设置大一点，官方建议64G

官方不是建议8个G吗
