### ISSUE TITLE
paddlepaddle-gpu 安装问题？

### ISSUE THREAD

**Issue by hejing-maker** [PaddlePaddle/PaddleClas#965]
cuda  : 10.1
   cudnn：7.6.5
   driver：430.64
   安装paddlepaddle 2.1.0
  
   测试安装是否成功时报错：
      Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
W0624 14:32:46.220422 23029 init.cc:136] Compiled with WITH_GPU, but no GPU found in runtime.
/home/hejing/.local/lib/python3.6/site-packages/paddle/fluid/framework.py:298: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  "You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default."
  请问是什么原因呢？

**Comment by TingquanGao** [comment]
和GPU驱动、CUDA 版本不兼容导致的。可以尝试升级一下显卡驱动。我这边的配置：
 NVIDIA-SMI 440.118.02   Driver Version: 440.118.02   CUDA Version: 10.2

**Comment by Williamwsk** [comment]
> 和GPU驱动、CUDA 版本不兼容导致的。可以尝试升级一下显卡驱动。我这边的配置： NVIDIA-SMI 440.118.02 Driver Version: 440.118.02 CUDA Version: 10.2

我的配置和你这个一样， docker里也报同样的错
