### ISSUE TITLE
--use_tensorrt=True， 怎么导出tensorrt引擎模型

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/PaddleClas#97]
想请问下，能否单独导出trt引擎文件，希望更灵活的使用trt模型，比如deep stream。

**Comment by NHZlX** [comment]
您好，可以在这里的enable_tensorrt_engine 接口加上一个参数，https://github.com/PaddlePaddle/PaddleClas/blob/f6527e351b3a861c2c55e1ff6d45c2e239de0c80/tools/infer/predict.py#L58 ， `use_static=True`, 表明第一次预测时候会将trt engine 序列化。此序列化文件可以被trt 原生接口加载预测（需要保证模型没有用到plugin。）

**Comment by thunder95** [comment]
> 您好，可以在这里的enable_tensorrt_engine 接口加上 `use_static=True`, 参数，
> 
> https://github.com/PaddlePaddle/PaddleClas/blob/f6527e351b3a861c2c55e1ff6d45c2e239de0c80/tools/infer/predict.py#L58
> 
> ， 表明第一次预测时候会将trt engine 序列化。此序列化文件可以被trt 原生接口加载预测（需要保证模型没有用到plugin。）

请问序列化文件保存在哪个路径下的
