### ISSUE TITLE
PaddleClas能检测的种类有哪些

### ISSUE THREAD

**Issue by guoxixiao** [PaddlePaddle/PaddleClas#970]
PaddleClas能检测的种类有哪些？

**Comment by yanchaoguo** [comment]
PaddleClas\ppcls\utils\imagenet1k_label_list.txt

**Comment by cuicheng01** [comment]
检测模型只是返回主体的位置哈，最终识别的种类是依赖你自己建的数据库的类别。

**Comment by weisy11** [comment]
目前提供的模型可以检测大多数的商品、车辆、动漫人物和logo
