### ISSUE TITLE
ImportError: cannot import name 'logger' from 'utils' (F:\tf_train\models\research\object_detection\utils\__init__.py)

### ISSUE THREAD

**Issue by gitqinxinyu** [PaddlePaddle/PaddleClas#971]
(pp) F:\PaddleClas\deploy>python python/predict_system.py -c configs/inference_product.yaml
Traceback (most recent call last):
  File "python/predict_system.py", line 24, in <module>
    from python.predict_rec import RecPredictor
  File "F:\PaddleClas\deploy\python\predict_rec.py", line 23, in <module>
    from utils import logger
ImportError: cannot import name 'logger' from 'utils' (F:\tf_train\models\research\object_detection\utils\__init__.py)

**Comment by cuicheng01** [comment]
里边为什么会有tf_train\models\research\object_detection\utils_init_.py？

**Comment by yangguangyu369** [comment]
怎么解决的啊，我也这样
