### ISSUE TITLE
有车辆细分类的pretrained model吗？

### ISSUE THREAD

**Issue by frotms** [PaddlePaddle/PaddleClas#976]
想根据pretrained model在自己的数据fine-tuning，请问有车辆431分类的pretrained model吗？

**Comment by aichase** [comment]
同问

**Comment by weisy11** [comment]
我们有车辆细分类的pretrained model，下周整理下上传。

**Comment by RainFrost1** [comment]
今天还在训练一个更好的训练模型，明天（6.29）应该会上传

**Comment by RainFrost1** [comment]
https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/rec/models/pretrain/vehicle_cls_ResNet50_CompCars_v1.1_pretrained.pdparams, 431 类的pretrained model链接，top1 acc: 0.97369
