### ISSUE TITLE
ImportError: cannot import name 'hard_sigmoid' from 'paddle.nn.functional.activation' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/activation.py)

### ISSUE THREAD

**Issue by peteli25** [PaddlePaddle/PaddleClas#977]
ImportError: cannot import name 'hard_sigmoid' from 'paddle.nn.functional.activation' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/activation.py)

**Comment by weisy11** [comment]
What's version of your paddle? You can see it by running `paddle.__version__` in python. 
We suggest you using paddle of version >= 2.0.2
