### ISSUE TITLE
未知图像识别建立索引的疑问

### ISSUE THREAD

**Issue by coderchuan** [PaddlePaddle/PaddleClas#986]
未知图像识别可以增量添加索引吗，而不是全部重新建立索引

**Comment by Intsigstephon** [comment]
暂时不支持

**Comment by weisy11** [comment]
最近已经增加增量索引功能，详见：
https://github.com/PaddlePaddle/PaddleClas/pull/1006

**Comment by coderchuan** [comment]
thanks

**Comment by coderchuan** [comment]
> 最近已经增加增量索引功能，详见：
> #1006

thanks
